import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "Good morning. I have an appointment at ten o'clock.",
        "lithuanian": "Labas rytas. Turiu vizitą dešimtą valandą.",
        "latvian": "Labrīt. Man ir pieraksts pulksten desmitos.",
        "estonian": "Tere hommikust. Mul on aeg kell kümme.",
        "german": "Guten Morgen. Ich habe einen Termin um zehn Uhr.",
        "french": "Bonjour. J'ai un rendez-vous à dix heures.",
        "spanish": "Buenos días. Tengo una cita a las diez.",
        "italian": "Buongiorno. Ho un appuntamento alle dieci.",
        "portuguese": "Bom dia. Tenho uma consulta às dez horas.",
        "dutch": "Goedemorgen. Ik heb een afspraak om tien uur.",
        "polish": "Dzień dobry. Mam wizytę o dziesiątej.",
        "ukrainian": "Доброго ранку. У мене запис на десяту годину.",
        "russian": "Доброе утро. У меня запись на десять часов.",
        "swedish": "God morgon. Jag har en tid klockan tio.",
        "norwegian": "God morgen. Jeg har time klokken ti.",
        "danish": "God morgen. Jeg har en tid klokken ti.",
        "finnish": "Hyvää huomenta. Minulla on aika kello kymmenen.",
        "greek": "Καλημέρα. Έχω ραντεβού στις δέκα.",
        "brazilian_portuguese": "Bom dia. Tenho uma consulta às dez horas.",
        "mandarin": "早上好。我有十点钟的预约。",
        "japanese": "おはようございます。十時に予約があります。",
        "korean": "안녕하세요. 열 시에 예약이 있어요.",
        "hindi": "सुप्रभात। मेरी दस बजे की अपॉइंटमेंट है।",
        "vietnamese": "Chào buổi sáng. Tôi có hẹn lúc mười giờ.",
        "arabic": "صباح الخير. لدي موعد الساعة العاشرة.",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "Your name please?",
        "lithuanian": "Jūsų vardas, prašau?",
        "latvian": "Jūsu vārds, lūdzu?",
        "estonian": "Teie nimi palun?",
        "german": "Ihr Name bitte?",
        "french": "Votre nom s'il vous plaît?",
        "spanish": "Su nombre por favor?",
        "italian": "Il suo nome per favore?",
        "portuguese": "O seu nome por favor?",
        "dutch": "Uw naam alstublieft?",
        "polish": "Pana nazwisko proszę?",
        "ukrainian": "Ваше ім'я будь ласка?",
        "russian": "Ваше имя пожалуйста?",
        "swedish": "Ditt namn tack?",
        "norwegian": "Ditt navn takk?",
        "danish": "Dit navn tak?",
        "finnish": "Nimenne kiitos?",
        "greek": "Το όνομά σας παρακαλώ;",
        "brazilian_portuguese": "Seu nome por favor?",
        "mandarin": "请问您的名字？",
        "japanese": "お名前をお願いします。",
        "korean": "성함이 어떻게 되세요?",
        "hindi": "आपका नाम क्या है?",
        "vietnamese": "Tên bạn là gì?",
        "arabic": "اسمك من فضلك؟",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "My name is Alex Johansson.",
        "lithuanian": "Mano vardas Aleksas Johansonas.",
        "latvian": "Mani sauc Alekss Johansons.",
        "estonian": "Minu nimi on Alex Johansson.",
        "german": "Mein Name ist Alex Johansson.",
        "french": "Je m'appelle Alex Johansson.",
        "spanish": "Me llamo Alex Johansson.",
        "italian": "Mi chiamo Alex Johansson.",
        "portuguese": "Chamo-me Alex Johansson.",
        "dutch": "Mijn naam is Alex Johansson.",
        "polish": "Nazywam się Alex Johansson.",
        "ukrainian": "Мене звуть Алекс Йоханссон.",
        "russian": "Меня зовут Алекс Йоханссон.",
        "swedish": "Mitt namn är Alex Johansson.",
        "norwegian": "Jeg heter Alex Johansson.",
        "danish": "Jeg hedder Alex Johansson.",
        "finnish": "Nimeni on Alex Johansson.",
        "greek": "Το όνομά μου είναι Άλεξ Γιόχανσον.",
        "brazilian_portuguese": "Meu nome é Alex Johansson.",
        "mandarin": "我叫亚历克斯·约翰逊。",
        "japanese": "アレックス・ヨハンソンです。",
        "korean": "제 이름은 알렉스 요한슨입니다.",
        "hindi": "मेरा नाम एलेक्स जोहानसन है।",
        "vietnamese": "Tên tôi là Alex Johansson.",
        "arabic": "اسمي أليكس يوهانسون.",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "Please sit down. The doctor is ready.",
        "lithuanian": "Prašom sėstis. Gydytojas pasiruošęs.",
        "latvian": "Lūdzu apsēdieties. Ārsts ir gatavs.",
        "estonian": "Palun istuge. Arst on valmis.",
        "german": "Bitte setzen Sie sich. Der Arzt ist bereit.",
        "french": "Veuillez vous asseoir. Le médecin est prêt.",
        "spanish": "Por favor siéntese. El médico está listo.",
        "italian": "Prego si sieda. Il dottore è pronto.",
        "portuguese": "Por favor sente-se. O médico está pronto.",
        "dutch": "Gaat u zitten. De dokter is klaar.",
        "polish": "Proszę usiąść. Lekarz jest gotowy.",
        "ukrainian": "Прошу сідайте. Лікар готовий.",
        "russian": "Пожалуйста присядьте. Доктор готов.",
        "swedish": "Varsågod och sätt dig. Läkaren är redo.",
        "norwegian": "Vær så snill å sett deg. Legen er klar.",
        "danish": "Vær venlig at sætte dig. Lægen er klar.",
        "finnish": "Istukaahan. Lääkäri on valmis.",
        "greek": "Παρακαλώ καθίστε. Ο γιατρός είναι έτοιμος.",
        "brazilian_portuguese": "Por favor sente-se. O médico está pronto.",
        "mandarin": "请坐。医生准备好了。",
        "japanese": "どうぞお座りください。医師の準備ができています。",
        "korean": "앉으세요. 의사 선생님이 준비됐습니다.",
        "hindi": "कृपया बैठिए। डॉक्टर तैयार हैं।",
        "vietnamese": "Xin mời ngồi. Bác sĩ đã sẵn sàng.",
        "arabic": "تفضل بالجلوس. الطبيب جاهز.",
    },
    {
        "line_number": 5, "speaker_name": "Mia",
        "english": "Hello Alex. What is the problem today?",
        "lithuanian": "Sveiki Aleksai. Kuo šiandien galiu padėti?",
        "latvian": "Sveiki Alekss. Kāda ir problēma šodien?",
        "estonian": "Tere Alex. Mis on täna probleem?",
        "german": "Hallo Alex. Was ist heute das Problem?",
        "french": "Bonjour Alex. Quel est le problème aujourd'hui?",
        "spanish": "Hola Alex. ¿Cuál es el problema hoy?",
        "italian": "Ciao Alex. Qual è il problema oggi?",
        "portuguese": "Olá Alex. Qual é o problema hoje?",
        "dutch": "Hallo Alex. Wat is het probleem vandaag?",
        "polish": "Dzień dobry Alex. Co pana dziś boli?",
        "ukrainian": "Привіт Алексе. Яка проблема сьогодні?",
        "russian": "Привет Алекс. В чём проблема сегодня?",
        "swedish": "Hej Alex. Vad är problemet idag?",
        "norwegian": "Hei Alex. Hva er problemet i dag?",
        "danish": "Hej Alex. Hvad er problemet i dag?",
        "finnish": "Hei Alex. Mikä on ongelma tänään?",
        "greek": "Γεια σας Άλεξ. Ποιο είναι το πρόβλημα σήμερα;",
        "brazilian_portuguese": "Olá Alex. Qual é o problema hoje?",
        "mandarin": "你好亚历克斯。今天有什么问题？",
        "japanese": "こんにちはアレックス。今日はどうされましたか？",
        "korean": "안녕하세요 알렉스. 오늘 어디가 불편하세요?",
        "hindi": "नमस्ते एलेक्स। आज क्या समस्या है?",
        "vietnamese": "Xin chào Alex. Hôm nay có vấn đề gì?",
        "arabic": "مرحباً أليكس. ما هي المشكلة اليوم؟",
    },
    {
        "line_number": 6, "speaker_name": "Alex",
        "english": "I have a bad headache and I feel very tired.",
        "lithuanian": "Labai skauda galvą ir jaučiuosi labai pavargęs.",
        "latvian": "Man ļoti sāp galva un jūtos ļoti noguris.",
        "estonian": "Mul on tugev peavalu ja tunnen end väga väsinuna.",
        "german": "Ich habe starke Kopfschmerzen und fühle mich sehr müde.",
        "french": "J'ai un fort mal de tête et je me sens très fatigué.",
        "spanish": "Tengo un fuerte dolor de cabeza y me siento muy cansado.",
        "italian": "Ho un forte mal di testa e mi sento molto stanco.",
        "portuguese": "Tenho uma forte dor de cabeça e sinto-me muito cansado.",
        "dutch": "Ik heb erge hoofdpijn en voel me erg moe.",
        "polish": "Mam silny ból głowy i czuję się bardzo zmęczony.",
        "ukrainian": "У мене сильний головний біль і я дуже втомлений.",
        "russian": "У меня сильная головная боль и я очень устал.",
        "swedish": "Jag har svår huvudvärk och känner mig mycket trött.",
        "norwegian": "Jeg har sterk hodepine og føler meg veldig trøtt.",
        "danish": "Jeg har stærk hovedpine og føler mig meget træt.",
        "finnish": "Minulla on kova päänsärky ja tunnen itseni erittäin väsyneeksi.",
        "greek": "Έχω δυνατό πονοκέφαλο και νιώθω πολύ κουρασμένος.",
        "brazilian_portuguese": "Tenho uma forte dor de cabeça e me sinto muito cansado.",
        "mandarin": "我头痛得很厉害，感觉非常疲劳。",
        "japanese": "ひどい頭痛がして、とても疲れた感じがします。",
        "korean": "심한 두통이 있고 매우 피곤합니다.",
        "hindi": "मुझे बहुत तेज सिरदर्द है और मैं बहुत थका हुआ महसूस कर रहा हूँ।",
        "vietnamese": "Tôi bị đau đầu dữ dội và cảm thấy rất mệt.",
        "arabic": "لدي صداع شديد وأشعر بتعب كبير.",
    },
    {
        "line_number": 7, "speaker_name": "Mia",
        "english": "Since when do you have this headache?",
        "lithuanian": "Nuo kada turite šį galvos skausmą?",
        "latvian": "Kopš kad jums ir šīs galvassāpes?",
        "estonian": "Millest ajast on teil see peavalu?",
        "german": "Seit wann haben Sie diese Kopfschmerzen?",
        "french": "Depuis quand avez-vous ce mal de tête?",
        "spanish": "¿Desde cuándo tiene este dolor de cabeza?",
        "italian": "Da quando ha questo mal di testa?",
        "portuguese": "Desde quando tem esta dor de cabeça?",
        "dutch": "Sinds wanneer heeft u deze hoofdpijn?",
        "polish": "Od kiedy ma pan ten ból głowy?",
        "ukrainian": "З якого часу у вас цей головний біль?",
        "russian": "С каких пор у вас эта головная боль?",
        "swedish": "Sedan när har du den här huvudvärken?",
        "norwegian": "Siden når har du hatt denne hodepinen?",
        "danish": "Siden hvornår har du haft denne hovedpine?",
        "finnish": "Kuinka kauan sinulla on ollut tämä päänsärky?",
        "greek": "Από πότε έχετε αυτόν τον πονοκέφαλο;",
        "brazilian_portuguese": "Desde quando você tem essa dor de cabeça?",
        "mandarin": "您这头痛是从什么时候开始的？",
        "japanese": "この頭痛はいつからですか？",
        "korean": "이 두통은 언제부터 시작됐나요?",
        "hindi": "यह सिरदर्द कब से है?",
        "vietnamese": "Bạn bị đau đầu từ khi nào?",
        "arabic": "منذ متى وأنت تعاني من هذا الصداع؟",
    },
    {
        "line_number": 8, "speaker_name": "Alex",
        "english": "Since yesterday morning. I also have a fever.",
        "lithuanian": "Nuo vakarykščio ryto. Taip pat turiu temperatūrą.",
        "latvian": "Kopš vakardienas rīta. Man arī ir drudzis.",
        "estonian": "Eilsest hommikust. Mul on ka palavik.",
        "german": "Seit gestern Morgen. Ich habe auch Fieber.",
        "french": "Depuis hier matin. J'ai aussi de la fièvre.",
        "spanish": "Desde ayer por la mañana. También tengo fiebre.",
        "italian": "Da ieri mattina. Ho anche la febbre.",
        "portuguese": "Desde ontem de manhã. Também tenho febre.",
        "dutch": "Sinds gisterochtend. Ik heb ook koorts.",
        "polish": "Od wczorajszego rana. Mam też gorączkę.",
        "ukrainian": "З вчорашнього ранку. У мене також є температура.",
        "russian": "С вчерашнего утра. У меня также есть температура.",
        "swedish": "Sedan igår morgon. Jag har också feber.",
        "norwegian": "Siden i går morges. Jeg har også feber.",
        "danish": "Siden i går morges. Jeg har også feber.",
        "finnish": "Eilisestä aamusta. Minulla on myös kuumetta.",
        "greek": "Από χθες το πρωί. Έχω επίσης πυρετό.",
        "brazilian_portuguese": "Desde ontem de manhã. Também estou com febre.",
        "mandarin": "从昨天早上开始。我也发烧了。",
        "japanese": "昨日の朝からです。熱もあります。",
        "korean": "어제 아침부터요. 열도 있어요.",
        "hindi": "कल सुबह से। मुझे बुखार भी है।",
        "vietnamese": "Từ sáng hôm qua. Tôi cũng bị sốt.",
        "arabic": "منذ صباح أمس. لدي أيضاً حمى.",
    },
    {
        "line_number": 9, "speaker_name": "Mia",
        "english": "I see. Do you have a sore throat too?",
        "lithuanian": "Suprantu. Ar taip pat skauda gerklę?",
        "latvian": "Saprotu. Vai jums sāp arī kakls?",
        "estonian": "Saan aru. Kas teil on ka kurk valus?",
        "german": "Ich verstehe. Haben Sie auch Halsschmerzen?",
        "french": "Je vois. Avez-vous aussi mal à la gorge?",
        "spanish": "Ya veo. ¿También tiene dolor de garganta?",
        "italian": "Capisco. Ha anche mal di gola?",
        "portuguese": "Percebo. Também tem dor de garganta?",
        "dutch": "Ik begrijp het. Heeft u ook keelpijn?",
        "polish": "Rozumiem. Czy boli pana też gardło?",
        "ukrainian": "Розумію. У вас також болить горло?",
        "russian": "Понятно. У вас также болит горло?",
        "swedish": "Jag förstår. Har du också ont i halsen?",
        "norwegian": "Jeg skjønner. Har du også vondt i halsen?",
        "danish": "Jeg forstår. Har du også ondt i halsen?",
        "finnish": "Ymmärrän. Onko sinulla myös kurkkukipua?",
        "greek": "Καταλαβαίνω. Έχετε επίσης πονόλαιμο;",
        "brazilian_portuguese": "Entendo. Você também tem dor de garganta?",
        "mandarin": "我明白了。您也喉咙痛吗？",
        "japanese": "なるほど。のども痛いですか？",
        "korean": "알겠습니다. 목도 아프신가요?",
        "hindi": "समझ आया। क्या गला भी दर्द हो रहा है?",
        "vietnamese": "Tôi hiểu. Bạn có đau họng không?",
        "arabic": "أفهم. هل لديك أيضاً التهاب في الحلق؟",
    },
    {
        "line_number": 10, "speaker_name": "Alex",
        "english": "Yes, a little. And my body hurts.",
        "lithuanian": "Taip, šiek tiek. Ir skauda visą kūną.",
        "latvian": "Jā, nedaudz. Un sāp arī ķermenis.",
        "estonian": "Jah, natuke. Ja mu keha valutab.",
        "german": "Ja, ein bisschen. Und mein Körper tut weh.",
        "french": "Oui un peu. Et j'ai mal partout dans le corps.",
        "spanish": "Sí un poco. Y me duele el cuerpo.",
        "italian": "Sì un po'. E mi fa male il corpo.",
        "portuguese": "Sim um pouco. E dói-me o corpo.",
        "dutch": "Ja een beetje. En mijn lichaam doet pijn.",
        "polish": "Tak trochę. I boli mnie całe ciało.",
        "ukrainian": "Так трохи. І болить все тіло.",
        "russian": "Да немного. И болит всё тело.",
        "swedish": "Ja lite. Och hela kroppen gör ont.",
        "norwegian": "Ja litt. Og kroppen gjør vondt.",
        "danish": "Ja lidt. Og kroppen gør ondt.",
        "finnish": "Kyllä vähän. Ja koko keho särkee.",
        "greek": "Ναι λίγο. Και πονά το σώμα μου.",
        "brazilian_portuguese": "Sim um pouco. E meu corpo está doendo.",
        "mandarin": "是的，有点。全身都疼。",
        "japanese": "はい、少し。そして体が痛いです。",
        "korean": "네 조금요. 그리고 몸도 아파요.",
        "hindi": "हाँ थोड़ा। और पूरा शरीर दर्द कर रहा है।",
        "vietnamese": "Vâng một chút. Và người tôi đau nhức.",
        "arabic": "نعم قليلاً. وجسمي يؤلمني.",
    },
    {
        "line_number": 11, "speaker_name": "Mia",
        "english": "You probably have the flu. I will give you medicine.",
        "lithuanian": "Jūs turbūt sergate gripu. Duosiu jums vaistų.",
        "latvian": "Jums, iespējams, ir gripa. Es jums iedošu zāles.",
        "estonian": "Teil on tõenäoliselt gripp. Annan teile ravimeid.",
        "german": "Sie haben wahrscheinlich die Grippe. Ich gebe Ihnen Medikamente.",
        "french": "Vous avez probablement la grippe. Je vais vous donner des médicaments.",
        "spanish": "Probablemente tiene gripe. Le daré medicamentos.",
        "italian": "Probabilmente ha l'influenza. Le darò delle medicine.",
        "portuguese": "Provavelmente tem gripe. Vou dar-lhe medicamentos.",
        "dutch": "U heeft waarschijnlijk griep. Ik geef u medicijnen.",
        "polish": "Prawdopodobnie ma pan grypę. Dam panu leki.",
        "ukrainian": "Мабуть у вас грип. Я дам вам ліки.",
        "russian": "Вероятно у вас грипп. Я дам вам лекарства.",
        "swedish": "Du har troligen influensa. Jag ger dig medicin.",
        "norwegian": "Du har sannsynligvis influensa. Jeg vil gi deg medisin.",
        "danish": "Du har sandsynligvis influenza. Jeg vil give dig medicin.",
        "finnish": "Sinulla on todennäköisesti influenssa. Annan sinulle lääkkeitä.",
        "greek": "Μάλλον έχετε γρίπη. Θα σας δώσω φάρμακα.",
        "brazilian_portuguese": "Você provavelmente tem gripe. Vou te dar medicamentos.",
        "mandarin": "您可能得了流感。我给您开药。",
        "japanese": "インフルエンザかもしれません。薬を出します。",
        "korean": "독감인 것 같습니다. 약을 드리겠습니다.",
        "hindi": "आपको शायद फ्लू है। मैं आपको दवाई दूँगी।",
        "vietnamese": "Bạn có lẽ bị cúm. Tôi sẽ cho bạn thuốc.",
        "arabic": "ربما أصبت بالإنفلونزا. سأعطيك دواءً.",
    },
    {
        "line_number": 12, "speaker_name": "Alex",
        "english": "How many times a day should I take it?",
        "lithuanian": "Kiek kartų per dieną jį vartoti?",
        "latvian": "Cik reizes dienā man tas jālieto?",
        "estonian": "Mitu korda päevas peaksin seda võtma?",
        "german": "Wie oft am Tag soll ich es nehmen?",
        "french": "Combien de fois par jour dois-je le prendre?",
        "spanish": "¿Cuántas veces al día debo tomarlo?",
        "italian": "Quante volte al giorno devo prenderla?",
        "portuguese": "Quantas vezes por dia devo tomá-lo?",
        "dutch": "Hoe vaak per dag moet ik het innemen?",
        "polish": "Ile razy dziennie powinienem to brać?",
        "ukrainian": "Скільки разів на день мені це приймати?",
        "russian": "Сколько раз в день мне это принимать?",
        "swedish": "Hur många gånger om dagen ska jag ta det?",
        "norwegian": "Hvor mange ganger om dagen skal jeg ta det?",
        "danish": "Hvor mange gange om dagen skal jeg tage det?",
        "finnish": "Kuinka monta kertaa päivässä minun pitää ottaa sitä?",
        "greek": "Πόσες φορές την ημέρα πρέπει να το παίρνω;",
        "brazilian_portuguese": "Quantas vezes ao dia devo tomar?",
        "mandarin": "每天需要服用几次？",
        "japanese": "一日何回飲めばいいですか？",
        "korean": "하루에 몇 번 먹어야 하나요?",
        "hindi": "दिन में कितनी बार लेना है?",
        "vietnamese": "Tôi nên uống bao nhiêu lần một ngày?",
        "arabic": "كم مرة في اليوم يجب أن آخذه؟",
    },
    {
        "line_number": 13, "speaker_name": "Mia",
        "english": "Three times a day after meals. Drink a lot of water.",
        "lithuanian": "Tris kartus per dieną po valgio. Gerkite daug vandens.",
        "latvian": "Trīs reizes dienā pēc ēšanas. Dzeriet daudz ūdens.",
        "estonian": "Kolm korda päevas pärast sööki. Jooge palju vett.",
        "german": "Dreimal täglich nach den Mahlzeiten. Trinken Sie viel Wasser.",
        "french": "Trois fois par jour après les repas. Buvez beaucoup d'eau.",
        "spanish": "Tres veces al día después de las comidas. Beba mucha agua.",
        "italian": "Tre volte al giorno dopo i pasti. Beva molta acqua.",
        "portuguese": "Três vezes por dia depois das refeições. Beba muita água.",
        "dutch": "Drie keer per dag na de maaltijden. Drink veel water.",
        "polish": "Trzy razy dziennie po posiłkach. Proszę dużo pić wody.",
        "ukrainian": "Тричі на день після їди. Пийте багато води.",
        "russian": "Три раза в день после еды. Пейте много воды.",
        "swedish": "Tre gånger om dagen efter måltiderna. Drick mycket vatten.",
        "norwegian": "Tre ganger om dagen etter måltider. Drikk mye vann.",
        "danish": "Tre gange om dagen efter måltiderne. Drik meget vand.",
        "finnish": "Kolme kertaa päivässä aterioiden jälkeen. Juo paljon vettä.",
        "greek": "Τρεις φορές την ημέρα μετά τα γεύματα. Πιείτε πολύ νερό.",
        "brazilian_portuguese": "Três vezes ao dia após as refeições. Beba bastante água.",
        "mandarin": "一天三次，饭后服用。多喝水。",
        "japanese": "一日三回、食後に飲んでください。水をたくさん飲んでください。",
        "korean": "하루 세 번 식후에 드세요. 물을 많이 드세요.",
        "hindi": "दिन में तीन बार खाने के बाद। बहुत पानी पिएँ।",
        "vietnamese": "Ba lần một ngày sau bữa ăn. Uống nhiều nước.",
        "arabic": "ثلاث مرات يومياً بعد الوجبات. اشرب الكثير من الماء.",
    },
    {
        "line_number": 14, "speaker_name": "Alex",
        "english": "Should I stay at home?",
        "lithuanian": "Ar turėčiau likti namuose?",
        "latvian": "Vai man vajadzētu palikt mājās?",
        "estonian": "Kas peaksin kodus jääma?",
        "german": "Soll ich zu Hause bleiben?",
        "french": "Dois-je rester à la maison?",
        "spanish": "¿Debo quedarme en casa?",
        "italian": "Devo restare a casa?",
        "portuguese": "Devo ficar em casa?",
        "dutch": "Moet ik thuis blijven?",
        "polish": "Czy powinienem zostać w domu?",
        "ukrainian": "Чи повинен я залишатися вдома?",
        "russian": "Должен ли я оставаться дома?",
        "swedish": "Bör jag stanna hemma?",
        "norwegian": "Bør jeg bli hjemme?",
        "danish": "Bør jeg blive hjemme?",
        "finnish": "Pitäisikö minun jäädä kotiin?",
        "greek": "Πρέπει να μείνω σπίτι;",
        "brazilian_portuguese": "Devo ficar em casa?",
        "mandarin": "我应该待在家里吗？",
        "japanese": "家にいた方がいいですか？",
        "korean": "집에 있어야 하나요?",
        "hindi": "क्या मुझे घर पर रहना चाहिए?",
        "vietnamese": "Tôi có nên ở nhà không?",
        "arabic": "هل يجب أن أبقى في المنزل؟",
    },
    {
        "line_number": 15, "speaker_name": "Mia",
        "english": "Yes please. Rest for two or three days. Get well soon!",
        "lithuanian": "Taip prašau. Ilsėkitės dvi ar tris dienas. Greitai sveikite!",
        "latvian": "Jā lūdzu. Atpūtieties divas vai trīs dienas. Ātrā atveseļošanās!",
        "estonian": "Jah palun. Puhake kaks kuni kolm päeva. Tervist!",
        "german": "Ja bitte. Ruhen Sie sich zwei oder drei Tage aus. Gute Besserung!",
        "french": "Oui s'il vous plaît. Reposez-vous deux ou trois jours. Bon rétablissement!",
        "spanish": "Sí por favor. Descanse dos o tres días. ¡Que se mejore pronto!",
        "italian": "Sì per favore. Riposi per due o tre giorni. Guarisca presto!",
        "portuguese": "Sim por favor. Descanse dois ou três dias. Melhoras!",
        "dutch": "Ja graag. Rust twee of drie dagen. Beterschap!",
        "polish": "Tak proszę. Proszę odpoczywać dwa lub trzy dni. Szybkiego powrotu do zdrowia!",
        "ukrainian": "Так будь ласка. Відпочивайте два-три дні. Скоро одужуйте!",
        "russian": "Да пожалуйста. Отдыхайте два-три дня. Скорейшего выздоровления!",
        "swedish": "Ja tack. Vila i två eller tre dagar. God återhämtning!",
        "norwegian": "Ja takk. Hvil i to eller tre dager. God bedring!",
        "danish": "Ja tak. Hvil i to eller tre dage. God bedring!",
        "finnish": "Kyllä kiitos. Lepää kaksi tai kolme päivää. Pikaista toipumista!",
        "greek": "Ναι παρακαλώ. Ξεκουραστείτε δύο ή τρεις μέρες. Περαστικά!",
        "brazilian_portuguese": "Sim por favor. Descanse dois ou três dias. Melhoras!",
        "mandarin": "是的请。休息两三天。祝您早日康复！",
        "japanese": "はいお願いします。二三日休んでください。お大事に！",
        "korean": "네 부탁드립니다. 이삼 일 쉬세요. 빨리 낫기를 바랍니다!",
        "hindi": "हाँ कृपया। दो-तीन दिन आराम करें। जल्दी ठीक हो जाइए!",
        "vietnamese": "Vâng làm ơn. Nghỉ ngơi hai hoặc ba ngày. Chóng khỏe nhé!",
        "arabic": "نعم من فضلك. استرح يومين أو ثلاثة. سلامتك!",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="At the Doctor").first()
        if existing:
            print("A1 dialogue 'At the Doctor' already exists — skipping.")
            return

        dialogue = Dialogue(topic="At the Doctor", lang_level="A1", length=15)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded A1 dialogue ID {dialogue.id} — 15 lines in 25 languages.")


if __name__ == '__main__':
    seed()
