import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "Excuse me. Does this bus go to the city centre?",
        "lithuanian": "Atsiprašau. Ar šis autobusas važiuoja į miesto centrą?",
        "latvian": "Atvainojiet. Vai šis autobuss brauc uz pilsētas centru?",
        "estonian": "Vabandage. Kas see buss sõidab kesklinna?",
        "german": "Entschuldigung. Fährt dieser Bus ins Stadtzentrum?",
        "french": "Excusez-moi. Est-ce que ce bus va au centre-ville?",
        "spanish": "Perdone. ¿Este autobús va al centro de la ciudad?",
        "italian": "Scusi. Questo autobus va in centro?",
        "portuguese": "Com licença. Este autocarro vai ao centro da cidade?",
        "dutch": "Pardon. Gaat deze bus naar het stadscentrum?",
        "polish": "Przepraszam. Czy ten autobus jedzie do centrum?",
        "ukrainian": "Вибачте. Цей автобус їде до центру міста?",
        "russian": "Извините. Этот автобус едет в центр города?",
        "swedish": "Ursäkta. Går den här bussen till centrum?",
        "norwegian": "Unnskyld. Går denne bussen til bysentrum?",
        "danish": "Undskyld. Kører denne bus til bycentrum?",
        "finnish": "Anteeksi. Meneekö tämä bussi keskustaan?",
        "greek": "Συγγνώμη. Πηγαίνει αυτό το λεωφορείο στο κέντρο της πόλης;",
        "brazilian_portuguese": "Com licença. Este ônibus vai ao centro da cidade?",
        "mandarin": "打扰一下。这辆公交车去市中心吗？",
        "japanese": "すみません。このバスは市内中心部に行きますか？",
        "korean": "저기요. 이 버스 시내 중심가로 가나요?",
        "hindi": "माफ़ कीजिए। क्या यह बस शहर के केंद्र जाती है?",
        "vietnamese": "Xin lỗi. Xe buýt này có đi trung tâm thành phố không?",
        "arabic": "عفواً. هل يذهب هذا الباص إلى مركز المدينة؟",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "Yes it does. Get on.",
        "lithuanian": "Taip. Lipkite.",
        "latvian": "Jā. Iekāpiet.",
        "estonian": "Jah. Istuge sisse.",
        "german": "Ja. Steigen Sie ein.",
        "french": "Oui. Montez.",
        "spanish": "Sí. Suba.",
        "italian": "Sì. Salga.",
        "portuguese": "Sim. Entre.",
        "dutch": "Ja. Stap in.",
        "polish": "Tak. Proszę wsiadać.",
        "ukrainian": "Так. Заходьте.",
        "russian": "Да. Садитесь.",
        "swedish": "Ja det gör den. Stig på.",
        "norwegian": "Ja det gjør den. Bli med.",
        "danish": "Ja det gør den. Stig på.",
        "finnish": "Kyllä menee. Nouskaa.",
        "greek": "Ναι πηγαίνει. Μπείτε.",
        "brazilian_portuguese": "Sim vai. Entre.",
        "mandarin": "是的，上车吧。",
        "japanese": "はい行きます。乗ってください。",
        "korean": "네 맞아요. 타세요.",
        "hindi": "हाँ जाती है। चढ़ जाइए।",
        "vietnamese": "Vâng có. Lên đi.",
        "arabic": "نعم. تفضل بالركوب.",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "One ticket please. How much is it?",
        "lithuanian": "Vieną bilietą prašau. Kiek kainuoja?",
        "latvian": "Vienu biļeti lūdzu. Cik tas maksā?",
        "estonian": "Üks pilet palun. Kui palju see maksab?",
        "german": "Eine Fahrkarte bitte. Was kostet sie?",
        "french": "Un ticket s'il vous plaît. Combien ça coûte?",
        "spanish": "Un billete por favor. ¿Cuánto cuesta?",
        "italian": "Un biglietto per favore. Quanto costa?",
        "portuguese": "Um bilhete por favor. Quanto custa?",
        "dutch": "Eén kaartje alstublieft. Hoeveel kost het?",
        "polish": "Jeden bilet proszę. Ile kosztuje?",
        "ukrainian": "Один квиток будь ласка. Скільки коштує?",
        "russian": "Один билет пожалуйста. Сколько стоит?",
        "swedish": "En biljett tack. Hur mycket kostar det?",
        "norwegian": "En billett takk. Hvor mye koster det?",
        "danish": "En billet tak. Hvor meget koster det?",
        "finnish": "Yksi lippu kiitos. Kuinka paljon se maksaa?",
        "greek": "Ένα εισιτήριο παρακαλώ. Πόσο κοστίζει;",
        "brazilian_portuguese": "Uma passagem por favor. Quanto custa?",
        "mandarin": "一张票。多少钱？",
        "japanese": "一枚ください。いくらですか？",
        "korean": "표 한 장 주세요. 얼마예요?",
        "hindi": "एक टिकट दीजिए। कितने का है?",
        "vietnamese": "Một vé. Bao nhiêu tiền?",
        "arabic": "تذكرة واحدة من فضلك. كم سعرها؟",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "Two euros. Do you have the exact change?",
        "lithuanian": "Du eurai. Ar turite tikslią sumą?",
        "latvian": "Divi eiro. Vai jums ir precīza nauda?",
        "estonian": "Kaks eurot. Kas teil on täpne vahetus?",
        "german": "Zwei Euro. Haben Sie das passende Kleingeld?",
        "french": "Deux euros. Avez-vous la monnaie exacte?",
        "spanish": "Dos euros. ¿Tiene el cambio exacto?",
        "italian": "Due euro. Ha il resto esatto?",
        "portuguese": "Dois euros. Tem o troco exacto?",
        "dutch": "Twee euro. Heeft u het juiste wisselgeld?",
        "polish": "Dwa euro. Czy ma pan odliczone?",
        "ukrainian": "Два євро. У вас є точна сума?",
        "russian": "Два евро. У вас есть точная сумма?",
        "swedish": "Två euro. Har du jämna pengar?",
        "norwegian": "To euro. Har du oppgjort?",
        "danish": "To euro. Har du det rigtige beløb?",
        "finnish": "Kaksi euroa. Onko teillä tasan?",
        "greek": "Δύο ευρώ. Έχετε τα ρέστα;",
        "brazilian_portuguese": "Dois euros. Tem troco?",
        "mandarin": "两欧元。你有零钱吗？",
        "japanese": "二ユーロです。ちょうどありますか？",
        "korean": "이 유로예요. 잔돈 있으세요?",
        "hindi": "दो यूरो। क्या आपके पास सही पैसे हैं?",
        "vietnamese": "Hai euro. Bạn có tiền lẻ không?",
        "arabic": "يورويان. هل معك المبلغ بالضبط؟",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "Yes here you are.",
        "lithuanian": "Taip štai.",
        "latvian": "Jā lūdzu.",
        "estonian": "Jah palun.",
        "german": "Ja hier bitte.",
        "french": "Oui voilà.",
        "spanish": "Sí aquí tiene.",
        "italian": "Sì eccolo.",
        "portuguese": "Sim aqui tem.",
        "dutch": "Ja alstublieft.",
        "polish": "Tak proszę.",
        "ukrainian": "Так ось.",
        "russian": "Да вот пожалуйста.",
        "swedish": "Ja varsågod.",
        "norwegian": "Ja vær så god.",
        "danish": "Ja værsgo.",
        "finnish": "Kyllä olkaa hyvä.",
        "greek": "Ναι ορίστε.",
        "brazilian_portuguese": "Sim aqui está.",
        "mandarin": "是的，给你。",
        "japanese": "はいどうぞ。",
        "korean": "네 여기요.",
        "hindi": "हाँ लीजिए।",
        "vietnamese": "Vâng đây.",
        "arabic": "نعم تفضل.",
    },
    {
        "line_number": 6, "speaker_name": "Alex",
        "english": "How many stops to the centre?",
        "lithuanian": "Kiek stočių iki centro?",
        "latvian": "Cik pieturas līdz centram?",
        "estonian": "Mitu peatust kesklinnani?",
        "german": "Wie viele Haltestellen bis zum Zentrum?",
        "french": "Combien d'arrêts jusqu'au centre?",
        "spanish": "¿Cuántas paradas hasta el centro?",
        "italian": "Quante fermate fino al centro?",
        "portuguese": "Quantas paragens até ao centro?",
        "dutch": "Hoeveel haltes tot het centrum?",
        "polish": "Ile przystanków do centrum?",
        "ukrainian": "Скільки зупинок до центру?",
        "russian": "Сколько остановок до центра?",
        "swedish": "Hur många hållplatser till centrum?",
        "norwegian": "Hvor mange stopp til sentrum?",
        "danish": "Hvor mange stop til centrum?",
        "finnish": "Kuinka monta pysäkkiä keskustaan?",
        "greek": "Πόσες στάσεις μέχρι το κέντρο;",
        "brazilian_portuguese": "Quantas paradas até o centro?",
        "mandarin": "到市中心几站？",
        "japanese": "センターまで何停留所ですか？",
        "korean": "시내까지 몇 정거장이에요?",
        "hindi": "केंद्र तक कितने स्टॉप हैं?",
        "vietnamese": "Bao nhiêu trạm đến trung tâm?",
        "arabic": "كم محطة حتى المركز؟",
    },
    {
        "line_number": 7, "speaker_name": "Mia",
        "english": "Five stops. About ten minutes.",
        "lithuanian": "Penkios stotelės. Apie dešimt minučių.",
        "latvian": "Piecas pieturas. Apmēram desmit minūtes.",
        "estonian": "Viis peatust. Umbes kümme minutit.",
        "german": "Fünf Haltestellen. Ungefähr zehn Minuten.",
        "french": "Cinq arrêts. Environ dix minutes.",
        "spanish": "Cinco paradas. Unos diez minutos.",
        "italian": "Cinque fermate. Circa dieci minuti.",
        "portuguese": "Cinco paragens. Cerca de dez minutos.",
        "dutch": "Vijf haltes. Ongeveer tien minuten.",
        "polish": "Pięć przystanków. Około dziesięciu minut.",
        "ukrainian": "П'ять зупинок. Приблизно десять хвилин.",
        "russian": "Пять остановок. Примерно десять минут.",
        "swedish": "Fem hållplatser. Ungefär tio minuter.",
        "norwegian": "Fem stopp. Omtrent ti minutter.",
        "danish": "Fem stop. Cirka ti minutter.",
        "finnish": "Viisi pysäkkiä. Noin kymmenen minuuttia.",
        "greek": "Πέντε στάσεις. Περίπου δέκα λεπτά.",
        "brazilian_portuguese": "Cinco paradas. Cerca de dez minutos.",
        "mandarin": "五站。大约十分钟。",
        "japanese": "五つの停留所です。約十分です。",
        "korean": "다섯 정거장이요. 약 십 분 걸려요.",
        "hindi": "पाँच स्टॉप। लगभग दस मिनट।",
        "vietnamese": "Năm trạm. Khoảng mười phút.",
        "arabic": "خمس محطات. حوالي عشر دقائق.",
    },
    {
        "line_number": 8, "speaker_name": "Alex",
        "english": "Can you tell me when to get off?",
        "lithuanian": "Ar galite pasakyti man, kada išlipti?",
        "latvian": "Vai jūs varat man pateikt, kad izkāpt?",
        "estonian": "Kas saate mulle öelda, millal maha minna?",
        "german": "Können Sie mir sagen, wann ich aussteigen soll?",
        "french": "Pouvez-vous me dire quand descendre?",
        "spanish": "¿Puede decirme cuándo bajarme?",
        "italian": "Può dirmi quando scendere?",
        "portuguese": "Pode dizer-me quando sair?",
        "dutch": "Kunt u me zeggen wanneer ik moet uitstappen?",
        "polish": "Czy może mi pan powiedzieć kiedy wysiąść?",
        "ukrainian": "Можете сказати мені, коли виходити?",
        "russian": "Можете сказать мне, когда выходить?",
        "swedish": "Kan du säga till mig när jag ska stiga av?",
        "norwegian": "Kan du si til meg når jeg skal gå av?",
        "danish": "Kan du sige til mig hvornår jeg skal stige af?",
        "finnish": "Voitteko sanoa minulle milloin poistua?",
        "greek": "Μπορείτε να μου πείτε πότε να κατεβώ;",
        "brazilian_portuguese": "Você pode me dizer quando descer?",
        "mandarin": "您能告诉我什么时候下车吗？",
        "japanese": "どこで降りればいいか教えてもらえますか？",
        "korean": "어디서 내려야 하는지 알려주실 수 있나요?",
        "hindi": "क्या आप मुझे बता सकती हैं कब उतरना है?",
        "vietnamese": "Bạn có thể cho tôi biết khi nào xuống không?",
        "arabic": "هل يمكنك إخباري متى أنزل؟",
    },
    {
        "line_number": 9, "speaker_name": "Mia",
        "english": "Of course. I will tell you.",
        "lithuanian": "Žinoma. Pasakysiu jums.",
        "latvian": "Protams. Es jums pateikšu.",
        "estonian": "Muidugi. Ma ütlen teile.",
        "german": "Natürlich. Ich sage es Ihnen.",
        "french": "Bien sûr. Je vous dirai.",
        "spanish": "Por supuesto. Le avisaré.",
        "italian": "Certo. Glielo dirò.",
        "portuguese": "Claro. Digo-lhe.",
        "dutch": "Natuurlijk. Ik zal het u zeggen.",
        "polish": "Oczywiście. Powiem panu.",
        "ukrainian": "Звичайно. Я скажу вам.",
        "russian": "Конечно. Я скажу вам.",
        "swedish": "Självklart. Jag säger till dig.",
        "norwegian": "Selvfølgelig. Jeg skal si til deg.",
        "danish": "Selvfølgelig. Jeg skal sige til dig.",
        "finnish": "Tietysti. Kerron sinulle.",
        "greek": "Φυσικά. Θα σου πω.",
        "brazilian_portuguese": "Claro. Vou te avisar.",
        "mandarin": "当然。我来告诉你。",
        "japanese": "もちろんです。お知らせします。",
        "korean": "물론이죠. 알려드릴게요.",
        "hindi": "बिल्कुल। मैं आपको बताऊँगी।",
        "vietnamese": "Tất nhiên. Tôi sẽ nói cho bạn.",
        "arabic": "بالطبع. سأخبرك.",
    },
    {
        "line_number": 10, "speaker_name": "Alex",
        "english": "Is there a market near the bus stop?",
        "lithuanian": "Ar yra turgus šalia autobusų stotelės?",
        "latvian": "Vai pie autobusa pieturas ir tirgus?",
        "estonian": "Kas bussipeatuse lähedal on turg?",
        "german": "Gibt es einen Markt in der Nähe der Bushaltestelle?",
        "french": "Y a-t-il un marché près de l'arrêt de bus?",
        "spanish": "¿Hay un mercado cerca de la parada de autobús?",
        "italian": "C'è un mercato vicino alla fermata dell'autobus?",
        "portuguese": "Há um mercado perto da paragem de autocarro?",
        "dutch": "Is er een markt bij de bushalte?",
        "polish": "Czy jest rynek w pobliżu przystanku autobusowego?",
        "ukrainian": "Є ринок поблизу автобусної зупинки?",
        "russian": "Есть ли рынок рядом с автобусной остановкой?",
        "swedish": "Finns det en marknad nära busshållplatsen?",
        "norwegian": "Er det et marked nær bussholdeplassen?",
        "danish": "Er der et marked tæt på busstoppestedet?",
        "finnish": "Onko bussipysäkin lähellä tori?",
        "greek": "Υπάρχει αγορά κοντά στη στάση του λεωφορείου;",
        "brazilian_portuguese": "Tem um mercado perto do ponto de ônibus?",
        "mandarin": "公交车站附近有市场吗？",
        "japanese": "バス停の近くに市場はありますか？",
        "korean": "버스 정류장 근처에 시장이 있나요?",
        "hindi": "बस स्टॉप के पास कोई बाजार है?",
        "vietnamese": "Có chợ gần trạm xe buýt không?",
        "arabic": "هل يوجد سوق قريب من موقف الباص؟",
    },
    {
        "line_number": 11, "speaker_name": "Mia",
        "english": "Yes a big market. It opens at eight.",
        "lithuanian": "Taip didelis turgus. Jis atidaromas aštuntą.",
        "latvian": "Jā liels tirgus. Tas atver astoņos.",
        "estonian": "Jah suur turg. See avaneb kell kaheksa.",
        "german": "Ja ein großer Markt. Er öffnet um acht Uhr.",
        "french": "Oui un grand marché. Il ouvre à huit heures.",
        "spanish": "Sí un mercado grande. Abre a las ocho.",
        "italian": "Sì un grande mercato. Apre alle otto.",
        "portuguese": "Sim um mercado grande. Abre às oito.",
        "dutch": "Ja een grote markt. Het opent om acht uur.",
        "polish": "Tak duży rynek. Otwiera się o ósmej.",
        "ukrainian": "Так великий ринок. Він відкривається о восьмій.",
        "russian": "Да большой рынок. Он открывается в восемь.",
        "swedish": "Ja en stor marknad. Den öppnar klockan åtta.",
        "norwegian": "Ja et stort marked. Det åpner klokken åtte.",
        "danish": "Ja et stort marked. Det åbner klokken otte.",
        "finnish": "Kyllä iso tori. Se avaa kello kahdeksan.",
        "greek": "Ναι μια μεγάλη αγορά. Ανοίγει στις οκτώ.",
        "brazilian_portuguese": "Sim um grande mercado. Abre às oito.",
        "mandarin": "是的，有个大市场。八点开门。",
        "japanese": "はい大きな市場があります。八時に開きます。",
        "korean": "네 큰 시장이 있어요. 여덟 시에 열어요.",
        "hindi": "हाँ एक बड़ा बाज़ार है। आठ बजे खुलता है।",
        "vietnamese": "Vâng một khu chợ lớn. Mở cửa lúc tám giờ.",
        "arabic": "نعم سوق كبير. يفتح الساعة الثامنة.",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "This is your stop. The centre is right there.",
        "lithuanian": "Čia jūsų stotelė. Centras yra čia pat.",
        "latvian": "Šī ir jūsu pieturas. Centrs ir tieši tur.",
        "estonian": "See on teie peatus. Kesklinn on just seal.",
        "german": "Das ist Ihre Haltestelle. Das Zentrum ist gleich dort.",
        "french": "C'est votre arrêt. Le centre est juste là.",
        "spanish": "Esta es su parada. El centro está justo ahí.",
        "italian": "Questa è la sua fermata. Il centro è proprio lì.",
        "portuguese": "Esta é a sua paragem. O centro está mesmo ali.",
        "dutch": "Dit is uw halte. Het centrum is precies daar.",
        "polish": "To jest pana przystanek. Centrum jest właśnie tam.",
        "ukrainian": "Це ваша зупинка. Центр прямо там.",
        "russian": "Это ваша остановка. Центр прямо там.",
        "swedish": "Det här är din hållplats. Centrum är precis där.",
        "norwegian": "Dette er din holdeplass. Sentrum er rett der.",
        "danish": "Dette er dit stop. Centrum er lige der.",
        "finnish": "Tämä on pysäkkisi. Keskusta on aivan tuolla.",
        "greek": "Αυτή είναι η στάση σας. Το κέντρο είναι ακριβώς εκεί.",
        "brazilian_portuguese": "Esta é a sua parada. O centro fica bem ali.",
        "mandarin": "这是您的站。市中心就在那里。",
        "japanese": "これがあなたの停留所です。センターはすぐそこです。",
        "korean": "여기가 당신의 정류장이에요. 시내가 바로 저기예요.",
        "hindi": "यह आपका स्टॉप है। केंद्र बिल्कुल वहीं है।",
        "vietnamese": "Đây là trạm của bạn. Trung tâm ngay đó.",
        "arabic": "هذه محطتك. المركز في مكانه تماماً.",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="On the Bus").first()
        if existing:
            print("A1 dialogue 'On the Bus' already exists — skipping.")
            return

        dialogue = Dialogue(topic="On the Bus", lang_level="A1", length=12)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded A1 dialogue ID {dialogue.id} — 12 lines in 25 languages.")


if __name__ == '__main__':
    seed()
