import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "Excuse me. I would like to buy a ticket to Paris please.",
        "lithuanian": "Atsiprašau. Norėčiau nusipirkti bilietą į Paryžių prašau.",
        "latvian": "Atvainojiet. Es gribētu nopirkt biļeti uz Parīzi lūdzu.",
        "estonian": "Vabandage. Sooviksin osta pileti Pariisi palun.",
        "german": "Entschuldigung. Ich möchte eine Fahrkarte nach Paris kaufen bitte.",
        "french": "Excusez-moi. Je voudrais acheter un billet pour Paris s'il vous plaît.",
        "spanish": "Perdone. Me gustaría comprar un billete a París por favor.",
        "italian": "Scusi. Vorrei comprare un biglietto per Parigi per favore.",
        "portuguese": "Com licença. Gostaria de comprar um bilhete para Paris por favor.",
        "dutch": "Pardon. Ik wil graag een kaartje naar Parijs kopen alstublieft.",
        "polish": "Przepraszam. Chciałbym kupić bilet do Paryża proszę.",
        "ukrainian": "Вибачте. Я хотів би купити квиток до Парижа будь ласка.",
        "russian": "Извините. Я хотел бы купить билет в Париж пожалуйста.",
        "swedish": "Ursäkta mig. Jag skulle vilja köpa en biljett till Paris tack.",
        "norwegian": "Unnskyld. Jeg vil gjerne kjøpe en billett til Paris takk.",
        "danish": "Undskyld. Jeg vil gerne købe en billet til Paris tak.",
        "finnish": "Anteeksi. Haluaisin ostaa lipun Pariisiin kiitos.",
        "greek": "Συγγνώμη. Θα ήθελα να αγοράσω ένα εισιτήριο για το Παρίσι παρακαλώ.",
        "brazilian_portuguese": "Com licença. Gostaria de comprar uma passagem para Paris por favor.",
        "mandarin": "打扰一下。我想买一张去巴黎的票。",
        "japanese": "すみません。パリ行きのチケットを購入したいのですが。",
        "korean": "저기요. 파리행 티켓을 사고 싶어요.",
        "hindi": "माफ़ कीजिए। मैं पेरिस का टिकट लेना चाहूँगा।",
        "vietnamese": "Xin lỗi. Tôi muốn mua vé đến Paris.",
        "arabic": "عفواً. أود شراء تذكرة إلى باريس من فضلك.",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "Of course. When would you like to travel?",
        "lithuanian": "Žinoma. Kada norėtumėte keliauti?",
        "latvian": "Protams. Kad jūs vēlētos ceļot?",
        "estonian": "Muidugi. Millal soovite reisida?",
        "german": "Natürlich. Wann möchten Sie reisen?",
        "french": "Bien sûr. Quand souhaitez-vous voyager?",
        "spanish": "Por supuesto. ¿Cuándo le gustaría viajar?",
        "italian": "Certo. Quando vorrebbe viaggiare?",
        "portuguese": "Claro. Quando gostaria de viajar?",
        "dutch": "Natuurlijk. Wanneer wilt u reizen?",
        "polish": "Oczywiście. Kiedy chciałby pan podróżować?",
        "ukrainian": "Звичайно. Коли ви хотіли б подорожувати?",
        "russian": "Конечно. Когда вы хотели бы путешествовать?",
        "swedish": "Naturligtvis. När vill du resa?",
        "norwegian": "Selvfølgelig. Når vil du reise?",
        "danish": "Selvfølgelig. Hvornår vil du rejse?",
        "finnish": "Tietysti. Milloin haluaisitte matkustaa?",
        "greek": "Βεβαίως. Πότε θα θέλατε να ταξιδέψετε;",
        "brazilian_portuguese": "Claro. Quando você gostaria de viajar?",
        "mandarin": "当然。您想什么时候出行？",
        "japanese": "もちろんです。いつご旅行されますか？",
        "korean": "물론이죠. 언제 여행하실 건가요?",
        "hindi": "बिल्कुल। आप कब यात्रा करना चाहेंगे?",
        "vietnamese": "Tất nhiên. Bạn muốn đi khi nào?",
        "arabic": "بالطبع. متى تريد السفر؟",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "This Saturday morning. I want to arrive before noon.",
        "lithuanian": "Šį šeštadienio rytą. Noriu atvykti prieš vidurdienį.",
        "latvian": "Šajā sestdienā no rīta. Es gribu ierasties pirms pusdienlaika.",
        "estonian": "Sel laupäeval hommikul. Tahan saabuda enne lõunat.",
        "german": "Diesen Samstagmorgen. Ich möchte vor dem Mittag ankommen.",
        "french": "Ce samedi matin. Je veux arriver avant midi.",
        "spanish": "Este sábado por la mañana. Quiero llegar antes del mediodía.",
        "italian": "Questo sabato mattina. Voglio arrivare prima di mezzogiorno.",
        "portuguese": "Este sábado de manhã. Quero chegar antes do meio-dia.",
        "dutch": "Deze zaterdagochtend. Ik wil voor de middag aankomen.",
        "polish": "W tę sobotę rano. Chcę dotrzeć przed południem.",
        "ukrainian": "Цієї суботи вранці. Хочу прибути до полудня.",
        "russian": "В эту субботу утром. Хочу приехать до полудня.",
        "swedish": "Denna lördagsmorgon. Jag vill komma fram innan middag.",
        "norwegian": "Denne lørdagsmorgenen. Jeg vil ankomme før middag.",
        "danish": "Denne lørdag morgen. Jeg vil ankomme inden middag.",
        "finnish": "Tänä lauantaiaamuna. Haluan saapua ennen puoltapäivää.",
        "greek": "Αυτό το Σάββατο το πρωί. Θέλω να φτάσω πριν το μεσημέρι.",
        "brazilian_portuguese": "Neste sábado de manhã. Quero chegar antes do meio-dia.",
        "mandarin": "这个周六早上。我想在中午之前到达。",
        "japanese": "今週の土曜日の朝です。正午前に到着したいです。",
        "korean": "이번 토요일 아침이요. 정오 전에 도착하고 싶어요.",
        "hindi": "इस शनिवार की सुबह। मैं दोपहर से पहले पहुँचना चाहता हूँ।",
        "vietnamese": "Sáng thứ bảy này. Tôi muốn đến trước buổi trưa.",
        "arabic": "صباح هذا السبت. أريد الوصول قبل الظهر.",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "There is a train at seven fifteen. It arrives in Paris at eleven forty. Is that good?",
        "lithuanian": "Yra traukinys 7:15. Jis atvyksta į Paryžių 11:40. Ar tai tinka?",
        "latvian": "Ir vilciens plkst. 7:15. Tas ierodas Parīzē plkst. 11:40. Vai tas der?",
        "estonian": "On rong kell 7:15. See saabub Pariisi kell 11:40. Kas see sobib?",
        "german": "Es gibt einen Zug um sieben Uhr fünfzehn. Er kommt um elf Uhr vierzig in Paris an. Ist das gut?",
        "french": "Il y a un train à sept heures quinze. Il arrive à Paris à onze heures quarante. Est-ce que ça vous convient?",
        "spanish": "Hay un tren a las siete y cuarto. Llega a París a las once cuarenta. ¿Le viene bien?",
        "italian": "C'è un treno alle sette e quindici. Arriva a Parigi alle undici e quaranta. Va bene?",
        "portuguese": "Há um comboio às sete e quinze. Chega a Paris às onze e quarenta. Está bom?",
        "dutch": "Er is een trein om zeven uur vijftien. Hij komt om elf uur veertig aan in Parijs. Is dat goed?",
        "polish": "Jest pociąg o 7:15. Przyjeżdża do Paryża o 11:40. Czy to odpowiada?",
        "ukrainian": "Є потяг о 7:15. Він прибуває до Парижа о 11:40. Це підходить?",
        "russian": "Есть поезд в 7:15. Он прибывает в Париж в 11:40. Это подходит?",
        "swedish": "Det finns ett tåg klockan sju femton. Det anländer till Paris klockan elva fyrtio. Är det bra?",
        "norwegian": "Det er et tog klokken syv femten. Det ankommer Paris klokken elleve førti. Er det greit?",
        "danish": "Der er et tog klokken syv femten. Det ankommer Paris klokken elleve fyrre. Er det godt?",
        "finnish": "On juna kello 7:15. Se saapuu Pariisiin kello 11:40. Sopiiko se?",
        "greek": "Υπάρχει τρένο στις επτά και τέταρτο. Φτάνει στο Παρίσι στις έντεκα και σαράντα. Σας βολεύει;",
        "brazilian_portuguese": "Tem um trem às sete e quinze. Chega em Paris às onze e quarenta. Está bom?",
        "mandarin": "有一班七点一刻的火车。十一点四十到达巴黎。这样可以吗？",
        "japanese": "七時十五分の電車があります。パリに十一時四十分に到着します。よろしいですか？",
        "korean": "일곱 시 십오 분 기차가 있어요. 파리에 열한 시 사십 분에 도착해요. 괜찮으세요?",
        "hindi": "सात बजकर पंद्रह मिनट पर एक ट्रेन है। यह पेरिस में ग्यारह बजकर चालीस मिनट पर पहुँचती है। क्या यह ठीक है?",
        "vietnamese": "Có chuyến tàu lúc bảy giờ mười lăm. Đến Paris lúc mười một giờ bốn mươi. Có được không?",
        "arabic": "يوجد قطار الساعة السابعة والربع. يصل إلى باريس الساعة الحادية عشرة وأربعين دقيقة. هل هذا مناسب؟",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "Yes that is perfect. One ticket please. How much is it?",
        "lithuanian": "Taip tai puiku. Vieną bilietą prašau. Kiek kainuoja?",
        "latvian": "Jā tas ir lieliski. Vienu biļeti lūdzu. Cik tas maksā?",
        "estonian": "Jah see on suurepärane. Üks pilet palun. Kui palju see maksab?",
        "german": "Ja das ist perfekt. Eine Fahrkarte bitte. Wie viel kostet sie?",
        "french": "Oui c'est parfait. Un billet s'il vous plaît. Combien ça coûte?",
        "spanish": "Sí es perfecto. Un billete por favor. ¿Cuánto cuesta?",
        "italian": "Sì è perfetto. Un biglietto per favore. Quanto costa?",
        "portuguese": "Sim é perfeito. Um bilhete por favor. Quanto custa?",
        "dutch": "Ja dat is perfect. Één kaartje alstublieft. Hoeveel kost het?",
        "polish": "Tak to doskonałe. Jeden bilet proszę. Ile kosztuje?",
        "ukrainian": "Так це чудово. Один квиток будь ласка. Скільки коштує?",
        "russian": "Да это отлично. Один билет пожалуйста. Сколько стоит?",
        "swedish": "Ja det är perfekt. En biljett tack. Hur mycket kostar det?",
        "norwegian": "Ja det er perfekt. En billett takk. Hvor mye koster det?",
        "danish": "Ja det er perfekt. En billet tak. Hvor meget koster det?",
        "finnish": "Kyllä se on täydellinen. Yksi lippu kiitos. Paljonko se maksaa?",
        "greek": "Ναι είναι τέλειο. Ένα εισιτήριο παρακαλώ. Πόσο κοστίζει;",
        "brazilian_portuguese": "Sim é perfeito. Uma passagem por favor. Quanto custa?",
        "mandarin": "是的，太好了。一张票。多少钱？",
        "japanese": "はい完璧です。一枚ください。いくらですか？",
        "korean": "네 완벽해요. 표 한 장 주세요. 얼마예요?",
        "hindi": "हाँ यह बिल्कुल सही है। एक टिकट दीजिए। कितना है?",
        "vietnamese": "Vâng hoàn hảo. Một vé. Bao nhiêu tiền?",
        "arabic": "نعم هذا مثالي. تذكرة واحدة من فضلك. كم سعرها؟",
    },
    {
        "line_number": 6, "speaker_name": "Mia",
        "english": "A second class ticket is sixty-five euros. First class is ninety euros.",
        "lithuanian": "Antros klasės bilietas yra šešiasdešimt penki eurai. Pirmos klasės devyniasdešimt eurų.",
        "latvian": "Otrās klases biļete ir sešdesmit pieci eiro. Pirmās klases ir deviņdesmit eiro.",
        "estonian": "Teise klassi pilet on kuuskümmend viis eurot. Esimene klass on üheksakümmend eurot.",
        "german": "Eine Fahrkarte zweiter Klasse kostet fünfundsechzig Euro. Erste Klasse kostet neunzig Euro.",
        "french": "Un billet de deuxième classe coûte soixante-cinq euros. La première classe coûte quatre-vingt-dix euros.",
        "spanish": "Un billete de segunda clase cuesta sesenta y cinco euros. La primera clase cuesta noventa euros.",
        "italian": "Un biglietto di seconda classe costa sessantacinque euro. La prima classe costa novanta euro.",
        "portuguese": "Um bilhete de segunda classe custa sessenta e cinco euros. A primeira classe custa noventa euros.",
        "dutch": "Een tweedeklaskaartje kost vijfenzestig euro. Eerste klas kost negentig euro.",
        "polish": "Bilet drugiej klasy kosztuje sześćdziesiąt pięć euro. Pierwsza klasa kosztuje dziewięćdziesiąt euro.",
        "ukrainian": "Квиток другого класу коштує шістдесят п'ять євро. Перший клас — дев'яносто євро.",
        "russian": "Билет второго класса стоит шестьдесят пять евро. Первый класс — девяносто евро.",
        "swedish": "En biljett i andra klass kostar sextio fem euro. Första klass kostar nittio euro.",
        "norwegian": "En billett i andre klasse koster seksti fem euro. Første klasse koster nitti euro.",
        "danish": "En billet i anden klasse koster femogtreds euro. Første klasse koster halvfems euro.",
        "finnish": "Toisen luokan lippu on kuusikymmentäviisi euroa. Ensimmäinen luokka on yhdeksänkymmentä euroa.",
        "greek": "Ένα εισιτήριο δεύτερης θέσης κοστίζει εξήντα πέντε ευρώ. Η πρώτη θέση κοστίζει ενενήντα ευρώ.",
        "brazilian_portuguese": "Uma passagem de segunda classe custa sessenta e cinco euros. A primeira classe custa noventa euros.",
        "mandarin": "二等座票六十五欧元。头等座九十欧元。",
        "japanese": "二等席のチケットは六十五ユーロです。一等席は九十ユーロです。",
        "korean": "2등석 티켓은 육십오 유로예요. 1등석은 구십 유로예요.",
        "hindi": "दूसरी श्रेणी का टिकट पैंसठ यूरो है। प्रथम श्रेणी नब्बे यूरो।",
        "vietnamese": "Vé hạng hai là sáu mươi lăm euro. Hạng nhất là chín mươi euro.",
        "arabic": "تذكرة الدرجة الثانية بخمسة وستين يورو. الدرجة الأولى بتسعين يورو.",
    },
    {
        "line_number": 7, "speaker_name": "Alex",
        "english": "Second class is fine. Is there a seat near the window available?",
        "lithuanian": "Antros klasės pakanka. Ar yra laisva vieta prie lango?",
        "latvian": "Otrā klase ir labi. Vai ir pieejama vieta pie loga?",
        "estonian": "Teine klass on hea. Kas on akna lähedal koht vaba?",
        "german": "Zweite Klasse ist gut. Gibt es einen freien Sitzplatz am Fenster?",
        "french": "La deuxième classe c'est bien. Y a-t-il une place disponible près de la fenêtre?",
        "spanish": "La segunda clase está bien. ¿Hay un asiento disponible cerca de la ventana?",
        "italian": "La seconda classe va bene. C'è un posto vicino al finestrino disponibile?",
        "portuguese": "A segunda classe está bem. Há um lugar disponível perto da janela?",
        "dutch": "Tweede klas is goed. Is er een stoel bij het raam beschikbaar?",
        "polish": "Druga klasa wystarczy. Czy jest wolne miejsce przy oknie?",
        "ukrainian": "Другий клас підходить. Чи є вільне місце біля вікна?",
        "russian": "Второй класс подойдёт. Есть ли свободное место у окна?",
        "swedish": "Andra klass duger. Finns det en plats vid fönstret tillgänglig?",
        "norwegian": "Andre klasse er bra. Er det et sete ved vinduet tilgjengelig?",
        "danish": "Anden klasse er fint. Er der et sæde ved vinduet tilgængeligt?",
        "finnish": "Toinen luokka riittää. Onko ikkunapaikka vapaana?",
        "greek": "Η δεύτερη θέση είναι καλά. Υπάρχει διαθέσιμη θέση κοντά στο παράθυρο;",
        "brazilian_portuguese": "Segunda classe está bom. Tem algum assento disponível perto da janela?",
        "mandarin": "二等座就好。有靠窗的座位吗？",
        "japanese": "二等席で大丈夫です。窓側の席は空いていますか？",
        "korean": "2등석도 괜찮아요. 창가 자리가 있나요?",
        "hindi": "दूसरी श्रेणी ठीक है। क्या खिड़की के पास कोई सीट उपलब्ध है?",
        "vietnamese": "Hạng hai được rồi. Có chỗ ngồi gần cửa sổ không?",
        "arabic": "الدرجة الثانية جيدة. هل يوجد مقعد بالقرب من النافذة؟",
    },
    {
        "line_number": 8, "speaker_name": "Mia",
        "english": "Yes seat twenty-three B is free. It is a window seat on the left side.",
        "lithuanian": "Taip vieta dvidešimt trys B yra laisva. Tai lango vieta kairėje pusėje.",
        "latvian": "Jā vieta divdesmit trīs B ir brīva. Tā ir loga vieta kreisajā pusē.",
        "estonian": "Jah koht kakskümmend kolm B on vaba. See on aknakoht vasakul pool.",
        "german": "Ja Sitzplatz dreiundzwanzig B ist frei. Es ist ein Fensterplatz auf der linken Seite.",
        "french": "Oui le siège vingt-trois B est libre. C'est une place côté fenêtre sur le côté gauche.",
        "spanish": "Sí el asiento veintitrés B está libre. Es un asiento de ventana en el lado izquierdo.",
        "italian": "Sì il posto ventitré B è libero. È un posto finestrino sul lato sinistro.",
        "portuguese": "Sim o lugar vinte e três B está livre. É um lugar de janela do lado esquerdo.",
        "dutch": "Ja stoel drieëntwintig B is vrij. Het is een raamstoel aan de linkerkant.",
        "polish": "Tak miejsce dwadzieścia trzy B jest wolne. To miejsce przy oknie po lewej stronie.",
        "ukrainian": "Так місце двадцять три B вільне. Це місце біля вікна з лівого боку.",
        "russian": "Да место двадцать три B свободно. Это место у окна с левой стороны.",
        "swedish": "Ja säte tjugotre B är ledigt. Det är ett fönsterplats på vänster sida.",
        "norwegian": "Ja sete tjuetre B er ledig. Det er en vindusplass på venstre side.",
        "danish": "Ja sæde treogtyve B er ledigt. Det er et vinduesæde på den venstre side.",
        "finnish": "Kyllä paikka kaksikymmentäkolme B on vapaa. Se on ikkunapaikka vasemmalla puolella.",
        "greek": "Ναι η θέση είκοσι τρία Β είναι ελεύθερη. Είναι θέση παραθύρου στην αριστερή πλευρά.",
        "brazilian_portuguese": "Sim o assento vinte e três B está livre. É um assento de janela no lado esquerdo.",
        "mandarin": "是的，二十三号B座是空的。是左侧的靠窗座位。",
        "japanese": "はい二十三番Bの席が空いています。左側の窓際の席です。",
        "korean": "네, 이십삼번 B석이 비어 있어요. 왼쪽 창가 자리예요.",
        "hindi": "हाँ सीट तेईस बी खाली है। यह बाईं तरफ की खिड़की वाली सीट है।",
        "vietnamese": "Vâng ghế hai mươi ba B trống. Đó là ghế cửa sổ bên trái.",
        "arabic": "نعم المقعد ثلاثة وعشرون ب شاغر. إنه مقعد نافذة على الجانب الأيسر.",
    },
    {
        "line_number": 9, "speaker_name": "Alex",
        "english": "Wonderful. I will take that seat. Do I need to reserve it?",
        "lithuanian": "Puiku. Paimsiu tą vietą. Ar reikia ją rezervuoti?",
        "latvian": "Brīnišķīgi. Es ņemšu to vietu. Vai man tā ir jārezervē?",
        "estonian": "Suurepärane. Võtan selle koha. Kas ma pean seda broneerima?",
        "german": "Wunderbar. Ich nehme diesen Platz. Muss ich ihn reservieren?",
        "french": "Merveilleux. Je prends cette place. Dois-je la réserver?",
        "spanish": "Maravilloso. Tomaré ese asiento. ¿Necesito reservarlo?",
        "italian": "Meraviglioso. Prendo quel posto. Devo prenotarlo?",
        "portuguese": "Maravilhoso. Fico com esse lugar. Preciso de o reservar?",
        "dutch": "Geweldig. Ik neem die stoel. Moet ik hem reserveren?",
        "polish": "Wspaniale. Wezmę to miejsce. Czy muszę je zarezerwować?",
        "ukrainian": "Чудово. Візьму це місце. Чи потрібно його бронювати?",
        "russian": "Замечательно. Возьму это место. Нужно ли его резервировать?",
        "swedish": "Underbart. Jag tar den platsen. Behöver jag boka den?",
        "norwegian": "Flott. Jeg tar det setet. Trenger jeg å reservere det?",
        "danish": "Vidunderligt. Jeg tager det sæde. Behøver jeg at reservere det?",
        "finnish": "Mahtavaa. Otan sen paikan. Pitääkö se varata?",
        "greek": "Υπέροχο. Θα πάρω αυτή τη θέση. Χρειάζεται να την κλείσω;",
        "brazilian_portuguese": "Maravilhoso. Vou ficar com esse assento. Preciso reservá-lo?",
        "mandarin": "太好了。我就要那个座位。需要预订吗？",
        "japanese": "素晴らしいです。その席にします。予約する必要がありますか？",
        "korean": "좋아요. 그 자리로 할게요. 예약해야 하나요?",
        "hindi": "शानदार। मैं वह सीट लूँगा। क्या मुझे इसे बुक करना होगा?",
        "vietnamese": "Tuyệt vời. Tôi sẽ lấy chỗ đó. Tôi có cần đặt trước không?",
        "arabic": "رائع. سآخذ ذلك المقعد. هل أحتاج لحجزه؟",
    },
    {
        "line_number": 10, "speaker_name": "Mia",
        "english": "The seat reservation is included in the ticket price. Here is your ticket.",
        "lithuanian": "Vietos rezervacija įtraukta į bilieto kainą. Štai jūsų bilietas.",
        "latvian": "Vietas rezervācija ir iekļauta biļetes cenā. Lūk jūsu biļete.",
        "estonian": "Kohabroneering sisaldub piletihinna. Siin on teie pilet.",
        "german": "Die Sitzplatzreservierung ist im Ticketpreis inbegriffen. Hier ist Ihre Fahrkarte.",
        "french": "La réservation de siège est incluse dans le prix du billet. Voici votre billet.",
        "spanish": "La reserva de asiento está incluida en el precio del billete. Aquí tiene su billete.",
        "italian": "La prenotazione del posto è inclusa nel prezzo del biglietto. Ecco il suo biglietto.",
        "portuguese": "A reserva de lugar está incluída no preço do bilhete. Aqui está o seu bilhete.",
        "dutch": "De stoelreservering is inbegrepen in de ticketprijs. Hier is uw kaartje.",
        "polish": "Rezerwacja miejsca jest wliczona w cenę biletu. Oto pana bilet.",
        "ukrainian": "Бронювання місця включено у вартість квитка. Ось ваш квиток.",
        "russian": "Резервация места включена в стоимость билета. Вот ваш билет.",
        "swedish": "Platsreserveringen ingår i biljettpriset. Här är din biljett.",
        "norwegian": "Setereservasjonen er inkludert i billettprisen. Her er billetten din.",
        "danish": "Sædereservationen er inkluderet i billetprisen. Her er din billet.",
        "finnish": "Paikkavaraus sisältyy lipun hintaan. Tässä on lippunne.",
        "greek": "Η κράτηση θέσης περιλαμβάνεται στην τιμή του εισιτηρίου. Ορίστε το εισιτήριό σας.",
        "brazilian_portuguese": "A reserva de assento está incluída no preço da passagem. Aqui está a sua passagem.",
        "mandarin": "座位预订已包含在票价中。这是您的票。",
        "japanese": "座席予約はチケット代に含まれています。こちらがお客様のチケットです。",
        "korean": "좌석 예약은 티켓 가격에 포함되어 있어요. 여기 티켓입니다.",
        "hindi": "सीट आरक्षण टिकट की कीमत में शामिल है। यह रहा आपका टिकट।",
        "vietnamese": "Đặt chỗ ngồi đã bao gồm trong giá vé. Đây là vé của bạn.",
        "arabic": "حجز المقعد مشمول في سعر التذكرة. هذه تذكرتك.",
    },
    {
        "line_number": 11, "speaker_name": "Alex",
        "english": "Thank you. Which platform does the train leave from?",
        "lithuanian": "Ačiū. Nuo kurio perono išvyksta traukinys?",
        "latvian": "Paldies. No kura perona vilciens izbrauc?",
        "estonian": "Tänan. Milliselt perroonilt rong väljub?",
        "german": "Danke. Von welchem Gleis fährt der Zug ab?",
        "french": "Merci. De quel quai part le train?",
        "spanish": "Gracias. ¿De qué andén sale el tren?",
        "italian": "Grazie. Da quale binario parte il treno?",
        "portuguese": "Obrigado. De que cais parte o comboio?",
        "dutch": "Dank u. Van welk perron vertrekt de trein?",
        "polish": "Dziękuję. Z którego peronu odjeżdża pociąg?",
        "ukrainian": "Дякую. З якої платформи відправляється потяг?",
        "russian": "Спасибо. С какой платформы отправляется поезд?",
        "swedish": "Tack. Från vilket spår avgår tåget?",
        "norwegian": "Takk. Fra hvilken plattform avgår toget?",
        "danish": "Tak. Fra hvilken perron afgår toget?",
        "finnish": "Kiitos. Miltä laiturelta juna lähtee?",
        "greek": "Ευχαριστώ. Από ποια αποβάθρα φεύγει το τρένο;",
        "brazilian_portuguese": "Obrigado. De que plataforma o trem parte?",
        "mandarin": "谢谢。火车从哪个站台出发？",
        "japanese": "ありがとうございます。電車はどのホームから出発しますか？",
        "korean": "감사합니다. 기차가 몇 번 플랫폼에서 출발하나요?",
        "hindi": "धन्यवाद। ट्रेन किस प्लेटफॉर्म से जाती है?",
        "vietnamese": "Cảm ơn. Tàu khởi hành từ sân ga nào?",
        "arabic": "شكراً. من أي رصيف يغادر القطار؟",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "Platform four. Please check the board for any changes on the day.",
        "lithuanian": "Ketvirtasis peronas. Prašom patikrinti skelbimų lentą dėl galimų pakeitimų dieną.",
        "latvian": "Ceturtais perons. Lūdzu pārbaudiet tablo dienas laikā, vai nav izmaiņu.",
        "estonian": "Neljas perroon. Palun kontrollige päeval infotahvlit muutuste suhtes.",
        "german": "Gleis vier. Bitte überprüfen Sie am Tag des Abfahrt die Tafel auf mögliche Änderungen.",
        "french": "Quai quatre. Veuillez vérifier le tableau le jour même pour d'éventuels changements.",
        "spanish": "Andén cuatro. Por favor compruebe el tablero el día de viaje por si hay cambios.",
        "italian": "Binario quattro. Si prega di controllare il tabellone il giorno stesso per eventuali cambiamenti.",
        "portuguese": "Cais quatro. Por favor verifique o painel no próprio dia para eventuais alterações.",
        "dutch": "Perron vier. Controleer op de dag zelf het bord op eventuele wijzigingen.",
        "polish": "Peron czwarty. Proszę sprawdzić tablicę w dniu podróży pod kątem ewentualnych zmian.",
        "ukrainian": "Четверта платформа. Перевірте табло в день відправлення щодо можливих змін.",
        "russian": "Четвёртая платформа. В день поездки проверьте табло на наличие изменений.",
        "swedish": "Spår fyra. Kontrollera tavlan på dagen för eventuella ändringar.",
        "norwegian": "Plattform fire. Sjekk tavlen på reisedagen for eventuelle endringer.",
        "danish": "Perron fire. Tjek venligst tavlen på dagen for eventuelle ændringer.",
        "finnish": "Laituri neljä. Tarkistakaa päivänä infotaulu mahdollisten muutosten varalta.",
        "greek": "Αποβάθρα τέσσερα. Παρακαλώ ελέγξτε τον πίνακα την ημέρα για τυχόν αλλαγές.",
        "brazilian_portuguese": "Plataforma quatro. Por favor verifique o painel no dia por possíveis mudanças.",
        "mandarin": "四号站台。请在当天检查显示板，看看是否有变化。",
        "japanese": "四番ホームです。当日は変更がないか掲示板をご確認ください。",
        "korean": "사번 플랫폼이에요. 당일에 변경 사항이 있는지 안내판을 확인해 주세요.",
        "hindi": "प्लेटफॉर्म चार। यात्रा के दिन किसी बदलाव के लिए बोर्ड जांचें।",
        "vietnamese": "Sân ga bốn. Hãy kiểm tra bảng thông tin vào ngày đó để biết có thay đổi không.",
        "arabic": "الرصيف الرابع. يرجى التحقق من اللوحة يوم السفر للتأكد من أي تغييرات.",
    },
    {
        "line_number": 13, "speaker_name": "Alex",
        "english": "Is there a dining car on the train?",
        "lithuanian": "Ar traukinyje yra valgomasis vagonas?",
        "latvian": "Vai vilcienā ir ēdamvagons?",
        "estonian": "Kas rongis on söögiauto?",
        "german": "Gibt es einen Speisewagen im Zug?",
        "french": "Y a-t-il un wagon-restaurant dans le train?",
        "spanish": "¿Hay vagón restaurante en el tren?",
        "italian": "C'è un vagone ristorante sul treno?",
        "portuguese": "Há um vagão restaurante no comboio?",
        "dutch": "Is er een restauratiewagon in de trein?",
        "polish": "Czy w pociągu jest wagon restauracyjny?",
        "ukrainian": "У потязі є вагон-ресторан?",
        "russian": "Есть ли в поезде вагон-ресторан?",
        "swedish": "Finns det en restaurangvagn på tåget?",
        "norwegian": "Er det en spisevogn på toget?",
        "danish": "Er der en spisevogn på toget?",
        "finnish": "Onko junassa ravintolavaunu?",
        "greek": "Υπάρχει βαγόνι εστιατόριο στο τρένο;",
        "brazilian_portuguese": "Tem vagão restaurante no trem?",
        "mandarin": "火车上有餐车吗？",
        "japanese": "電車に食堂車はありますか？",
        "korean": "기차에 식당 칸이 있나요?",
        "hindi": "क्या ट्रेन में डाइनिंग कार है?",
        "vietnamese": "Có toa ăn trên tàu không?",
        "arabic": "هل يوجد عربة طعام في القطار؟",
    },
    {
        "line_number": 14, "speaker_name": "Mia",
        "english": "Yes there is. It is in wagon five. They serve hot drinks and sandwiches.",
        "lithuanian": "Taip yra. Jis yra penktame vagone. Ten patiekiami karšti gėrimai ir sumuštiniai.",
        "latvian": "Jā ir. Tas ir piektajā vagonā. Tur pasniedz karstus dzērienus un sviestmaizes.",
        "estonian": "Jah on. See on viiendas vagunis. Seal serveeritakse kuumi jooke ja võileibu.",
        "german": "Ja gibt es. Er ist in Wagen fünf. Es werden heiße Getränke und Sandwiches serviert.",
        "french": "Oui il y en a un. Il est dans le wagon cinq. On y sert des boissons chaudes et des sandwichs.",
        "spanish": "Sí hay uno. Está en el vagón cinco. Sirven bebidas calientes y sándwiches.",
        "italian": "Sì c'è. È nel vagone cinque. Servono bevande calde e panini.",
        "portuguese": "Sim há. Fica no vagão cinco. Servem bebidas quentes e sandes.",
        "dutch": "Ja die is er. Het is in wagon vijf. Er worden warme dranken en sandwiches geserveerd.",
        "polish": "Tak jest. Jest w wagonie piątym. Serwują ciepłe napoje i kanapki.",
        "ukrainian": "Так є. Він у п'ятому вагоні. Там подають гарячі напої та сендвічі.",
        "russian": "Да есть. Он в пятом вагоне. Там подают горячие напитки и бутерброды.",
        "swedish": "Ja det finns. Det är i vagn fem. De serverar varma drycker och smörgåsar.",
        "norwegian": "Ja det er det. Det er i vogn fem. De serverer varme drikker og smørbrød.",
        "danish": "Ja det er der. Det er i vogn fem. De serverer varme drikkevarer og sandwicher.",
        "finnish": "Kyllä on. Se on viidennessä vaunussa. Siellä tarjoillaan kuumia juomia ja voileipiä.",
        "greek": "Ναι υπάρχει. Είναι στο βαγόνι πέντε. Σερβίρουν ζεστά ροφήματα και σάντουιτς.",
        "brazilian_portuguese": "Sim tem. Está no vagão cinco. Servem bebidas quentes e sanduíches.",
        "mandarin": "有的。在五号车厢。供应热饮和三明治。",
        "japanese": "はいあります。五号車です。ホットドリンクとサンドイッチを提供しています。",
        "korean": "네 있어요. 5호 차에 있어요. 뜨거운 음료와 샌드위치를 제공해요.",
        "hindi": "हाँ है। यह पाँचवें डिब्बे में है। वे गर्म पेय और सैंडविच परोसते हैं।",
        "vietnamese": "Vâng có. Nó ở toa số năm. Họ phục vụ đồ uống nóng và bánh mì kẹp.",
        "arabic": "نعم يوجد. إنه في العربة الخامسة. يقدمون مشروبات ساخنة وسندويشات.",
    },
    {
        "line_number": 15, "speaker_name": "Alex",
        "english": "Good. Is the train usually on time?",
        "lithuanian": "Gerai. Ar traukinys paprastai nevėluoja?",
        "latvian": "Labi. Vai vilciens parasti ir laikā?",
        "estonian": "Hea. Kas rong on tavaliselt õigeaegselt?",
        "german": "Gut. Ist der Zug normalerweise pünktlich?",
        "french": "Bien. Le train est-il généralement à l'heure?",
        "spanish": "Bien. ¿Suele llegar el tren puntualmente?",
        "italian": "Bene. Il treno è di solito in orario?",
        "portuguese": "Bem. O comboio costuma ser pontual?",
        "dutch": "Goed. Is de trein normaal op tijd?",
        "polish": "Dobrze. Czy pociąg jest zwykle punktualny?",
        "ukrainian": "Добре. Чи потяг зазвичай вчасно?",
        "russian": "Хорошо. Обычно ли поезд приходит вовремя?",
        "swedish": "Bra. Är tåget vanligtvis i tid?",
        "norwegian": "Bra. Er toget vanligvis i rute?",
        "danish": "Godt. Er toget normalt til tiden?",
        "finnish": "Hyvä. Onko juna yleensä ajallaan?",
        "greek": "Καλά. Το τρένο είναι συνήθως στην ώρα του;",
        "brazilian_portuguese": "Bom. O trem costuma ser pontual?",
        "mandarin": "好的。火车通常准时吗？",
        "japanese": "いいですね。この電車は通常時間通りですか？",
        "korean": "좋아요. 기차가 보통 제때 오나요?",
        "hindi": "अच्छा। क्या ट्रेन आमतौर पर समय पर आती है?",
        "vietnamese": "Tốt. Tàu thường đúng giờ không?",
        "arabic": "جيد. هل القطار في الموعد المحدد عادةً؟",
    },
    {
        "line_number": 16, "speaker_name": "Mia",
        "english": "Usually yes. Delays are rare on this route. Maybe five minutes sometimes.",
        "lithuanian": "Paprastai taip. Vėlavimai šiame maršrute yra reti. Gal kartais penkios minutės.",
        "latvian": "Parasti jā. Kavēšanās šajā maršrutā ir reta. Dažreiz varbūt piecas minūtes.",
        "estonian": "Tavaliselt jah. Hilinemised on sellel marsruudil haruldased. Vahel äkki viis minutit.",
        "german": "Normalerweise ja. Verspätungen sind auf dieser Strecke selten. Manchmal vielleicht fünf Minuten.",
        "french": "Généralement oui. Les retards sont rares sur cette ligne. Peut-être cinq minutes parfois.",
        "spanish": "Normalmente sí. Los retrasos son raros en esta ruta. Quizás cinco minutos a veces.",
        "italian": "Di solito sì. I ritardi sono rari su questa tratta. Forse cinque minuti a volte.",
        "portuguese": "Normalmente sim. Os atrasos são raros nesta rota. Talvez cinco minutos às vezes.",
        "dutch": "Gewoonlijk wel. Vertragingen zijn zeldzaam op deze route. Misschien vijf minuten soms.",
        "polish": "Zwykle tak. Opóźnienia na tej trasie są rzadkie. Może pięć minut czasami.",
        "ukrainian": "Зазвичай так. Затримки на цьому маршруті рідкісні. Може, іноді п'ять хвилин.",
        "russian": "Обычно да. Задержки на этом маршруте редки. Иногда, может, пять минут.",
        "swedish": "Vanligtvis ja. Förseningar är sällsynta på den här sträckan. Kanske fem minuter ibland.",
        "norwegian": "Vanligvis ja. Forsinkelser er sjeldne på denne ruten. Kanskje fem minutter noen ganger.",
        "danish": "Normalt ja. Forsinkelser er sjældne på denne rute. Måske fem minutter nogle gange.",
        "finnish": "Yleensä kyllä. Viivästykset ovat harvinaisia tällä reitillä. Ehkä viisi minuuttia joskus.",
        "greek": "Συνήθως ναι. Οι καθυστερήσεις είναι σπάνιες σε αυτή τη διαδρομή. Ίσως πέντε λεπτά μερικές φορές.",
        "brazilian_portuguese": "Normalmente sim. Atrasos são raros nesta rota. Talvez cinco minutos às vezes.",
        "mandarin": "通常是的。这条线路的延误很少见。有时可能五分钟。",
        "japanese": "通常はそうです。このルートでは遅延はめったにありません。時々五分くらいかもしれません。",
        "korean": "보통은요. 이 노선은 지연이 드물어요. 가끔 오 분 정도는 있을 수 있어요.",
        "hindi": "आमतौर पर हाँ। इस रूट पर देरी कम होती है। कभी-कभी पाँच मिनट हो सकते हैं।",
        "vietnamese": "Thường là vậy. Sự chậm trễ rất hiếm trên tuyến này. Đôi khi có thể năm phút.",
        "arabic": "عادةً نعم. التأخيرات نادرة على هذا الخط. ربما خمس دقائق أحياناً.",
    },
    {
        "line_number": 17, "speaker_name": "Alex",
        "english": "That is good to know. Where is the left luggage office? I have a large bag.",
        "lithuanian": "Malonu žinoti. Kur yra bagažo saugykla? Turiu didelį krepšį.",
        "latvian": "Labi to zināt. Kur ir bagāžas glabātava? Man ir liela soma.",
        "estonian": "Hea teada. Kus on pagasihoidla? Mul on suur kott.",
        "german": "Das ist gut zu wissen. Wo ist die Gepäckaufbewahrung? Ich habe eine große Tasche.",
        "french": "C'est bon à savoir. Où est la consigne? J'ai un grand sac.",
        "spanish": "Es bueno saberlo. ¿Dónde está la consigna de equipaje? Tengo una bolsa grande.",
        "italian": "Bello saperlo. Dov'è il deposito bagagli? Ho una borsa grande.",
        "portuguese": "É bom saber. Onde é a bagageira? Tenho uma mala grande.",
        "dutch": "Goed om te weten. Waar is de bagageopslag? Ik heb een grote tas.",
        "polish": "Dobrze wiedzieć. Gdzie jest przechowalnia bagażu? Mam dużą torbę.",
        "ukrainian": "Добре знати. Де знаходиться камера зберігання? У мене велика сумка.",
        "russian": "Хорошо знать. Где находится камера хранения? У меня большая сумка.",
        "swedish": "Bra att veta. Var är bagageförvaringen? Jag har en stor väska.",
        "norwegian": "Godt å vite. Hvor er bagasjeoppbevaringen? Jeg har en stor veske.",
        "danish": "Godt at vide. Hvor er bagageopbevaringen? Jeg har en stor taske.",
        "finnish": "Hyvä tietää. Missä on matkatavarasäilytys? Minulla on iso laukku.",
        "greek": "Καλό να το ξέρω. Πού είναι η φύλαξη αποσκευών; Έχω μια μεγάλη τσάντα.",
        "brazilian_portuguese": "Bom saber. Onde fica o guarda-volumes? Tenho uma bolsa grande.",
        "mandarin": "很好知道。行李寄存处在哪里？我有一个大包。",
        "japanese": "それは知っておいて良かったです。手荷物預かり所はどこですか？大きなバッグがあります。",
        "korean": "알아두면 좋겠네요. 수하물 보관소가 어디 있나요? 큰 가방이 있어요.",
        "hindi": "यह जानना अच्छा है। सामान रखने की जगह कहाँ है? मेरे पास एक बड़ा बैग है।",
        "vietnamese": "Tốt khi biết điều đó. Phòng gửi hành lý ở đâu? Tôi có một túi lớn.",
        "arabic": "جيد أن أعرف ذلك. أين مكتب حفظ الأمتعة؟ لديّ حقيبة كبيرة.",
    },
    {
        "line_number": 18, "speaker_name": "Mia",
        "english": "It is on the ground floor near entrance B. It costs three euros per bag per day.",
        "lithuanian": "Ji yra pirmame aukšte prie įėjimo B. Kainuoja trys eurai per krepšį per dieną.",
        "latvian": "Tā atrodas pirmajā stāvā pie ieejas B. Tas maksā trīs eiro par somu dienā.",
        "estonian": "See on esimesel korrusel sissepääsu B juures. See maksab kolm eurot koti kohta päevas.",
        "german": "Sie befindet sich im Erdgeschoss in der Nähe von Eingang B. Es kostet drei Euro pro Tasche pro Tag.",
        "french": "Elle est au rez-de-chaussée près de l'entrée B. Ça coûte trois euros par bagage par jour.",
        "spanish": "Está en la planta baja cerca de la entrada B. Cuesta tres euros por bolsa al día.",
        "italian": "Si trova al piano terra vicino all'ingresso B. Costa tre euro per borsa al giorno.",
        "portuguese": "Fica no rés do chão perto da entrada B. Custa três euros por mala por dia.",
        "dutch": "Het is op de begane grond bij ingang B. Het kost drie euro per tas per dag.",
        "polish": "Znajduje się na parterze przy wejściu B. Kosztuje trzy euro za torbę na dzień.",
        "ukrainian": "Вона знаходиться на першому поверсі біля входу B. Це коштує три євро за сумку на день.",
        "russian": "Она находится на первом этаже у входа B. Это стоит три евро за сумку в день.",
        "swedish": "Det är på bottenvåningen nära ingång B. Det kostar tre euro per väska per dag.",
        "norwegian": "Det er i første etasje nær inngang B. Det koster tre euro per veske per dag.",
        "danish": "Det er i stueetagen nær indgang B. Det koster tre euro per taske per dag.",
        "finnish": "Se on pohjakerroksessa sisäänkäynti B:n lähellä. Se maksaa kolme euroa laukkua kohden päivässä.",
        "greek": "Είναι στο ισόγειο κοντά στην είσοδο Β. Κοστίζει τρία ευρώ ανά τσάντα ανά ημέρα.",
        "brazilian_portuguese": "Fica no térreo perto da entrada B. Custa três euros por bolsa por dia.",
        "mandarin": "在B入口附近的一楼。每袋每天三欧元。",
        "japanese": "B入口近くの一階にあります。一袋一日三ユーロです。",
        "korean": "B 입구 근처 1층에 있어요. 가방 하나당 하루 삼 유로예요.",
        "hindi": "यह B प्रवेश द्वार के पास भूतल पर है। प्रति बैग प्रति दिन तीन यूरो लगते हैं।",
        "vietnamese": "Ở tầng trệt gần lối vào B. Mỗi túi mỗi ngày ba euro.",
        "arabic": "إنه في الطابق الأرضي بالقرب من المدخل ب. يكلف ثلاثة يورو في اليوم للحقيبة الواحدة.",
    },
    {
        "line_number": 19, "speaker_name": "Alex",
        "english": "Perfect. Is there a cafe in the station where I can wait?",
        "lithuanian": "Puiku. Ar stotyje yra kavinė, kur galiu palaukti?",
        "latvian": "Lieliski. Vai stacijā ir kafejnīca, kur varu pagaidīt?",
        "estonian": "Suurepärane. Kas jaamas on kohvik kus saab oodata?",
        "german": "Perfekt. Gibt es ein Café im Bahnhof wo ich warten kann?",
        "french": "Parfait. Y a-t-il un café dans la gare où je peux attendre?",
        "spanish": "Perfecto. ¿Hay una cafetería en la estación donde pueda esperar?",
        "italian": "Perfetto. C'è un bar nella stazione dove posso aspettare?",
        "portuguese": "Perfeito. Há um café na estação onde possa esperar?",
        "dutch": "Perfect. Is er een café in het station waar ik kan wachten?",
        "polish": "Świetnie. Czy na stacji jest kawiarnia gdzie mogę poczekać?",
        "ukrainian": "Чудово. Чи є на вокзалі кафе де я можу почекати?",
        "russian": "Отлично. Есть ли на вокзале кафе где я могу подождать?",
        "swedish": "Perfekt. Finns det ett café på stationen där jag kan vänta?",
        "norwegian": "Perfekt. Er det en kafé på stasjonen der jeg kan vente?",
        "danish": "Perfekt. Er der en cafe på stationen, hvor jeg kan vente?",
        "finnish": "Täydellinen. Onko asemalla kahvila jossa voin odottaa?",
        "greek": "Τέλεια. Υπάρχει ένα καφέ στο σταθμό όπου μπορώ να περιμένω;",
        "brazilian_portuguese": "Perfeito. Tem um café na estação onde eu possa esperar?",
        "mandarin": "太好了。车站里有咖啡馆可以等车吗？",
        "japanese": "完璧です。駅に待てるカフェはありますか？",
        "korean": "완벽해요. 역에서 기다릴 수 있는 카페가 있나요?",
        "hindi": "बढ़िया। क्या स्टेशन में कोई कैफे है जहाँ मैं इंतज़ार कर सकता हूँ?",
        "vietnamese": "Tuyệt vời. Có quán cà phê nào trong ga để tôi chờ không?",
        "arabic": "ممتاز. هل يوجد مقهى في المحطة يمكنني الانتظار فيه؟",
    },
    {
        "line_number": 20, "speaker_name": "Mia",
        "english": "Yes there is a nice cafe on the first floor. It has a view of the platforms so you can watch for your train. Have a wonderful journey!",
        "lithuanian": "Taip, pirmame aukšte yra graži kavinė. Ji turi vaizdą į peronų, todėl galite stebėti savo traukinį. Puikios kelionės!",
        "latvian": "Jā, pirmajā stāvā ir laba kafejnīca. Tajā ir skats uz peroniem, tāpēc varat novērot savu vilcienu. Brīnišķīgu ceļojumu!",
        "estonian": "Jah, esimesel korrusel on armas kohvik. Sellest on vaade perroonidele nii et saate oma rongi jälgida. Head reisi!",
        "german": "Ja, es gibt ein nettes Café im ersten Stock. Es hat Blick auf die Gleise, sodass Sie nach Ihrem Zug Ausschau halten können. Gute Reise!",
        "french": "Oui il y a un joli café au premier étage. Il a une vue sur les quais donc vous pouvez guetter votre train. Bon voyage!",
        "spanish": "Sí hay un bonito café en el primer piso. Tiene vista a los andenes por lo que puede ver su tren. ¡Que tenga un buen viaje!",
        "italian": "Sì c'è un bel bar al primo piano. Ha una vista sui binari quindi può tenere d'occhio il suo treno. Buon viaggio!",
        "portuguese": "Sim há um bom café no primeiro andar. Tem vista para as plataformas por isso pode ver o seu comboio. Boa viagem!",
        "dutch": "Ja er is een leuk café op de eerste verdieping. Het heeft uitzicht op de perrons zodat u uw trein in de gaten kunt houden. Goede reis!",
        "polish": "Tak jest ładna kawiarnia na pierwszym piętrze. Ma widok na perony więc może pan obserwować swój pociąg. Udanej podróży!",
        "ukrainian": "Так, на першому поверсі є затишне кафе. З нього відкривається вид на перони, тому ви можете спостерігати за своїм потягом. Чудової подорожі!",
        "russian": "Да, на первом этаже есть уютное кафе. Из него открывается вид на платформы, так что вы можете наблюдать за своим поездом. Счастливого пути!",
        "swedish": "Ja det finns ett trevligt café på första våningen. Det har utsikt över spåren så du kan hålla utkik efter ditt tåg. Ha en underbar resa!",
        "norwegian": "Ja det er en hyggelig kafé i første etasje. Den har utsikt over plattformene så du kan se etter toget ditt. God reise!",
        "danish": "Ja der er en dejlig cafe på første sal. Den har udsigt over perroner så du kan holde øje med dit tog. God rejse!",
        "finnish": "Kyllä, ensimmäisessä kerroksessa on mukava kahvila. Sieltä on näkymä laitureille joten voit tarkkailla junasi saapumista. Hyvää matkaa!",
        "greek": "Ναι υπάρχει ένα ωραίο καφέ στον πρώτο όροφο. Έχει θέα στις αποβάθρες έτσι μπορείτε να παρακολουθείτε για το τρένο σας. Καλό ταξίδι!",
        "brazilian_portuguese": "Sim há um café agradável no primeiro andar. Tem vista para as plataformas então você pode ficar de olho no trem. Boa viagem!",
        "mandarin": "是的，一楼有一家很好的咖啡馆。可以看到站台，这样您就可以留意您的火车。旅途愉快！",
        "japanese": "はい、一階に素敵なカフェがあります。ホームが見えるので電車を確認できますよ。素晴らしい旅を！",
        "korean": "네, 1층에 좋은 카페가 있어요. 플랫폼이 보여서 기차를 확인할 수 있어요. 좋은 여행 되세요!",
        "hindi": "हाँ, पहली मंजिल पर एक अच्छा कैफे है। वहाँ से प्लेटफॉर्म दिखते हैं इसलिए आप अपनी ट्रेन देख सकते हैं। शानदार यात्रा हो!",
        "vietnamese": "Vâng có một quán cà phê tuyệt đẹp ở tầng một. Nhìn ra các sân ga để bạn có thể theo dõi tàu của mình. Chúc bạn có chuyến đi tuyệt vời!",
        "arabic": "نعم يوجد مقهى جميل في الطابق الأول. يطل على الأرصفة حتى تتمكن من مراقبة قطارك. أتمنى لك رحلة رائعة!",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="At the Train Station").first()
        if existing:
            print("A2 dialogue 'At the Train Station' already exists — skipping.")
            return

        dialogue = Dialogue(topic="At the Train Station", lang_level="A2", length=20)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded A2 dialogue ID {dialogue.id} — 20 lines in 25 languages.")


if __name__ == '__main__':
    seed()
