import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "I have been trying to live more healthily lately. Have you made any changes too?",
        "lithuanian": "Pastaruoju metu stengiuosi gyventi sveikiau. Ar tu taip pat padarei kokių nors pokyčių?",
        "latvian": "Pēdējā laikā esmu mēģinājis dzīvot veselīgāk. Vai arī tu esi veicis kādas izmaiņas?",
        "estonian": "Viimasel ajal olen püüdnud elada tervislikumalt. Kas sina oled ka muudatusi teinud?",
        "german": "Ich versuche in letzter Zeit gesünder zu leben. Hast du auch Änderungen vorgenommen?",
        "french": "J'essaie de vivre plus sainement ces derniers temps. As-tu aussi fait des changements?",
        "spanish": "Últimamente estoy intentando vivir de manera más saludable. ¿Tú también has hecho cambios?",
        "italian": "Ultimamente sto cercando di vivere in modo più sano. Hai fatto dei cambiamenti anche tu?",
        "portuguese": "Ultimamente tenho tentado viver de forma mais saudável. Também fizeste algumas mudanças?",
        "dutch": "Ik probeer de laatste tijd gezonder te leven. Heb jij ook veranderingen gemaakt?",
        "polish": "Ostatnio staram się żyć zdrowiej. Czy też wprowadziłeś jakieś zmiany?",
        "ukrainian": "Останнім часом намагаюся жити здоровіше. Чи ти теж щось змінив?",
        "russian": "В последнее время стараюсь жить здоровее. Ты тоже что-то изменил?",
        "swedish": "Jag försöker leva hälsosammare på sistone. Har du också gjort några förändringar?",
        "norwegian": "Jeg har prøvd å leve sunnere i det siste. Har du også gjort noen endringer?",
        "danish": "Jeg har forsøgt at leve sundere på det seneste. Har du også foretaget ændringer?",
        "finnish": "Olen yrittänyt elää terveellisemmin viime aikoina. Oletko sinäkin tehnyt muutoksia?",
        "greek": "Τελευταία προσπαθώ να ζω πιο υγιεινά. Έχεις κάνει κι εσύ αλλαγές;",
        "brazilian_portuguese": "Ultimamente tenho tentado viver de forma mais saudável. Você também fez alguma mudança?",
        "mandarin": "最近我一直在努力更健康地生活。你也有什么改变吗？",
        "japanese": "最近、より健康的に生活しようとしています。あなたも変化を加えましたか？",
        "korean": "최근에 더 건강하게 살려고 노력하고 있어요. 당신도 변화를 줬나요?",
        "hindi": "मैं हाल ही में अधिक स्वस्थ जीवन जीने की कोशिश कर रहा हूँ। क्या तुमने भी कोई बदलाव किए हैं?",
        "vietnamese": "Gần đây tôi đang cố gắng sống lành mạnh hơn. Bạn cũng có thay đổi gì không?",
        "arabic": "أحاول مؤخراً أن أعيش بصحة أفضل. هل أجريت أنت أيضاً بعض التغييرات؟",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "Yes I started running three times a week. It has made a big difference.",
        "lithuanian": "Taip, pradėjau bėgioti tris kartus per savaitę. Tai labai pakeitė situaciją.",
        "latvian": "Jā, es sāku skriet trīs reizes nedēļā. Tas ir daudz mainījis.",
        "estonian": "Jah, hakkasin kolm korda nädalas jooksma. See on palju muutnud.",
        "german": "Ja, ich habe angefangen dreimal die Woche zu laufen. Das hat einen großen Unterschied gemacht.",
        "french": "Oui j'ai commencé à courir trois fois par semaine. Ça a fait une grande différence.",
        "spanish": "Sí empecé a correr tres veces a la semana. Ha marcado una gran diferencia.",
        "italian": "Sì ho iniziato a correre tre volte a settimana. Ha fatto una grande differenza.",
        "portuguese": "Sim comecei a correr três vezes por semana. Fez uma grande diferença.",
        "dutch": "Ja ik begon drie keer per week te hardlopen. Dat heeft een groot verschil gemaakt.",
        "polish": "Tak zaczęłam biegać trzy razy w tygodniu. To zrobiło dużą różnicę.",
        "ukrainian": "Так, я почала бігати тричі на тиждень. Це дуже змінило ситуацію.",
        "russian": "Да, я начала бегать три раза в неделю. Это многое изменило.",
        "swedish": "Ja jag började springa tre gånger i veckan. Det har gjort stor skillnad.",
        "norwegian": "Ja jeg begynte å løpe tre ganger i uken. Det har gjort stor forskjell.",
        "danish": "Ja jeg begyndte at løbe tre gange om ugen. Det har gjort en stor forskel.",
        "finnish": "Kyllä, aloin juosta kolme kertaa viikossa. Se on muuttanut paljon.",
        "greek": "Ναι άρχισα να τρέχω τρεις φορές την εβδομάδα. Έχει κάνει μεγάλη διαφορά.",
        "brazilian_portuguese": "Sim comecei a correr três vezes por semana. Fez uma grande diferença.",
        "mandarin": "是的，我开始每周跑步三次。这带来了很大的改变。",
        "japanese": "はい、週に三回走り始めました。大きな違いをもたらしました。",
        "korean": "네, 일주일에 세 번 달리기를 시작했어요. 큰 차이를 만들었어요.",
        "hindi": "हाँ, मैंने हफ्ते में तीन बार दौड़ना शुरू किया। इसने बड़ा फर्क डाला।",
        "vietnamese": "Vâng, tôi bắt đầu chạy bộ ba lần một tuần. Điều đó tạo ra sự khác biệt lớn.",
        "arabic": "نعم بدأت الجري ثلاث مرات أسبوعياً. وقد أحدث ذلك فرقاً كبيراً.",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "How long did it take before you started to feel better?",
        "lithuanian": "Kiek laiko prireikė, kol pradėjai jaustis geriau?",
        "latvian": "Cik ilgi pagāja, pirms sāki justies labāk?",
        "estonian": "Kui kaua kulus aega enne kui hakkasid end paremini tundma?",
        "german": "Wie lange hat es gedauert, bis du dich besser zu fühlen begannst?",
        "french": "Combien de temps a-t-il fallu avant de commencer à se sentir mieux?",
        "spanish": "¿Cuánto tiempo pasó antes de que empezaras a sentirte mejor?",
        "italian": "Quanto tempo ha impiegato prima che iniziassi a sentirti meglio?",
        "portuguese": "Quanto tempo demorou antes de começares a sentir-te melhor?",
        "dutch": "Hoe lang duurde het voordat je je beter begon te voelen?",
        "polish": "Jak długo minęło zanim zaczęłaś czuć się lepiej?",
        "ukrainian": "Скільки часу пройшло, перш ніж ти почала почуватися краще?",
        "russian": "Сколько времени прошло прежде чем ты начала чувствовать себя лучше?",
        "swedish": "Hur lång tid tog det innan du började må bättre?",
        "norwegian": "Hvor lang tid tok det før du begynte å føle deg bedre?",
        "danish": "Hvor lang tid tog det før du begyndte at føle dig bedre?",
        "finnish": "Kuinka kauan kesti ennen kuin aloit voida paremmin?",
        "greek": "Πόσο καιρό χρειάστηκε πριν αρχίσεις να αισθάνεσαι καλύτερα;",
        "brazilian_portuguese": "Quanto tempo levou antes de você começar a se sentir melhor?",
        "mandarin": "你开始感觉好些需要多长时间？",
        "japanese": "良くなり始めるまでどのくらいかかりましたか？",
        "korean": "기분이 나아지기까지 얼마나 걸렸나요?",
        "hindi": "बेहतर महसूस करने में कितना समय लगा?",
        "vietnamese": "Mất bao lâu để bạn bắt đầu cảm thấy tốt hơn?",
        "arabic": "كم استغرق الأمر قبل أن تبدأ تشعر بتحسن؟",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "About two weeks. After a month I had much more energy every day.",
        "lithuanian": "Maždaug dvi savaitės. Po mėnesio turėjau daug daugiau energijos kiekvieną dieną.",
        "latvian": "Apmēram divas nedēļas. Pēc mēneša man bija daudz vairāk enerģijas katru dienu.",
        "estonian": "Umbes kaks nädalat. Kuu pärast oli mul igapäevaselt palju rohkem energiat.",
        "german": "Etwa zwei Wochen. Nach einem Monat hatte ich jeden Tag viel mehr Energie.",
        "french": "Environ deux semaines. Après un mois j'avais beaucoup plus d'énergie chaque jour.",
        "spanish": "Unas dos semanas. Después de un mes tenía mucha más energía cada día.",
        "italian": "Circa due settimane. Dopo un mese avevo molta più energia ogni giorno.",
        "portuguese": "Cerca de duas semanas. Depois de um mês tinha muito mais energia todos os dias.",
        "dutch": "Ongeveer twee weken. Na een maand had ik elke dag veel meer energie.",
        "polish": "Około dwa tygodnie. Po miesiącu miałam każdego dnia znacznie więcej energii.",
        "ukrainian": "Приблизно два тижні. Через місяць у мене було набагато більше енергії щодня.",
        "russian": "Около двух недель. Через месяц у меня было гораздо больше энергии каждый день.",
        "swedish": "Ungefär två veckor. Efter en månad hade jag mycket mer energi varje dag.",
        "norwegian": "Omtrent to uker. Etter en måned hadde jeg mye mer energi hver dag.",
        "danish": "Cirka to uger. Efter en måned havde jeg meget mere energi hver dag.",
        "finnish": "Noin kaksi viikkoa. Kuukauden jälkeen minulla oli joka päivä paljon enemmän energiaa.",
        "greek": "Περίπου δύο εβδομάδες. Μετά από ένα μήνα είχα πολύ περισσότερη ενέργεια κάθε μέρα.",
        "brazilian_portuguese": "Umas duas semanas. Depois de um mês eu tinha muito mais energia todo dia.",
        "mandarin": "大约两周。一个月后，我每天都有更多的精力。",
        "japanese": "約二週間です。一ヶ月後には毎日ずっと元気になりました。",
        "korean": "약 2주요. 한 달 후에는 매일 에너지가 훨씬 많아졌어요.",
        "hindi": "लगभग दो हफ्ते। एक महीने के बाद हर दिन बहुत अधिक ऊर्जा महसूस होती थी।",
        "vietnamese": "Khoảng hai tuần. Sau một tháng tôi có nhiều năng lượng hơn mỗi ngày.",
        "arabic": "نحو أسبوعين. بعد شهر كان لديّ طاقة أكبر بكثير كل يوم.",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "I have also cut down on sugar. It was really difficult at first.",
        "lithuanian": "Taip pat sumažinau cukraus vartojimą. Iš pradžių buvo tikrai sunku.",
        "latvian": "Es arī esmu samazinājis cukura patēriņu. Sākumā tas bija ļoti grūti.",
        "estonian": "Ma olen ka suhkrut vähendanud. Alguses oli see tõesti raske.",
        "german": "Ich habe auch den Zuckerkonsum reduziert. Es war anfangs wirklich schwer.",
        "french": "J'ai aussi réduit le sucre. C'était vraiment difficile au début.",
        "spanish": "También he reducido el azúcar. Al principio fue realmente difícil.",
        "italian": "Ho anche ridotto lo zucchero. All'inizio è stato davvero difficile.",
        "portuguese": "Também reduzi o açúcar. Foi realmente difícil no início.",
        "dutch": "Ik heb ook suiker verminderd. Het was in het begin echt moeilijk.",
        "polish": "Ograniczyłem też cukier. Na początku było naprawdę trudno.",
        "ukrainian": "Я також скоротив споживання цукру. Спочатку було справді важко.",
        "russian": "Я также сократил потребление сахара. Сначала это было действительно трудно.",
        "swedish": "Jag har också minskat på socker. Det var verkligen svårt i början.",
        "norwegian": "Jeg har også redusert sukker. Det var virkelig vanskelig i begynnelsen.",
        "danish": "Jeg har også skåret ned på sukker. Det var virkelig svært i starten.",
        "finnish": "Olen myös vähentänyt sokeria. Se oli aluksi todella vaikeaa.",
        "greek": "Έχω επίσης μειώσει τη ζάχαρη. Ήταν πολύ δύσκολο στην αρχή.",
        "brazilian_portuguese": "Também reduzi o açúcar. Foi realmente difícil no início.",
        "mandarin": "我也减少了糖的摄入。一开始真的很难。",
        "japanese": "砂糖も減らしました。最初は本当に大変でした。",
        "korean": "설탕도 줄였어요. 처음에는 정말 힘들었어요.",
        "hindi": "मैंने चीनी भी कम कर दी है। शुरुआत में यह सच में मुश्किल था।",
        "vietnamese": "Tôi cũng đã cắt giảm đường. Lúc đầu thực sự khó khăn.",
        "arabic": "لقد قلّلت أيضاً من السكر. كان الأمر صعباً في البداية حقاً.",
    },
    {
        "line_number": 6, "speaker_name": "Mia",
        "english": "Sugar is so addictive. Did you replace it with anything?",
        "lithuanian": "Cukrus labai geistinas. Ar kuo nors jį pakeitei?",
        "latvian": "Cukurs ir tik atkarību radošs. Vai tu to ar ko aizvietoji?",
        "estonian": "Suhkur on nii sõltuvust tekitav. Kas asendasid selle millegi muuga?",
        "german": "Zucker macht so süchtig. Hast du ihn durch etwas ersetzt?",
        "french": "Le sucre est tellement addictif. Tu l'as remplacé par quelque chose?",
        "spanish": "El azúcar es muy adictivo. ¿Lo reemplazaste por algo?",
        "italian": "Lo zucchero è così dipendente. L'hai sostituito con qualcosa?",
        "portuguese": "O açúcar é muito viciante. Substituíste por algo?",
        "dutch": "Suiker is zo verslavend. Heb je het door iets vervangen?",
        "polish": "Cukier jest tak uzależniający. Czy zastąpiłeś go czymś?",
        "ukrainian": "Цукор такий звикаючий. Ти чимось його замінив?",
        "russian": "Сахар такой аддиктивный. Ты заменил его чем-нибудь?",
        "swedish": "Socker är så beroendeframkallande. Ersatte du det med något?",
        "norwegian": "Sukker er så vanedannende. Erstattet du det med noe?",
        "danish": "Sukker er så vanedannende. Erstattede du det med noget?",
        "finnish": "Sokeri on niin koukuttavaa. Korvaksitko sen jollakin?",
        "greek": "Η ζάχαρη είναι τόσο εθιστική. Την αντικατέστησες με κάτι;",
        "brazilian_portuguese": "O açúcar é muito viciante. Você substituiu por algo?",
        "mandarin": "糖真的很令人上瘾。你用什么代替了它？",
        "japanese": "砂糖はとても中毒性がありますね。何かで置き換えましたか？",
        "korean": "설탕은 정말 중독성이 있어요. 다른 것으로 대체했나요?",
        "hindi": "चीनी बहुत लत लगाने वाली होती है। क्या तुमने इसे किसी और चीज़ से बदला?",
        "vietnamese": "Đường rất gây nghiện. Bạn có thay thế bằng thứ gì không?",
        "arabic": "السكر مدمن جداً. هل استبدلته بشيء آخر؟",
    },
    {
        "line_number": 7, "speaker_name": "Alex",
        "english": "I started eating more fruit. Bananas and apples mostly.",
        "lithuanian": "Pradėjau valgyti daugiau vaisių. Daugiausia bananų ir obuolių.",
        "latvian": "Es sāku ēst vairāk augļu. Galvenokārt banānus un ābolus.",
        "estonian": "Hakkasin rohkem puuvilju sööma. Enamasti banaane ja õunu.",
        "german": "Ich habe angefangen mehr Obst zu essen. Hauptsächlich Bananen und Äpfel.",
        "french": "J'ai commencé à manger plus de fruits. Des bananes et des pommes surtout.",
        "spanish": "Empecé a comer más fruta. Sobre todo plátanos y manzanas.",
        "italian": "Ho iniziato a mangiare più frutta. Soprattutto banane e mele.",
        "portuguese": "Comecei a comer mais fruta. Principalmente bananas e maçãs.",
        "dutch": "Ik begon meer fruit te eten. Vooral bananen en appels.",
        "polish": "Zacząłem jeść więcej owoców. Głównie banany i jabłka.",
        "ukrainian": "Я почав їсти більше фруктів. Переважно банани та яблука.",
        "russian": "Я начал есть больше фруктов. В основном бананы и яблоки.",
        "swedish": "Jag började äta mer frukt. Bananer och äpplen mest.",
        "norwegian": "Jeg begynte å spise mer frukt. Mest bananer og epler.",
        "danish": "Jeg begyndte at spise mere frugt. Primært bananer og æbler.",
        "finnish": "Aloin syödä enemmän hedelmiä. Lähinnä banaaneja ja omenoita.",
        "greek": "Άρχισα να τρώω περισσότερα φρούτα. Κυρίως μπανάνες και μήλα.",
        "brazilian_portuguese": "Comecei a comer mais frutas. Principalmente bananas e maçãs.",
        "mandarin": "我开始多吃水果。主要是香蕉和苹果。",
        "japanese": "もっと果物を食べるようになりました。主にバナナとリンゴです。",
        "korean": "과일을 더 많이 먹기 시작했어요. 주로 바나나와 사과를요.",
        "hindi": "मैंने अधिक फल खाना शुरू किया। ज़्यादातर केले और सेब।",
        "vietnamese": "Tôi bắt đầu ăn nhiều trái cây hơn. Chủ yếu là chuối và táo.",
        "arabic": "بدأت بتناول المزيد من الفاكهة. الموز والتفاح في الغالب.",
    },
    {
        "line_number": 8, "speaker_name": "Mia",
        "english": "That is a smart choice. Do you also drink enough water every day?",
        "lithuanian": "Tai protingas pasirinkimas. Ar taip pat gersi pakankamai vandens kiekvieną dieną?",
        "latvian": "Tas ir gudrs izvēles. Vai tu arī dzer pietiekami daudz ūdens katru dienu?",
        "estonian": "See on tark valik. Kas jood ka iga päev piisavalt vett?",
        "german": "Das ist eine kluge Wahl. Trinkst du auch jeden Tag genug Wasser?",
        "french": "C'est un choix intelligent. Est-ce que tu bois aussi assez d'eau chaque jour?",
        "spanish": "Es una elección inteligente. ¿También bebes suficiente agua cada día?",
        "italian": "È una scelta intelligente. Bevi anche abbastanza acqua ogni giorno?",
        "portuguese": "É uma escolha inteligente. Também bebes água suficiente todos os dias?",
        "dutch": "Dat is een slimme keuze. Drink je ook elke dag genoeg water?",
        "polish": "To mądry wybór. Czy pijesz też wystarczająco dużo wody każdego dnia?",
        "ukrainian": "Це розумний вибір. Чи ти також п'єш достатньо води щодня?",
        "russian": "Это умный выбор. Ты также пьёшь достаточно воды каждый день?",
        "swedish": "Det är ett smart val. Dricker du också tillräckligt med vatten varje dag?",
        "norwegian": "Det er et smart valg. Drikker du også nok vann hver dag?",
        "danish": "Det er et smart valg. Drikker du også nok vand hver dag?",
        "finnish": "Se on viisas valinta. Juotko myös riittävästi vettä joka päivä?",
        "greek": "Είναι έξυπνη επιλογή. Πίνεις επίσης αρκετό νερό κάθε μέρα;",
        "brazilian_portuguese": "É uma escolha inteligente. Você também bebe água suficiente todo dia?",
        "mandarin": "这是个明智的选择。你每天也喝足够的水吗？",
        "japanese": "賢い選択ですね。毎日十分な水も飲んでいますか？",
        "korean": "현명한 선택이에요. 매일 충분한 물도 마시나요?",
        "hindi": "यह एक स्मार्ट विकल्प है। क्या तुम हर दिन पर्याप्त पानी भी पीते हो?",
        "vietnamese": "Đó là lựa chọn thông minh. Bạn có uống đủ nước mỗi ngày không?",
        "arabic": "هذا خيار ذكي. هل تشرب أيضاً ما يكفي من الماء يومياً؟",
    },
    {
        "line_number": 9, "speaker_name": "Alex",
        "english": "Honestly no. I forget to drink water during the day.",
        "lithuanian": "Sąžiningai sakant, ne. Dienos metu pamirštu gerti vandenį.",
        "latvian": "Godīgi sakot, nē. Dienas laikā aizmirstu dzert ūdeni.",
        "estonian": "Ausalt öeldes, ei. Ma unustan päeva jooksul vett juua.",
        "german": "Ehrlich gesagt nein. Ich vergesse tagsüber Wasser zu trinken.",
        "french": "Honnêtement non. J'oublie de boire de l'eau pendant la journée.",
        "spanish": "Honestamente no. Me olvido de beber agua durante el día.",
        "italian": "Onestamente no. Mi dimentico di bere acqua durante il giorno.",
        "portuguese": "Honestamente não. Esqueço-me de beber água durante o dia.",
        "dutch": "Eerlijk gezegd nee. Ik vergeet overdag water te drinken.",
        "polish": "Szczerze mówiąc nie. W ciągu dnia zapominam pić wodę.",
        "ukrainian": "Чесно кажучи, ні. Протягом дня забуваю пити воду.",
        "russian": "Честно говоря, нет. В течение дня забываю пить воду.",
        "swedish": "Ärligt talat nej. Jag glömmer att dricka vatten under dagen.",
        "norwegian": "Ærlig talt nei. Jeg glemmer å drikke vann i løpet av dagen.",
        "danish": "Ærligt talt nej. Jeg glemmer at drikke vand i løbet af dagen.",
        "finnish": "Rehellisesti sanoen ei. Unohdan juoda vettä päivän aikana.",
        "greek": "Ειλικρινά όχι. Ξεχνώ να πιω νερό κατά τη διάρκεια της ημέρας.",
        "brazilian_portuguese": "Honestamente não. Esqueço de beber água durante o dia.",
        "mandarin": "说实话，没有。我白天忘了喝水。",
        "japanese": "正直に言うと、いいえ。日中、水を飲むのを忘れてしまいます。",
        "korean": "솔직히 아니요. 낮에 물 마시는 걸 잊어버려요.",
        "hindi": "ईमानदारी से कहूँ तो नहीं। मैं दिन के दौरान पानी पीना भूल जाता हूँ।",
        "vietnamese": "Thật lòng thì không. Tôi quên uống nước trong ngày.",
        "arabic": "بصراحة لا. أنسى شرب الماء خلال اليوم.",
    },
    {
        "line_number": 10, "speaker_name": "Mia",
        "english": "Try keeping a bottle on your desk. It really helps as a reminder.",
        "lithuanian": "Pamėgink laikyti butelį ant stalo. Tai tikrai padeda kaip priminimas.",
        "latvian": "Mēģini turēt pudeli uz galda. Tas tiešām palīdz kā atgādinājums.",
        "estonian": "Proovi hoida pudel laua peal. See aitab tõesti meeldetuletajana.",
        "german": "Versuche eine Flasche auf deinem Schreibtisch zu halten. Es hilft wirklich als Erinnerung.",
        "french": "Essaie de garder une bouteille sur ton bureau. Ça aide vraiment comme rappel.",
        "spanish": "Intenta mantener una botella en tu escritorio. Ayuda mucho como recordatorio.",
        "italian": "Prova a tenere una bottiglia sulla tua scrivania. Aiuta davvero come promemoria.",
        "portuguese": "Tenta manter uma garrafa na tua secretária. Ajuda mesmo como lembrete.",
        "dutch": "Probeer een fles op je bureau te houden. Het helpt echt als herinnering.",
        "polish": "Spróbuj trzymać butelkę na biurku. Naprawdę pomaga jako przypomnienie.",
        "ukrainian": "Спробуй тримати пляшку на столі. Це дійсно допомагає як нагадування.",
        "russian": "Попробуй держать бутылку на столе. Это действительно помогает как напоминание.",
        "swedish": "Försök att ha en flaska på skrivbordet. Det hjälper verkligen som påminnelse.",
        "norwegian": "Prøv å holde en flaske på skrivebordet. Det hjelper virkelig som en påminnelse.",
        "danish": "Prøv at holde en flaske på skrivebordet. Det hjælper virkelig som en påmindelse.",
        "finnish": "Yritä pitää pullo pöydällä. Se auttaa todella muistuttajana.",
        "greek": "Δοκίμασε να κρατάς ένα μπουκάλι στο γραφείο. Βοηθά πραγματικά ως υπενθύμιση.",
        "brazilian_portuguese": "Tente manter uma garrafa na sua mesa. Realmente ajuda como lembrete.",
        "mandarin": "试着在桌上放一瓶水。真的很有帮助，可以提醒自己。",
        "japanese": "机の上にボトルを置いておくようにしてみてください。本当にリマインダーとして役立ちます。",
        "korean": "책상 위에 물병을 두어 보세요. 정말로 상기시켜주는 역할을 해요.",
        "hindi": "अपनी मेज पर एक बोतल रखने की कोशिश करो। यह याद दिलाने में सच में मदद करती है।",
        "vietnamese": "Hãy thử để một chai nước trên bàn làm việc. Thực sự giúp như một lời nhắc.",
        "arabic": "جرّب أن تبقي زجاجة على مكتبك. يساعد كثيراً كتذكير.",
    },
    {
        "line_number": 11, "speaker_name": "Alex",
        "english": "Good idea. What about sleep? I have been sleeping quite badly recently.",
        "lithuanian": "Gera mintis. O kaip su miegu? Pastaruoju metu miegu gana blogai.",
        "latvian": "Laba ideja. Ko darīt ar miegu? Pēdējā laikā es guļu diezgan slikti.",
        "estonian": "Hea mõte. Aga uni? Viimasel ajal olen maganud üsna halvasti.",
        "german": "Gute Idee. Was ist mit Schlaf? Ich schlafe in letzter Zeit ziemlich schlecht.",
        "french": "Bonne idée. Et le sommeil? J'ai dormi assez mal récemment.",
        "spanish": "Buena idea. ¿Y el sueño? Últimamente he dormido bastante mal.",
        "italian": "Buona idea. E il sonno? Ultimamente ho dormito abbastanza male.",
        "portuguese": "Boa ideia. E o sono? Ultimamente tenho dormido bastante mal.",
        "dutch": "Goed idee. En slaap? Ik heb de laatste tijd vrij slecht geslapen.",
        "polish": "Dobry pomysł. A co ze snem? Ostatnio sypiam dość źle.",
        "ukrainian": "Гарна ідея. А як щодо сну? Останнім часом я сплю досить погано.",
        "russian": "Хорошая идея. А как насчёт сна? Последнее время я сплю довольно плохо.",
        "swedish": "Bra idé. Och sömn? Jag har sovit ganska dåligt på sistone.",
        "norwegian": "God idé. Og søvn? Jeg har sovet ganske dårlig i det siste.",
        "danish": "God idé. Hvad med søvn? Jeg har sovet ret dårligt for nylig.",
        "finnish": "Hyvä idea. Entä uni? Olen nukkunut viime aikoina melko huonosti.",
        "greek": "Καλή ιδέα. Και ο ύπνος; Έχω κοιμηθεί αρκετά άσχημα τελευταία.",
        "brazilian_portuguese": "Boa ideia. E o sono? Ultimamente tenho dormido bastante mal.",
        "mandarin": "好主意。睡眠怎么样？最近我睡得很差。",
        "japanese": "いいアイデアですね。睡眠はどうですか？最近かなり眠れていません。",
        "korean": "좋은 생각이에요. 수면은 어때요? 최근에 잠을 꽤 못 자고 있어요.",
        "hindi": "अच्छा विचार। नींद के बारे में क्या? हाल ही में मेरी नींद काफी खराब रही है।",
        "vietnamese": "Ý hay đó. Còn giấc ngủ thì sao? Gần đây tôi ngủ khá kém.",
        "arabic": "فكرة جيدة. وماذا عن النوم؟ لقد كنت أنام بشكل سيئ مؤخراً.",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "Poor sleep affects everything. Do you use your phone in bed?",
        "lithuanian": "Blogas miegas veikia viską. Ar naudoji telefoną lovoje?",
        "latvian": "Slikts miegs ietekmē visu. Vai tu izmanto telefonu gultā?",
        "estonian": "Halb uni mõjutab kõike. Kas kasutad telefoni voodis?",
        "german": "Schlechter Schlaf beeinflusst alles. Benutzt du das Handy im Bett?",
        "french": "Le mauvais sommeil affecte tout. Est-ce que tu utilises ton téléphone au lit?",
        "spanish": "El mal sueño afecta todo. ¿Usas el teléfono en la cama?",
        "italian": "Il sonno scarso influisce su tutto. Usi il telefono a letto?",
        "portuguese": "O mau sono afeta tudo. Usas o telemóvel na cama?",
        "dutch": "Slechte slaap beïnvloedt alles. Gebruik je je telefoon in bed?",
        "polish": "Zły sen wpływa na wszystko. Czy używasz telefonu w łóżku?",
        "ukrainian": "Поганий сон впливає на все. Чи ти користуєшся телефоном у ліжку?",
        "russian": "Плохой сон влияет на всё. Ты пользуешься телефоном в постели?",
        "swedish": "Dålig sömn påverkar allt. Använder du telefonen i sängen?",
        "norwegian": "Dårlig søvn påvirker alt. Bruker du telefonen i sengen?",
        "danish": "Dårlig søvn påvirker alt. Bruger du din telefon i sengen?",
        "finnish": "Huono uni vaikuttaa kaikkeen. Käytätkö puhelinta sängyssä?",
        "greek": "Ο κακός ύπνος επηρεάζει τα πάντα. Χρησιμοποιείς το τηλέφωνό σου στο κρεβάτι;",
        "brazilian_portuguese": "O sono ruim afeta tudo. Você usa o celular na cama?",
        "mandarin": "睡眠不好影响一切。你在床上用手机吗？",
        "japanese": "睡眠不足はあらゆることに影響します。ベッドでスマホを使っていますか？",
        "korean": "수면 부족은 모든 것에 영향을 미쳐요. 침대에서 핸드폰을 사용하나요?",
        "hindi": "खराब नींद सब पर असर डालती है। क्या तुम बिस्तर में फोन इस्तेमाल करते हो?",
        "vietnamese": "Ngủ kém ảnh hưởng đến mọi thứ. Bạn có dùng điện thoại trên giường không?",
        "arabic": "النوم السيئ يؤثر على كل شيء. هل تستخدم هاتفك في السرير؟",
    },
    {
        "line_number": 13, "speaker_name": "Alex",
        "english": "Yes probably too much. I scroll through social media before sleeping.",
        "lithuanian": "Taip, tikriausiai per daug. Prieš miegant naršau socialiniuose tinkluose.",
        "latvian": "Jā, iespējams pārāk daudz. Es pirms gulētiešanas ritinu sociālos medijus.",
        "estonian": "Jah, ilmselt liiga palju. Kerin enne magamist sotsiaalmeediat.",
        "german": "Ja wahrscheinlich zu viel. Ich scrolle vor dem Schlafen durch soziale Medien.",
        "french": "Oui probablement trop. Je fais défiler les réseaux sociaux avant de dormir.",
        "spanish": "Sí probablemente demasiado. Me pongo a desplazarme por las redes sociales antes de dormir.",
        "italian": "Sì probabilmente troppo. Scorro i social media prima di dormire.",
        "portuguese": "Sim provavelmente demasiado. Fico a fazer scroll nas redes sociais antes de dormir.",
        "dutch": "Ja waarschijnlijk te veel. Ik scroll door sociale media voor het slapengaan.",
        "polish": "Tak pewnie za dużo. Przed snem przeglądam media społecznościowe.",
        "ukrainian": "Так, мабуть, занадто багато. Я гортаю соціальні мережі перед сном.",
        "russian": "Да, наверное, слишком много. Листаю соцсети перед сном.",
        "swedish": "Ja förmodligen för mycket. Jag scrollar igenom sociala medier innan jag sover.",
        "norwegian": "Ja sannsynligvis for mye. Jeg scroller gjennom sosiale medier før jeg sover.",
        "danish": "Ja sandsynligvis for meget. Jeg ruller gennem sociale medier inden jeg sover.",
        "finnish": "Kyllä, luultavasti liikaa. Selaan sosiaalista mediaa ennen nukkumaan menoa.",
        "greek": "Ναι μάλλον πολύ. Κάνω scroll στα social media πριν κοιμηθώ.",
        "brazilian_portuguese": "Sim provavelmente demais. Fico rolando as redes sociais antes de dormir.",
        "mandarin": "是的，可能太多了。睡前我会刷社交媒体。",
        "japanese": "はい、おそらく多すぎます。寝る前にSNSをスクロールしています。",
        "korean": "네, 아마 너무 많이요. 자기 전에 소셜 미디어를 스크롤해요.",
        "hindi": "हाँ, शायद बहुत ज़्यादा। मैं सोने से पहले सोशल मीडिया स्क्रॉल करता हूँ।",
        "vietnamese": "Vâng có lẽ quá nhiều. Tôi lướt mạng xã hội trước khi ngủ.",
        "arabic": "نعم ربما كثيراً. أتصفح وسائل التواصل الاجتماعي قبل النوم.",
    },
    {
        "line_number": 14, "speaker_name": "Mia",
        "english": "That is the biggest mistake. The screen light keeps your brain awake.",
        "lithuanian": "Tai didžiausia klaida. Ekrano šviesa laiko smegenis budrumą.",
        "latvian": "Tā ir lielākā kļūda. Ekrāna gaisma tur smadzenes nomodā.",
        "estonian": "See on suurim viga. Ekraani valgus hoiab aju ärkvel.",
        "german": "Das ist der größte Fehler. Das Bildschirmlicht hält dein Gehirn wach.",
        "french": "C'est la plus grande erreur. La lumière de l'écran maintient ton cerveau éveillé.",
        "spanish": "Ese es el mayor error. La luz de la pantalla mantiene tu cerebro despierto.",
        "italian": "Questo è il più grande errore. La luce dello schermo tiene il cervello sveglio.",
        "portuguese": "Esse é o maior erro. A luz do ecrã mantém o teu cérebro acordado.",
        "dutch": "Dat is de grootste fout. Het schermslicht houdt je hersenen wakker.",
        "polish": "To największy błąd. Światło ekranu utrzymuje mózg w stanie czuwania.",
        "ukrainian": "Це найбільша помилка. Світло екрану не дає мозку заснути.",
        "russian": "Это самая большая ошибка. Свет экрана не даёт мозгу уснуть.",
        "swedish": "Det är det största misstaget. Skärmljuset håller din hjärna vaken.",
        "norwegian": "Det er den største feilen. Skjermlyset holder hjernen din våken.",
        "danish": "Det er den største fejl. Skærmlyset holder din hjerne vågen.",
        "finnish": "Se on suurin virhe. Näytön valo pitää aivosi hereillä.",
        "greek": "Αυτό είναι το μεγαλύτερο λάθος. Το φως της οθόνης κρατά τον εγκέφαλό σου ξύπνιο.",
        "brazilian_portuguese": "Esse é o maior erro. A luz da tela mantém seu cérebro acordado.",
        "mandarin": "这是最大的错误。屏幕的光线会让你的大脑保持清醒。",
        "japanese": "それが一番大きなミスです。画面の光が脳を覚醒させたままにします。",
        "korean": "그게 가장 큰 실수예요. 화면 빛이 뇌를 깨어있게 해요.",
        "hindi": "यह सबसे बड़ी गलती है। स्क्रीन की रोशनी दिमाग को जागते रहने देती है।",
        "vietnamese": "Đó là sai lầm lớn nhất. Ánh sáng màn hình giữ cho não bạn tỉnh táo.",
        "arabic": "هذه أكبر خطأ. ضوء الشاشة يبقي دماغك مستيقظاً.",
    },
    {
        "line_number": 15, "speaker_name": "Alex",
        "english": "I know I should stop but it is hard to put the phone down.",
        "lithuanian": "Žinau, turėčiau liautis, bet sunku padėti telefoną.",
        "latvian": "Es zinu, man vajadzētu pārtraukt, bet ir grūti nolikt telefonu.",
        "estonian": "Tean, et peaksin lõpetama, aga on raske telefoni käest panna.",
        "german": "Ich weiß, ich sollte aufhören, aber es ist schwer das Handy wegzulegen.",
        "french": "Je sais que je devrais arrêter mais c'est difficile de poser le téléphone.",
        "spanish": "Sé que debería parar pero es difícil dejar el teléfono.",
        "italian": "So che dovrei smettere ma è difficile posare il telefono.",
        "portuguese": "Sei que devia parar mas é difícil largar o telemóvel.",
        "dutch": "Ik weet dat ik moet stoppen maar het is moeilijk om de telefoon neer te leggen.",
        "polish": "Wiem że powinienem przestać ale ciężko odłożyć telefon.",
        "ukrainian": "Знаю, що слід зупинитися, але важко відкласти телефон.",
        "russian": "Знаю, что нужно прекратить, но сложно отложить телефон.",
        "swedish": "Jag vet att jag borde sluta men det är svårt att lägga ner telefonen.",
        "norwegian": "Jeg vet at jeg burde stoppe men det er vanskelig å legge ned telefonen.",
        "danish": "Jeg ved at jeg burde stoppe men det er svært at lægge telefonen.",
        "finnish": "Tiedän, että minun pitäisi lopettaa, mutta puhelimen laskeminen on vaikeaa.",
        "greek": "Ξέρω ότι πρέπει να σταματήσω αλλά είναι δύσκολο να αφήσω το τηλέφωνο.",
        "brazilian_portuguese": "Sei que deveria parar mas é difícil largar o celular.",
        "mandarin": "我知道我应该停下来，但很难放下手机。",
        "japanese": "やめなければとわかっていますが、スマホを置くのが難しいです。",
        "korean": "멈춰야 한다는 걸 알지만 핸드폰을 내려놓기가 힘들어요.",
        "hindi": "मैं जानता हूँ मुझे रुकना चाहिए लेकिन फोन रखना मुश्किल है।",
        "vietnamese": "Tôi biết mình nên dừng lại nhưng khó buông điện thoại xuống.",
        "arabic": "أعلم أنني يجب أن أتوقف لكن من الصعب وضع الهاتف جانباً.",
    },
    {
        "line_number": 16, "speaker_name": "Mia",
        "english": "Try putting your phone in another room at night. Sleep improved a lot for me after that.",
        "lithuanian": "Pamėgink naktį dėti telefoną į kitą kambarį. Po to mano miegas labai pagerėjo.",
        "latvian": "Mēģini naktī ielikt telefonu citā istabā. Man pēc tam miegs ievērojami uzlabojās.",
        "estonian": "Proovi öösel panna telefon teise tuppa. Mul paranes uni pärast seda palju.",
        "german": "Versuche nachts dein Handy in einem anderen Zimmer zu lassen. Mein Schlaf hat sich danach sehr verbessert.",
        "french": "Essaie de mettre ton téléphone dans une autre pièce la nuit. Mon sommeil s'est beaucoup amélioré après ça.",
        "spanish": "Intenta poner el teléfono en otra habitación por la noche. Mi sueño mejoró mucho después de eso.",
        "italian": "Prova a mettere il telefono in un'altra stanza di notte. Il mio sonno è migliorato molto dopo quello.",
        "portuguese": "Tenta colocar o telemóvel noutra divisão à noite. O meu sono melhorou muito depois disso.",
        "dutch": "Probeer je telefoon 's nachts in een andere kamer te leggen. Mijn slaap verbeterde daarna veel.",
        "polish": "Spróbuj kłaść telefon w innym pokoju na noc. Mój sen znacznie się poprawił po tym.",
        "ukrainian": "Спробуй клас телефон вночі в іншу кімнату. Після цього мій сон значно покращився.",
        "russian": "Попробуй оставлять телефон на ночь в другой комнате. После этого мой сон значительно улучшился.",
        "swedish": "Försök att lägga telefonen i ett annat rum på natten. Sömnen förbättrades mycket för mig efter det.",
        "norwegian": "Prøv å legge telefonen i et annet rom om natten. Søvnen ble mye bedre for meg etter det.",
        "danish": "Prøv at lægge din telefon i et andet rum om natten. Søvnen blev meget bedre for mig efter det.",
        "finnish": "Yritä laittaa puhelin yöllä toiseen huoneeseen. Uneni parani paljon sen jälkeen.",
        "greek": "Δοκίμασε να βάζεις το τηλέφωνό σου σε άλλο δωμάτιο τη νύχτα. Ο ύπνος μου βελτιώθηκε πολύ μετά από αυτό.",
        "brazilian_portuguese": "Tente colocar o celular em outro quarto à noite. Meu sono melhorou muito depois disso.",
        "mandarin": "试着晚上把手机放在另一个房间。那之后我的睡眠改善了很多。",
        "japanese": "夜は別の部屋に電話を置いてみてください。その後、睡眠がずっと改善しました。",
        "korean": "밤에 다른 방에 핸드폰을 두어 보세요. 그 후로 수면이 많이 좋아졌어요.",
        "hindi": "रात में फोन को दूसरे कमरे में रखने की कोशिश करो। उसके बाद मेरी नींद बहुत बेहतर हो गई।",
        "vietnamese": "Hãy thử để điện thoại ở phòng khác vào ban đêm. Giấc ngủ của tôi cải thiện nhiều sau đó.",
        "arabic": "جرّب وضع هاتفك في غرفة أخرى ليلاً. تحسّن نومي كثيراً بعد ذلك.",
    },
    {
        "line_number": 17, "speaker_name": "Alex",
        "english": "I will try that tonight. What about stress? Do you have any good tips?",
        "lithuanian": "Pabandysiu tai šiandien vakare. O kaip su stresu? Ar turi gerų patarimų?",
        "latvian": "Es to izmēģināšu šovakar. Ko darīt ar stresu? Vai tev ir kādi labi padomi?",
        "estonian": "Proovin seda täna õhtul. Aga stress? Kas sul on häid nõuandeid?",
        "german": "Das werde ich heute Abend ausprobieren. Was ist mit Stress? Hast du gute Tipps?",
        "french": "Je vais essayer ça ce soir. Et le stress? Tu as de bons conseils?",
        "spanish": "Lo intentaré esta noche. ¿Y el estrés? ¿Tienes buenos consejos?",
        "italian": "Lo proverò stasera. E lo stress? Hai buoni consigli?",
        "portuguese": "Vou experimentar esta noite. E o stress? Tens bons conselhos?",
        "dutch": "Dat ga ik vanavond proberen. En stress? Heb je goede tips?",
        "polish": "Spróbuję tego dzisiejszego wieczoru. A co ze stresem? Masz jakieś dobre porady?",
        "ukrainian": "Спробую це сьогодні ввечері. А стрес? Є якісь хороші поради?",
        "russian": "Попробую это сегодня вечером. А стресс? Есть хорошие советы?",
        "swedish": "Jag ska prova det ikväll. Och stress? Har du några bra tips?",
        "norwegian": "Jeg skal prøve det i kveld. Og stress? Har du noen gode tips?",
        "danish": "Jeg vil prøve det i aften. Og stress? Har du gode råd?",
        "finnish": "Kokeilen sitä tänä iltana. Entä stressi? Onko sinulla hyviä vinkkejä?",
        "greek": "Θα το δοκιμάσω απόψε. Και το άγχος; Έχεις καλές συμβουλές;",
        "brazilian_portuguese": "Vou tentar isso esta noite. E o estresse? Tem bons conselhos?",
        "mandarin": "今晚我会试试。压力呢？你有什么好建议吗？",
        "japanese": "今夜試してみます。ストレスについてはどうですか？良いアドバイスはありますか？",
        "korean": "오늘 밤 시도해 볼게요. 스트레스는 어떤가요? 좋은 팁이 있나요?",
        "hindi": "मैं आज रात यह कोशिश करूँगा। तनाव के बारे में क्या? क्या तुम्हारे पास कोई अच्छे सुझाव हैं?",
        "vietnamese": "Tôi sẽ thử tối nay. Còn căng thẳng thì sao? Bạn có mẹo hay không?",
        "arabic": "سأجرب ذلك الليلة. وماذا عن التوتر؟ هل لديك نصائح جيدة؟",
    },
    {
        "line_number": 18, "speaker_name": "Mia",
        "english": "Walking in nature helps me enormously. Even just thirty minutes makes a difference.",
        "lithuanian": "Pasivaikščiojimai gamtoje man labai padeda. Net tik trisdešimt minučių daro skirtumą.",
        "latvian": "Pastaiga dabā man ļoti palīdz. Pat tikai trīsdesmit minūtes dara atšķirību.",
        "estonian": "Loodus jalutamine aitab mul ennast tunda tohutult. Isegi kolmkümmend minutit teeb vahe.",
        "german": "In der Natur spazieren zu gehen hilft mir enorm. Schon dreißig Minuten machen einen Unterschied.",
        "french": "Marcher dans la nature m'aide énormément. Même juste trente minutes fait une différence.",
        "spanish": "Caminar en la naturaleza me ayuda enormemente. Incluso solo treinta minutos marcan la diferencia.",
        "italian": "Camminare nella natura mi aiuta enormemente. Anche solo trenta minuti fanno la differenza.",
        "portuguese": "Andar na natureza ajuda-me enormemente. Mesmo só trinta minutos fazem diferença.",
        "dutch": "In de natuur wandelen helpt me enorm. Zelfs maar dertig minuten maakt een verschil.",
        "polish": "Chodzenie w naturze pomaga mi ogromnie. Nawet trzydzieści minut robi różnicę.",
        "ukrainian": "Прогулянки на природі допомагають мені надзвичайно. Навіть тридцять хвилин роблять різницю.",
        "russian": "Прогулки на природе помогают мне очень сильно. Даже тридцать минут делают разницу.",
        "swedish": "Att promenera i naturen hjälper mig enormt. Även bara trettio minuter gör skillnad.",
        "norwegian": "Å gå i naturen hjelper meg enormt. Selv bare tretti minutter gjør en forskjell.",
        "danish": "At gå i naturen hjælper mig enormt. Selv bare tredive minutter gør en forskel.",
        "finnish": "Luonnossa kävely auttaa minua valtavasti. Jo kolmekymmentä minuuttia tekee eron.",
        "greek": "Το να περπατώ στη φύση με βοηθά τεράστια. Ακόμα και τριάντα λεπτά κάνουν διαφορά.",
        "brazilian_portuguese": "Caminhar na natureza me ajuda imensamente. Até mesmo trinta minutos fazem diferença.",
        "mandarin": "在大自然中散步对我帮助很大。即使只有三十分钟也会有所不同。",
        "japanese": "自然の中を歩くことが私にとって非常に助けになります。たった三十分でも違いを生みます。",
        "korean": "자연 속에서 걷는 것이 저에게 엄청나게 도움이 돼요. 30분만으로도 차이를 만들어요.",
        "hindi": "प्रकृति में चलना मुझे बहुत मदद करता है। सिर्फ तीस मिनट भी फर्क डालते हैं।",
        "vietnamese": "Đi bộ trong thiên nhiên giúp tôi rất nhiều. Ngay cả ba mươi phút cũng tạo ra sự khác biệt.",
        "arabic": "المشي في الطبيعة يساعدني كثيراً. حتى ثلاثون دقيقة فقط تُحدث فرقاً.",
    },
    {
        "line_number": 19, "speaker_name": "Alex",
        "english": "I live near a park actually. I should use it more often.",
        "lithuanian": "Tiesą sakant, gyvenu netoli parko. Turėčiau juo naudotis dažniau.",
        "latvian": "Patiesībā es dzīvoju netālu no parka. Man vajadzētu to izmantot biežāk.",
        "estonian": "Tegelikult elan pargi lähedal. Peaksin seda sagedamini kasutama.",
        "german": "Ich wohne eigentlich in der Nähe eines Parks. Ich sollte ihn öfter nutzen.",
        "french": "J'habite en fait près d'un parc. Je devrais l'utiliser plus souvent.",
        "spanish": "En realidad vivo cerca de un parque. Debería usarlo más seguido.",
        "italian": "In realtà vivo vicino a un parco. Dovrei usarlo più spesso.",
        "portuguese": "Na verdade vivo perto de um parque. Devia usá-lo mais frequentemente.",
        "dutch": "Ik woon eigenlijk bij een park in de buurt. Ik zou het vaker moeten gebruiken.",
        "polish": "Właściwie mieszkam niedaleko parku. Powinienem korzystać z niego częściej.",
        "ukrainian": "Насправді я живу поруч із парком. Треба частіше ним користуватися.",
        "russian": "Я на самом деле живу рядом с парком. Нужно чаще им пользоваться.",
        "swedish": "Jag bor faktiskt nära en park. Jag borde använda den oftare.",
        "norwegian": "Jeg bor faktisk nær en park. Jeg burde bruke den oftere.",
        "danish": "Jeg bor faktisk tæt på en park. Jeg burde bruge den oftere.",
        "finnish": "Asun oikeastaan puiston lähellä. Minun pitäisi käyttää sitä useammin.",
        "greek": "Στην πραγματικότητα μένω κοντά σε ένα πάρκο. Πρέπει να το χρησιμοποιώ πιο συχνά.",
        "brazilian_portuguese": "Na verdade moro perto de um parque. Deveria usá-lo com mais frequência.",
        "mandarin": "实际上我住在公园附近。我应该更经常使用它。",
        "japanese": "実は公園の近くに住んでいます。もっとよく使うべきですね。",
        "korean": "사실 공원 근처에 살아요. 더 자주 이용해야겠어요.",
        "hindi": "मैं दरअसल एक पार्क के पास रहता हूँ। मुझे इसे अधिक बार इस्तेमाल करना चाहिए।",
        "vietnamese": "Thực ra tôi sống gần một công viên. Tôi nên dùng nó thường xuyên hơn.",
        "arabic": "في الواقع أنا أسكن بالقرب من متنزه. يجب أن أستخدمه أكثر.",
    },
    {
        "line_number": 20, "speaker_name": "Mia",
        "english": "Start small. Even a short walk each morning will change how you feel. Small steps lead to big changes.",
        "lithuanian": "Pradėk nuo mažo. Net trumpas pasivaikščiojimas kiekvieną rytą pakeis tai, kaip jautiesi. Maži žingsniai veda prie didelių pokyčių.",
        "latvian": "Sāc mazā veidā. Pat īss pastaiga katru rītu mainīs to, kā jūties. Mazi soļi noved pie lielām pārmaiņām.",
        "estonian": "Alusta väikeselt. Isegi lühike jalutuskäik iga hommik muudab seda, kuidas ennast tunned. Väikesed sammud viivad suure muutuseni.",
        "german": "Fange klein an. Sogar ein kurzer Spaziergang jeden Morgen wird verändern wie du dich fühlst. Kleine Schritte führen zu großen Veränderungen.",
        "french": "Commence petit. Même une courte promenade chaque matin changera comment tu te sens. Les petits pas mènent à de grands changements.",
        "spanish": "Empieza poco a poco. Incluso una pequeña caminata cada mañana cambiará cómo te sientes. Los pequeños pasos llevan a grandes cambios.",
        "italian": "Inizia in piccolo. Anche una breve passeggiata ogni mattina cambierà come ti senti. I piccoli passi portano a grandi cambiamenti.",
        "portuguese": "Começa aos poucos. Mesmo uma curta caminhada cada manhã vai mudar como te sentes. Pequenos passos levam a grandes mudanças.",
        "dutch": "Begin klein. Zelfs een korte wandeling elke ochtend zal veranderen hoe je je voelt. Kleine stappen leiden tot grote veranderingen.",
        "polish": "Zacznij od małego. Nawet krótki spacer każdego ranka zmieni to jak się czujesz. Małe kroki prowadzą do wielkich zmian.",
        "ukrainian": "Починай з малого. Навіть короткая прогулянка кожного ранку змінить те, як ти себе почуваєш. Маленькі кроки ведуть до великих змін.",
        "russian": "Начни с малого. Даже короткая прогулка каждое утро изменит то, как ты себя чувствуешь. Маленькие шаги ведут к большим переменам.",
        "swedish": "Börja i liten skala. Till och med en kort promenad varje morgon kommer att förändra hur du mår. Små steg leder till stora förändringar.",
        "norwegian": "Start i det små. Selv en kort tur hver morgen vil endre hvordan du har det. Små skritt fører til store endringer.",
        "danish": "Start småt. Selv en kort tur hver morgen vil ændre hvordan du har det. Små skridt fører til store forandringer.",
        "finnish": "Aloita pienestä. Jo lyhyt kävely joka aamu muuttaa tunnettasi. Pienet askeleet johtavat suuriin muutoksiin.",
        "greek": "Ξεκίνα μικρά. Ακόμα και μια σύντομη βόλτα κάθε πρωί θα αλλάξει πώς αισθάνεσαι. Τα μικρά βήματα οδηγούν σε μεγάλες αλλαγές.",
        "brazilian_portuguese": "Comece aos poucos. Mesmo uma caminhada curta toda manhã vai mudar como você se sente. Pequenos passos levam a grandes mudanças.",
        "mandarin": "从小事做起。每天早晨短暂散步也会改变你的感受。小步骤导致大改变。",
        "japanese": "小さく始めましょう。毎朝の短い散歩でも、気分が変わります。小さな一歩が大きな変化につながります。",
        "korean": "작게 시작하세요. 매일 아침 짧은 산책만으로도 기분이 달라질 거예요. 작은 걸음이 큰 변화를 만들어요.",
        "hindi": "छोटे से शुरू करो। हर सुबह एक छोटी सी सैर भी तुम्हारे महसूस करने का तरीका बदल देगी। छोटे कदम बड़े बदलाव लाते हैं।",
        "vietnamese": "Bắt đầu từ nhỏ. Ngay cả một chuyến đi bộ ngắn mỗi sáng cũng sẽ thay đổi cảm giác của bạn. Những bước nhỏ dẫn đến những thay đổi lớn.",
        "arabic": "ابدأ بخطوات صغيرة. حتى مجرد نزهة قصيرة كل صباح ستغير طريقة شعورك. الخطوات الصغيرة تؤدي إلى تغييرات كبيرة.",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="Discussing Health and Lifestyle").first()
        if existing:
            print("B1 dialogue 'Discussing Health and Lifestyle' already exists — skipping.")
            return

        dialogue = Dialogue(topic="Discussing Health and Lifestyle", lang_level="B1", length=20)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded B1 dialogue ID {dialogue.id} — 20 lines in 25 languages.")


if __name__ == '__main__':
    seed()
