import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "I heard you changed jobs recently. How is it going?",
        "lithuanian": "Girdėjau, kad neseniai pakeitei darbą. Kaip sekasi?",
        "latvian": "Es dzirdēju, ka tu nesen mainīji darbu. Kā iet?",
        "estonian": "Kuulsin, et sa vahetasid hiljuti töö. Kuidas läheb?",
        "german": "Ich hörte, dass du kürzlich den Job gewechselt hast. Wie läuft es?",
        "french": "J'ai entendu dire que tu as changé de travail récemment. Comment ça se passe?",
        "spanish": "Escuché que cambiaste de trabajo recientemente. ¿Cómo te va?",
        "italian": "Ho sentito che hai cambiato lavoro di recente. Com'è andata?",
        "portuguese": "Soube que mudaste de emprego recentemente. Como está a correr?",
        "dutch": "Ik hoorde dat je onlangs van baan veranderde. Hoe gaat het?",
        "polish": "Słyszałem, że niedawno zmieniłeś pracę. Jak idzie?",
        "ukrainian": "Я чув, що ти нещодавно змінив роботу. Як справи?",
        "russian": "Слышал, что ты недавно сменил работу. Как дела?",
        "swedish": "Jag hörde att du bytte jobb nyligen. Hur går det?",
        "norwegian": "Jeg hørte at du nylig byttet jobb. Hvordan går det?",
        "danish": "Jeg hørte du for nylig skiftede job. Hvordan går det?",
        "finnish": "Kuulin, että vaihdoit hiljattain töitä. Miten menee?",
        "greek": "Άκουσα ότι άλλαξες δουλειά πρόσφατα. Πώς πάει;",
        "brazilian_portuguese": "Ouvi dizer que você mudou de emprego recentemente. Como está indo?",
        "mandarin": "我听说你最近换工作了。进展如何？",
        "japanese": "最近仕事を変えたって聞きました。どうですか？",
        "korean": "최근에 직장을 바꿨다고 들었어요. 어떻게 지내고 있나요?",
        "hindi": "सुना कि तुमने हाल ही में नौकरी बदली है। कैसा जा रहा है?",
        "vietnamese": "Tôi nghe nói bạn mới đổi việc. Mọi việc thế nào rồi?",
        "arabic": "سمعت أنك غيّرت عملك مؤخراً. كيف تسير الأمور؟",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "It is going really well actually. I am much happier than I was before.",
        "lithuanian": "Sekasi tikrai gerai. Esu daug laimingesnė nei anksčiau.",
        "latvian": "Patiesībā iet ļoti labi. Es esmu daudz laimīgāka nekā iepriekš.",
        "estonian": "Tegelikult läheb väga hästi. Olen palju õnnelikum kui varem.",
        "german": "Es läuft eigentlich wirklich gut. Ich bin viel glücklicher als vorher.",
        "french": "Ça se passe vraiment bien en fait. Je suis beaucoup plus heureuse qu'avant.",
        "spanish": "En realidad va muy bien. Soy mucho más feliz que antes.",
        "italian": "In realtà va davvero bene. Sono molto più felice di prima.",
        "portuguese": "Na verdade está a correr muito bem. Estou muito mais feliz do que estava antes.",
        "dutch": "Het gaat eigenlijk heel goed. Ik ben veel gelukkiger dan ik was.",
        "polish": "Naprawdę dobrze idzie. Jestem znacznie szczęśliwsza niż wcześniej.",
        "ukrainian": "Насправді все дуже добре. Я набагато щасливіша, ніж раніше.",
        "russian": "На самом деле всё идёт очень хорошо. Я намного счастливее, чем была раньше.",
        "swedish": "Det går faktiskt riktigt bra. Jag är mycket lyckligare än jag var tidigare.",
        "norwegian": "Det går faktisk veldig bra. Jeg er mye lykkeligere enn jeg var før.",
        "danish": "Det går faktisk rigtig godt. Jeg er meget lykkeligere end jeg var før.",
        "finnish": "Menee oikeastaan todella hyvin. Olen paljon onnellisempi kuin ennen.",
        "greek": "Πάει πολύ καλά στην πραγματικότητα. Είμαι πολύ πιο χαρούμενη από πριν.",
        "brazilian_portuguese": "Na verdade está indo muito bem. Estou muito mais feliz do que estava antes.",
        "mandarin": "其实进展真的很好。我比以前快乐多了。",
        "japanese": "実はとてもうまくいっています。前よりずっと幸せです。",
        "korean": "사실 정말 잘 되고 있어요. 이전보다 훨씬 더 행복해요.",
        "hindi": "सच में बहुत अच्छा जा रहा है। मैं पहले से बहुत ज़्यादा खुश हूँ।",
        "vietnamese": "Thực ra mọi chuyện đang rất tốt. Tôi hạnh phúc hơn trước nhiều.",
        "arabic": "في الواقع يسير الأمر بشكل رائع. أنا أكثر سعادة بكثير مما كنت عليه.",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "What do you do in your new position?",
        "lithuanian": "Ką veiki naujoje pareigose?",
        "latvian": "Ko tu dari savā jaunajā amatā?",
        "estonian": "Mida sa oma uuel ametikohal teed?",
        "german": "Was machst du in deiner neuen Stelle?",
        "french": "Qu'est-ce que tu fais dans ton nouveau poste?",
        "spanish": "¿Qué haces en tu nuevo puesto?",
        "italian": "Cosa fai nella tua nuova posizione?",
        "portuguese": "O que fazes na tua nova posição?",
        "dutch": "Wat doe je in je nieuwe functie?",
        "polish": "Co robisz na nowym stanowisku?",
        "ukrainian": "Чим ти займаєшся на новій посаді?",
        "russian": "Чем ты занимаешься на новой должности?",
        "swedish": "Vad gör du på din nya position?",
        "norwegian": "Hva gjør du i din nye stilling?",
        "danish": "Hvad laver du i din nye stilling?",
        "finnish": "Mitä teet uudessa tehtävässäsi?",
        "greek": "Τι κάνεις στη νέα σου θέση;",
        "brazilian_portuguese": "O que você faz na sua nova posição?",
        "mandarin": "你在新职位上做什么工作？",
        "japanese": "新しい職場では何をしていますか？",
        "korean": "새 직책에서 무슨 일을 하나요?",
        "hindi": "तुम अपनी नई पोस्ट में क्या काम करते हो?",
        "vietnamese": "Bạn làm gì ở vị trí mới?",
        "arabic": "ماذا تفعل في منصبك الجديد؟",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "I manage a small team of six people. We work on digital marketing projects.",
        "lithuanian": "Vadovauju mažai šešių žmonių komandai. Dirbame su skaitmeninės rinkodaros projektais.",
        "latvian": "Es vadīju nelielu komandu no sešiem cilvēkiem. Mēs strādājam pie digitālā mārketinga projektiem.",
        "estonian": "Juhin väikest kuueinimeselist meeskonda. Töötame digitaalse turunduse projektidega.",
        "german": "Ich leite ein kleines Team von sechs Personen. Wir arbeiten an digitalen Marketingprojekten.",
        "french": "Je gère une petite équipe de six personnes. Nous travaillons sur des projets de marketing digital.",
        "spanish": "Dirijo un pequeño equipo de seis personas. Trabajamos en proyectos de marketing digital.",
        "italian": "Gestisco un piccolo team di sei persone. Lavoriamo su progetti di marketing digitale.",
        "portuguese": "Giro uma pequena equipa de seis pessoas. Trabalhamos em projetos de marketing digital.",
        "dutch": "Ik leid een klein team van zes mensen. We werken aan digitale marketingprojecten.",
        "polish": "Zarządzam małym zespołem sześciu osób. Pracujemy nad projektami marketingu cyfrowego.",
        "ukrainian": "Я керую невеликою командою з шести людей. Ми працюємо над проектами цифрового маркетингу.",
        "russian": "Я руковожу небольшой командой из шести человек. Мы работаем над проектами цифрового маркетинга.",
        "swedish": "Jag leder ett litet team med sex personer. Vi jobbar med digitala marknadsföringsprojekt.",
        "norwegian": "Jeg leder et lite team på seks personer. Vi jobber med digitale markedsføringsprosjekter.",
        "danish": "Jeg leder et lille team på seks personer. Vi arbejder på digitale marketingprojekter.",
        "finnish": "Johdan pientä kuuden hengen tiimiä. Työskentelemme digitaalisten markkinointiprojektien parissa.",
        "greek": "Διαχειρίζομαι μια μικρή ομάδα έξι ατόμων. Εργαζόμαστε σε έργα ψηφιακού μάρκετινγκ.",
        "brazilian_portuguese": "Gerencio uma pequena equipe de seis pessoas. Trabalhamos em projetos de marketing digital.",
        "mandarin": "我管理一个六人小团队。我们从事数字营销项目。",
        "japanese": "六人の小チームを管理しています。デジタルマーケティングのプロジェクトに取り組んでいます。",
        "korean": "6명의 소규모 팀을 관리해요. 디지털 마케팅 프로젝트를 진행하고 있어요.",
        "hindi": "मैं छह लोगों की एक छोटी टीम का प्रबंधन करती हूँ। हम डिजिटल मार्केटिंग प्रोजेक्ट पर काम करते हैं।",
        "vietnamese": "Tôi quản lý một nhóm nhỏ sáu người. Chúng tôi làm việc về các dự án marketing kỹ thuật số.",
        "arabic": "أدير فريقاً صغيراً من ستة أشخاص. نعمل على مشاريع التسويق الرقمي.",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "That sounds interesting. Did you need any special training for the role?",
        "lithuanian": "Tai skamba įdomiai. Ar reikėjo specialaus mokymo šiam vaidmeniui?",
        "latvian": "Tas izklausās interesanti. Vai tev bija nepieciešama kāda īpaša apmācība šim amatam?",
        "estonian": "See kõlab huvitavalt. Kas sul oli vaja erilist koolitust selle rolli jaoks?",
        "german": "Das klingt interessant. Brauchtest du eine besondere Schulung für die Rolle?",
        "french": "Ça a l'air intéressant. Avais-tu besoin d'une formation spéciale pour ce rôle?",
        "spanish": "Eso suena interesante. ¿Necesitabas alguna formación especial para el puesto?",
        "italian": "Sembra interessante. Avevi bisogno di una formazione speciale per il ruolo?",
        "portuguese": "Isso parece interessante. Precisaste de alguma formação especial para a função?",
        "dutch": "Dat klinkt interessant. Had je speciale training nodig voor de rol?",
        "polish": "To brzmi interesująco. Czy potrzebowałeś specjalnego szkolenia do tej roli?",
        "ukrainian": "Це звучить цікаво. Чи потрібно було спеціальне навчання для цієї ролі?",
        "russian": "Звучит интересно. Нужна ли была специальная подготовка для этой роли?",
        "swedish": "Det låter intressant. Behövde du någon speciell utbildning för rollen?",
        "norwegian": "Det høres interessant ut. Trengte du noen spesiell opplæring for rollen?",
        "danish": "Det lyder interessant. Havde du brug for nogen særlig uddannelse til rollen?",
        "finnish": "Kuulostaa mielenkiintoiselta. Tarvitsitko erityistä koulutusta tehtävään?",
        "greek": "Ακούγεται ενδιαφέρον. Χρειαζόσουν ειδική εκπαίδευση για τον ρόλο;",
        "brazilian_portuguese": "Isso soa interessante. Você precisou de treinamento especial para o cargo?",
        "mandarin": "听起来很有趣。你需要接受特殊培训吗？",
        "japanese": "面白そうですね。その役割に特別な研修は必要でしたか？",
        "korean": "흥미롭네요. 이 역할에 특별한 교육이 필요했나요?",
        "hindi": "यह दिलचस्प लगता है। क्या इस भूमिका के लिए विशेष प्रशिक्षण की जरूरत थी?",
        "vietnamese": "Nghe có vẻ thú vị. Bạn có cần đào tạo đặc biệt cho vị trí đó không?",
        "arabic": "يبدو ذلك مثيراً للاهتمام. هل احتجت إلى تدريب خاص للدور؟",
    },
    {
        "line_number": 6, "speaker_name": "Mia",
        "english": "I did an online course in project management last year. That helped a lot.",
        "lithuanian": "Pernai baigiau internetinį projektų valdymo kursą. Tai labai padėjo.",
        "latvian": "Pagājušajā gadā apmeklēju tiešsaistes kursu projektu vadībā. Tas palīdzēja daudz.",
        "estonian": "Tegin eelmisel aastal projektijuhtimise veebikursuse. See aitas palju.",
        "german": "Ich habe letztes Jahr einen Online-Kurs in Projektmanagement gemacht. Das hat sehr geholfen.",
        "french": "J'ai fait un cours en ligne en gestion de projet l'année dernière. Ça a beaucoup aidé.",
        "spanish": "Hice un curso online de gestión de proyectos el año pasado. Eso ayudó mucho.",
        "italian": "Ho fatto un corso online in gestione di progetti l'anno scorso. Ha aiutato molto.",
        "portuguese": "Fiz um curso online em gestão de projetos no ano passado. Isso ajudou muito.",
        "dutch": "Ik deed vorig jaar een online cursus projectmanagement. Dat hielp veel.",
        "polish": "W zeszłym roku zrobiłam internetowy kurs z zarządzania projektami. To bardzo pomogło.",
        "ukrainian": "Я пройшла онлайн-курс з управління проектами минулого року. Це дуже допомогло.",
        "russian": "В прошлом году я прошла онлайн-курс по управлению проектами. Это очень помогло.",
        "swedish": "Jag gjorde en onlinekurs i projektledning förra året. Det hjälpte mycket.",
        "norwegian": "Jeg tok et nettkurs i prosjektledelse i fjor. Det hjalp mye.",
        "danish": "Jeg tog et online kursus i projektledelse sidste år. Det hjalp meget.",
        "finnish": "Tein viime vuonna verkkokurssin projektinhallinnasta. Se auttoi paljon.",
        "greek": "Έκανα ένα διαδικτυακό μάθημα στη διαχείριση έργων πέρυσι. Αυτό βοήθησε πολύ.",
        "brazilian_portuguese": "Fiz um curso online de gerenciamento de projetos no ano passado. Isso ajudou muito.",
        "mandarin": "我去年参加了一个项目管理的在线课程。那很有帮助。",
        "japanese": "昨年、プロジェクトマネジメントのオンラインコースを受講しました。それがとても役立ちました。",
        "korean": "작년에 프로젝트 관리 온라인 강좌를 들었어요. 그게 많은 도움이 됐어요.",
        "hindi": "मैंने पिछले साल प्रोजेक्ट मैनेजमेंट का ऑनलाइन कोर्स किया। उससे बहुत मदद मिली।",
        "vietnamese": "Tôi đã học một khóa quản lý dự án trực tuyến năm ngoái. Điều đó giúp ích rất nhiều.",
        "arabic": "أجريت دورة إدارة المشاريع عبر الإنترنت العام الماضي. ساعد ذلك كثيراً.",
    },
    {
        "line_number": 7, "speaker_name": "Alex",
        "english": "I am also thinking about studying something new. My current job feels a bit boring.",
        "lithuanian": "Aš taip pat galvoju apie kažko naujo mokymąsi. Dabartinis darbas šiek tiek nuobodus.",
        "latvian": "Es arī domāju par ko jaunu mācīties. Mans pašreizējais darbs šķiet mazliet garlaicīgs.",
        "estonian": "Mõtlen ka millegi uue õppimisele. Minu praegune töö tundub natuke igav.",
        "german": "Ich denke auch daran, etwas Neues zu lernen. Mein aktueller Job fühlt sich etwas langweilig an.",
        "french": "Je pense aussi à étudier quelque chose de nouveau. Mon travail actuel semble un peu ennuyeux.",
        "spanish": "También estoy pensando en estudiar algo nuevo. Mi trabajo actual se siente un poco aburrido.",
        "italian": "Sto pensando anche di studiare qualcosa di nuovo. Il mio lavoro attuale sembra un po' noioso.",
        "portuguese": "Também estou a pensar em estudar algo novo. O meu trabalho atual parece um pouco aborrecido.",
        "dutch": "Ik denk er ook aan iets nieuws te studeren. Mijn huidige baan voelt een beetje saai.",
        "polish": "Myślę też o nauce czegoś nowego. Moja obecna praca jest trochę nudna.",
        "ukrainian": "Я теж думаю про вивчення чогось нового. Моя поточна робота здається трохи нудною.",
        "russian": "Я тоже думаю о том, чтобы изучить что-то новое. Моя нынешняя работа кажется немного скучной.",
        "swedish": "Jag tänker också på att studera något nytt. Mitt nuvarande jobb känns lite tråkigt.",
        "norwegian": "Jeg tenker også på å studere noe nytt. Jobben min nå føles litt kjedelig.",
        "danish": "Jeg tænker også på at studere noget nyt. Mit nuværende job føles lidt kedeligt.",
        "finnish": "Harkitsen myös jonkin uuden opiskelua. Nykyinen työ tuntuu hieman tylsältä.",
        "greek": "Σκέφτομαι επίσης να σπουδάσω κάτι νέο. Η τρέχουσα δουλειά μου νιώθεις λίγο βαρετή.",
        "brazilian_portuguese": "Também estou pensando em estudar algo novo. Meu trabalho atual parece um pouco chato.",
        "mandarin": "我也在考虑学习一些新东西。我目前的工作感觉有点无聊。",
        "japanese": "私も何か新しいことを勉強しようかと考えています。今の仕事が少し退屈に感じます。",
        "korean": "저도 새로운 것을 배울까 생각 중이에요. 지금 하는 일이 좀 지루하게 느껴져요.",
        "hindi": "मैं भी कुछ नया पढ़ने के बारे में सोच रहा हूँ। मेरी मौजूदा नौकरी थोड़ी उबाऊ लगती है।",
        "vietnamese": "Tôi cũng đang nghĩ đến việc học thêm điều gì đó mới. Công việc hiện tại của tôi cảm thấy hơi nhàm chán.",
        "arabic": "أفكر أيضاً في دراسة شيء جديد. يبدو عملي الحالي مملاً بعض الشيء.",
    },
    {
        "line_number": 8, "speaker_name": "Mia",
        "english": "What kind of work do you actually enjoy doing?",
        "lithuanian": "Kokio darbo iš tikrųjų mėgsti?",
        "latvian": "Kādu darbu tev patīk darīt?",
        "estonian": "Millist tööd sulle tegelikult meeldib teha?",
        "german": "Welche Art von Arbeit macht dir eigentlich Spaß?",
        "french": "Quel genre de travail est-ce que tu aimes vraiment faire?",
        "spanish": "¿Qué tipo de trabajo realmente disfrutas hacer?",
        "italian": "Che tipo di lavoro ti piace davvero fare?",
        "portuguese": "Que tipo de trabalho gostas realmente de fazer?",
        "dutch": "Welk soort werk geniet je eigenlijk van?",
        "polish": "Jaki rodzaj pracy naprawdę lubisz wykonywać?",
        "ukrainian": "Яку роботу ти насправді любиш виконувати?",
        "russian": "Какую работу тебе действительно нравится делать?",
        "swedish": "Vilket slags arbete tycker du egentligen om att göra?",
        "norwegian": "Hva slags arbeid liker du egentlig å gjøre?",
        "danish": "Hvad slags arbejde nyder du egentlig at lave?",
        "finnish": "Millaista työtä sinusta oikeasti on hauskaa tehdä?",
        "greek": "Τι είδους δουλειά σου αρέσει πραγματικά να κάνεις;",
        "brazilian_portuguese": "Que tipo de trabalho você realmente gosta de fazer?",
        "mandarin": "你真正喜欢做什么类型的工作？",
        "japanese": "実際にはどんな仕事が好きですか？",
        "korean": "사실 어떤 종류의 일을 즐겨 하나요?",
        "hindi": "तुम्हें वास्तव में कैसा काम करना पसंद है?",
        "vietnamese": "Bạn thực sự thích làm loại công việc nào?",
        "arabic": "ما نوع العمل الذي تستمتع به فعلاً؟",
    },
    {
        "line_number": 9, "speaker_name": "Alex",
        "english": "I like working with people and solving problems. I am thinking about human resources.",
        "lithuanian": "Man patinka dirbti su žmonėmis ir spręsti problemas. Galvoju apie žmogiškuosius išteklius.",
        "latvian": "Man patīk strādāt ar cilvēkiem un risināt problēmas. Es domāju par cilvēkresursiem.",
        "estonian": "Mulle meeldib töötada inimestega ja probleeme lahendada. Mõtlen personalitöö peale.",
        "german": "Ich arbeite gerne mit Menschen und löse Probleme. Ich denke an Personalwesen.",
        "french": "J'aime travailler avec les gens et résoudre des problèmes. Je pense aux ressources humaines.",
        "spanish": "Me gusta trabajar con personas y resolver problemas. Estoy pensando en recursos humanos.",
        "italian": "Mi piace lavorare con le persone e risolvere problemi. Sto pensando alle risorse umane.",
        "portuguese": "Gosto de trabalhar com pessoas e resolver problemas. Estou a pensar em recursos humanos.",
        "dutch": "Ik werk graag met mensen en los problemen op. Ik denk aan personeelszaken.",
        "polish": "Lubię pracować z ludźmi i rozwiązywać problemy. Myślę o zasobach ludzkich.",
        "ukrainian": "Мені подобається працювати з людьми і вирішувати проблеми. Думаю про управління персоналом.",
        "russian": "Мне нравится работать с людьми и решать проблемы. Я думаю об управлении персоналом.",
        "swedish": "Jag gillar att jobba med människor och lösa problem. Jag tänker på personalfrågor.",
        "norwegian": "Jeg liker å jobbe med mennesker og løse problemer. Jeg tenker på personalledelse.",
        "danish": "Jeg kan lide at arbejde med mennesker og løse problemer. Jeg tænker på menneskelige ressourcer.",
        "finnish": "Pidän ihmisten kanssa työskentelystä ja ongelmien ratkaisemisesta. Mietin henkilöstöhallintoa.",
        "greek": "Μου αρέσει να εργάζομαι με ανθρώπους και να λύνω προβλήματα. Σκέφτομαι τους ανθρώπινους πόρους.",
        "brazilian_portuguese": "Gosto de trabalhar com pessoas e resolver problemas. Estou pensando em recursos humanos.",
        "mandarin": "我喜欢与人合作并解决问题。我在考虑人力资源。",
        "japanese": "人と働くことと問題解決が好きです。人事を考えています。",
        "korean": "사람들과 함께 일하고 문제를 해결하는 것을 좋아해요. 인사관리를 생각하고 있어요.",
        "hindi": "मुझे लोगों के साथ काम करना और समस्याएँ सुलझाना पसंद है। मैं मानव संसाधन के बारे में सोच रहा हूँ।",
        "vietnamese": "Tôi thích làm việc với mọi người và giải quyết vấn đề. Tôi đang nghĩ đến nhân sự.",
        "arabic": "أحب العمل مع الناس وحل المشكلات. أفكر في الموارد البشرية.",
    },
    {
        "line_number": 10, "speaker_name": "Mia",
        "english": "HR is a great field. There is a lot of demand for good HR professionals.",
        "lithuanian": "Personalo valdymas yra puiki sritis. Yra didelė paklausa gerų personalo specialistų.",
        "latvian": "Cilvēkresursi ir lieliska joma. Ir liels pieprasījums pēc labiem personāla speciālistiem.",
        "estonian": "Personalitöö on suurepärane valdkond. Heade personalispetsialistide järele on suur nõudlus.",
        "german": "HR ist ein großartiges Fachgebiet. Es gibt eine große Nachfrage nach guten HR-Fachleuten.",
        "french": "Les RH sont un excellent domaine. Il y a beaucoup de demandes pour de bons professionnels RH.",
        "spanish": "RRHH es un gran campo. Hay mucha demanda de buenos profesionales de RRHH.",
        "italian": "Le risorse umane sono un ottimo campo. C'è molta domanda di buoni professionisti HR.",
        "portuguese": "RH é uma ótima área. Há muita procura de bons profissionais de RH.",
        "dutch": "HR is een geweldig vakgebied. Er is veel vraag naar goede HR-professionals.",
        "polish": "HR to świetna dziedzina. Jest duże zapotrzebowanie na dobrych specjalistów HR.",
        "ukrainian": "HR — чудова сфера. Є великий попит на хороших HR-спеціалістів.",
        "russian": "HR — это отличная область. Хороших HR-специалистов очень ждут.",
        "swedish": "HR är ett fantastiskt område. Det finns stor efterfrågan på bra HR-proffs.",
        "norwegian": "HR er et flott felt. Det er stor etterspørsel etter gode HR-profesjonelle.",
        "danish": "HR er et fantastisk felt. Der er stor efterspørgsel efter gode HR-professionelle.",
        "finnish": "HR on hieno ala. Hyville HR-ammattilaisille on paljon kysyntää.",
        "greek": "Τα ανθρώπινα δυναμικά είναι ένας εξαιρετικός τομέας. Υπάρχει μεγάλη ζήτηση για καλούς επαγγελματίες HR.",
        "brazilian_portuguese": "RH é uma área ótima. Há muita demanda por bons profissionais de RH.",
        "mandarin": "人力资源是一个很好的领域。对优秀人力资源专业人士的需求很大。",
        "japanese": "HRは素晴らしい分野です。優れたHR専門家への需要はとても多いです。",
        "korean": "HR은 훌륭한 분야예요. 좋은 HR 전문가에 대한 수요가 많아요.",
        "hindi": "HR एक बेहतरीन क्षेत्र है। अच्छे HR पेशेवरों की बड़ी माँग है।",
        "vietnamese": "HR là lĩnh vực tuyệt vời. Có nhu cầu lớn đối với các chuyên gia nhân sự giỏi.",
        "arabic": "الموارد البشرية مجال رائع. هناك طلب كبير على متخصصي الموارد البشرية الجيدين.",
    },
    {
        "line_number": 11, "speaker_name": "Alex",
        "english": "What salary can I expect in that kind of role?",
        "lithuanian": "Kokio atlyginimo galiu tikėtis tokiose pareigose?",
        "latvian": "Kādu algu es varu sagaidīt šādā amatā?",
        "estonian": "Millist palka saab sellises rollis oodata?",
        "german": "Welches Gehalt kann ich in einer solchen Rolle erwarten?",
        "french": "Quel salaire puis-je espérer dans ce genre de rôle?",
        "spanish": "¿Qué salario puedo esperar en ese tipo de puesto?",
        "italian": "Che stipendio posso aspettarmi in quel tipo di ruolo?",
        "portuguese": "Que salário posso esperar nesse tipo de função?",
        "dutch": "Welk salaris kan ik verwachten in dat soort rol?",
        "polish": "Jakiej pensji mogę się spodziewać w takiej roli?",
        "ukrainian": "Яку зарплату можна очікувати на такій посаді?",
        "russian": "Какую зарплату можно ожидать на такой должности?",
        "swedish": "Vilken lön kan jag förvänta mig i den typen av roll?",
        "norwegian": "Hvilken lønn kan jeg forvente i den typen stilling?",
        "danish": "Hvilken løn kan jeg forvente i den slags rolle?",
        "finnish": "Millaista palkkaa voi odottaa sellaisessa roolissa?",
        "greek": "Ποιος μισθός μπορώ να περιμένω σε αυτό το είδος ρόλου;",
        "brazilian_portuguese": "Que salário posso esperar nesse tipo de cargo?",
        "mandarin": "在那种职位上我能期待什么薪水？",
        "japanese": "そのような役割ではどんな給与が期待できますか？",
        "korean": "그런 역할에서 어떤 연봉을 기대할 수 있나요?",
        "hindi": "उस तरह की भूमिका में मुझे किस वेतन की उम्मीद हो सकती है?",
        "vietnamese": "Tôi có thể kỳ vọng mức lương nào trong loại vai trò đó?",
        "arabic": "ما الراتب الذي يمكنني توقعه في هذا النوع من المناصب؟",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "It depends on the country and the company. Entry level is usually quite reasonable.",
        "lithuanian": "Tai priklauso nuo šalies ir įmonės. Pradinis lygis paprastai gana tinkamas.",
        "latvian": "Tas ir atkarīgs no valsts un uzņēmuma. Ievada līmenis parasti ir diezgan saprātīgs.",
        "estonian": "See sõltub riigist ja ettevõttest. Algajate tase on tavaliselt üsna mõistlik.",
        "german": "Es hängt vom Land und vom Unternehmen ab. Einstiegsniveau ist normalerweise recht vernünftig.",
        "french": "Ça dépend du pays et de l'entreprise. Le niveau débutant est généralement assez raisonnable.",
        "spanish": "Depende del país y la empresa. El nivel inicial suele ser bastante razonable.",
        "italian": "Dipende dal paese e dall'azienda. Il livello iniziale è di solito abbastanza ragionevole.",
        "portuguese": "Depende do país e da empresa. O nível inicial é geralmente bastante razoável.",
        "dutch": "Het hangt af van het land en het bedrijf. Instapniveau is normaal redelijk.",
        "polish": "To zależy od kraju i firmy. Poziom podstawowy jest zwykle całkiem rozsądny.",
        "ukrainian": "Це залежить від країни та компанії. Початковий рівень зазвичай цілком прийнятний.",
        "russian": "Зависит от страны и компании. Начальный уровень обычно вполне разумный.",
        "swedish": "Det beror på landet och företaget. Ingångsnivån är vanligtvis ganska rimlig.",
        "norwegian": "Det avhenger av landet og selskapet. Inngangsnivå er vanligvis ganske rimelig.",
        "danish": "Det afhænger af landet og virksomheden. Begynderniveau er normalt ganske rimeligt.",
        "finnish": "Se riippuu maasta ja yrityksestä. Lähtötaso on yleensä melko kohtuullinen.",
        "greek": "Εξαρτάται από τη χώρα και την εταιρεία. Το επίπεδο εισόδου είναι συνήθως αρκετά λογικό.",
        "brazilian_portuguese": "Depende do país e da empresa. O nível inicial é geralmente bastante razoável.",
        "mandarin": "这取决于国家和公司。入门级通常相当合理。",
        "japanese": "国と会社によります。エントリーレベルは通常かなり合理的です。",
        "korean": "나라와 회사에 따라 달라요. 신입 수준은 보통 꽤 적절해요.",
        "hindi": "यह देश और कंपनी पर निर्भर करता है। प्रवेश स्तर आमतौर पर काफी उचित होता है।",
        "vietnamese": "Tùy thuộc vào đất nước và công ty. Mức vào nghề thường khá hợp lý.",
        "arabic": "يعتمد ذلك على البلد والشركة. المستوى الابتدائي معقول عادةً.",
    },
    {
        "line_number": 13, "speaker_name": "Alex",
        "english": "Do you think working from home is better than working in an office?",
        "lithuanian": "Ar manai, kad dirbti iš namų yra geriau nei dirbti biure?",
        "latvian": "Vai tu domā, ka strādāt no mājām ir labāk nekā birojā?",
        "estonian": "Kas sa arvad, et kodust töötamine on parem kui kontoris töötamine?",
        "german": "Glaubst du, dass Arbeiten von zu Hause besser ist als im Büro zu arbeiten?",
        "french": "Penses-tu que travailler à domicile est mieux que travailler dans un bureau?",
        "spanish": "¿Crees que trabajar desde casa es mejor que trabajar en una oficina?",
        "italian": "Pensi che lavorare da casa sia meglio che lavorare in ufficio?",
        "portuguese": "Achas que trabalhar de casa é melhor do que trabalhar num escritório?",
        "dutch": "Denk je dat thuiswerken beter is dan op kantoor werken?",
        "polish": "Czy uważasz że praca z domu jest lepsza niż praca w biurze?",
        "ukrainian": "Як ти вважаєш, чи робота вдома краща ніж в офісі?",
        "russian": "Ты думаешь, что работа из дома лучше, чем в офисе?",
        "swedish": "Tror du att jobba hemifrån är bättre än att jobba på kontoret?",
        "norwegian": "Tror du at det er bedre å jobbe hjemmefra enn på kontoret?",
        "danish": "Tror du at det er bedre at arbejde hjemmefra end på kontoret?",
        "finnish": "Luuletko, että kotona työskentely on parempaa kuin toimistossa?",
        "greek": "Πιστεύεις ότι η εργασία από το σπίτι είναι καλύτερη από το να δουλεύεις σε γραφείο;",
        "brazilian_portuguese": "Você acha que trabalhar em casa é melhor do que trabalhar no escritório?",
        "mandarin": "你认为在家工作比在办公室工作更好吗？",
        "japanese": "在宅勤務はオフィス勤務よりいいと思いますか？",
        "korean": "재택근무가 사무실 근무보다 낫다고 생각하나요?",
        "hindi": "क्या तुम्हें लगता है कि घर से काम करना ऑफिस में काम करने से बेहतर है?",
        "vietnamese": "Bạn có nghĩ làm việc ở nhà tốt hơn làm việc ở văn phòng không?",
        "arabic": "هل تعتقد أن العمل من المنزل أفضل من العمل في مكتب؟",
    },
    {
        "line_number": 14, "speaker_name": "Mia",
        "english": "I think a mix of both is ideal. You need the social side of an office too.",
        "lithuanian": "Manau, kad abiejų derinys yra idealus. Tau taip pat reikia socialinės biuro pusės.",
        "latvian": "Es domāju, ka abējo kombinācija ir ideāla. Tev arī vajag biroja sociālo pusi.",
        "estonian": "Arvan, et mõlema segu on ideaalne. Sul on vaja ka kontori sotsiaalset poolt.",
        "german": "Ich denke, eine Mischung aus beidem ist ideal. Du brauchst auch die soziale Seite eines Büros.",
        "french": "Je pense qu'un mélange des deux est idéal. Tu as aussi besoin de l'aspect social d'un bureau.",
        "spanish": "Creo que una mezcla de ambos es ideal. También necesitas la parte social de una oficina.",
        "italian": "Penso che una combinazione di entrambi sia ideale. Hai bisogno anche della parte sociale di un ufficio.",
        "portuguese": "Acho que uma mistura de ambos é ideal. Precisas também do lado social de um escritório.",
        "dutch": "Ik denk dat een mix van beide ideaal is. Je hebt ook de sociale kant van een kantoor nodig.",
        "polish": "Myślę że połączenie obojga jest idealne. Potrzebujesz też społecznej strony biura.",
        "ukrainian": "Думаю, що поєднання обох є ідеальним. Тобі також потрібна соціальна сторона офісу.",
        "russian": "Думаю, сочетание обоих идеально. Тебе нужна и социальная сторона офиса.",
        "swedish": "Jag tror att en blandning av båda är idealisk. Du behöver också den sociala sidan av ett kontor.",
        "norwegian": "Jeg tror at en blanding av begge er ideell. Du trenger også den sosiale siden av et kontor.",
        "danish": "Jeg tror at en blanding af begge er ideel. Du har også brug for den sociale side af et kontor.",
        "finnish": "Luulen, että molempien sekoitus on ihanteellinen. Tarvitset myös toimiston sosiaalisen puolen.",
        "greek": "Νομίζω ότι ένα μείγμα και των δύο είναι ιδανικό. Χρειάζεσαι επίσης την κοινωνική πλευρά ενός γραφείου.",
        "brazilian_portuguese": "Acho que uma mistura dos dois é ideal. Você também precisa do lado social de um escritório.",
        "mandarin": "我认为两者兼顾是理想的。你也需要办公室的社交方面。",
        "japanese": "両方の組み合わせが理想的だと思います。オフィスの社交面も必要です。",
        "korean": "둘 다 혼합한 것이 이상적이라고 생각해요. 사무실의 사교적인 부분도 필요하거든요.",
        "hindi": "मुझे लगता है दोनों का मिश्रण आदर्श है। तुम्हें ऑफिस के सामाजिक पहलू की भी जरूरत है।",
        "vietnamese": "Tôi nghĩ kết hợp cả hai là lý tưởng. Bạn cũng cần mặt xã hội của văn phòng.",
        "arabic": "أعتقد أن المزج بين الاثنين هو المثالي. أنت بحاجة أيضاً إلى الجانب الاجتماعي للمكتب.",
    },
    {
        "line_number": 15, "speaker_name": "Alex",
        "english": "That is true. I miss talking to colleagues in person.",
        "lithuanian": "Tai tiesa. Pasiilgau bendravimo su kolegomis asmeniškai.",
        "latvian": "Tas ir taisnība. Man pietrūkst personiskas sarunu ar kolēģiem.",
        "estonian": "See on tõsi. Igatsen kolleegidega isiklikku suhtlemist.",
        "german": "Das stimmt. Ich vermisse das persönliche Gespräch mit Kollegen.",
        "french": "C'est vrai. Je regrette les conversations en personne avec mes collègues.",
        "spanish": "Es verdad. Echo de menos hablar con los colegas en persona.",
        "italian": "È vero. Mi manca parlare con i colleghi di persona.",
        "portuguese": "É verdade. Tenho saudades de falar com os colegas pessoalmente.",
        "dutch": "Dat is waar. Ik mis het persoonlijk praten met collega's.",
        "polish": "To prawda. Brakuje mi rozmów z kolegami osobiście.",
        "ukrainian": "Це правда. Мені бракує особистого спілкування з колегами.",
        "russian": "Это правда. Мне не хватает личного общения с коллегами.",
        "swedish": "Det stämmer. Jag saknar att prata med kollegor personligen.",
        "norwegian": "Det er sant. Jeg savner å snakke med kollegaer personlig.",
        "danish": "Det er sandt. Jeg savner at tale med kollegaer personligt.",
        "finnish": "Se on totta. Kaipaan kollegoiden kanssa kasvotusten puhumista.",
        "greek": "Αυτό είναι αλήθεια. Μου λείπει το να μιλώ με συναδέλφους προσωπικά.",
        "brazilian_portuguese": "É verdade. Sinto falta de conversar com colegas pessoalmente.",
        "mandarin": "这是真的。我想念与同事面对面交流。",
        "japanese": "そうですね。同僚と直接話すことが恋しいです。",
        "korean": "그건 맞아요. 동료들과 직접 대화하는 게 그리워요.",
        "hindi": "यह सच है। मुझे सहकर्मियों से व्यक्तिगत रूप से बात करने की याद आती है।",
        "vietnamese": "Điều đó đúng. Tôi nhớ việc nói chuyện trực tiếp với các đồng nghiệp.",
        "arabic": "هذا صحيح. أفتقد التحدث مع الزملاء وجهاً لوجه.",
    },
    {
        "line_number": 16, "speaker_name": "Mia",
        "english": "The social side is so important for motivation and for learning from others.",
        "lithuanian": "Socialinė pusė yra labai svarbi motyvacijai ir mokymuisi iš kitų.",
        "latvian": "Sociālā puse ir tik svarīga motivācijai un mācīšanai no citiem.",
        "estonian": "Sotsiaalne pool on nii oluline motivatsiooni ja teistelt õppimise jaoks.",
        "german": "Die soziale Seite ist so wichtig für die Motivation und um von anderen zu lernen.",
        "french": "La partie sociale est si importante pour la motivation et pour apprendre des autres.",
        "spanish": "La parte social es tan importante para la motivación y para aprender de los demás.",
        "italian": "La parte sociale è così importante per la motivazione e per imparare dagli altri.",
        "portuguese": "A parte social é tão importante para a motivação e para aprender com os outros.",
        "dutch": "De sociale kant is zo belangrijk voor motivatie en om van anderen te leren.",
        "polish": "Część społeczna jest tak ważna dla motywacji i uczenia się od innych.",
        "ukrainian": "Соціальна сторона така важлива для мотивації та навчання у інших.",
        "russian": "Социальная сторона так важна для мотивации и обучения у других.",
        "swedish": "Den sociala sidan är så viktig för motivation och för att lära av andra.",
        "norwegian": "Den sosiale siden er så viktig for motivasjon og for å lære av andre.",
        "danish": "Den sociale side er så vigtig for motivation og for at lære af andre.",
        "finnish": "Sosiaalinen puoli on niin tärkeää motivaatiolle ja muilta oppimiselle.",
        "greek": "Η κοινωνική πλευρά είναι τόσο σημαντική για τα κίνητρα και για να μαθαίνεις από τους άλλους.",
        "brazilian_portuguese": "A parte social é tão importante para a motivação e para aprender com os outros.",
        "mandarin": "社交方面对于激励和向他人学习非常重要。",
        "japanese": "社交面はモチベーションや他者から学ぶためにとても重要です。",
        "korean": "사교적인 측면은 동기부여와 타인에게서 배우는 것에 매우 중요해요.",
        "hindi": "सामाजिक पहलू प्रेरणा और दूसरों से सीखने के लिए बहुत महत्वपूर्ण है।",
        "vietnamese": "Khía cạnh xã hội rất quan trọng cho động lực và học hỏi từ người khác.",
        "arabic": "الجانب الاجتماعي مهم جداً للتحفيز والتعلم من الآخرين.",
    },
    {
        "line_number": 17, "speaker_name": "Alex",
        "english": "How did you find your new job? Did you use a recruitment agency?",
        "lithuanian": "Kaip radai naują darbą? Ar naudojaisi įdarbinimo agentūra?",
        "latvian": "Kā tu atradi savu jauno darbu? Vai tu izmantoji vervēšanas aģentūru?",
        "estonian": "Kuidas sa oma uue töö leidsid? Kas kasutasid värbamisagentuuri?",
        "german": "Wie hast du deinen neuen Job gefunden? Hast du eine Personalvermittlung benutzt?",
        "french": "Comment as-tu trouvé ton nouveau travail? Tu as utilisé une agence de recrutement?",
        "spanish": "¿Cómo encontraste tu nuevo trabajo? ¿Usaste una agencia de reclutamiento?",
        "italian": "Come hai trovato il tuo nuovo lavoro? Hai usato un'agenzia di reclutamento?",
        "portuguese": "Como encontraste o teu novo emprego? Usaste uma agência de recrutamento?",
        "dutch": "Hoe vond je je nieuwe baan? Heb je een wervingsbureau gebruikt?",
        "polish": "Jak znalazłaś nową pracę? Czy korzystałaś z agencji rekrutacyjnej?",
        "ukrainian": "Як ти знайшла нову роботу? Ти використовувала агентство з підбору персоналу?",
        "russian": "Как ты нашла новую работу? Использовала кадровое агентство?",
        "swedish": "Hur hittade du ditt nya jobb? Använde du en rekryteringsbyrå?",
        "norwegian": "Hvordan fant du den nye jobben? Brukte du et rekrutteringsbyrå?",
        "danish": "Hvordan fandt du dit nye job? Brugte du et rekrutteringsbureau?",
        "finnish": "Miten löysit uuden työpaikkasi? Käytitkö rekrytointitoimistoa?",
        "greek": "Πώς βρήκες τη νέα σου δουλειά; Χρησιμοποίησες γραφείο εύρεσης εργασίας;",
        "brazilian_portuguese": "Como você encontrou seu novo emprego? Usou uma agência de recrutamento?",
        "mandarin": "你是怎么找到新工作的？你用了招聘公司吗？",
        "japanese": "新しい仕事はどうやって見つけましたか？採用エージェンシーを使いましたか？",
        "korean": "새 직장은 어떻게 찾았나요? 채용 에이전시를 이용했나요?",
        "hindi": "तुमने नई नौकरी कैसे ढूँढी? क्या तुमने भर्ती एजेंसी का इस्तेमाल किया?",
        "vietnamese": "Bạn tìm được việc mới như thế nào? Bạn có dùng công ty tuyển dụng không?",
        "arabic": "كيف وجدت وظيفتك الجديدة؟ هل استخدمت وكالة توظيف؟",
    },
    {
        "line_number": 18, "speaker_name": "Mia",
        "english": "No I found it through LinkedIn. I updated my profile and a company contacted me directly.",
        "lithuanian": "Ne, radau per LinkedIn. Atnaujinau savo profilį ir su manimi susisiekė įmonė.",
        "latvian": "Nē, es to atradu caur LinkedIn. Es atjaunināju savu profilu un uzņēmums sazinājās ar mani tieši.",
        "estonian": "Ei, leidsin selle LinkedIni kaudu. Uuendasin oma profiili ja ettevõte võttis minuga otse ühendust.",
        "german": "Nein, ich habe es über LinkedIn gefunden. Ich habe mein Profil aktualisiert und ein Unternehmen hat mich direkt kontaktiert.",
        "french": "Non je l'ai trouvé via LinkedIn. J'ai mis à jour mon profil et une entreprise m'a contacté directement.",
        "spanish": "No lo encontré a través de LinkedIn. Actualicé mi perfil y una empresa me contactó directamente.",
        "italian": "No l'ho trovato tramite LinkedIn. Ho aggiornato il mio profilo e un'azienda mi ha contattato direttamente.",
        "portuguese": "Não encontrei-o através do LinkedIn. Atualizei o meu perfil e uma empresa contactou-me diretamente.",
        "dutch": "Nee ik vond het via LinkedIn. Ik werkte mijn profiel bij en een bedrijf nam direct contact met me op.",
        "polish": "Nie znalazłam go przez LinkedIn. Zaktualizowałam profil i firma skontaktowała się ze mną bezpośrednio.",
        "ukrainian": "Ні, я знайшла її через LinkedIn. Оновила профіль і компанія зв'язалася зі мною напряму.",
        "russian": "Нет, я нашла через LinkedIn. Обновила профиль, и компания сама связалась со мной.",
        "swedish": "Nej jag hittade det via LinkedIn. Jag uppdaterade min profil och ett företag kontaktade mig direkt.",
        "norwegian": "Nei jeg fant det via LinkedIn. Jeg oppdaterte profilen min og et selskap kontaktet meg direkte.",
        "danish": "Nej jeg fandt det via LinkedIn. Jeg opdaterede min profil og et firma kontaktede mig direkte.",
        "finnish": "Ei, löysin sen LinkedInin kautta. Päivitin profiilin ja yritys otti minuun suoraan yhteyttä.",
        "greek": "Όχι το βρήκα μέσω LinkedIn. Ανέβαλα το προφίλ μου και μια εταιρεία επικοινώνησε μαζί μου απευθείας.",
        "brazilian_portuguese": "Não encontrei pelo LinkedIn. Atualizei meu perfil e uma empresa entrou em contato diretamente comigo.",
        "mandarin": "不，我通过LinkedIn找到的。我更新了个人资料，一家公司直接联系了我。",
        "japanese": "いいえ、LinkedInで見つけました。プロフィールを更新したら、会社から直接連絡が来ました。",
        "korean": "아니요, LinkedIn을 통해 찾았어요. 프로필을 업데이트했더니 회사에서 직접 연락이 왔어요.",
        "hindi": "नहीं, मैंने इसे LinkedIn के माध्यम से पाया। मैंने अपना प्रोफ़ाइल अपडेट किया और एक कंपनी ने सीधे संपर्क किया।",
        "vietnamese": "Không, tôi tìm thấy qua LinkedIn. Tôi cập nhật hồ sơ và một công ty liên hệ trực tiếp với tôi.",
        "arabic": "لا، وجدته عبر LinkedIn. حدّثت ملفي الشخصي فتواصلت معي شركة مباشرةً.",
    },
    {
        "line_number": 19, "speaker_name": "Alex",
        "english": "That is a great tip. My LinkedIn profile is very outdated.",
        "lithuanian": "Tai puikus patarimas. Mano LinkedIn profilis labai pasenęs.",
        "latvian": "Tas ir lielisks padoms. Mans LinkedIn profils ir ļoti novecojis.",
        "estonian": "See on suurepärane näpunäide. Minu LinkedIn profiil on väga aegunud.",
        "german": "Das ist ein toller Tipp. Mein LinkedIn-Profil ist sehr veraltet.",
        "french": "C'est un super conseil. Mon profil LinkedIn est très dépassé.",
        "spanish": "Es un gran consejo. Mi perfil de LinkedIn está muy desactualizado.",
        "italian": "È un ottimo consiglio. Il mio profilo LinkedIn è molto obsoleto.",
        "portuguese": "É uma ótima dica. O meu perfil do LinkedIn está muito desatualizado.",
        "dutch": "Dat is een geweldige tip. Mijn LinkedIn-profiel is erg verouderd.",
        "polish": "To świetna wskazówka. Mój profil na LinkedIn jest bardzo przestarzały.",
        "ukrainian": "Це чудова порада. Мій профіль у LinkedIn дуже застарілий.",
        "russian": "Отличный совет. Мой профиль в LinkedIn очень устаревший.",
        "swedish": "Det är ett bra tips. Min LinkedIn-profil är väldigt föråldrad.",
        "norwegian": "Det er et flott tips. Min LinkedIn-profil er veldig utdatert.",
        "danish": "Det er et godt tip. Min LinkedIn-profil er meget forældet.",
        "finnish": "Se on loistava vinkki. LinkedIn-profiilini on erittäin vanhentunut.",
        "greek": "Αυτή είναι μια εξαιρετική συμβουλή. Το προφίλ μου στο LinkedIn είναι πολύ ξεπερασμένο.",
        "brazilian_portuguese": "É uma ótima dica. Meu perfil no LinkedIn está muito desatualizado.",
        "mandarin": "这是个很好的建议。我的LinkedIn个人资料非常过时了。",
        "japanese": "それは素晴らしいヒントです。私のLinkedInプロフィールはとても古くなっています。",
        "korean": "좋은 팁이네요. 제 LinkedIn 프로필이 많이 오래됐어요.",
        "hindi": "यह एक बेहतरीन सुझाव है। मेरा LinkedIn प्रोफाइल बहुत पुराना है।",
        "vietnamese": "Đó là mẹo hay. Hồ sơ LinkedIn của tôi đã rất lỗi thời.",
        "arabic": "هذه نصيحة رائعة. ملفي الشخصي على LinkedIn قديم جداً.",
    },
    {
        "line_number": 20, "speaker_name": "Mia",
        "english": "Update it today. Add your skills and a professional photo. You might be surprised who contacts you.",
        "lithuanian": "Atnaujink jį šiandien. Pridėk savo įgūdžius ir profesionalią nuotrauką. Galbūt nustebsi, kas tave susisieks.",
        "latvian": "Atjaunini to šodien. Pievieno savas prasmes un profesionālu fotoattēlu. Tu varētu būt pārsteigts, kas ar tevi sazināsies.",
        "estonian": "Uuenda seda täna. Lisa oma oskused ja professionaalne foto. Võib-olla oled üllatunud, kes sinuga ühendust võtab.",
        "german": "Aktualisiere es heute. Füge deine Fähigkeiten und ein professionelles Foto hinzu. Du wärst vielleicht überrascht wer sich bei dir meldet.",
        "french": "Mets-le à jour aujourd'hui. Ajoute tes compétences et une photo professionnelle. Tu pourrais être surpris de qui te contacte.",
        "spanish": "Actualízalo hoy. Añade tus habilidades y una foto profesional. Podrías sorprenderte de quién te contacta.",
        "italian": "Aggiornalo oggi. Aggiungi le tue competenze e una foto professionale. Potresti essere sorpreso di chi ti contatta.",
        "portuguese": "Atualiza-o hoje. Adiciona as tuas competências e uma foto profissional. Pode surpreender-te quem te contacta.",
        "dutch": "Werk het vandaag bij. Voeg je vaardigheden en een professionele foto toe. Je zou misschien verrast zijn wie contact met je opneemt.",
        "polish": "Zaktualizuj go dzisiaj. Dodaj swoje umiejętności i profesjonalne zdjęcie. Możesz być zaskoczony kto się z tobą skontaktuje.",
        "ukrainian": "Оновіть його сьогодні. Додайте свої навички та професійне фото. Можливо, ти здивуєшся, хто з тобою зв'яжеться.",
        "russian": "Обнови его сегодня. Добавь свои навыки и профессиональное фото. Возможно, удивишься, кто с тобой свяжется.",
        "swedish": "Uppdatera det idag. Lägg till dina kunskaper och ett professionellt foto. Du kan bli förvånad över vem som kontaktar dig.",
        "norwegian": "Oppdater det i dag. Legg til ferdighetene dine og et profesjonelt bilde. Du kan bli overrasket over hvem som tar kontakt.",
        "danish": "Opdater det i dag. Tilføj dine færdigheder og et professionelt foto. Du kan blive overrasket over hvem der kontakter dig.",
        "finnish": "Päivitä se tänään. Lisää taitosi ja ammatillinen kuva. Saatat yllättyä siitä kuka ottaa sinuun yhteyttä.",
        "greek": "Ανανέωσέ το σήμερα. Πρόσθεσε τις δεξιότητές σου και μια επαγγελματική φωτογραφία. Μπορεί να εκπλαγείς από ποιον θα σε επικοινωνήσει.",
        "brazilian_portuguese": "Atualize hoje. Adicione suas habilidades e uma foto profissional. Você pode se surpreender com quem vai entrar em contato.",
        "mandarin": "今天就更新它。添加你的技能和一张专业照片。你可能会惊讶于谁联系你。",
        "japanese": "今日更新してください。スキルとプロ写真を追加してください。誰から連絡が来るか驚くかもしれません。",
        "korean": "오늘 업데이트하세요. 기술과 전문적인 사진을 추가하세요. 누가 연락할지 놀랄 수도 있어요.",
        "hindi": "इसे आज ही अपडेट करो। अपने कौशल और एक पेशेवर तस्वीर जोड़ो। तुम शायद हैरान हो जाओगे कि कौन संपर्क करता है।",
        "vietnamese": "Cập nhật nó ngay hôm nay. Thêm kỹ năng và ảnh chuyên nghiệp. Bạn có thể ngạc nhiên về ai liên hệ với bạn.",
        "arabic": "حدّثه اليوم. أضف مهاراتك وصورة احترافية. قد تتفاجأ بمن سيتواصل معك.",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="Talking About Work and Career").first()
        if existing:
            print("B1 dialogue 'Talking About Work and Career' already exists — skipping.")
            return

        dialogue = Dialogue(topic="Talking About Work and Career", lang_level="B1", length=20)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded B1 dialogue ID {dialogue.id} — 20 lines in 25 languages.")


if __name__ == '__main__':
    seed()
