import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "Good morning. I need something for a cold.",
        "lithuanian": "Labas rytas. Man reikia kažko nuo peršalimo.",
        "latvian": "Labrīt. Man vajag kaut ko pret saaukstēšanos.",
        "estonian": "Tere hommikust. Mul on vaja midagi nohu vastu.",
        "german": "Guten Morgen. Ich brauche etwas gegen eine Erkältung.",
        "french": "Bonjour. J'ai besoin de quelque chose contre un rhume.",
        "spanish": "Buenos días. Necesito algo para el resfriado.",
        "italian": "Buongiorno. Ho bisogno di qualcosa per il raffreddore.",
        "portuguese": "Bom dia. Preciso de algo para a constipação.",
        "dutch": "Goedemorgen. Ik heb iets nodig tegen een verkoudheid.",
        "polish": "Dzień dobry. Potrzebuję czegoś na przeziębienie.",
        "ukrainian": "Доброго ранку. Мені потрібно щось від застуди.",
        "russian": "Доброе утро. Мне нужно что-нибудь от простуды.",
        "swedish": "God morgon. Jag behöver något mot en förkylning.",
        "norwegian": "God morgen. Jeg trenger noe mot en forkjølelse.",
        "danish": "God morgen. Jeg har brug for noget mod en forkølelse.",
        "finnish": "Hyvää huomenta. Tarvitsen jotain nuhaa vastaan.",
        "greek": "Καλημέρα. Χρειάζομαι κάτι για το κρυολόγημα.",
        "brazilian_portuguese": "Bom dia. Preciso de algo para o resfriado.",
        "mandarin": "早上好。我需要一些感冒药。",
        "japanese": "おはようございます。風邪に効くものが必要です。",
        "korean": "안녕하세요. 감기약이 필요해요.",
        "hindi": "सुप्रभात। मुझे सर्दी के लिए कुछ चाहिए।",
        "vietnamese": "Chào buổi sáng. Tôi cần thứ gì đó để trị cảm lạnh.",
        "arabic": "صباح الخير. أحتاج شيئاً للزكام.",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "Of course. How long have you had the cold?",
        "lithuanian": "Žinoma. Kiek laiko sergate peršalimu?",
        "latvian": "Protams. Cik ilgi jums ir saaukstēšanās?",
        "estonian": "Muidugi. Kui kaua on teil nohu olnud?",
        "german": "Natürlich. Wie lange haben Sie schon die Erkältung?",
        "french": "Bien sûr. Depuis combien de temps avez-vous ce rhume?",
        "spanish": "Por supuesto. ¿Cuánto tiempo lleva con el resfriado?",
        "italian": "Certo. Da quanto tempo ha il raffreddore?",
        "portuguese": "Claro. Há quanto tempo está constipado?",
        "dutch": "Natuurlijk. Hoe lang heeft u al de verkoudheid?",
        "polish": "Oczywiście. Jak długo ma pan to przeziębienie?",
        "ukrainian": "Звичайно. Як давно у вас застуда?",
        "russian": "Конечно. Как давно у вас простуда?",
        "swedish": "Naturligtvis. Hur länge har du haft förkylningen?",
        "norwegian": "Selvfølgelig. Hvor lenge har du hatt forkjølelsen?",
        "danish": "Selvfølgelig. Hvor længe har du haft forkølelsen?",
        "finnish": "Tietysti. Kuinka kauan teillä on ollut nuha?",
        "greek": "Βεβαίως. Πόσο καιρό έχετε το κρυολόγημα;",
        "brazilian_portuguese": "Claro. Há quanto tempo você está resfriado?",
        "mandarin": "当然。您感冒多久了？",
        "japanese": "もちろんです。どのくらい前から風邪を引いていますか？",
        "korean": "물론이죠. 감기에 걸린 지 얼마나 됐어요?",
        "hindi": "बिल्कुल। आपको सर्दी कब से है?",
        "vietnamese": "Tất nhiên. Bạn bị cảm lạnh bao lâu rồi?",
        "arabic": "بالطبع. منذ متى وأنت مصاب بالزكام؟",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "Since yesterday. I have a runny nose a sore throat and a headache.",
        "lithuanian": "Nuo vakar. Turiu slogą gerklės skausmą ir galvos skausmą.",
        "latvian": "Kopš vakar. Man ir iesnas, sāp kakls un galva.",
        "estonian": "Eilsest. Mul on nohu kurk valutab ja peavalu.",
        "german": "Seit gestern. Ich habe eine laufende Nase Halsschmerzen und Kopfschmerzen.",
        "french": "Depuis hier. J'ai le nez qui coule un mal de gorge et un mal de tête.",
        "spanish": "Desde ayer. Tengo mocos dolor de garganta y dolor de cabeza.",
        "italian": "Da ieri. Ho il naso che cola mal di gola e mal di testa.",
        "portuguese": "Desde ontem. Tenho nariz a pingar dor de garganta e dor de cabeça.",
        "dutch": "Sinds gisteren. Ik heb een loopneus keelpijn en hoofdpijn.",
        "polish": "Od wczoraj. Mam katar ból gardła i ból głowy.",
        "ukrainian": "З вчора. У мене нежить біль у горлі та головний біль.",
        "russian": "Со вчера. У меня насморк боль в горле и головная боль.",
        "swedish": "Sedan igår. Jag har rinnande näsa ont i halsen och huvudvärk.",
        "norwegian": "Siden i går. Jeg har rennende nese vondt i halsen og hodepine.",
        "danish": "Siden i går. Jeg har løbende næse ondt i halsen og hovedpine.",
        "finnish": "Eilisestä. Minulla on vuotava nenä kurkkukipu ja päänsärky.",
        "greek": "Από χθες. Έχω μύτη που τρέχει πονόλαιμο και πονοκέφαλο.",
        "brazilian_portuguese": "Desde ontem. Tenho nariz escorrendo dor de garganta e dor de cabeça.",
        "mandarin": "从昨天开始。我流鼻涕、喉咙痛、头痛。",
        "japanese": "昨日からです。鼻水が出て喉が痛くて頭痛があります。",
        "korean": "어제부터요. 콧물이 나고 목이 아프고 두통이 있어요.",
        "hindi": "कल से। नाक बह रही है, गला दर्द हो रहा है और सिरदर्द है।",
        "vietnamese": "Từ hôm qua. Tôi bị chảy nước mũi đau họng và đau đầu.",
        "arabic": "منذ الأمس. لديّ سيلان في الأنف والتهاب في الحلق وصداع.",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "Do you have a fever?",
        "lithuanian": "Ar turite temperatūrą?",
        "latvian": "Vai jums ir drudzis?",
        "estonian": "Kas teil on palavik?",
        "german": "Haben Sie Fieber?",
        "french": "Avez-vous de la fièvre?",
        "spanish": "¿Tiene fiebre?",
        "italian": "Ha la febbre?",
        "portuguese": "Tem febre?",
        "dutch": "Heeft u koorts?",
        "polish": "Czy ma pan gorączkę?",
        "ukrainian": "У вас є температура?",
        "russian": "У вас есть температура?",
        "swedish": "Har du feber?",
        "norwegian": "Har du feber?",
        "danish": "Har du feber?",
        "finnish": "Onko teillä kuumetta?",
        "greek": "Έχετε πυρετό;",
        "brazilian_portuguese": "Você está com febre?",
        "mandarin": "您发烧吗？",
        "japanese": "熱はありますか？",
        "korean": "열이 있나요?",
        "hindi": "क्या आपको बुखार है?",
        "vietnamese": "Bạn có bị sốt không?",
        "arabic": "هل لديك حمى؟",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "I do not think so. I feel cold but not hot.",
        "lithuanian": "Nemanau. Jaučiuosi šaltai bet ne karštai.",
        "latvian": "Es tā nedomāju. Man ir auksti bet ne karsti.",
        "estonian": "Ma ei arva. Tunnen end külmana aga mitte kuumana.",
        "german": "Ich glaube nicht. Mir ist kalt aber nicht heiß.",
        "french": "Je ne pense pas. Je me sens froid mais pas chaud.",
        "spanish": "Creo que no. Siento frío pero no calor.",
        "italian": "Non credo. Mi sento freddo ma non caldo.",
        "portuguese": "Acho que não. Sinto frio mas não calor.",
        "dutch": "Ik denk het niet. Ik voel me koud maar niet warm.",
        "polish": "Nie sądzę. Czuję się zimno ale nie gorąco.",
        "ukrainian": "Не думаю. Мені холодно але не гаряче.",
        "russian": "Не думаю. Мне холодно но не жарко.",
        "swedish": "Jag tror inte det. Jag känner mig kall men inte het.",
        "norwegian": "Jeg tror ikke det. Jeg føler meg kald men ikke varm.",
        "danish": "Jeg tror ikke det. Jeg føler mig kold men ikke varm.",
        "finnish": "En usko. Minulla on kylmä mutta ei kuuma.",
        "greek": "Δεν νομίζω. Αισθάνομαι κρύο αλλά όχι ζέστη.",
        "brazilian_portuguese": "Acho que não. Me sinto frio mas não com calor.",
        "mandarin": "我不这么认为。感觉冷但不热。",
        "japanese": "そうは思いません。寒く感じますが熱くはありません。",
        "korean": "그런 것 같지 않아요. 춥지만 덥진 않아요.",
        "hindi": "मुझे नहीं लगता। ठंड लग रही है लेकिन बुखार नहीं।",
        "vietnamese": "Tôi không nghĩ vậy. Tôi cảm thấy lạnh nhưng không nóng.",
        "arabic": "لا أعتقد ذلك. أشعر بالبرد لا بالحرارة.",
    },
    {
        "line_number": 6, "speaker_name": "Mia",
        "english": "I recommend this cold medicine. It helps with all your symptoms.",
        "lithuanian": "Rekomenduoju šį vaistą nuo peršalimo. Jis padeda nuo visų jūsų simptomų.",
        "latvian": "Es iesaku šo saaukstēšanās zāles. Tās palīdz pret visiem jūsu simptomiem.",
        "estonian": "Soovitan seda nohuravimit. See aitab kõigi teie sümptomite vastu.",
        "german": "Ich empfehle dieses Erkältungsmittel. Es hilft bei allen Ihren Symptomen.",
        "french": "Je recommande ce médicament contre le rhume. Il aide pour tous vos symptômes.",
        "spanish": "Le recomiendo este medicamento para el resfriado. Ayuda con todos sus síntomas.",
        "italian": "Consiglio questo medicinale per il raffreddore. Aiuta con tutti i suoi sintomi.",
        "portuguese": "Recomendo este medicamento para a constipação. Ajuda com todos os seus sintomas.",
        "dutch": "Ik beveel dit verkoudheidsmedicijn aan. Het helpt bij al uw symptomen.",
        "polish": "Polecam ten lek na przeziębienie. Pomaga na wszystkie pana objawy.",
        "ukrainian": "Рекомендую цей засіб від застуди. Він допомагає від усіх ваших симптомів.",
        "russian": "Рекомендую это лекарство от простуды. Оно помогает при всех ваших симптомах.",
        "swedish": "Jag rekommenderar det här förkylningsmedlet. Det hjälper med alla dina symptom.",
        "norwegian": "Jeg anbefaler dette forkjølelsesmiddelet. Det hjelper med alle symptomene dine.",
        "danish": "Jeg anbefaler dette forkølelsesmiddel. Det hjælper med alle dine symptomer.",
        "finnish": "Suosittelen tätä nuhulääkettä. Se auttaa kaikkiin oireisiinne.",
        "greek": "Συνιστώ αυτό το φάρμακο για το κρυολόγημα. Βοηθά με όλα τα συμπτώματά σας.",
        "brazilian_portuguese": "Recomendo este remédio para o resfriado. Ele ajuda com todos os seus sintomas.",
        "mandarin": "我推荐这种感冒药。它可以缓解您的所有症状。",
        "japanese": "この風邪薬をお勧めします。すべての症状に効きます。",
        "korean": "이 감기약을 추천해요. 모든 증상에 도움이 돼요.",
        "hindi": "मैं यह सर्दी की दवा सुझाता हूँ। यह आपके सभी लक्षणों में मदद करती है।",
        "vietnamese": "Tôi khuyên dùng thuốc cảm lạnh này. Nó giúp với tất cả các triệu chứng của bạn.",
        "arabic": "أنصح بهذا الدواء للزكام. يساعد على جميع أعراضك.",
    },
    {
        "line_number": 7, "speaker_name": "Alex",
        "english": "How many times a day should I take it?",
        "lithuanian": "Kiek kartų per dieną jį vartoti?",
        "latvian": "Cik reizes dienā man tas jālieto?",
        "estonian": "Mitu korda päevas peaksin seda võtma?",
        "german": "Wie oft am Tag soll ich es nehmen?",
        "french": "Combien de fois par jour dois-je le prendre?",
        "spanish": "¿Cuántas veces al día debo tomarlo?",
        "italian": "Quante volte al giorno devo prenderlo?",
        "portuguese": "Quantas vezes por dia devo tomá-lo?",
        "dutch": "Hoe vaak per dag moet ik het innemen?",
        "polish": "Ile razy dziennie powinienem to brać?",
        "ukrainian": "Скільки разів на день мені це приймати?",
        "russian": "Сколько раз в день мне это принимать?",
        "swedish": "Hur många gånger om dagen ska jag ta det?",
        "norwegian": "Hvor mange ganger om dagen skal jeg ta det?",
        "danish": "Hvor mange gange om dagen skal jeg tage det?",
        "finnish": "Kuinka monta kertaa päivässä minun pitää ottaa sitä?",
        "greek": "Πόσες φορές την ημέρα πρέπει να το παίρνω;",
        "brazilian_portuguese": "Quantas vezes ao dia devo tomar?",
        "mandarin": "我一天需要服用几次？",
        "japanese": "一日何回飲めばいいですか？",
        "korean": "하루에 몇 번 먹어야 하나요?",
        "hindi": "दिन में कितनी बार लेनी है?",
        "vietnamese": "Tôi nên uống bao nhiêu lần một ngày?",
        "arabic": "كم مرة في اليوم يجب أن آخذه؟",
    },
    {
        "line_number": 8, "speaker_name": "Mia",
        "english": "Take one tablet three times a day with food. Do not take more than three per day.",
        "lithuanian": "Vartokite vieną tabletę tris kartus per dieną su maistu. Nevartokite daugiau nei trijų per dieną.",
        "latvian": "Lietojiet vienu tableti trīs reizes dienā ar ēdienu. Neļaujiet vairāk kā trīs dienā.",
        "estonian": "Võtke üks tablett kolm korda päevas koos toiduga. Ärge võtke rohkem kui kolm päevas.",
        "german": "Nehmen Sie eine Tablette dreimal täglich mit dem Essen. Nehmen Sie nicht mehr als drei pro Tag.",
        "french": "Prenez un comprimé trois fois par jour avec de la nourriture. Ne prenez pas plus de trois par jour.",
        "spanish": "Tome un comprimido tres veces al día con comida. No tome más de tres al día.",
        "italian": "Prenda una compressa tre volte al giorno con il cibo. Non prenda più di tre al giorno.",
        "portuguese": "Tome um comprimido três vezes por dia com comida. Não tome mais de três por dia.",
        "dutch": "Neem één tablet drie keer per dag bij het eten. Neem niet meer dan drie per dag.",
        "polish": "Bierz jedną tabletkę trzy razy dziennie z jedzeniem. Nie bierz więcej niż trzy dziennie.",
        "ukrainian": "Приймайте одну таблетку три рази на день з їжею. Не приймайте більше трьох на день.",
        "russian": "Принимайте одну таблетку три раза в день с едой. Не принимайте больше трёх в день.",
        "swedish": "Ta en tablett tre gånger om dagen med mat. Ta inte mer än tre per dag.",
        "norwegian": "Ta en tablett tre ganger om dagen med mat. Ikke ta mer enn tre per dag.",
        "danish": "Tag en tablet tre gange om dagen med mad. Tag ikke mere end tre om dagen.",
        "finnish": "Ota yksi tabletti kolme kertaa päivässä ruoan kanssa. Älä ota enemmän kuin kolme päivässä.",
        "greek": "Πάρτε ένα δισκίο τρεις φορές την ημέρα με φαγητό. Μην παίρνετε περισσότερα από τρία την ημέρα.",
        "brazilian_portuguese": "Tome um comprimido três vezes ao dia com alimento. Não tome mais de três por dia.",
        "mandarin": "每天随餐服用一片，一天三次。每天不超过三片。",
        "japanese": "食事と一緒に一日三回一錠飲んでください。一日三錠以上は飲まないでください。",
        "korean": "하루 세 번 식사와 함께 한 알씩 드세요. 하루에 세 알 이상은 드시지 마세요.",
        "hindi": "खाने के साथ दिन में तीन बार एक गोली लें। एक दिन में तीन से ज़्यादा न लें।",
        "vietnamese": "Uống một viên ba lần mỗi ngày cùng với thức ăn. Không uống quá ba viên mỗi ngày.",
        "arabic": "خذ قرصاً واحداً ثلاث مرات يومياً مع الطعام. لا تأخذ أكثر من ثلاثة في اليوم.",
    },
    {
        "line_number": 9, "speaker_name": "Alex",
        "english": "Does it make you sleepy?",
        "lithuanian": "Ar tai sukelia mieguistumą?",
        "latvian": "Vai tas izraisa miegainību?",
        "estonian": "Kas see teeb uniseks?",
        "german": "Macht es schläfrig?",
        "french": "Est-ce que ça rend somnolent?",
        "spanish": "¿Produce somnolencia?",
        "italian": "Dà sonno?",
        "portuguese": "Provoca sonolência?",
        "dutch": "Maakt het slaperig?",
        "polish": "Czy powoduje senność?",
        "ukrainian": "Чи викликає це сонливість?",
        "russian": "Вызывает ли это сонливость?",
        "swedish": "Gör det dig sömnig?",
        "norwegian": "Gjør det deg søvnig?",
        "danish": "Gør det dig søvnig?",
        "finnish": "Aiheuttaako se uneliaisuutta?",
        "greek": "Προκαλεί υπνηλία;",
        "brazilian_portuguese": "Causa sonolência?",
        "mandarin": "它会让人犯困吗？",
        "japanese": "眠くなりますか？",
        "korean": "졸리게 만드나요?",
        "hindi": "क्या इससे नींद आती है?",
        "vietnamese": "Nó có gây buồn ngủ không?",
        "arabic": "هل يسبب النعاس؟",
    },
    {
        "line_number": 10, "speaker_name": "Mia",
        "english": "Yes a little. So do not drive after taking it. Drink lots of water too.",
        "lithuanian": "Taip šiek tiek. Todėl nevairuokite po jo vartojimo. Taip pat gerkite daug vandens.",
        "latvian": "Jā nedaudz. Tādēļ nevadiet automašīnu pēc tā lietošanas. Dzeriet arī daudz ūdens.",
        "estonian": "Jah veidi. Seetõttu ärge sõitke pärast selle võtmist. Jooge ka palju vett.",
        "german": "Ja ein bisschen. Fahren Sie daher nach der Einnahme nicht Auto. Trinken Sie auch viel Wasser.",
        "french": "Oui un peu. Donc ne conduisez pas après l'avoir pris. Buvez aussi beaucoup d'eau.",
        "spanish": "Sí un poco. Así que no conduzca después de tomarlo. Beba también mucha agua.",
        "italian": "Sì un po'. Quindi non guidare dopo averlo preso. Bevi anche molta acqua.",
        "portuguese": "Sim um pouco. Então não conduza depois de o tomar. Beba também muita água.",
        "dutch": "Ja een beetje. Rijd daarom niet na het innemen. Drink ook veel water.",
        "polish": "Tak trochę. Nie należy więc prowadzić po zażyciu. Pij też dużo wody.",
        "ukrainian": "Так трохи. Тому не керуйте автомобілем після прийому. Пийте також багато води.",
        "russian": "Да немного. Поэтому не садитесь за руль после приёма. Также пейте много воды.",
        "swedish": "Ja lite. Kör därför inte efter att ha tagit det. Drick också mycket vatten.",
        "norwegian": "Ja litt. Så ikke kjør etter å ha tatt det. Drikk også mye vann.",
        "danish": "Ja lidt. Så kør ikke efter at have taget det. Drik også meget vand.",
        "finnish": "Kyllä hiukan. Älä siis aja autoa sen ottamisen jälkeen. Juo myös paljon vettä.",
        "greek": "Ναι λίγο. Άρα μην οδηγείτε αφού το πάρετε. Πιείτε επίσης πολύ νερό.",
        "brazilian_portuguese": "Sim um pouco. Então não dirija depois de tomar. Beba também muita água.",
        "mandarin": "是的，有点。所以服药后不要开车。也要多喝水。",
        "japanese": "はい少し眠くなります。ですから服用後は運転しないでください。水もたくさん飲んでください。",
        "korean": "네, 조금요. 그러니 복용 후에는 운전하지 마세요. 물도 많이 드세요.",
        "hindi": "हाँ, थोड़ा। इसलिए इसे लेने के बाद गाड़ी न चलाएँ। खूब पानी भी पिएँ।",
        "vietnamese": "Vâng một chút. Vì vậy đừng lái xe sau khi uống. Cũng uống nhiều nước.",
        "arabic": "نعم قليلاً. لذا لا تقود السيارة بعد تناوله. واشرب أيضاً الكثير من الماء.",
    },
    {
        "line_number": 11, "speaker_name": "Alex",
        "english": "Do you have vitamin C tablets as well?",
        "lithuanian": "Ar taip pat turite vitamino C tablečių?",
        "latvian": "Vai jums ir arī C vitamīna tabletes?",
        "estonian": "Kas teil on ka C-vitamiini tablette?",
        "german": "Haben Sie auch Vitamin-C-Tabletten?",
        "french": "Avez-vous aussi des comprimés de vitamine C?",
        "spanish": "¿Tiene también comprimidos de vitamina C?",
        "italian": "Ha anche le compresse di vitamina C?",
        "portuguese": "Tem também comprimidos de vitamina C?",
        "dutch": "Heeft u ook vitamine C tabletten?",
        "polish": "Czy ma pan też tabletki witaminy C?",
        "ukrainian": "У вас також є таблетки вітаміну С?",
        "russian": "У вас также есть таблетки витамина С?",
        "swedish": "Har du också C-vitamintabletter?",
        "norwegian": "Har du også C-vitamintabletter?",
        "danish": "Har du også C-vitamintabletter?",
        "finnish": "Onko teillä myös C-vitamiinitabletteja?",
        "greek": "Έχετε επίσης δισκία βιταμίνης C;",
        "brazilian_portuguese": "Você tem também comprimidos de vitamina C?",
        "mandarin": "您也有维生素C片吗？",
        "japanese": "ビタミンCのタブレットもありますか？",
        "korean": "비타민 C 정제도 있나요?",
        "hindi": "क्या आपके पास विटामिन सी की गोलियाँ भी हैं?",
        "vietnamese": "Bạn có viên vitamin C không?",
        "arabic": "هل لديك أيضاً أقراص فيتامين سي؟",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "Yes. These are very good. They are orange flavour. Take one every morning.",
        "lithuanian": "Taip. Šie labai geri. Jie yra apelsinų skonio. Vartokite vieną kiekvieną rytą.",
        "latvian": "Jā. Šie ir ļoti labi. Tie ir apelsīnu garšas. Lietojiet vienu katru rītu.",
        "estonian": "Jah. Need on väga head. Need on apelsinimaitselised. Võtke üks iga hommik.",
        "german": "Ja. Diese sind sehr gut. Sie haben Orangengeschmack. Nehmen Sie jeden Morgen eines.",
        "french": "Oui. Ceux-ci sont très bons. Ils sont au goût d'orange. Prenez-en un chaque matin.",
        "spanish": "Sí. Estos son muy buenos. Son de sabor naranja. Tome uno cada mañana.",
        "italian": "Sì. Questi sono molto buoni. Sono al gusto di arancia. Prendane uno ogni mattina.",
        "portuguese": "Sim. Estes são muito bons. São de sabor a laranja. Tome um cada manhã.",
        "dutch": "Ja. Deze zijn erg goed. Ze hebben sinaasappelsmaak. Neem elke ochtend één.",
        "polish": "Tak. Te są bardzo dobre. Mają smak pomarańczowy. Bierz jeden każdego ranka.",
        "ukrainian": "Так. Ці дуже хороші. Вони апельсинового смаку. Приймайте один кожного ранку.",
        "russian": "Да. Эти очень хорошие. Они апельсинового вкуса. Принимайте один каждое утро.",
        "swedish": "Ja. Dessa är mycket bra. De har apelsinsmak. Ta en varje morgon.",
        "norwegian": "Ja. Disse er veldig gode. De er med appelsinsmak. Ta en hver morgen.",
        "danish": "Ja. Disse er meget gode. De er med appelsinssmag. Tag en hver morgen.",
        "finnish": "Kyllä. Nämä ovat erittäin hyviä. Ne ovat appelsiinin makuisia. Ottakaa yksi joka aamu.",
        "greek": "Ναι. Αυτά είναι πολύ καλά. Είναι γεύση πορτοκαλιού. Πάρτε ένα κάθε πρωί.",
        "brazilian_portuguese": "Sim. Estes são muito bons. São de sabor laranja. Tome um toda manhã.",
        "mandarin": "是的。这些很好。是橙味的。每天早晨吃一颗。",
        "japanese": "はい。これらはとても良いです。オレンジ味です。毎朝一つ飲んでください。",
        "korean": "네. 이건 아주 좋아요. 오렌지 맛이에요. 매일 아침 하나씩 드세요.",
        "hindi": "हाँ। ये बहुत अच्छे हैं। ये संतरे के स्वाद के हैं। हर सुबह एक लें।",
        "vietnamese": "Vâng. Những cái này rất tốt. Chúng có vị cam. Uống một viên mỗi buổi sáng.",
        "arabic": "نعم. هذه جيدة جداً. بنكهة البرتقال. خذ واحداً كل صباح.",
    },
    {
        "line_number": 13, "speaker_name": "Alex",
        "english": "Good idea. Can I also get some throat lozenges?",
        "lithuanian": "Gera mintis. Ar galiu gauti ir pastilių gerklei?",
        "latvian": "Laba ideja. Vai es varu arī dabūt kādas kakla pastillas?",
        "estonian": "Hea mõte. Kas ma saan ka mõned kurguimemistabletid?",
        "german": "Gute Idee. Kann ich auch Halspastillen bekommen?",
        "french": "Bonne idée. Puis-je aussi avoir des pastilles pour la gorge?",
        "spanish": "Buena idea. ¿Puedo conseguir también algunas pastillas para la garganta?",
        "italian": "Buona idea. Posso avere anche delle pastiglie per la gola?",
        "portuguese": "Boa ideia. Posso também pegar algumas pastilhas para a garganta?",
        "dutch": "Goed idee. Kan ik ook keelpastilles krijgen?",
        "polish": "Dobry pomysł. Czy mogę też dostać pastylki na gardło?",
        "ukrainian": "Гарна ідея. Чи можу я також отримати льодяники для горла?",
        "russian": "Хорошая идея. Могу ли я также получить таблетки от горла?",
        "swedish": "Bra idé. Kan jag också få lite halstabletter?",
        "norwegian": "God idé. Kan jeg også få noen halspastiller?",
        "danish": "God idé. Kan jeg også få nogle halspastiller?",
        "finnish": "Hyvä idea. Voinko myös saada kurkkupastilleja?",
        "greek": "Καλή ιδέα. Μπορώ να πάρω και μερικές παστίλιες για τον λαιμό;",
        "brazilian_portuguese": "Boa ideia. Posso pegar também algumas pastilhas para a garganta?",
        "mandarin": "好主意。我也可以买一些润喉糖吗？",
        "japanese": "いい考えですね。のど飴も買えますか？",
        "korean": "좋은 생각이에요. 목 사탕도 살 수 있나요?",
        "hindi": "अच्छा विचार है। क्या मुझे गले की गोलियाँ भी मिल सकती हैं?",
        "vietnamese": "Ý hay đó. Tôi có thể mua một số kẹo ngậm họng không?",
        "arabic": "فكرة جيدة. هل يمكنني الحصول أيضاً على أقراص للحلق؟",
    },
    {
        "line_number": 14, "speaker_name": "Mia",
        "english": "Yes. We have honey and lemon or mint. Which do you prefer?",
        "lithuanian": "Taip. Turime medaus ir citrinos arba mėtų. Kurių pageidaujate?",
        "latvian": "Jā. Mums ir medus un citronu vai piparmētru. Kurus jūs dodat priekšroku?",
        "estonian": "Jah. Meil on mee ja sidruni või piparmündi maitsega. Kumba eelistate?",
        "german": "Ja. Wir haben Honig und Zitrone oder Minze. Welche bevorzugen Sie?",
        "french": "Oui. Nous avons miel et citron ou menthe. Lesquelles préférez-vous?",
        "spanish": "Sí. Tenemos miel y limón o menta. ¿Cuál prefiere?",
        "italian": "Sì. Abbiamo miele e limone o menta. Quale preferisce?",
        "portuguese": "Sim. Temos mel e limão ou menta. Qual prefere?",
        "dutch": "Ja. We hebben honing en citroen of munt. Welke heeft u liever?",
        "polish": "Tak. Mamy miód i cytrynę lub miętę. Który pan woli?",
        "ukrainian": "Так. У нас є мед і лимон або м'ята. Які ви надаєте перевагу?",
        "russian": "Да. У нас есть мёд и лимон или мята. Какие вы предпочитаете?",
        "swedish": "Ja. Vi har honung och citron eller mynta. Vilka föredrar du?",
        "norwegian": "Ja. Vi har honning og sitron eller mynte. Hvilken foretrekker du?",
        "danish": "Ja. Vi har honning og citron eller mynte. Hvilken foretrækker du?",
        "finnish": "Kyllä. Meillä on hunaja ja sitruuna tai minttu. Kumman suositte?",
        "greek": "Ναι. Έχουμε μέλι και λεμόνι ή μέντα. Ποιες προτιμάτε;",
        "brazilian_portuguese": "Sim. Temos mel e limão ou menta. Qual você prefere?",
        "mandarin": "是的。我们有蜂蜜柠檬味或薄荷味。您喜欢哪种？",
        "japanese": "はい。ハニーレモン味かミント味があります。どちらがお好みですか？",
        "korean": "네. 꿀레몬 맛이나 민트 맛이 있어요. 어떤 게 좋으세요?",
        "hindi": "हाँ। हमारे पास शहद और नींबू या पुदीना है। आप कौन सा पसंद करते हैं?",
        "vietnamese": "Vâng. Chúng tôi có vị mật ong chanh hoặc bạc hà. Bạn thích loại nào?",
        "arabic": "نعم. لدينا العسل والليمون أو النعناع. أيهما تفضل؟",
    },
    {
        "line_number": 15, "speaker_name": "Alex",
        "english": "Honey and lemon please. They are my favourite.",
        "lithuanian": "Medaus ir citrinos prašau. Tai mano mėgstamiausi.",
        "latvian": "Medus un citronu lūdzu. Tie ir mani mīļākie.",
        "estonian": "Mee ja sidrunit palun. Need on minu lemmikud.",
        "german": "Honig und Zitrone bitte. Das sind meine Lieblinge.",
        "french": "Miel et citron s'il vous plaît. Ce sont mes préférés.",
        "spanish": "Miel y limón por favor. Son mis favoritas.",
        "italian": "Miele e limone per favore. Sono le mie preferite.",
        "portuguese": "Mel e limão por favor. São as minhas favoritas.",
        "dutch": "Honing en citroen alstublieft. Dat zijn mijn favorieten.",
        "polish": "Miód i cytrynę proszę. To moje ulubione.",
        "ukrainian": "Мед і лимон будь ласка. Вони мої улюблені.",
        "russian": "Мёд и лимон пожалуйста. Это мои любимые.",
        "swedish": "Honung och citron tack. De är mina favoriter.",
        "norwegian": "Honning og sitron takk. De er mine favoritter.",
        "danish": "Honning og citron tak. De er mine favoritter.",
        "finnish": "Hunajaa ja sitruunaa kiitos. Ne ovat suosikkejani.",
        "greek": "Μέλι και λεμόνι παρακαλώ. Είναι τα αγαπημένα μου.",
        "brazilian_portuguese": "Mel e limão por favor. São os meus favoritos.",
        "mandarin": "蜂蜜柠檬味。这是我最喜欢的。",
        "japanese": "ハニーレモンをください。私のお気に入りです。",
        "korean": "꿀레몬으로 주세요. 제가 가장 좋아하는 거예요.",
        "hindi": "शहद और नींबू वाले दीजिए। ये मेरे पसंदीदा हैं।",
        "vietnamese": "Mật ong chanh. Đó là thứ yêu thích của tôi.",
        "arabic": "العسل والليمون من فضلك. هما المفضلان لديّ.",
    },
    {
        "line_number": 16, "speaker_name": "Mia",
        "english": "Is there anything else you need today?",
        "lithuanian": "Ar jums šiandien reikia dar ko nors?",
        "latvian": "Vai jums šodien vēl kaut kas vajadzīgs?",
        "estonian": "Kas teil on täna midagi muud vaja?",
        "german": "Brauchen Sie heute noch etwas anderes?",
        "french": "Avez-vous besoin d'autre chose aujourd'hui?",
        "spanish": "¿Necesita algo más hoy?",
        "italian": "Ha bisogno di qualcos'altro oggi?",
        "portuguese": "Precisa de mais alguma coisa hoje?",
        "dutch": "Heeft u vandaag nog iets anders nodig?",
        "polish": "Czy potrzebuje pan dziś czegoś jeszcze?",
        "ukrainian": "Вам сьогодні ще щось потрібно?",
        "russian": "Вам сегодня ещё что-нибудь нужно?",
        "swedish": "Behöver du något annat idag?",
        "norwegian": "Trenger du noe annet i dag?",
        "danish": "Har du brug for noget andet i dag?",
        "finnish": "Tarvitsetteko jotain muuta tänään?",
        "greek": "Χρειάζεστε κάτι άλλο σήμερα;",
        "brazilian_portuguese": "Você precisa de mais alguma coisa hoje?",
        "mandarin": "今天还需要其他什么吗？",
        "japanese": "今日は他に何か必要なものはありますか？",
        "korean": "오늘 다른 건 필요하신 게 없으세요?",
        "hindi": "क्या आज आपको कुछ और चाहिए?",
        "vietnamese": "Hôm nay bạn có cần gì khác không?",
        "arabic": "هل تحتاج شيئاً آخر اليوم؟",
    },
    {
        "line_number": 17, "speaker_name": "Alex",
        "english": "Yes. Can I get some plasters? I cut my finger yesterday.",
        "lithuanian": "Taip. Ar galiu gauti pleistrų? Vakar įsipjoviau pirštą.",
        "latvian": "Jā. Vai es varu dabūt dažus plāksterus? Vakar es iegriezu pirkstu.",
        "estonian": "Jah. Kas ma saan mõned plaastrid? Lõikasin eile sõrme.",
        "german": "Ja. Kann ich einige Pflaster bekommen? Ich habe mir gestern in den Finger geschnitten.",
        "french": "Oui. Puis-je avoir des pansements? Je me suis coupé le doigt hier.",
        "spanish": "Sí. ¿Puedo conseguir algunas tiritas? Me corté el dedo ayer.",
        "italian": "Sì. Posso avere dei cerotti? Mi sono tagliato il dito ieri.",
        "portuguese": "Sim. Posso ter alguns pensos rápidos? Cortei o dedo ontem.",
        "dutch": "Ja. Kan ik wat pleisters krijgen? Ik heb mijn vinger gisteren gesneden.",
        "polish": "Tak. Czy mogę dostać plastry? Wczoraj skaleczyłem się w palec.",
        "ukrainian": "Так. Чи можу я отримати пластирі? Вчора порізав палець.",
        "russian": "Да. Могу ли я получить пластыри? Вчера порезал палец.",
        "swedish": "Ja. Kan jag få lite plåster? Jag skar mig i fingret igår.",
        "norwegian": "Ja. Kan jeg få noen plaster? Jeg kuttet fingeren i går.",
        "danish": "Ja. Kan jeg få nogle plaster? Jeg skar mig i fingeren i går.",
        "finnish": "Kyllä. Voinko saada laastareita? Leikkasin sormeani eilen.",
        "greek": "Ναι. Μπορώ να πάρω λίγα επιθέματα; Έκοψα το δάχτυλό μου χθες.",
        "brazilian_portuguese": "Sim. Posso pegar alguns curativos? Cortei o dedo ontem.",
        "mandarin": "是的。我可以买一些创可贴吗？我昨天割伤了手指。",
        "japanese": "はい。絆創膏をもらえますか？昨日指を切ってしまいました。",
        "korean": "네. 반창고도 살 수 있나요? 어제 손가락을 베었어요.",
        "hindi": "हाँ। क्या मुझे कुछ पट्टी मिल सकती है? कल मैंने अपनी उँगली काट ली।",
        "vietnamese": "Vâng. Tôi có thể mua một số băng cá nhân không? Tôi bị đứt ngón tay hôm qua.",
        "arabic": "نعم. هل يمكنني الحصول على بعض الضمادات؟ لقد جرحت إصبعي أمس.",
    },
    {
        "line_number": 18, "speaker_name": "Mia",
        "english": "Of course. These are waterproof and very comfortable. They are good for fingers.",
        "lithuanian": "Žinoma. Šie yra vandeniui atsparūs ir labai patogūs. Jie tinka pirštams.",
        "latvian": "Protams. Šie ir ūdensnecaurlaidīgi un ļoti ērti. Tie ir piemēroti pirkstiem.",
        "estonian": "Muidugi. Need on veekindlad ja väga mugavad. Need sobivad sõrmede jaoks.",
        "german": "Natürlich. Diese sind wasserdicht und sehr bequem. Sie sind gut für Finger.",
        "french": "Bien sûr. Ceux-ci sont imperméables et très confortables. Ils sont bons pour les doigts.",
        "spanish": "Por supuesto. Estas son impermeables y muy cómodas. Son buenas para los dedos.",
        "italian": "Certo. Questi sono impermeabili e molto comodi. Sono ottimi per le dita.",
        "portuguese": "Claro. Estes são impermeáveis e muito confortáveis. São bons para os dedos.",
        "dutch": "Natuurlijk. Deze zijn waterdicht en erg comfortabel. Ze zijn goed voor vingers.",
        "polish": "Oczywiście. Te są wodoodporne i bardzo wygodne. Są dobre do palców.",
        "ukrainian": "Звичайно. Ці водонепроникні та дуже зручні. Вони підходять для пальців.",
        "russian": "Конечно. Эти водонепроницаемые и очень удобные. Они хороши для пальцев.",
        "swedish": "Naturligtvis. Dessa är vattentäta och väldigt bekväma. De är bra för fingrar.",
        "norwegian": "Selvfølgelig. Disse er vanntette og veldig komfortable. De er bra for fingre.",
        "danish": "Selvfølgelig. Disse er vandtætte og meget komfortable. De er gode til fingre.",
        "finnish": "Tietysti. Nämä ovat vedenpitäviä ja erittäin mukavia. Ne ovat hyviä sormille.",
        "greek": "Βεβαίως. Αυτά είναι αδιάβροχα και πολύ άνετα. Είναι καλά για τα δάχτυλα.",
        "brazilian_portuguese": "Claro. Estes são à prova d'água e muito confortáveis. São bons para os dedos.",
        "mandarin": "当然。这些是防水的，非常舒适。适合手指使用。",
        "japanese": "もちろんです。これらは防水で非常に快適です。指に最適です。",
        "korean": "물론이죠. 이건 방수가 되고 아주 편해요. 손가락에 잘 맞아요.",
        "hindi": "बिल्कुल। ये वाटरप्रूफ और बहुत आरामदायक हैं। उँगलियों के लिए अच्छे हैं।",
        "vietnamese": "Tất nhiên. Những cái này chống thấm nước và rất thoải mái. Chúng tốt cho ngón tay.",
        "arabic": "بالطبع. هذه مقاومة للماء ومريحة جداً. إنها جيدة للأصابع.",
    },
    {
        "line_number": 19, "speaker_name": "Alex",
        "english": "Perfect. What is the total price for everything?",
        "lithuanian": "Puiku. Kokia bendra kaina už viską?",
        "latvian": "Lieliski. Cik ir kopējā cena par visu?",
        "estonian": "Suurepärane. Mis on kõige kogumaksumus?",
        "german": "Perfekt. Was ist der Gesamtpreis für alles?",
        "french": "Parfait. Quel est le prix total pour tout?",
        "spanish": "Perfecto. ¿Cuál es el precio total de todo?",
        "italian": "Perfetto. Qual è il prezzo totale per tutto?",
        "portuguese": "Perfeito. Qual é o preço total de tudo?",
        "dutch": "Perfect. Wat is de totaalprijs voor alles?",
        "polish": "Świetnie. Jaka jest łączna cena za wszystko?",
        "ukrainian": "Чудово. Яка загальна ціна за все?",
        "russian": "Отлично. Какова общая цена за всё?",
        "swedish": "Perfekt. Vad är det totala priset för allt?",
        "norwegian": "Perfekt. Hva er totalprisen for alt?",
        "danish": "Perfekt. Hvad er den samlede pris for alt?",
        "finnish": "Täydellinen. Paljonko kaikki maksaa yhteensä?",
        "greek": "Τέλεια. Ποια είναι η συνολική τιμή για όλα;",
        "brazilian_portuguese": "Perfeito. Qual é o preço total de tudo?",
        "mandarin": "太好了。所有东西一共多少钱？",
        "japanese": "完璧です。全部でいくらですか？",
        "korean": "좋아요. 전부 합해서 얼마예요?",
        "hindi": "बढ़िया। सब कुछ मिलाकर कुल कितना हुआ?",
        "vietnamese": "Tuyệt vời. Tổng giá tất cả là bao nhiêu?",
        "arabic": "ممتاز. ما هو السعر الإجمالي لكل شيء؟",
    },
    {
        "line_number": 20, "speaker_name": "Mia",
        "english": "The medicine is eight euros, vitamin C is four euros, lozenges are three fifty, and plasters are two twenty. Your total is seventeen euros seventy. I hope you feel better soon!",
        "lithuanian": "Vaistai yra aštuoni eurai, vitaminas C keturi eurai, pastilės trys penkiasdešimt, o pleistrai du dvidešimt. Jūsų suma yra septyniolika eurų septyniasdešimt. Tikiuosi greitai pasijusite geriau!",
        "latvian": "Zāles ir astoņi eiro, C vitamīns četri eiro, pastillas trīs piecdesmit un plāksteris divi divdesmit. Jūsu kopā ir septiņpadsmit eiro septiņdesmit. Ceru ka jūs drīz jutīsieties labāk!",
        "estonian": "Ravim on kaheksa eurot, C-vitamiin neli eurot, imemistabletid kolm viiskümmend ja plaastrid kaks kakskümmend. Teie kogusumma on seitseteist eurot seitsekümmend. Loodan et tunnete end varsti paremini!",
        "german": "Das Medikament kostet acht Euro, Vitamin C vier Euro, Pastillen drei fünfzig und Pflaster zwei zwanzig. Ihr Gesamtbetrag beträgt siebzehn Euro siebzig. Ich hoffe Sie fühlen sich bald besser!",
        "french": "Le médicament coûte huit euros, la vitamine C quatre euros, les pastilles trois euros cinquante et les pansements deux euros vingt. Votre total est dix-sept euros soixante-dix. J'espère que vous vous sentirez mieux bientôt!",
        "spanish": "El medicamento son ocho euros, la vitamina C cuatro euros, las pastillas tres cincuenta y las tiritas dos veinte. Su total es diecisiete euros setenta. ¡Espero que se sienta mejor pronto!",
        "italian": "Il medicinale è otto euro, la vitamina C quattro euro, le pastiglie tre e cinquanta e i cerotti due e venti. Il suo totale è diciassette euro e settanta. Spero si senta meglio presto!",
        "portuguese": "O medicamento é oito euros, a vitamina C quatro euros, as pastilhas três e cinquenta e os pensos dois e vinte. O seu total é dezassete euros e setenta. Espero que se sinta melhor em breve!",
        "dutch": "Het medicijn is acht euro, vitamine C vier euro, pastilles drie vijftig en pleisters twee twintig. Uw totaal is zeventien euro zeventig. Ik hoop dat u zich snel beter voelt!",
        "polish": "Lek to osiem euro, witamina C cztery euro, pastylki trzy pięćdziesiąt i plastry dwa dwadzieścia. Pana łączna kwota to siedemnaście euro siedemdziesiąt. Mam nadzieję że wkrótce poczuje się pan lepiej!",
        "ukrainian": "Ліки коштують вісім євро, вітамін С чотири євро, льодяники три п'ятдесят, а пластирі два двадцять. Ваша загальна сума сімнадцять євро сімдесят. Сподіваюся ви скоро почуєтесь краще!",
        "russian": "Лекарство стоит восемь евро, витамин С четыре евро, пастилки три пятьдесят, а пластыри два двадцать. Ваш итого — семнадцать евро семьдесят. Надеюсь вы скоро почувствуете себя лучше!",
        "swedish": "Medicinen är åtta euro, C-vitamin fyra euro, halstabletter tre femtio och plåster två tjugo. Din totala summa är sjutton euro sjuttio. Jag hoppas att du känner dig bättre snart!",
        "norwegian": "Medisinen er åtte euro, C-vitamin fire euro, halspastiller tre femti og plaster to tjue. Din totale sum er sytten euro sytti. Jeg håper du føler deg bedre snart!",
        "danish": "Medicinen er otte euro, C-vitamin fire euro, halspastiller tre halvtreds og plaster to tyve. Din samlede total er sytten euro halvfjerds. Jeg håber du snart har det bedre!",
        "finnish": "Lääke on kahdeksan euroa, C-vitamiini neljä euroa, pastillit kolme viisikymmentä ja laastarit kaksi kaksikymmentä. Kokonaissummasi on seitsemäntoista euroa seitsemänkymmentä. Toivon sinun tervehtyvan pian!",
        "greek": "Το φάρμακο είναι οκτώ ευρώ, η βιταμίνη C τέσσερα ευρώ, οι παστίλιες τρία πενήντα και τα επιθέματα δύο είκοσι. Το σύνολό σας είναι δεκαεπτά ευρώ εβδομήντα. Ελπίζω να αισθανθείτε καλύτερα σύντομα!",
        "brazilian_portuguese": "O remédio é oito euros, a vitamina C quatro euros, as pastilhas três e cinquenta e os curativos dois e vinte. Seu total é dezessete euros e setenta. Espero que você se sinta melhor em breve!",
        "mandarin": "药物八欧元，维生素C四欧元，润喉糖三欧元五十分，创可贴两欧元二十分。总计十七欧元七十分。希望您早日康复！",
        "japanese": "薬が八ユーロ、ビタミンCが四ユーロ、のど飴が三ユーロ五十セント、絆創膏が二ユーロ二十セントです。合計は十七ユーロ七十セントです。早くよくなりますように！",
        "korean": "약이 팔 유로, 비타민 C가 사 유로, 목 사탕이 삼 유로 오십 센트, 반창고가 이 유로 이십 센트예요. 총계는 십칠 유로 칠십 센트입니다. 빨리 나으시길 바랍니다!",
        "hindi": "दवाई आठ यूरो, विटामिन सी चार यूरो, गोलियाँ तीन पचास, और पट्टी दो बीस। आपका कुल सत्रह यूरो सत्तर सेंट है। उम्मीद है जल्दी ठीक हो जाएंगे!",
        "vietnamese": "Thuốc tám euro, vitamin C bốn euro, kẹo ngậm ba euro năm mươi xu và băng cá nhân hai euro hai mươi xu. Tổng của bạn là mười bảy euro bảy mươi xu. Hy vọng bạn sớm khỏe lại!",
        "arabic": "الدواء ثمانية يورو وفيتامين سي أربعة يورو والأقراص ثلاثة وخمسون سنتاً والضمادات اثنان وعشرون سنتاً. مجموعك سبعة عشر يورو وسبعون سنتاً. أتمنى أن تتحسن صحتك قريباً!",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="At the Pharmacy").first()
        if existing:
            print("A2 dialogue 'At the Pharmacy' already exists — skipping.")
            return

        dialogue = Dialogue(topic="At the Pharmacy", lang_level="A2", length=20)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded A2 dialogue ID {dialogue.id} — 20 lines in 25 languages.")


if __name__ == '__main__':
    seed()
