import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "Good afternoon. I would like to book a room for two nights.",
        "lithuanian": "Laba diena. Norėčiau užsakyti kambarį dviem naktims.",
        "latvian": "Labdien. Es gribētu rezervēt istabu divām naktīm.",
        "estonian": "Tere päevast. Sooviksin broneerida toa kaheks ööks.",
        "german": "Guten Tag. Ich möchte ein Zimmer für zwei Nächte buchen.",
        "french": "Bonjour. Je voudrais réserver une chambre pour deux nuits.",
        "spanish": "Buenas tardes. Me gustaría reservar una habitación para dos noches.",
        "italian": "Buon pomeriggio. Vorrei prenotare una camera per due notti.",
        "portuguese": "Boa tarde. Gostaria de reservar um quarto por duas noites.",
        "dutch": "Goedemiddag. Ik wil graag een kamer voor twee nachten boeken.",
        "polish": "Dzień dobry. Chciałbym zarezerwować pokój na dwie noce.",
        "ukrainian": "Добрий день. Я хотів би забронювати номер на дві ночі.",
        "russian": "Добрый день. Я хотел бы забронировать номер на две ночи.",
        "swedish": "God eftermiddag. Jag skulle vilja boka ett rum för två nätter.",
        "norwegian": "God ettermiddag. Jeg vil gjerne bestille et rom for to netter.",
        "danish": "God eftermiddag. Jeg vil gerne booke et værelse for to nætter.",
        "finnish": "Hyvää iltapäivää. Haluaisin varata huoneen kahdeksi yöksi.",
        "greek": "Καλησπέρα. Θα ήθελα να κλείσω ένα δωμάτιο για δύο νύχτες.",
        "brazilian_portuguese": "Boa tarde. Gostaria de reservar um quarto por duas noites.",
        "mandarin": "下午好。我想预订一个房间，住两晚。",
        "japanese": "こんにちは。二泊分の部屋を予約したいのですが。",
        "korean": "안녕하세요. 이틀 동안 방을 예약하고 싶습니다.",
        "hindi": "नमस्ते। मैं दो रातों के लिए एक कमरा बुक करना चाहूँगा।",
        "vietnamese": "Xin chào. Tôi muốn đặt phòng cho hai đêm.",
        "arabic": "مساء الخير. أود حجز غرفة لليلتين.",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "Of course. What type of room do you prefer — single or double?",
        "lithuanian": "Žinoma. Kokio tipo kambarį pageidaujate — vienvietį ar dvivietį?",
        "latvian": "Protams. Kāda tipa istabu jūs vēlaties — vienvietīgu vai divvietīgu?",
        "estonian": "Muidugi. Millist tüüpi tuba eelistate — üheinimese- või kaheinimesetuba?",
        "german": "Natürlich. Welche Art von Zimmer bevorzugen Sie — Einzel- oder Doppelzimmer?",
        "french": "Bien sûr. Quel type de chambre préférez-vous — simple ou double?",
        "spanish": "Por supuesto. ¿Qué tipo de habitación prefiere — individual o doble?",
        "italian": "Certo. Che tipo di camera preferisce — singola o doppia?",
        "portuguese": "Claro. Que tipo de quarto prefere — simples ou duplo?",
        "dutch": "Natuurlijk. Wat voor soort kamer heeft u liever — enkel of dubbel?",
        "polish": "Oczywiście. Jaki rodzaj pokoju pan preferuje — jednoosobowy czy dwuosobowy?",
        "ukrainian": "Звичайно. Який тип номера ви бажаєте — одномісний чи двомісний?",
        "russian": "Конечно. Какой тип номера вы предпочитаете — одноместный или двухместный?",
        "swedish": "Naturligtvis. Vilken typ av rum föredrar du — enkel eller dubbel?",
        "norwegian": "Selvfølgelig. Hvilken type rom foretrekker du — enkelt eller dobbelt?",
        "danish": "Selvfølgelig. Hvilken type værelse foretrækker du — enkelt eller dobbelt?",
        "finnish": "Tietysti. Minkä tyyppistä huonetta suositte — yhden vai kahden hengen?",
        "greek": "Βεβαίως. Τι τύπο δωματίου προτιμάτε — μονό ή διπλό;",
        "brazilian_portuguese": "Claro. Que tipo de quarto você prefere — simples ou duplo?",
        "mandarin": "当然。您想要哪种类型的房间——单人间还是双人间？",
        "japanese": "もちろんです。シングルルームとダブルルームどちらがよろしいですか？",
        "korean": "물론이죠. 싱글룸과 더블룸 중 어느 것을 원하시나요?",
        "hindi": "बिल्कुल। आप किस प्रकार का कमरा चाहेंगे — एकल या दोहरा?",
        "vietnamese": "Tất nhiên. Bạn muốn loại phòng nào — phòng đơn hay phòng đôi?",
        "arabic": "بالطبع. ما نوع الغرفة التي تفضل — مفردة أم مزدوجة؟",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "A double room please. My wife is coming with me.",
        "lithuanian": "Dvivietį kambarį prašau. Mano žmona keliauja su manimi.",
        "latvian": "Divvietīgu istabu lūdzu. Mana sieva nāk kopā ar mani.",
        "estonian": "Kaheinimsete tuba palun. Minu naine tuleb minuga kaasa.",
        "german": "Ein Doppelzimmer bitte. Meine Frau kommt mit mir.",
        "french": "Une chambre double s'il vous plaît. Ma femme vient avec moi.",
        "spanish": "Una habitación doble por favor. Mi esposa viene conmigo.",
        "italian": "Una camera doppia per favore. Mia moglie viene con me.",
        "portuguese": "Um quarto duplo por favor. A minha esposa vem comigo.",
        "dutch": "Een tweepersoonskamer alstublieft. Mijn vrouw komt met mij mee.",
        "polish": "Pokój dwuosobowy proszę. Moja żona jedzie ze mną.",
        "ukrainian": "Двомісний номер будь ласка. Моя дружина їде зі мною.",
        "russian": "Двухместный номер пожалуйста. Моя жена едет со мной.",
        "swedish": "Ett dubbelrum tack. Min fru kommer med mig.",
        "norwegian": "Et dobbeltrom takk. Min kone kommer med meg.",
        "danish": "Et dobbeltværelse tak. Min kone kommer med mig.",
        "finnish": "Kahden hengen huone kiitos. Vaimoni tulee minun kanssani.",
        "greek": "Ένα διπλό δωμάτιο παρακαλώ. Η γυναίκα μου έρχεται μαζί μου.",
        "brazilian_portuguese": "Um quarto duplo por favor. Minha esposa vem comigo.",
        "mandarin": "请给我双人间。我妻子和我一起来。",
        "japanese": "ダブルルームをお願いします。妻も一緒に来ます。",
        "korean": "더블룸으로 주세요. 아내가 저와 함께 옵니다.",
        "hindi": "डबल रूम दीजिए। मेरी पत्नी मेरे साथ आ रही है।",
        "vietnamese": "Phòng đôi. Vợ tôi đi cùng.",
        "arabic": "غرفة مزدوجة من فضلك. زوجتي ستأتي معي.",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "When would you like to check in?",
        "lithuanian": "Kada norėtumėte atvykti?",
        "latvian": "Kad jūs vēlētos ieregistrēties?",
        "estonian": "Millal soovite sisse registreeruda?",
        "german": "Wann möchten Sie einchecken?",
        "french": "Quand souhaitez-vous vous enregistrer?",
        "spanish": "¿Cuándo le gustaría hacer el check-in?",
        "italian": "Quando vorrebbe fare il check-in?",
        "portuguese": "Quando gostaria de fazer o check-in?",
        "dutch": "Wanneer wilt u inchecken?",
        "polish": "Kiedy chciałby pan się zameldować?",
        "ukrainian": "Коли ви хотіли б заселитися?",
        "russian": "Когда вы хотели бы заселиться?",
        "swedish": "När vill du checka in?",
        "norwegian": "Når vil du sjekke inn?",
        "danish": "Hvornår vil du tjekke ind?",
        "finnish": "Milloin haluaisitte kirjautua sisään?",
        "greek": "Πότε θα θέλατε να κάνετε check-in;",
        "brazilian_portuguese": "Quando você gostaria de fazer o check-in?",
        "mandarin": "您想什么时候入住？",
        "japanese": "チェックインはいつのご予定ですか？",
        "korean": "언제 체크인을 하실 건가요?",
        "hindi": "आप कब चेक-इन करना चाहेंगे?",
        "vietnamese": "Bạn muốn nhận phòng khi nào?",
        "arabic": "متى تود تسجيل الوصول؟",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "This Friday the fifteenth. We will arrive around six in the evening.",
        "lithuanian": "Šį penktadienį penkioliktą. Atvyksime apie šeštą vakaro.",
        "latvian": "Šo piektdienu piecpadsmitajā. Mēs ieradīsimies ap sešiem vakarā.",
        "estonian": "Sel reedel viieteistkümnendal. Jõuame kohale umbes kell kuus õhtul.",
        "german": "Diesen Freitag den Fünfzehnten. Wir kommen gegen sechs Uhr abends an.",
        "french": "Ce vendredi le quinze. Nous arriverons vers six heures du soir.",
        "spanish": "Este viernes el quince. Llegaremos alrededor de las seis de la tarde.",
        "italian": "Questo venerdì il quindici. Arriveremo verso le sei di sera.",
        "portuguese": "Esta sexta-feira dia quinze. Chegaremos por volta das seis da tarde.",
        "dutch": "Deze vrijdag de vijftiende. We komen rond zes uur 's avonds aan.",
        "polish": "W ten piątek piętnastego. Przyjedziemy około szóstej wieczorem.",
        "ukrainian": "Цієї п'ятниці п'ятнадцятого. Ми приїдемо близько шостої вечора.",
        "russian": "В эту пятницу пятнадцатого. Мы приедем около шести вечера.",
        "swedish": "Denna fredag den femtonde. Vi anländer runt klockan sex på kvällen.",
        "norwegian": "Denne fredag den femtende. Vi ankommer rundt klokken seks om kvelden.",
        "danish": "Denne fredag den femtende. Vi ankommer omkring klokken seks om aftenen.",
        "finnish": "Tänä perjantaina viidestoista. Saavumme noin kello kuusi illalla.",
        "greek": "Αυτή την Παρασκευή τις δεκαπέντε. Θα φτάσουμε γύρω στις έξι το απόγευμα.",
        "brazilian_portuguese": "Esta sexta-feira dia quinze. Chegaremos por volta das seis da tarde.",
        "mandarin": "这个星期五，十五号。我们大约晚上六点到。",
        "japanese": "今週の金曜日十五日です。夕方六時頃に到着します。",
        "korean": "이번 금요일 십오일이에요. 저녁 여섯 시쯤 도착할 것 같아요.",
        "hindi": "इस शुक्रवार पंद्रह तारीख को। हम शाम छह बजे के आसपास पहुँचेंगे।",
        "vietnamese": "Thứ sáu này, ngày mười lăm. Chúng tôi sẽ đến khoảng sáu giờ tối.",
        "arabic": "هذا الجمعة الخامس عشر. سنصل حوالي الساعة السادسة مساءً.",
    },
    {
        "line_number": 6, "speaker_name": "Mia",
        "english": "Perfect. Breakfast is included. It starts at seven.",
        "lithuanian": "Puiku. Pusryčiai įskaičiuoti. Jie prasideda septintą.",
        "latvian": "Lieliski. Brokastis ir iekļautas. Tās sākas pulksten septiņos.",
        "estonian": "Suurepärane. Hommikusöök on kaasas. See algab kell seitse.",
        "german": "Perfekt. Das Frühstück ist inklusive. Es beginnt um sieben Uhr.",
        "french": "Parfait. Le petit déjeuner est inclus. Il commence à sept heures.",
        "spanish": "Perfecto. El desayuno está incluido. Empieza a las siete.",
        "italian": "Perfetto. La colazione è inclusa. Inizia alle sette.",
        "portuguese": "Perfeito. O pequeno-almoço está incluído. Começa às sete.",
        "dutch": "Perfect. Het ontbijt is inbegrepen. Het begint om zeven uur.",
        "polish": "Świetnie. Śniadanie jest wliczone. Zaczyna się o siódmej.",
        "ukrainian": "Чудово. Сніданок включено. Він починається о сьомій.",
        "russian": "Отлично. Завтрак включён. Он начинается в семь.",
        "swedish": "Perfekt. Frukost ingår. Den börjar klockan sju.",
        "norwegian": "Perfekt. Frokost er inkludert. Den starter klokken syv.",
        "danish": "Perfekt. Morgenmad er inkluderet. Den starter klokken syv.",
        "finnish": "Täydellinen. Aamiainen kuuluu hintaan. Se alkaa kello seitsemän.",
        "greek": "Τέλεια. Το πρωινό περιλαμβάνεται. Ξεκινά στις επτά.",
        "brazilian_portuguese": "Perfeito. O café da manhã está incluído. Começa às sete.",
        "mandarin": "太好了。含早餐。从七点开始。",
        "japanese": "完璧です。朝食が含まれています。七時から始まります。",
        "korean": "좋아요. 조식이 포함되어 있습니다. 일곱 시부터 시작해요.",
        "hindi": "बढ़िया। नाश्ता शामिल है। यह सात बजे शुरू होता है।",
        "vietnamese": "Tuyệt vời. Bữa sáng đã bao gồm. Bắt đầu lúc bảy giờ.",
        "arabic": "ممتاز. الإفطار مشمول. يبدأ الساعة السابعة.",
    },
    {
        "line_number": 7, "speaker_name": "Alex",
        "english": "Does the room have a view of the sea?",
        "lithuanian": "Ar kambarys turi vaizdą į jūrą?",
        "latvian": "Vai istabai ir skats uz jūru?",
        "estonian": "Kas toa aknast on vaade merele?",
        "german": "Hat das Zimmer Meerblick?",
        "french": "La chambre a-t-elle une vue sur la mer?",
        "spanish": "¿La habitación tiene vista al mar?",
        "italian": "La camera ha vista sul mare?",
        "portuguese": "O quarto tem vista para o mar?",
        "dutch": "Heeft de kamer uitzicht op zee?",
        "polish": "Czy pokój ma widok na morze?",
        "ukrainian": "Чи є у номері вид на море?",
        "russian": "Есть ли в номере вид на море?",
        "swedish": "Har rummet havsutsikt?",
        "norwegian": "Har rommet utsikt over havet?",
        "danish": "Har værelset havudsigt?",
        "finnish": "Onko huoneesta merinäköala?",
        "greek": "Έχει το δωμάτιο θέα στη θάλασσα;",
        "brazilian_portuguese": "O quarto tem vista para o mar?",
        "mandarin": "这个房间有海景吗？",
        "japanese": "お部屋から海が見えますか？",
        "korean": "방에서 바다가 보이나요?",
        "hindi": "क्या कमरे से समुद्र दिखता है?",
        "vietnamese": "Phòng có nhìn ra biển không?",
        "arabic": "هل الغرفة لها إطلالة على البحر؟",
    },
    {
        "line_number": 8, "speaker_name": "Mia",
        "english": "Yes, all rooms on the third floor have a sea view. It is beautiful.",
        "lithuanian": "Taip, visi trečio aukšto kambariai turi vaizdą į jūrą. Tai gražu.",
        "latvian": "Jā, visām trešā stāva istabām ir skats uz jūru. Tas ir skaisti.",
        "estonian": "Jah, kõikidel kolmanda korruse tubadel on vaade merele. See on ilus.",
        "german": "Ja, alle Zimmer im dritten Stock haben Meerblick. Es ist wunderschön.",
        "french": "Oui, toutes les chambres au troisième étage ont vue sur la mer. C'est magnifique.",
        "spanish": "Sí, todas las habitaciones del tercer piso tienen vista al mar. Es hermoso.",
        "italian": "Sì, tutte le camere al terzo piano hanno vista sul mare. È bellissimo.",
        "portuguese": "Sim, todos os quartos do terceiro andar têm vista para o mar. É lindo.",
        "dutch": "Ja, alle kamers op de derde verdieping hebben zeezicht. Het is prachtig.",
        "polish": "Tak, wszystkie pokoje na trzecim piętrze mają widok na morze. To piękne.",
        "ukrainian": "Так, усі номери на третьому поверсі мають вид на море. Це красиво.",
        "russian": "Да, все номера на третьем этаже имеют вид на море. Это красиво.",
        "swedish": "Ja, alla rum på tredje våningen har havsutsikt. Det är vackert.",
        "norwegian": "Ja, alle rom i tredje etasje har havutsikt. Det er vakkert.",
        "danish": "Ja, alle værelser på tredje sal har havudsigt. Det er smukt.",
        "finnish": "Kyllä, kaikista kolmannen kerroksen huoneista on merinäköala. Se on kaunis.",
        "greek": "Ναι, όλα τα δωμάτια στον τρίτο όροφο έχουν θέα στη θάλασσα. Είναι υπέροχη.",
        "brazilian_portuguese": "Sim, todos os quartos no terceiro andar têm vista para o mar. É lindo.",
        "mandarin": "是的，三楼所有房间都有海景。非常美丽。",
        "japanese": "はい、三階のすべてのお部屋から海が見えます。とても美しいですよ。",
        "korean": "네, 3층 모든 방에서 바다가 보입니다. 정말 아름다워요.",
        "hindi": "हाँ, तीसरे मंजिल के सभी कमरों से समुद्र दिखता है। यह बहुत सुंदर है।",
        "vietnamese": "Vâng, tất cả các phòng ở tầng ba đều có view biển. Rất đẹp.",
        "arabic": "نعم، جميع الغرف في الطابق الثالث لها إطلالة على البحر. إنها جميلة.",
    },
    {
        "line_number": 9, "speaker_name": "Alex",
        "english": "How much does it cost per night?",
        "lithuanian": "Kiek kainuoja viena naktis?",
        "latvian": "Cik maksā viena nakts?",
        "estonian": "Kui palju see ühe öö kohta maksab?",
        "german": "Was kostet es pro Nacht?",
        "french": "Combien ça coûte par nuit?",
        "spanish": "¿Cuánto cuesta por noche?",
        "italian": "Quanto costa a notte?",
        "portuguese": "Quanto custa por noite?",
        "dutch": "Hoeveel kost het per nacht?",
        "polish": "Ile kosztuje za noc?",
        "ukrainian": "Скільки коштує одна ніч?",
        "russian": "Сколько стоит одна ночь?",
        "swedish": "Hur mycket kostar det per natt?",
        "norwegian": "Hvor mye koster det per natt?",
        "danish": "Hvor meget koster det per nat?",
        "finnish": "Kuinka paljon se maksaa yöltä?",
        "greek": "Πόσο κοστίζει ανά διανυκτέρευση;",
        "brazilian_portuguese": "Quanto custa por noite?",
        "mandarin": "每晚多少钱？",
        "japanese": "一泊いくらですか？",
        "korean": "하룻밤에 얼마예요?",
        "hindi": "प्रति रात कितना खर्च होगा?",
        "vietnamese": "Một đêm bao nhiêu tiền?",
        "arabic": "كم يكلف في الليلة؟",
    },
    {
        "line_number": 10, "speaker_name": "Mia",
        "english": "Ninety euros per night with breakfast. That is one hundred and eighty euros in total.",
        "lithuanian": "Devyniasdešimt eurų už naktį su pusryčiais. Tai iš viso šimtas aštuoniasdešimt eurų.",
        "latvian": "Deviņdesmit eiro par nakti ar brokastīm. Kopā tas ir simts astoņdesmit eiro.",
        "estonian": "Üheksakümmend eurot öö kohta koos hommikusöögiga. Kokku on see sada kaheksakümmend eurot.",
        "german": "Neunzig Euro pro Nacht mit Frühstück. Das sind insgesamt einhundertachtzig Euro.",
        "french": "Quatre-vingt-dix euros par nuit avec le petit déjeuner. Ça fait cent quatre-vingts euros en tout.",
        "spanish": "Noventa euros por noche con desayuno. Son ciento ochenta euros en total.",
        "italian": "Novanta euro a notte con colazione. In totale sono centottanta euro.",
        "portuguese": "Noventa euros por noite com pequeno-almoço. São cento e oitenta euros no total.",
        "dutch": "Negentig euro per nacht met ontbijt. Dat is in totaal honderdtachtig euro.",
        "polish": "Dziewięćdziesiąt euro za noc ze śniadaniem. To razem sto osiemdziesiąt euro.",
        "ukrainian": "Дев'яносто євро за ніч зі сніданком. Разом сто вісімдесят євро.",
        "russian": "Девяносто евро за ночь с завтраком. Итого сто восемьдесят евро.",
        "swedish": "Nittio euro per natt med frukost. Det är totalt etthundraåttio euro.",
        "norwegian": "Nitti euro per natt med frokost. Det er totalt hundreogåtti euro.",
        "danish": "Halvfems euro per nat med morgenmad. Det er i alt hundredeogtreds euro.",
        "finnish": "Yhdeksänkymmentä euroa yöltä aamiaisella. Se on yhteensä satakahdeksankymmentä euroa.",
        "greek": "Ενενήντα ευρώ τη νύχτα με πρωινό. Είναι συνολικά εκατόν ογδόντα ευρώ.",
        "brazilian_portuguese": "Noventa euros por noite com café da manhã. São cento e oitenta euros no total.",
        "mandarin": "含早餐每晚九十欧元。总共一百八十欧元。",
        "japanese": "朝食付きで一泊九十ユーロです。合計で百八十ユーロになります。",
        "korean": "조식 포함 하룻밤에 구십 유로입니다. 총 백팔십 유로예요.",
        "hindi": "नाश्ते के साथ प्रति रात नब्बे यूरो। कुल एक सौ अस्सी यूरो।",
        "vietnamese": "Chín mươi euro mỗi đêm bao gồm bữa sáng. Tổng cộng một trăm tám mươi euro.",
        "arabic": "تسعون يورو في الليلة مع الإفطار. المجموع مئة وثمانون يورو.",
    },
    {
        "line_number": 11, "speaker_name": "Alex",
        "english": "That sounds good. Is there a swimming pool?",
        "lithuanian": "Tai skamba gerai. Ar yra baseinas?",
        "latvian": "Tas izklausās labi. Vai ir peldbaseins?",
        "estonian": "See kõlab hästi. Kas on bassein?",
        "german": "Das klingt gut. Gibt es einen Pool?",
        "french": "Ça semble bien. Y a-t-il une piscine?",
        "spanish": "Eso suena bien. ¿Hay piscina?",
        "italian": "Sembra bene. C'è una piscina?",
        "portuguese": "Isso parece bom. Há piscina?",
        "dutch": "Dat klinkt goed. Is er een zwembad?",
        "polish": "To brzmi dobrze. Czy jest basen?",
        "ukrainian": "Це звучить добре. Є басейн?",
        "russian": "Звучит хорошо. Есть ли бассейн?",
        "swedish": "Det låter bra. Finns det en pool?",
        "norwegian": "Det høres bra ut. Er det et basseng?",
        "danish": "Det lyder godt. Er der en swimmingpool?",
        "finnish": "Kuulostaa hyvältä. Onko siellä uima-allas?",
        "greek": "Αυτό ακούγεται καλό. Υπάρχει πισίνα;",
        "brazilian_portuguese": "Isso parece ótimo. Tem piscina?",
        "mandarin": "听起来不错。有游泳池吗？",
        "japanese": "いいですね。プールはありますか？",
        "korean": "좋은데요. 수영장이 있나요?",
        "hindi": "यह अच्छा लगता है। क्या स्विमिंग पूल है?",
        "vietnamese": "Nghe có vẻ tốt. Có hồ bơi không?",
        "arabic": "يبدو جيداً. هل هناك مسبح؟",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "Yes we have an outdoor pool. It opens at eight and closes at nine.",
        "lithuanian": "Taip, turime lauko baseiną. Jis atidaromas aštuntą ir užsidaro devintą.",
        "latvian": "Jā, mums ir āra baseins. Tas atver astoņos un aizver deviņos.",
        "estonian": "Jah, meil on välibasein. See avab kell kaheksa ja sulgub kell üheksa.",
        "german": "Ja, wir haben einen Außenpool. Er öffnet um acht und schließt um neun.",
        "french": "Oui nous avons une piscine extérieure. Elle ouvre à huit heures et ferme à neuf heures.",
        "spanish": "Sí tenemos una piscina al aire libre. Abre a las ocho y cierra a las nueve.",
        "italian": "Sì abbiamo una piscina all'aperto. Apre alle otto e chiude alle nove.",
        "portuguese": "Sim temos uma piscina exterior. Abre às oito e fecha às nove.",
        "dutch": "Ja we hebben een buitenzwembad. Het opent om acht uur en sluit om negen uur.",
        "polish": "Tak mamy basen zewnętrzny. Otwiera się o ósmej i zamyka o dziewiątej.",
        "ukrainian": "Так, у нас є відкритий басейн. Він відкривається о восьмій і закривається о дев'ятій.",
        "russian": "Да, у нас есть открытый бассейн. Он открывается в восемь и закрывается в девять.",
        "swedish": "Ja vi har en utomhuspool. Den öppnar klockan åtta och stänger klockan nio.",
        "norwegian": "Ja vi har et utendørsbasseng. Det åpner klokken åtte og stenger klokken ni.",
        "danish": "Ja vi har en udendørs pool. Den åbner klokken otte og lukker klokken ni.",
        "finnish": "Kyllä meillä on ulkoallas. Se avaa kello kahdeksan ja sulkeutuu kello yhdeksän.",
        "greek": "Ναι έχουμε εξωτερική πισίνα. Ανοίγει στις οκτώ και κλείνει στις εννιά.",
        "brazilian_portuguese": "Sim temos uma piscina ao ar livre. Abre às oito e fecha às nove.",
        "mandarin": "是的，我们有室外游泳池。早上八点开放，晚上九点关闭。",
        "japanese": "はい、屋外プールがあります。八時に開いて九時に閉まります。",
        "korean": "네, 야외 수영장이 있어요. 여덟 시에 열고 아홉 시에 닫아요.",
        "hindi": "हाँ, हमारे पास एक आउटडोर पूल है। यह आठ बजे खुलता है और नौ बजे बंद होता है।",
        "vietnamese": "Vâng chúng tôi có hồ bơi ngoài trời. Mở lúc tám giờ và đóng lúc chín giờ.",
        "arabic": "نعم لدينا مسبح خارجي. يفتح الساعة الثامنة ويغلق الساعة التاسعة.",
    },
    {
        "line_number": 13, "speaker_name": "Alex",
        "english": "Is there parking for the car?",
        "lithuanian": "Ar yra automobilių stovėjimo aikštelė?",
        "latvian": "Vai ir stāvvieta automašīnai?",
        "estonian": "Kas on parkimiskoht autole?",
        "german": "Gibt es einen Parkplatz für das Auto?",
        "french": "Y a-t-il un parking pour la voiture?",
        "spanish": "¿Hay aparcamiento para el coche?",
        "italian": "C'è un parcheggio per l'auto?",
        "portuguese": "Há estacionamento para o carro?",
        "dutch": "Is er parkeerruimte voor de auto?",
        "polish": "Czy jest parking dla samochodu?",
        "ukrainian": "Є паркування для машини?",
        "russian": "Есть ли парковка для машины?",
        "swedish": "Finns det parkering för bilen?",
        "norwegian": "Er det parkering for bilen?",
        "danish": "Er der parkering til bilen?",
        "finnish": "Onko siellä autopaikoitus?",
        "greek": "Υπάρχει χώρος στάθμευσης για αυτοκίνητο;",
        "brazilian_portuguese": "Tem estacionamento para o carro?",
        "mandarin": "有停车场吗？",
        "japanese": "車の駐車場はありますか？",
        "korean": "주차 공간이 있나요?",
        "hindi": "कार के लिए पार्किंग है?",
        "vietnamese": "Có chỗ đậu xe không?",
        "arabic": "هل هناك موقف سيارات؟",
    },
    {
        "line_number": 14, "speaker_name": "Mia",
        "english": "Yes, free parking is behind the hotel. It is very easy to find.",
        "lithuanian": "Taip, nemokama stovėjimo aikštelė yra už viešbučio. Ją labai lengva rasti.",
        "latvian": "Jā, bezmaksas stāvvieta atrodas aiz viesnīcas. To ir ļoti viegli atrast.",
        "estonian": "Jah, tasuta parkimine on hotelli taga. Seda on väga lihtne leida.",
        "german": "Ja, kostenloses Parken ist hinter dem Hotel. Es ist sehr leicht zu finden.",
        "french": "Oui, le parking gratuit est derrière l'hôtel. C'est très facile à trouver.",
        "spanish": "Sí el estacionamiento gratuito está detrás del hotel. Es muy fácil de encontrar.",
        "italian": "Sì il parcheggio gratuito è dietro l'hotel. È molto facile da trovare.",
        "portuguese": "Sim o estacionamento gratuito fica atrás do hotel. É muito fácil de encontrar.",
        "dutch": "Ja, gratis parkeren is achter het hotel. Het is erg makkelijk te vinden.",
        "polish": "Tak bezpłatny parking jest za hotelem. Bardzo łatwo go znaleźć.",
        "ukrainian": "Так, безкоштовне паркування знаходиться за готелем. Його дуже легко знайти.",
        "russian": "Да, бесплатная парковка находится за отелем. Её очень легко найти.",
        "swedish": "Ja, gratis parkering finns bakom hotellet. Det är mycket lätt att hitta.",
        "norwegian": "Ja, gratis parkering er bak hotellet. Det er veldig lett å finne.",
        "danish": "Ja, gratis parkering er bag hotellet. Det er meget nemt at finde.",
        "finnish": "Kyllä, ilmainen pysäköinti on hotellin takana. Se on erittäin helppo löytää.",
        "greek": "Ναι, η δωρεάν στάθμευση είναι πίσω από το ξενοδοχείο. Είναι πολύ εύκολο να βρεθεί.",
        "brazilian_portuguese": "Sim, o estacionamento gratuito fica atrás do hotel. É muito fácil de encontrar.",
        "mandarin": "是的，酒店后面有免费停车场。很容易找到。",
        "japanese": "はい、無料駐車場はホテルの裏にあります。とても分かりやすいですよ。",
        "korean": "네, 무료 주차장이 호텔 뒤에 있어요. 아주 찾기 쉬워요.",
        "hindi": "हाँ, होटल के पीछे मुफ़्त पार्किंग है। इसे ढूँढना बहुत आसान है।",
        "vietnamese": "Vâng, bãi đậu xe miễn phí ở phía sau khách sạn. Rất dễ tìm.",
        "arabic": "نعم، موقف السيارات المجاني خلف الفندق. من السهل جداً إيجاده.",
    },
    {
        "line_number": 15, "speaker_name": "Alex",
        "english": "Can I book the room now?",
        "lithuanian": "Ar galiu dabar užsakyti kambarį?",
        "latvian": "Vai es varu tagad rezervēt istabu?",
        "estonian": "Kas ma saan toa nüüd broneerida?",
        "german": "Kann ich das Zimmer jetzt buchen?",
        "french": "Puis-je réserver la chambre maintenant?",
        "spanish": "¿Puedo reservar la habitación ahora?",
        "italian": "Posso prenotare la camera adesso?",
        "portuguese": "Posso reservar o quarto agora?",
        "dutch": "Kan ik de kamer nu boeken?",
        "polish": "Czy mogę teraz zarezerwować pokój?",
        "ukrainian": "Я можу забронювати номер зараз?",
        "russian": "Могу ли я забронировать номер сейчас?",
        "swedish": "Kan jag boka rummet nu?",
        "norwegian": "Kan jeg bestille rommet nå?",
        "danish": "Kan jeg booke værelset nu?",
        "finnish": "Voinko varata huoneen nyt?",
        "greek": "Μπορώ να κλείσω το δωμάτιο τώρα;",
        "brazilian_portuguese": "Posso reservar o quarto agora?",
        "mandarin": "我现在可以预订房间吗？",
        "japanese": "今すぐ部屋を予約できますか？",
        "korean": "지금 방을 예약할 수 있나요?",
        "hindi": "क्या मैं अभी कमरा बुक कर सकता हूँ?",
        "vietnamese": "Tôi có thể đặt phòng ngay bây giờ không?",
        "arabic": "هل يمكنني حجز الغرفة الآن؟",
    },
    {
        "line_number": 16, "speaker_name": "Mia",
        "english": "Yes. I just need your name and a credit card number.",
        "lithuanian": "Taip. Man tik reikia jūsų vardo ir kredito kortelės numerio.",
        "latvian": "Jā. Man tikai nepieciešams jūsu vārds un kredītkartes numurs.",
        "estonian": "Jah. Vajan ainult teie nime ja krediitkaardi numbrit.",
        "german": "Ja. Ich brauche nur Ihren Namen und eine Kreditkartennummer.",
        "french": "Oui. J'ai juste besoin de votre nom et d'un numéro de carte de crédit.",
        "spanish": "Sí. Solo necesito su nombre y un número de tarjeta de crédito.",
        "italian": "Sì. Ho solo bisogno del suo nome e di un numero di carta di credito.",
        "portuguese": "Sim. Só preciso do seu nome e de um número de cartão de crédito.",
        "dutch": "Ja. Ik heb alleen uw naam en een creditcardnummer nodig.",
        "polish": "Tak. Potrzebuję tylko pana imię i numer karty kredytowej.",
        "ukrainian": "Так. Мені потрібне лише ваше ім'я та номер кредитної картки.",
        "russian": "Да. Мне нужны только ваше имя и номер кредитной карты.",
        "swedish": "Ja. Jag behöver bara ditt namn och ett kreditkortsnummer.",
        "norwegian": "Ja. Jeg trenger bare ditt navn og et kredittkortnummer.",
        "danish": "Ja. Jeg skal blot bruge dit navn og et kreditkortnummer.",
        "finnish": "Kyllä. Tarvitsen vain nimenne ja luottokortin numeron.",
        "greek": "Ναι. Χρειάζομαι μόνο το όνομά σας και έναν αριθμό πιστωτικής κάρτας.",
        "brazilian_portuguese": "Sim. Só preciso do seu nome e de um número de cartão de crédito.",
        "mandarin": "好的。我只需要您的姓名和信用卡号码。",
        "japanese": "はい。お名前とクレジットカード番号だけいただければ大丈夫です。",
        "korean": "네. 성함과 신용카드 번호만 있으면 됩니다.",
        "hindi": "हाँ। मुझे बस आपका नाम और क्रेडिट कार्ड नंबर चाहिए।",
        "vietnamese": "Vâng. Tôi chỉ cần tên và số thẻ tín dụng của bạn.",
        "arabic": "نعم. أحتاج فقط إلى اسمك ورقم بطاقة الائتمان.",
    },
    {
        "line_number": 17, "speaker_name": "Alex",
        "english": "My name is Alex Johansson. Here is my card.",
        "lithuanian": "Mano vardas Aleksas Johansonas. Štai mano kortelė.",
        "latvian": "Mani sauc Alekss Johansons. Lūk mana karte.",
        "estonian": "Minu nimi on Alex Johansson. Siin on minu kaart.",
        "german": "Mein Name ist Alex Johansson. Hier ist meine Karte.",
        "french": "Je m'appelle Alex Johansson. Voici ma carte.",
        "spanish": "Me llamo Alex Johansson. Aquí está mi tarjeta.",
        "italian": "Mi chiamo Alex Johansson. Ecco la mia carta.",
        "portuguese": "Chamo-me Alex Johansson. Aqui está o meu cartão.",
        "dutch": "Mijn naam is Alex Johansson. Hier is mijn kaart.",
        "polish": "Mam na imię Alex Johansson. Oto moja karta.",
        "ukrainian": "Мене звуть Алекс Йоханссон. Ось моя картка.",
        "russian": "Меня зовут Алекс Йоханссон. Вот моя карта.",
        "swedish": "Mitt namn är Alex Johansson. Här är mitt kort.",
        "norwegian": "Jeg heter Alex Johansson. Her er kortet mitt.",
        "danish": "Mit navn er Alex Johansson. Her er mit kort.",
        "finnish": "Nimeni on Alex Johansson. Tässä on korttini.",
        "greek": "Το όνομά μου είναι Άλεξ Γιόχανσον. Ορίστε η κάρτα μου.",
        "brazilian_portuguese": "Meu nome é Alex Johansson. Aqui está meu cartão.",
        "mandarin": "我叫亚历克斯·约翰逊。这是我的卡。",
        "japanese": "アレックス・ヨハンソンです。こちらが私のカードです。",
        "korean": "제 이름은 알렉스 요한슨입니다. 여기 카드입니다.",
        "hindi": "मेरा नाम एलेक्स जोहानसन है। यह रहा मेरा कार्ड।",
        "vietnamese": "Tên tôi là Alex Johansson. Đây là thẻ của tôi.",
        "arabic": "اسمي أليكس يوهانسون. ها هي بطاقتي.",
    },
    {
        "line_number": 18, "speaker_name": "Mia",
        "english": "Thank you. Your booking is confirmed. Here is your confirmation number.",
        "lithuanian": "Ačiū. Jūsų rezervacija patvirtinta. Štai jūsų patvirtinimo numeris.",
        "latvian": "Paldies. Jūsu rezervācija ir apstiprināta. Lūk jūsu apstiprinājuma numurs.",
        "estonian": "Tänan. Teie broneering on kinnitatud. Siin on teie kinnitusnumber.",
        "german": "Danke. Ihre Buchung ist bestätigt. Hier ist Ihre Bestätigungsnummer.",
        "french": "Merci. Votre réservation est confirmée. Voici votre numéro de confirmation.",
        "spanish": "Gracias. Su reserva está confirmada. Aquí está su número de confirmación.",
        "italian": "Grazie. La sua prenotazione è confermata. Ecco il suo numero di conferma.",
        "portuguese": "Obrigada. A sua reserva está confirmada. Aqui está o seu número de confirmação.",
        "dutch": "Dank u. Uw boeking is bevestigd. Hier is uw bevestigingsnummer.",
        "polish": "Dziękuję. Pana rezerwacja jest potwierdzona. Oto numer potwierdzenia.",
        "ukrainian": "Дякую. Ваше бронювання підтверджено. Ось ваш номер підтвердження.",
        "russian": "Спасибо. Ваше бронирование подтверждено. Вот номер подтверждения.",
        "swedish": "Tack. Din bokning är bekräftad. Här är ditt bekräftelsenummer.",
        "norwegian": "Takk. Din bestilling er bekreftet. Her er bekreftelsesnummeret ditt.",
        "danish": "Tak. Din bestilling er bekræftet. Her er dit bekræftelsesnummer.",
        "finnish": "Kiitos. Varauksesi on vahvistettu. Tässä on vahvistusnumerosi.",
        "greek": "Ευχαριστώ. Η κράτησή σας έχει επιβεβαιωθεί. Ορίστε ο αριθμός επιβεβαίωσης.",
        "brazilian_portuguese": "Obrigada. Sua reserva está confirmada. Aqui está seu número de confirmação.",
        "mandarin": "谢谢。您的预订已确认。这是您的确认号码。",
        "japanese": "ありがとうございます。ご予約が確定しました。こちらが確認番号です。",
        "korean": "감사합니다. 예약이 확인되었습니다. 확인 번호입니다.",
        "hindi": "धन्यवाद। आपकी बुकिंग की पुष्टि हो गई है। यह रहा आपका पुष्टिकरण नंबर।",
        "vietnamese": "Cảm ơn. Đặt phòng của bạn đã được xác nhận. Đây là số xác nhận của bạn.",
        "arabic": "شكراً. تم تأكيد حجزك. هذا هو رقم التأكيد.",
    },
    {
        "line_number": 19, "speaker_name": "Alex",
        "english": "Is there anything special near the hotel to visit?",
        "lithuanian": "Ar yra kažkas ypatingo šalia viešbučio, ką galima aplankyti?",
        "latvian": "Vai tuvumā ir kāda īpaša vieta, ko apmeklēt?",
        "estonian": "Kas hotelli lähedal on midagi erilist, mida külastada?",
        "german": "Gibt es etwas Besonderes in der Nähe des Hotels zu besuchen?",
        "french": "Y a-t-il quelque chose de spécial à visiter près de l'hôtel?",
        "spanish": "¿Hay algo especial para visitar cerca del hotel?",
        "italian": "C'è qualcosa di speciale da visitare vicino all'hotel?",
        "portuguese": "Há algo especial para visitar perto do hotel?",
        "dutch": "Is er iets bijzonders in de buurt van het hotel om te bezoeken?",
        "polish": "Czy jest coś wyjątkowego do odwiedzenia w pobliżu hotelu?",
        "ukrainian": "Чи є щось особливе поблизу готелю для відвідування?",
        "russian": "Есть ли что-то особенное рядом с отелем для посещения?",
        "swedish": "Finns det något speciellt att besöka nära hotellet?",
        "norwegian": "Er det noe spesielt å besøke i nærheten av hotellet?",
        "danish": "Er der noget særligt at besøge i nærheden af hotellet?",
        "finnish": "Onko hotellin lähellä jotain erityistä vierailtavaa?",
        "greek": "Υπάρχει κάτι ιδιαίτερο να επισκεφθεί κοντά στο ξενοδοχείο;",
        "brazilian_portuguese": "Tem algo especial para visitar perto do hotel?",
        "mandarin": "酒店附近有什么特别的地方可以参观吗？",
        "japanese": "ホテルの近くに何か特別な観光スポットはありますか？",
        "korean": "호텔 근처에 특별히 방문할 만한 곳이 있나요?",
        "hindi": "क्या होटल के पास कोई खास जगह है जो देखने लायक हो?",
        "vietnamese": "Gần khách sạn có gì đặc biệt để tham quan không?",
        "arabic": "هل هناك شيء مميز للزيارة بالقرب من الفندق؟",
    },
    {
        "line_number": 20, "speaker_name": "Mia",
        "english": "Yes, there is an old castle ten minutes from here and a very good fish restaurant on the beach. I hope you enjoy your stay!",
        "lithuanian": "Taip, dešimties minučių atstumu nuo čia yra sena pilis ir labai geras žuvies restoranas paplūdimyje. Tikiuosi jums patiks viešnagė!",
        "latvian": "Jā, desmit minūšu attālumā ir veca pils un ļoti labs zivju restorāns pludmalē. Ceru ka jums patiks uzturēšanās!",
        "estonian": "Jah, kümme minutit siit on vana loss ja väga hea kalarestoran rannas. Loodan, et teile meeldib teie viibimine!",
        "german": "Ja, es gibt eine alte Burg zehn Minuten von hier und ein sehr gutes Fischrestaurant am Strand. Ich hoffe Sie genießen Ihren Aufenthalt!",
        "french": "Oui, il y a un vieux château à dix minutes d'ici et un très bon restaurant de poisson sur la plage. J'espère que vous apprécierez votre séjour!",
        "spanish": "Sí hay un castillo antiguo a diez minutos de aquí y un muy buen restaurante de pescado en la playa. ¡Espero que disfrute su estancia!",
        "italian": "Sì c'è un vecchio castello a dieci minuti da qui e un ottimo ristorante di pesce sulla spiaggia. Spero che si goda il suo soggiorno!",
        "portuguese": "Sim há um castelo antigo a dez minutos daqui e um restaurante de peixe muito bom na praia. Espero que aprecie a sua estadia!",
        "dutch": "Ja er is een oud kasteel op tien minuten van hier en een heel goed visrestaurant op het strand. Ik hoop dat u geniet van uw verblijf!",
        "polish": "Tak jest stary zamek dziesięć minut stąd i bardzo dobra restauracja rybna na plaży. Mam nadzieję że spodoba się panu pobyt!",
        "ukrainian": "Так, за десять хвилин звідси є старий замок і дуже гарний рибний ресторан на пляжі. Сподіваюся вам сподобається перебування!",
        "russian": "Да, в десяти минутах отсюда есть старый замок и очень хороший рыбный ресторан на пляже. Надеюсь вам понравится пребывание!",
        "swedish": "Ja det finns ett gammalt slott tio minuter härifrån och en väldigt bra fiskrestaurang på stranden. Jag hoppas du trivs under din vistelse!",
        "norwegian": "Ja det er en gammel borg ti minutter herfra og en veldig god fiskerestaurant på stranden. Jeg håper du trives under oppholdet ditt!",
        "danish": "Ja der er et gammelt slot ti minutter herfra og en meget god fiskerestaurant på stranden. Jeg håber du nyder dit ophold!",
        "finnish": "Kyllä, kymmenen minuutin päässä täältä on vanha linna ja erittäin hyvä kalaravintola rannalla. Toivottavasti viihdytte!",
        "greek": "Ναι, υπάρχει ένα παλιό κάστρο δέκα λεπτά από εδώ και ένα πολύ καλό ψαροταβέρνα στην παραλία. Ελπίζω να απολαύσετε τη διαμονή σας!",
        "brazilian_portuguese": "Sim, há um castelo antigo a dez minutos daqui e um ótimo restaurante de peixe na praia. Espero que aproveite a estadia!",
        "mandarin": "是的，这里十分钟处有一座古堡，海滩上还有一家非常好的海鲜餐厅。希望您入住愉快！",
        "japanese": "はい、ここから十分のところに古いお城があり、ビーチにとても良い魚料理のレストランがあります。どうぞ楽しいご滞在を！",
        "korean": "네, 여기서 십 분 거리에 오래된 성이 있고 해변에 매우 맛있는 해산물 레스토랑이 있어요. 즐거운 숙박이 되길 바랍니다!",
        "hindi": "हाँ, यहाँ से दस मिनट की दूरी पर एक पुराना महल है और समुद्र तट पर एक बहुत अच्छा मछली रेस्टोरेंट है। आशा है आपको यहाँ रहना पसंद आएगा!",
        "vietnamese": "Vâng, cách đây mười phút có một lâu đài cổ và một nhà hàng hải sản rất ngon trên bãi biển. Hy vọng bạn tận hưởng kỳ nghỉ!",
        "arabic": "نعم هناك قلعة قديمة على بعد عشر دقائق من هنا ومطعم أسماك رائع على الشاطئ. أتمنى لك إقامة ممتعة!",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="Booking a Hotel Room").first()
        if existing:
            print("A2 dialogue 'Booking a Hotel Room' already exists — skipping.")
            return

        dialogue = Dialogue(topic="Booking a Hotel Room", lang_level="A2", length=20)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded A2 dialogue ID {dialogue.id} — 20 lines in 25 languages.")


if __name__ == '__main__':
    seed()
