import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Mia",
        "english": "Good evening. Do you have a reservation?",
        "lithuanian": "Labas vakaras. Ar turite rezervaciją?",
        "latvian": "Labvakar. Vai jums ir rezervācija?",
        "estonian": "Tere õhtust. Kas teil on reservatsioon?",
        "german": "Guten Abend. Haben Sie eine Reservierung?",
        "french": "Bonsoir. Avez-vous une réservation?",
        "spanish": "Buenas noches. ¿Tiene una reserva?",
        "italian": "Buona sera. Ha una prenotazione?",
        "portuguese": "Boa noite. Tem uma reserva?",
        "dutch": "Goedenavond. Heeft u een reservering?",
        "polish": "Dobry wieczór. Czy ma pan rezerwację?",
        "ukrainian": "Добрий вечір. У вас є бронювання?",
        "russian": "Добрый вечер. У вас есть бронирование?",
        "swedish": "God kväll. Har du en reservation?",
        "norwegian": "God kveld. Har du en reservasjon?",
        "danish": "God aften. Har du en reservation?",
        "finnish": "Hyvää iltaa. Onko teillä varaus?",
        "greek": "Καλησπέρα. Έχετε κράτηση;",
        "brazilian_portuguese": "Boa noite. Tem uma reserva?",
        "mandarin": "晚上好。您有预订吗？",
        "japanese": "いらっしゃいませ。ご予約はございますか？",
        "korean": "안녕하세요. 예약하셨나요?",
        "hindi": "शुभ संध्या। क्या आपके पास आरक्षण है?",
        "vietnamese": "Chào buổi tối. Bạn có đặt bàn không?",
        "arabic": "مساء الخير. هل لديكم حجز؟",
    },
    {
        "line_number": 2, "speaker_name": "Alex",
        "english": "No I do not. Is there a table for two?",
        "lithuanian": "Ne neturiu. Ar yra staliukas dviems?",
        "latvian": "Nē man nav. Vai ir galdiņš diviem?",
        "estonian": "Ei ole. Kas on laud kahele?",
        "german": "Nein ich habe keine. Gibt es einen Tisch für zwei?",
        "french": "Non je n'en ai pas. Y a-t-il une table pour deux?",
        "spanish": "No no tengo. ¿Hay una mesa para dos?",
        "italian": "No non ce l'ho. C'è un tavolo per due?",
        "portuguese": "Não não tenho. Há uma mesa para dois?",
        "dutch": "Nee die heb ik niet. Is er een tafel voor twee?",
        "polish": "Nie nie mam. Czy jest stolik dla dwóch osób?",
        "ukrainian": "Ні немає. Є столик на двох?",
        "russian": "Нет нет. Есть ли столик на двоих?",
        "swedish": "Nej det har jag inte. Finns det ett bord för två?",
        "norwegian": "Nei det har jeg ikke. Er det et bord for to?",
        "danish": "Nej det har jeg ikke. Er der et bord til to?",
        "finnish": "Ei minulla ole. Onko pöytä kahdelle?",
        "greek": "Όχι δεν έχω. Υπάρχει τραπέζι για δύο;",
        "brazilian_portuguese": "Não não tenho. Tem uma mesa para dois?",
        "mandarin": "没有。有两人桌吗？",
        "japanese": "いいえ、ありません。二人用の席はありますか？",
        "korean": "아니요. 두 명 자리 있나요?",
        "hindi": "नहीं। दो लोगों के लिए मेज़ है?",
        "vietnamese": "Không. Có bàn cho hai người không?",
        "arabic": "لا ليس لدي. هل هناك طاولة لشخصين؟",
    },
    {
        "line_number": 3, "speaker_name": "Mia",
        "english": "Yes please follow me. Here is the menu.",
        "lithuanian": "Taip sekite mane prašau. Štai meniu.",
        "latvian": "Jā lūdzu sekojiet man. Lūk ēdienkarte.",
        "estonian": "Jah palun järgige mind. Siin on menüü.",
        "german": "Ja bitte folgen Sie mir. Hier ist die Speisekarte.",
        "french": "Oui suivez-moi s'il vous plaît. Voici la carte.",
        "spanish": "Sí síganme por favor. Aquí tiene el menú.",
        "italian": "Sì mi segua per favore. Ecco il menù.",
        "portuguese": "Sim siga-me por favor. Aqui está o menu.",
        "dutch": "Ja volgt u mij alstublieft. Hier is het menu.",
        "polish": "Tak proszę za mną. Oto menu.",
        "ukrainian": "Так ідіть за мною будь ласка. Ось меню.",
        "russian": "Да следуйте за мной пожалуйста. Вот меню.",
        "swedish": "Ja följ mig tack. Här är menyn.",
        "norwegian": "Ja følg meg takk. Her er menyen.",
        "danish": "Ja følg mig tak. Her er menuen.",
        "finnish": "Kyllä seuratkaa minua. Tässä on menu.",
        "greek": "Ναι ακολουθήστε με παρακαλώ. Ορίστε ο κατάλογος.",
        "brazilian_portuguese": "Sim me siga por favor. Aqui está o cardápio.",
        "mandarin": "好的请跟我来。这是菜单。",
        "japanese": "はいこちらへどうぞ。メニューです。",
        "korean": "네 따라오세요. 메뉴입니다.",
        "hindi": "हाँ मेरे पीछे आइए। यह रहा मेनू।",
        "vietnamese": "Vâng mời theo tôi. Đây là thực đơn.",
        "arabic": "نعم تفضل معي. هذه القائمة.",
    },
    {
        "line_number": 4, "speaker_name": "Alex",
        "english": "Thank you. What do you recommend today?",
        "lithuanian": "Ačiū. Ką šiandien rekomenduojate?",
        "latvian": "Paldies. Ko jūs šodien iesakāt?",
        "estonian": "Tänan. Mida soovitad täna?",
        "german": "Danke. Was empfehlen Sie heute?",
        "french": "Merci. Que recommandez-vous aujourd'hui?",
        "spanish": "Gracias. ¿Qué recomienda hoy?",
        "italian": "Grazie. Cosa consiglia oggi?",
        "portuguese": "Obrigado. O que recomenda hoje?",
        "dutch": "Dank u. Wat raadt u vandaag aan?",
        "polish": "Dziękuję. Co pan poleca dzisiaj?",
        "ukrainian": "Дякую. Що ви рекомендуєте сьогодні?",
        "russian": "Спасибо. Что вы рекомендуете сегодня?",
        "swedish": "Tack. Vad rekommenderar du idag?",
        "norwegian": "Takk. Hva anbefaler du i dag?",
        "danish": "Tak. Hvad anbefaler du i dag?",
        "finnish": "Kiitos. Mitä suosittelet tänään?",
        "greek": "Ευχαριστώ. Τι συνιστάτε σήμερα;",
        "brazilian_portuguese": "Obrigado. O que você recomenda hoje?",
        "mandarin": "谢谢。您今天有什么推荐？",
        "japanese": "ありがとうございます。今日のお勧めは何ですか？",
        "korean": "감사합니다. 오늘 추천해주실 게 있나요?",
        "hindi": "धन्यवाद। आज आप क्या सुझाएंगे?",
        "vietnamese": "Cảm ơn. Hôm nay bạn đề xuất món gì?",
        "arabic": "شكراً. ماذا تنصح اليوم؟",
    },
    {
        "line_number": 5, "speaker_name": "Mia",
        "english": "The grilled salmon is very popular. The soup is also excellent today.",
        "lithuanian": "Keptas lašiša labai populiari. Sriuba šiandien taip pat puiki.",
        "latvian": "Grilēts lasis ir ļoti populārs. Zupa šodien arī ir lieliska.",
        "estonian": "Grillitud lõhe on väga populaarne. Ka supp on täna suurepärane.",
        "german": "Der gegrillte Lachs ist sehr beliebt. Die Suppe ist heute auch ausgezeichnet.",
        "french": "Le saumon grillé est très populaire. La soupe est aussi excellente aujourd'hui.",
        "spanish": "El salmón a la parrilla es muy popular. La sopa también está excelente hoy.",
        "italian": "Il salmone alla griglia è molto popolare. Anche la zuppa è eccellente oggi.",
        "portuguese": "O salmão grelhado é muito popular. A sopa também está excelente hoje.",
        "dutch": "De gegrilde zalm is erg populair. De soep is vandaag ook uitstekend.",
        "polish": "Grillowany łosoś jest bardzo popularny. Zupa jest dziś też doskonała.",
        "ukrainian": "Смажений лосось дуже популярний. Суп також чудовий сьогодні.",
        "russian": "Жареный лосось очень популярен. Суп также сегодня превосходный.",
        "swedish": "Den grillade laxen är mycket populär. Soppan är också utmärkt idag.",
        "norwegian": "Den grillede laksen er veldig populær. Suppen er også utmerket i dag.",
        "danish": "Den grillede laks er meget populær. Suppen er også fremragende i dag.",
        "finnish": "Grillattu lohi on erittäin suosittu. Keitto on myös tänään erinomainen.",
        "greek": "Ο ψητός σολομός είναι πολύ δημοφιλής. Η σούπα είναι επίσης εξαιρετική σήμερα.",
        "brazilian_portuguese": "O salmão grelhado é muito popular. A sopa também está excelente hoje.",
        "mandarin": "烤三文鱼非常受欢迎。今天的汤也很棒。",
        "japanese": "グリルサーモンがとても人気です。今日のスープも素晴らしいですよ。",
        "korean": "구운 연어가 인기가 많아요. 오늘 수프도 정말 맛있어요.",
        "hindi": "ग्रिल्ड सैल्मन बहुत लोकप्रिय है। आज का सूप भी बेहतरीन है।",
        "vietnamese": "Cá hồi nướng rất được ưa chuộng. Súp hôm nay cũng tuyệt vời.",
        "arabic": "السلمون المشوي شائع جداً. الحساء ممتاز أيضاً اليوم.",
    },
    {
        "line_number": 6, "speaker_name": "Alex",
        "english": "I will take the salmon please. And a green salad.",
        "lithuanian": "Paimsiu lašišą prašau. Ir žalią salotas.",
        "latvian": "Es ņemšu lasi lūdzu. Un zaļos salātus.",
        "estonian": "Võtan lõhe palun. Ja rohelise salati.",
        "german": "Ich nehme den Lachs bitte. Und einen grünen Salat.",
        "french": "Je prends le saumon s'il vous plaît. Et une salade verte.",
        "spanish": "Tomaré el salmón por favor. Y una ensalada verde.",
        "italian": "Prendo il salmone per favore. E un'insalata verde.",
        "portuguese": "Vou tomar o salmão por favor. E uma salada verde.",
        "dutch": "Ik neem de zalm alstublieft. En een groene salade.",
        "polish": "Wezmę łososia proszę. I zieloną sałatkę.",
        "ukrainian": "Візьму лосося будь ласка. І зелений салат.",
        "russian": "Я возьму лосося пожалуйста. И зелёный салат.",
        "swedish": "Jag tar laxen tack. Och en grön sallad.",
        "norwegian": "Jeg tar laksen takk. Og en grønn salat.",
        "danish": "Jeg tager laksen tak. Og en grøn salat.",
        "finnish": "Otan lohen kiitos. Ja vihreän salaatin.",
        "greek": "Θα πάρω τον σολομό παρακαλώ. Και μια πράσινη σαλάτα.",
        "brazilian_portuguese": "Vou pegar o salmão por favor. E uma salada verde.",
        "mandarin": "我要三文鱼。还要一份绿沙拉。",
        "japanese": "サーモンをください。あとグリーンサラダも。",
        "korean": "연어로 주세요. 그리고 그린 샐러드도요.",
        "hindi": "मुझे सैल्मन चाहिए। और एक हरा सलाद।",
        "vietnamese": "Cho tôi cá hồi. Và một đĩa salad rau xanh.",
        "arabic": "سآخذ السلمون من فضلك. وسلطة خضراء.",
    },
    {
        "line_number": 7, "speaker_name": "Mia",
        "english": "And what would you like to drink?",
        "lithuanian": "O ką norėtumėte gerti?",
        "latvian": "Un ko jūs vēlētos dzert?",
        "estonian": "Ja mida sooviksite juua?",
        "german": "Und was möchten Sie trinken?",
        "french": "Et que voudriez-vous boire?",
        "spanish": "¿Y qué le gustaría beber?",
        "italian": "E cosa vorrebbe da bere?",
        "portuguese": "E o que gostaria de beber?",
        "dutch": "En wat wilt u drinken?",
        "polish": "A co chciałby pan do picia?",
        "ukrainian": "А що ви хотіли б випити?",
        "russian": "А что вы хотели бы выпить?",
        "swedish": "Och vad vill du dricka?",
        "norwegian": "Og hva vil du drikke?",
        "danish": "Og hvad vil du drikke?",
        "finnish": "Ja mitä haluaisitte juoda?",
        "greek": "Και τι θα θέλατε να πιείτε;",
        "brazilian_portuguese": "E o que gostaria de beber?",
        "mandarin": "您想喝什么？",
        "japanese": "お飲み物はいかがですか？",
        "korean": "음료는 무엇으로 드시겠어요?",
        "hindi": "आप क्या पीना चाहेंगे?",
        "vietnamese": "Và bạn muốn uống gì?",
        "arabic": "وماذا تريد أن تشرب؟",
    },
    {
        "line_number": 8, "speaker_name": "Alex",
        "english": "A glass of white wine and some sparkling water please.",
        "lithuanian": "Taurę balto vyno ir truputį mineralinio vandens prašau.",
        "latvian": "Glāzi baltvīna un nedaudz gāzēta ūdens lūdzu.",
        "estonian": "Klaas valget veini ja veidi gaseeritud vett palun.",
        "german": "Ein Glas Weißwein und etwas Sprudelwasser bitte.",
        "french": "Un verre de vin blanc et de l'eau gazeuse s'il vous plaît.",
        "spanish": "Una copa de vino blanco y algo de agua con gas por favor.",
        "italian": "Un bicchiere di vino bianco e un po' di acqua frizzante per favore.",
        "portuguese": "Um copo de vinho branco e um pouco de água com gás por favor.",
        "dutch": "Een glas witte wijn en wat bruisend water alstublieft.",
        "polish": "Kieliszek białego wina i trochę wody gazowanej proszę.",
        "ukrainian": "Бокал білого вина і трохи газованої води будь ласка.",
        "russian": "Бокал белого вина и немного газированной воды пожалуйста.",
        "swedish": "Ett glas vitt vin och lite kolsyrat vatten tack.",
        "norwegian": "Et glass hvitvin og litt kullsyreholdig vann takk.",
        "danish": "Et glas hvidvin og lidt mineralvand tak.",
        "finnish": "Lasi valkoviiniä ja hiukan kivennäisvettä kiitos.",
        "greek": "Ένα ποτήρι λευκό κρασί και λίγο ανθρακούχο νερό παρακαλώ.",
        "brazilian_portuguese": "Uma taça de vinho branco e um pouco de água com gás por favor.",
        "mandarin": "一杯白葡萄酒和一些气泡水。",
        "japanese": "白ワインを一杯とスパークリングウォーターをください。",
        "korean": "화이트 와인 한 잔과 탄산수 주세요.",
        "hindi": "एक गिलास सफेद वाइन और थोड़ा स्पार्कलिंग पानी।",
        "vietnamese": "Một ly rượu vang trắng và một ít nước có ga.",
        "arabic": "كأس نبيذ أبيض وبعض المياه الفوارة من فضلك.",
    },
    {
        "line_number": 9, "speaker_name": "Mia",
        "english": "Of course. Are you allergic to anything?",
        "lithuanian": "Žinoma. Ar esate alergiški kam nors?",
        "latvian": "Protams. Vai jums ir kāda alerģija?",
        "estonian": "Muidugi. Kas teil on mõni allergia?",
        "german": "Natürlich. Haben Sie irgendwelche Allergien?",
        "french": "Bien sûr. Êtes-vous allergique à quelque chose?",
        "spanish": "Por supuesto. ¿Es alérgico a algo?",
        "italian": "Certo. È allergico a qualcosa?",
        "portuguese": "Claro. Tem alergia a alguma coisa?",
        "dutch": "Natuurlijk. Bent u ergens allergisch voor?",
        "polish": "Oczywiście. Czy jest pan na coś uczulony?",
        "ukrainian": "Звичайно. Чи є у вас алергія на щось?",
        "russian": "Конечно. Есть ли у вас аллергия на что-нибудь?",
        "swedish": "Naturligtvis. Är du allergisk mot något?",
        "norwegian": "Selvfølgelig. Er du allergisk mot noe?",
        "danish": "Selvfølgelig. Er du allergisk over for noget?",
        "finnish": "Tietysti. Onko teillä allergiaa jollekin?",
        "greek": "Βεβαίως. Έχετε αλλεργία σε κάτι;",
        "brazilian_portuguese": "Claro. Você é alérgico a alguma coisa?",
        "mandarin": "当然。您对什么东西过敏吗？",
        "japanese": "もちろんです。何かアレルギーはありますか？",
        "korean": "물론이죠. 알레르기가 있으신가요?",
        "hindi": "बिल्कुल। क्या आपको किसी चीज़ से एलर्जी है?",
        "vietnamese": "Tất nhiên. Bạn có dị ứng với gì không?",
        "arabic": "بالطبع. هل أنت مصاب بأي حساسية؟",
    },
    {
        "line_number": 10, "speaker_name": "Alex",
        "english": "I am allergic to nuts. Please no nuts in my food.",
        "lithuanian": "Esu alergikas riešutams. Prašau be riešutų mano maiste.",
        "latvian": "Man ir alerģija pret riekstiem. Lūdzu bez riekstiem manā ēdienā.",
        "estonian": "Ma olen pähklite suhtes allergiline. Palun ei pähkleid minu toidus.",
        "german": "Ich bin allergisch gegen Nüsse. Bitte keine Nüsse in meinem Essen.",
        "french": "Je suis allergique aux noix. Pas de noix dans mon repas s'il vous plaît.",
        "spanish": "Soy alérgico a los frutos secos. Por favor sin frutos secos en mi comida.",
        "italian": "Sono allergico alle noci. Per favore niente noci nel mio cibo.",
        "portuguese": "Sou alérgico a frutos secos. Por favor sem frutos secos na minha comida.",
        "dutch": "Ik ben allergisch voor noten. Geen noten in mijn eten alstublieft.",
        "polish": "Jestem uczulony na orzechy. Proszę bez orzechów w moim jedzeniu.",
        "ukrainian": "Я маю алергію на горіхи. Будь ласка без горіхів у моїй їжі.",
        "russian": "Я аллергик на орехи. Пожалуйста без орехов в моей еде.",
        "swedish": "Jag är allergisk mot nötter. Inga nötter i min mat tack.",
        "norwegian": "Jeg er allergisk mot nøtter. Ingen nøtter i maten min takk.",
        "danish": "Jeg er allergisk over for nødder. Ingen nødder i min mad tak.",
        "finnish": "Olen allerginen pähkinöille. Ei pähkinöitä ruoassani kiitos.",
        "greek": "Είμαι αλλεργικός στους ξηρούς καρπούς. Παρακαλώ χωρίς ξηρούς καρπούς στο φαγητό μου.",
        "brazilian_portuguese": "Sou alérgico a nozes. Por favor sem nozes na minha comida.",
        "mandarin": "我对坚果过敏。请不要在我的食物里放坚果。",
        "japanese": "ナッツアレルギーがあります。料理にナッツを入れないでください。",
        "korean": "저는 견과류 알레르기가 있어요. 음식에 견과류를 넣지 말아주세요.",
        "hindi": "मुझे नट्स से एलर्जी है। कृपया मेरे खाने में कोई नट्स न डालें।",
        "vietnamese": "Tôi bị dị ứng với hạt. Xin đừng cho hạt vào thức ăn của tôi.",
        "arabic": "أنا مصاب بحساسية من المكسرات. من فضلك لا مكسرات في طعامي.",
    },
    {
        "line_number": 11, "speaker_name": "Mia",
        "english": "No problem. I will tell the kitchen. Your food will be ready soon.",
        "lithuanian": "Jokių problemų. Pasakysiu virtuvei. Jūsų maistas bus paruoštas netrukus.",
        "latvian": "Nekādas problēmas. Es pastāstīšu virtuvei. Jūsu ēdiens būs gatavs drīz.",
        "estonian": "Pole probleemi. Ütlen köögile. Teie toit on varsti valmis.",
        "german": "Kein Problem. Ich sage der Küche Bescheid. Ihr Essen ist bald fertig.",
        "french": "Pas de problème. Je vais en informer la cuisine. Votre repas sera prêt bientôt.",
        "spanish": "No hay problema. Se lo digo a la cocina. Su comida estará lista pronto.",
        "italian": "Nessun problema. Lo dirò alla cucina. Il suo cibo sarà pronto presto.",
        "portuguese": "Sem problema. Vou avisar a cozinha. A sua comida ficará pronta em breve.",
        "dutch": "Geen probleem. Ik zeg het aan de keuken. Uw eten is snel klaar.",
        "polish": "Żaden problem. Powiem kuchni. Pana jedzenie będzie gotowe wkrótce.",
        "ukrainian": "Без проблем. Я скажу кухні. Ваша їжа буде готова скоро.",
        "russian": "Без проблем. Я скажу на кухню. Ваша еда скоро будет готова.",
        "swedish": "Inga problem. Jag talar om det för köket. Din mat är snart klar.",
        "norwegian": "Ikke noe problem. Jeg gir beskjed til kjøkkenet. Maten din er snart klar.",
        "danish": "Intet problem. Jeg fortæller køkkenet. Din mad er snart klar.",
        "finnish": "Ei ongelmaa. Kerron keittiölle. Ruokasi on pian valmis.",
        "greek": "Κανένα πρόβλημα. Θα το πω στην κουζίνα. Το φαγητό σας θα είναι έτοιμο σύντομα.",
        "brazilian_portuguese": "Sem problema. Vou avisar a cozinha. Sua comida ficará pronta em breve.",
        "mandarin": "没问题。我会告诉厨房的。您的食物很快就会好。",
        "japanese": "問題ありません。キッチンに伝えます。すぐにお食事をお持ちします。",
        "korean": "문제없어요. 주방에 말하겠습니다. 곧 음식이 나올 거예요.",
        "hindi": "कोई समस्या नहीं। मैं रसोई को बताऊँगी। आपका खाना जल्दी तैयार होगा।",
        "vietnamese": "Không sao. Tôi sẽ nói với bếp. Đồ ăn của bạn sẽ sẵn sàng sớm.",
        "arabic": "لا مشكلة. سأخبر المطبخ. طعامك سيكون جاهزاً قريباً.",
    },
    {
        "line_number": 12, "speaker_name": "Alex",
        "english": "Thank you. This restaurant is very beautiful.",
        "lithuanian": "Ačiū. Šis restoranas labai gražus.",
        "latvian": "Paldies. Šis restorāns ir ļoti skaists.",
        "estonian": "Tänan. See restoran on väga ilus.",
        "german": "Danke. Dieses Restaurant ist sehr schön.",
        "french": "Merci. Ce restaurant est très beau.",
        "spanish": "Gracias. Este restaurante es muy bonito.",
        "italian": "Grazie. Questo ristorante è molto bello.",
        "portuguese": "Obrigado. Este restaurante é muito bonito.",
        "dutch": "Dank u. Dit restaurant is erg mooi.",
        "polish": "Dziękuję. Ta restauracja jest bardzo piękna.",
        "ukrainian": "Дякую. Цей ресторан дуже гарний.",
        "russian": "Спасибо. Этот ресторан очень красивый.",
        "swedish": "Tack. Den här restaurangen är mycket vacker.",
        "norwegian": "Takk. Denne restauranten er veldig vakker.",
        "danish": "Tak. Denne restaurant er meget smuk.",
        "finnish": "Kiitos. Tämä ravintola on erittäin kaunis.",
        "greek": "Ευχαριστώ. Αυτό το εστιατόριο είναι πολύ όμορφο.",
        "brazilian_portuguese": "Obrigado. Este restaurante é muito bonito.",
        "mandarin": "谢谢。这家餐厅非常漂亮。",
        "japanese": "ありがとうございます。このレストランはとても素敵ですね。",
        "korean": "감사합니다. 이 식당 정말 아름답네요.",
        "hindi": "धन्यवाद। यह रेस्टोरेंट बहुत सुंदर है।",
        "vietnamese": "Cảm ơn. Nhà hàng này rất đẹp.",
        "arabic": "شكراً. هذا المطعم جميل جداً.",
    },
    {
        "line_number": 13, "speaker_name": "Mia",
        "english": "Thank you we opened three years ago. Here is your wine.",
        "lithuanian": "Ačiū, atidarėme prieš trejus metus. Štai jūsų vynas.",
        "latvian": "Paldies, mēs atvērāmies pirms trim gadiem. Lūk jūsu vīns.",
        "estonian": "Tänan, avasime kolm aastat tagasi. Siin on teie vein.",
        "german": "Danke, wir haben vor drei Jahren eröffnet. Hier ist Ihr Wein.",
        "french": "Merci nous avons ouvert il y a trois ans. Voici votre vin.",
        "spanish": "Gracias abrimos hace tres años. Aquí está su vino.",
        "italian": "Grazie abbiamo aperto tre anni fa. Ecco il suo vino.",
        "portuguese": "Obrigada abrimos há três anos. Aqui está o seu vinho.",
        "dutch": "Dank u, we zijn drie jaar geleden geopend. Hier is uw wijn.",
        "polish": "Dziękujemy, otworzyliśmy się trzy lata temu. Oto pana wino.",
        "ukrainian": "Дякуємо, ми відкрилися три роки тому. Ось ваше вино.",
        "russian": "Спасибо, мы открылись три года назад. Вот ваше вино.",
        "swedish": "Tack vi öppnade för tre år sedan. Här är ditt vin.",
        "norwegian": "Takk vi åpnet for tre år siden. Her er vinen din.",
        "danish": "Tak vi åbnede for tre år siden. Her er din vin.",
        "finnish": "Kiitos, avasimme kolme vuotta sitten. Tässä on viinisi.",
        "greek": "Ευχαριστώ ανοίξαμε πριν τρία χρόνια. Ορίστε το κρασί σας.",
        "brazilian_portuguese": "Obrigada, abrimos há três anos. Aqui está o seu vinho.",
        "mandarin": "谢谢，我们三年前开业的。这是您的葡萄酒。",
        "japanese": "ありがとうございます、三年前にオープンしました。ワインをどうぞ。",
        "korean": "감사합니다. 3년 전에 문을 열었어요. 와인입니다.",
        "hindi": "धन्यवाद, हमने तीन साल पहले खोला। यह रहा आपका वाइन।",
        "vietnamese": "Cảm ơn, chúng tôi mở cửa ba năm trước. Đây là rượu vang của bạn.",
        "arabic": "شكراً، افتتحنا منذ ثلاث سنوات. هذا نبيذك.",
    },
    {
        "line_number": 14, "speaker_name": "Alex",
        "english": "The salmon is delicious. I am very happy with this choice.",
        "lithuanian": "Lašiša yra skani. Esu labai patenkintas šiuo pasirinkimu.",
        "latvian": "Lasis ir garšīgs. Esmu ļoti apmierināts ar šo izvēli.",
        "estonian": "Lõhe on maitsev. Olen selle valikuga väga rahul.",
        "german": "Der Lachs ist köstlich. Ich bin sehr zufrieden mit dieser Wahl.",
        "french": "Le saumon est délicieux. Je suis très content de ce choix.",
        "spanish": "El salmón está delicioso. Estoy muy contento con esta elección.",
        "italian": "Il salmone è delizioso. Sono molto contento di questa scelta.",
        "portuguese": "O salmão está delicioso. Estou muito feliz com esta escolha.",
        "dutch": "De zalm is heerlijk. Ik ben erg blij met deze keuze.",
        "polish": "Łosoś jest pyszny. Jestem bardzo zadowolony z tego wyboru.",
        "ukrainian": "Лосось смачний. Я дуже задоволений цим вибором.",
        "russian": "Лосось восхитительный. Я очень доволен этим выбором.",
        "swedish": "Laxen är utsökt. Jag är mycket nöjd med det här valet.",
        "norwegian": "Laksen er deilig. Jeg er veldig fornøyd med dette valget.",
        "danish": "Laksen er lækker. Jeg er meget tilfreds med dette valg.",
        "finnish": "Lohi on herkullista. Olen erittäin tyytyväinen tähän valintaan.",
        "greek": "Ο σολομός είναι υπέροχος. Είμαι πολύ ευχαριστημένος με αυτή την επιλογή.",
        "brazilian_portuguese": "O salmão está delicioso. Estou muito feliz com essa escolha.",
        "mandarin": "三文鱼非常美味。我对这个选择非常满意。",
        "japanese": "サーモンがとても美味しいです。この選択に大満足です。",
        "korean": "연어가 정말 맛있어요. 이 선택에 매우 만족해요.",
        "hindi": "सैल्मन स्वादिष्ट है। मैं इस चुनाव से बहुत खुश हूँ।",
        "vietnamese": "Cá hồi rất ngon. Tôi rất hài lòng với lựa chọn này.",
        "arabic": "السلمون لذيذ جداً. أنا سعيد جداً بهذا الاختيار.",
    },
    {
        "line_number": 15, "speaker_name": "Mia",
        "english": "I am glad you like it. Would you like to see the dessert menu?",
        "lithuanian": "Džiaugiuosi, kad jums patinka. Ar norėtumėte pamatyti desertų meniu?",
        "latvian": "Esmu priecīga, ka jums patīk. Vai vēlētos redzēt deserta ēdienkarti?",
        "estonian": "Mul on hea meel, et meeldib. Kas sooviksite näha magustoidu menüüd?",
        "german": "Es freut mich, dass es Ihnen schmeckt. Möchten Sie die Dessertkarte sehen?",
        "french": "Je suis contente que ça vous plaise. Voulez-vous voir la carte des desserts?",
        "spanish": "Me alegra que le guste. ¿Le gustaría ver el menú de postres?",
        "italian": "Sono contenta che le piaccia. Vorrebbe vedere il menù dei dessert?",
        "portuguese": "Fico contente que goste. Gostaria de ver o menu de sobremesas?",
        "dutch": "Fijn dat u het lekker vindt. Wilt u het dessertmenu zien?",
        "polish": "Cieszę się że smakuje. Czy chciałby pan zobaczyć menu deserów?",
        "ukrainian": "Рада, що вам подобається. Хотіли б ви побачити меню десертів?",
        "russian": "Рада, что вам нравится. Хотели бы вы увидеть меню десертов?",
        "swedish": "Jag är glad att du tycker om det. Vill du se dessertmenyn?",
        "norwegian": "Jeg er glad for at du liker det. Vil du se dessertmenyen?",
        "danish": "Jeg er glad for at du kan lide det. Vil du se dessertmenuen?",
        "finnish": "Olen iloinen että pidätte siitä. Haluaisitteko nähdä jälkiruokalistan?",
        "greek": "Χαίρομαι που σας αρέσει. Θα θέλατε να δείτε τον κατάλογο με τα επιδόρπια;",
        "brazilian_portuguese": "Fico feliz que goste. Gostaria de ver o cardápio de sobremesas?",
        "mandarin": "很高兴您喜欢。您想看甜点菜单吗？",
        "japanese": "気に入っていただけて嬉しいです。デザートメニューをご覧になりますか？",
        "korean": "좋아해 주셔서 기쁩니다. 디저트 메뉴 보시겠어요?",
        "hindi": "खुशी है कि आपको पसंद आया। क्या आप मिठाई मेनू देखना चाहेंगे?",
        "vietnamese": "Vui vì bạn thích. Bạn có muốn xem thực đơn tráng miệng không?",
        "arabic": "يسعدني أنك تستمتع به. هل تريد رؤية قائمة الحلويات؟",
    },
    {
        "line_number": 16, "speaker_name": "Alex",
        "english": "Yes please. What is the chocolate cake like?",
        "lithuanian": "Taip prašau. Koks yra šokoladinis pyragas?",
        "latvian": "Jā lūdzu. Kāds ir šokolādes kūka?",
        "estonian": "Jah palun. Milline on šokolaadikook?",
        "german": "Ja bitte. Wie ist der Schokoladenkuchen?",
        "french": "Oui s'il vous plaît. Comment est le gâteau au chocolat?",
        "spanish": "Sí por favor. ¿Cómo es el pastel de chocolate?",
        "italian": "Sì per favore. Com'è la torta al cioccolato?",
        "portuguese": "Sim por favor. Como é o bolo de chocolate?",
        "dutch": "Ja graag. Hoe is de chocoladetaart?",
        "polish": "Tak proszę. Jaki jest tort czekoladowy?",
        "ukrainian": "Так будь ласка. Який шоколадний торт?",
        "russian": "Да пожалуйста. Каков шоколадный торт?",
        "swedish": "Ja tack. Hur är chokladkakan?",
        "norwegian": "Ja takk. Hvordan er sjokoladekaken?",
        "danish": "Ja tak. Hvordan er chokoladekagen?",
        "finnish": "Kyllä kiitos. Millainen on suklaakakku?",
        "greek": "Ναι παρακαλώ. Πώς είναι το κέικ σοκολάτας;",
        "brazilian_portuguese": "Sim por favor. Como é o bolo de chocolate?",
        "mandarin": "好的。巧克力蛋糕怎么样？",
        "japanese": "はいお願いします。チョコレートケーキはどんな感じですか？",
        "korean": "네 주세요. 초콜릿 케이크는 어때요?",
        "hindi": "हाँ। चॉकलेट केक कैसा है?",
        "vietnamese": "Vâng. Bánh sô-cô-la như thế nào?",
        "arabic": "نعم من فضلك. كيف هي كعكة الشوكولاتة؟",
    },
    {
        "line_number": 17, "speaker_name": "Mia",
        "english": "It is very rich and warm. We serve it with vanilla ice cream.",
        "lithuanian": "Ji labai soti ir šilta. Patiekiame su vaniliniu ledų kremu.",
        "latvian": "Tas ir ļoti bagātīgs un silts. Mēs to pasniedz ar vaniļas saldējumu.",
        "estonian": "See on väga rikkalik ja soe. Serveerime seda vanillijäätisega.",
        "german": "Er ist sehr reichhaltig und warm. Wir servieren ihn mit Vanilleeis.",
        "french": "Il est très riche et chaud. Nous le servons avec de la glace à la vanille.",
        "spanish": "Es muy rico y cálido. Lo servimos con helado de vainilla.",
        "italian": "È molto ricco e caldo. Lo serviamo con gelato alla vaniglia.",
        "portuguese": "É muito rico e quente. Servimos com gelado de baunilha.",
        "dutch": "Het is erg rijk en warm. We serveren het met vanille-ijs.",
        "polish": "Jest bardzo bogaty i ciepły. Podajemy go z lodami waniliowymi.",
        "ukrainian": "Він дуже ситний і теплий. Ми подаємо його з ванільним морозивом.",
        "russian": "Он очень насыщенный и тёплый. Мы подаём его с ванильным мороженым.",
        "swedish": "Den är mycket rik och varm. Vi serverar den med vaniljglass.",
        "norwegian": "Den er veldig rik og varm. Vi serverer den med vaniljeis.",
        "danish": "Den er meget rig og varm. Vi serverer den med vaniljeis.",
        "finnish": "Se on hyvin täyteläinen ja lämmin. Tarjoilemme sen vaniljajäätelön kanssa.",
        "greek": "Είναι πολύ πλούσιο και ζεστό. Το σερβίρουμε με παγωτό βανίλια.",
        "brazilian_portuguese": "É muito rico e quentinho. Servimos com sorvete de baunilha.",
        "mandarin": "非常浓郁温热。我们配香草冰淇淋一起上。",
        "japanese": "とてもリッチで温かいです。バニラアイスクリームと一緒にお出しします。",
        "korean": "아주 진하고 따뜻해요. 바닐라 아이스크림과 함께 드립니다.",
        "hindi": "यह बहुत समृद्ध और गर्म है। हम इसे वेनिला आइसक्रीम के साथ परोसते हैं।",
        "vietnamese": "Rất đậm đà và ấm. Chúng tôi phục vụ với kem vani.",
        "arabic": "إنها غنية جداً ودافئة. نقدمها مع آيس كريم الفانيليا.",
    },
    {
        "line_number": 18, "speaker_name": "Alex",
        "english": "Perfect. I will have that. And another glass of wine please.",
        "lithuanian": "Puiku. Paimsiu tai. Ir dar vieną taurę vyno prašau.",
        "latvian": "Lieliski. Es to ņemšu. Un vēl vienu glāzi vīna lūdzu.",
        "estonian": "Suurepärane. Võtan selle. Ja veel ühe klaasi veini palun.",
        "german": "Perfekt. Das nehme ich. Und noch ein Glas Wein bitte.",
        "french": "Parfait. Je prendrai ça. Et encore un verre de vin s'il vous plaît.",
        "spanish": "Perfecto. Me lo llevo. Y otra copa de vino por favor.",
        "italian": "Perfetto. Lo prendo. E un altro bicchiere di vino per favore.",
        "portuguese": "Perfeito. Quero isso. E mais um copo de vinho por favor.",
        "dutch": "Perfect. Dat neem ik. En nog een glas wijn alstublieft.",
        "polish": "Świetnie. Wezmę to. I jeszcze jeden kieliszek wina proszę.",
        "ukrainian": "Чудово. Візьму це. І ще один бокал вина будь ласка.",
        "russian": "Отлично. Возьму это. И ещё один бокал вина пожалуйста.",
        "swedish": "Perfekt. Jag tar det. Och ett glas vin till tack.",
        "norwegian": "Perfekt. Jeg tar det. Og et glass vin til takk.",
        "danish": "Perfekt. Det tager jeg. Og endnu et glas vin tak.",
        "finnish": "Täydellinen. Otan sen. Ja vielä yksi lasi viiniä kiitos.",
        "greek": "Τέλεια. Θα πάρω αυτό. Και άλλο ένα ποτήρι κρασί παρακαλώ.",
        "brazilian_portuguese": "Perfeito. Vou pegar esse. E mais uma taça de vinho por favor.",
        "mandarin": "太好了。就要这个。再来一杯葡萄酒。",
        "japanese": "完璧です。それをいただきます。もう一杯ワインもお願いします。",
        "korean": "완벽해요. 그걸로 할게요. 와인도 한 잔 더 주세요.",
        "hindi": "बढ़िया। यही लूँगा। और एक गिलास वाइन भी।",
        "vietnamese": "Tuyệt. Tôi sẽ dùng cái đó. Và thêm một ly rượu vang nữa.",
        "arabic": "ممتاز. سآخذ هذا. وكأس نبيذ آخر من فضلك.",
    },
    {
        "line_number": 19, "speaker_name": "Alex",
        "english": "Excuse me. Can I have the bill please?",
        "lithuanian": "Atsiprašau. Ar galiu gauti sąskaitą prašau?",
        "latvian": "Atvainojiet. Vai varu lūgt rēķinu lūdzu?",
        "estonian": "Vabandage. Kas saan arve palun?",
        "german": "Entschuldigung. Kann ich bitte die Rechnung haben?",
        "french": "Excusez-moi. Puis-je avoir l'addition s'il vous plaît?",
        "spanish": "Perdone. ¿Me puede traer la cuenta por favor?",
        "italian": "Scusi. Posso avere il conto per favore?",
        "portuguese": "Com licença. Posso ter a conta por favor?",
        "dutch": "Excuseer mij. Kan ik de rekening alstublieft?",
        "polish": "Przepraszam. Czy mogę prosić o rachunek?",
        "ukrainian": "Вибачте. Можу я отримати рахунок будь ласка?",
        "russian": "Извините. Могу я получить счёт пожалуйста?",
        "swedish": "Ursäkta mig. Kan jag få notan tack?",
        "norwegian": "Unnskyld. Kan jeg få regningen takk?",
        "danish": "Undskyld. Kan jeg få regningen tak?",
        "finnish": "Anteeksi. Voisin saada laskun kiitos?",
        "greek": "Συγγνώμη. Μπορώ να έχω τον λογαριασμό παρακαλώ;",
        "brazilian_portuguese": "Com licença. Pode trazer a conta por favor?",
        "mandarin": "打扰一下。请结账。",
        "japanese": "すみません。お会計をお願いします。",
        "korean": "저기요. 계산서 주세요.",
        "hindi": "माफ़ कीजिए। क्या मुझे बिल मिल सकता है?",
        "vietnamese": "Xin lỗi. Cho tôi hóa đơn được không?",
        "arabic": "عفواً. هل يمكنني الحصول على الفاتورة من فضلك؟",
    },
    {
        "line_number": 20, "speaker_name": "Mia",
        "english": "Of course. That is sixty-five euros. I hope you enjoyed your evening. Please come again!",
        "lithuanian": "Žinoma. Tai šešiasdešimt penki eurai. Tikiuosi jums patiko vakaras. Prašom sugrįžti!",
        "latvian": "Protams. Tas ir sešdesmit pieci eiro. Ceru ka jums patika vakars. Lūdzu nākiet atkal!",
        "estonian": "Muidugi. See on kuuskümmend viis eurot. Loodan et teile meeldis õhtu. Tulge jälle!",
        "german": "Natürlich. Das sind fünfundsechzig Euro. Ich hoffe Sie haben den Abend genossen. Bitte kommen Sie wieder!",
        "french": "Bien sûr. C'est soixante-cinq euros. J'espère que vous avez apprécié votre soirée. Revenez nous voir!",
        "spanish": "Por supuesto. Son sesenta y cinco euros. Espero que haya disfrutado de la velada. ¡Vuelva pronto!",
        "italian": "Certo. Sono sessantacinque euro. Spero che abbia gradito la serata. La aspettiamo di nuovo!",
        "portuguese": "Claro. São sessenta e cinco euros. Espero que tenha gostado da noite. Volte sempre!",
        "dutch": "Natuurlijk. Dat is vijfenzestig euro. Ik hoop dat u genoten heeft van uw avond. Kom alstublieft terug!",
        "polish": "Oczywiście. To sześćdziesiąt pięć euro. Mam nadzieję że miło pan spędził wieczór. Proszę wrócić!",
        "ukrainian": "Звичайно. Це шістдесят п'ять євро. Сподіваюся вам сподобався вечір. Будь ласка приходьте знову!",
        "russian": "Конечно. Это шестьдесят пять евро. Надеюсь вам понравился вечер. Пожалуйста приходите снова!",
        "swedish": "Naturligtvis. Det är sextio fem euro. Jag hoppas du njöt av kvällen. Välkommen tillbaka!",
        "norwegian": "Selvfølgelig. Det er seksti fem euro. Jeg håper du hadde en god kveld. Kom gjerne tilbake!",
        "danish": "Selvfølgelig. Det er femogtres euro. Jeg håber du nød aftenen. Kom gerne igen!",
        "finnish": "Tietysti. Se on kuusikymmentäviisi euroa. Toivottavasti nautitte illasta. Tervetuloa uudelleen!",
        "greek": "Βεβαίως. Είναι εξήντα πέντε ευρώ. Ελπίζω να απολαύσατε το βράδυ σας. Ελάτε ξανά!",
        "brazilian_portuguese": "Claro. São sessenta e cinco euros. Espero que tenha gostado da noite. Volte sempre!",
        "mandarin": "当然。六十五欧元。希望您度过了愉快的夜晚。欢迎再次光临！",
        "japanese": "もちろんです。六十五ユーロになります。素敵な夜をお過ごしいただけたなら幸いです。またのお越しをお待ちしております！",
        "korean": "물론이죠. 육십오 유로입니다. 즐거운 저녁 되셨길 바랍니다. 또 오세요!",
        "hindi": "बिल्कुल। पैंसठ यूरो हुए। उम्मीद है आपने शाम का आनंद लिया। फिर आइए!",
        "vietnamese": "Tất nhiên. Sáu mươi lăm euro. Hy vọng bạn tận hưởng buổi tối. Mời bạn quay lại!",
        "arabic": "بالطبع. المجموع خمسة وستون يورو. أتمنى أنك استمتعت بسهرتك. تفضل بزيارتنا مرة أخرى!",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="At the Restaurant").first()
        if existing:
            print("A2 dialogue 'At the Restaurant' already exists — skipping.")
            return

        dialogue = Dialogue(topic="At the Restaurant", lang_level="A2", length=20)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded A2 dialogue ID {dialogue.id} — 20 lines in 25 languages.")


if __name__ == '__main__':
    seed()
