import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "Hello. One coffee please.",
        "lithuanian": "Labas. Vieną kavą, prašau.",
        "latvian": "Sveiki. Vienu kafiju, lūdzu.",
        "estonian": "Tere. Üks kohv, palun.",
        "german": "Hallo. Einen Kaffee bitte.",
        "french": "Bonjour. Un café s'il vous plaît.",
        "spanish": "Hola. Un café por favor.",
        "italian": "Ciao. Un caffè per favore.",
        "portuguese": "Olá. Um café por favor.",
        "dutch": "Hallo. Één koffie alstublieft.",
        "polish": "Cześć. Jedną kawę proszę.",
        "ukrainian": "Привіт. Одну каву, будь ласка.",
        "russian": "Привет. Один кофе пожалуйста.",
        "swedish": "Hej. En kaffe tack.",
        "norwegian": "Hei. En kaffe takk.",
        "danish": "Hej. En kaffe tak.",
        "finnish": "Hei. Yksi kahvi kiitos.",
        "greek": "Γεια. Έναν καφέ παρακαλώ.",
        "brazilian_portuguese": "Olá. Um café por favor.",
        "mandarin": "你好。请给我一杯咖啡。",
        "japanese": "こんにちは。コーヒーを一つください。",
        "korean": "안녕하세요. 커피 한 잔 주세요.",
        "hindi": "नमस्ते। एक कॉफी दीजिए।",
        "vietnamese": "Xin chào. Cho tôi một cốc cà phê.",
        "arabic": "مرحباً. قهوة واحدة من فضلك.",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "Small or large?",
        "lithuanian": "Mažą ar didelę?",
        "latvian": "Mazu vai lielu?",
        "estonian": "Väike või suur?",
        "german": "Klein oder groß?",
        "french": "Petit ou grand?",
        "spanish": "Pequeño o grande?",
        "italian": "Piccolo o grande?",
        "portuguese": "Pequeno ou grande?",
        "dutch": "Klein of groot?",
        "polish": "Mała czy duża?",
        "ukrainian": "Маленьку чи велику?",
        "russian": "Маленький или большой?",
        "swedish": "Liten eller stor?",
        "norwegian": "Liten eller stor?",
        "danish": "Lille eller stor?",
        "finnish": "Pieni vai suuri?",
        "greek": "Μικρό ή μεγάλο;",
        "brazilian_portuguese": "Pequeno ou grande?",
        "mandarin": "小杯还是大杯？",
        "japanese": "小さいですか、大きいですか？",
        "korean": "작은 것 아니면 큰 것으로 드릴까요?",
        "hindi": "छोटा या बड़ा?",
        "vietnamese": "Nhỏ hay lớn?",
        "arabic": "صغير أم كبير؟",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "Large please. And a sandwich.",
        "lithuanian": "Didelę prašau. Ir sumuštinį.",
        "latvian": "Lielu lūdzu. Un sviestmaizi.",
        "estonian": "Suure palun. Ja võileib.",
        "german": "Groß bitte. Und ein Sandwich.",
        "french": "Grand s'il vous plaît. Et un sandwich.",
        "spanish": "Grande por favor. Y un sándwich.",
        "italian": "Grande per favore. E un panino.",
        "portuguese": "Grande por favor. E um sandes.",
        "dutch": "Groot alstublieft. En een sandwich.",
        "polish": "Dużą proszę. I kanapkę.",
        "ukrainian": "Велику будь ласка. І бутерброд.",
        "russian": "Большой пожалуйста. И бутерброд.",
        "swedish": "Stor tack. Och en smörgås.",
        "norwegian": "Stor takk. Og en sandwich.",
        "danish": "Stor tak. Og en sandwich.",
        "finnish": "Suuri kiitos. Ja voileipä.",
        "greek": "Μεγάλο παρακαλώ. Και ένα σάντουιτς.",
        "brazilian_portuguese": "Grande por favor. E um sanduíche.",
        "mandarin": "大杯的。还有一个三明治。",
        "japanese": "大きいのをください。それとサンドイッチも。",
        "korean": "큰 것으로 주세요. 그리고 샌드위치도요.",
        "hindi": "बड़ा दीजिए। और एक सैंडविच भी।",
        "vietnamese": "Cái lớn. Và một chiếc bánh mì.",
        "arabic": "كبير من فضلك. وشطيرة أيضاً.",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "We have cheese or ham.",
        "lithuanian": "Turime su sūriu arba kumpiu.",
        "latvian": "Mums ir ar sieru vai šķiņķi.",
        "estonian": "Meil on juustu või singiga.",
        "german": "Wir haben Käse oder Schinken.",
        "french": "Nous avons fromage ou jambon.",
        "spanish": "Tenemos queso o jamón.",
        "italian": "Abbiamo formaggio o prosciutto.",
        "portuguese": "Temos queijo ou fiambre.",
        "dutch": "We hebben kaas of ham.",
        "polish": "Mamy ser lub szynkę.",
        "ukrainian": "У нас є сир або шинка.",
        "russian": "У нас есть сыр или ветчина.",
        "swedish": "Vi har ost eller skinka.",
        "norwegian": "Vi har ost eller skinke.",
        "danish": "Vi har ost eller skinke.",
        "finnish": "Meillä on juustoa tai kinkkua.",
        "greek": "Έχουμε τυρί ή ζαμπόν.",
        "brazilian_portuguese": "Temos queijo ou presunto.",
        "mandarin": "我们有奶酪的或火腿的。",
        "japanese": "チーズかハムがあります。",
        "korean": "치즈나 햄이 있어요.",
        "hindi": "हमारे पास पनीर या हैम है।",
        "vietnamese": "Chúng tôi có phô mai hoặc giăm bông.",
        "arabic": "لدينا جبن أو لحم.",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "Ham please. How much is that?",
        "lithuanian": "Kumpį prašau. Kiek kainuoja?",
        "latvian": "Šķiņķi lūdzu. Cik tas maksā?",
        "estonian": "Sinki palun. Kui palju see maksab?",
        "german": "Schinken bitte. Was kostet das?",
        "french": "Jambon s'il vous plaît. C'est combien?",
        "spanish": "Jamón por favor. ¿Cuánto cuesta?",
        "italian": "Prosciutto per favore. Quanto costa?",
        "portuguese": "Fiambre por favor. Quanto custa?",
        "dutch": "Ham alstublieft. Hoeveel kost dat?",
        "polish": "Szynkę proszę. Ile to kosztuje?",
        "ukrainian": "Шинку будь ласка. Скільки це коштує?",
        "russian": "Ветчину пожалуйста. Сколько это стоит?",
        "swedish": "Skinka tack. Hur mycket kostar det?",
        "norwegian": "Skinke takk. Hvor mye koster det?",
        "danish": "Skinke tak. Hvor meget koster det?",
        "finnish": "Kinkkua kiitos. Kuinka paljon se maksaa?",
        "greek": "Ζαμπόν παρακαλώ. Πόσο κοστίζει;",
        "brazilian_portuguese": "Presunto por favor. Quanto custa?",
        "mandarin": "火腿的。多少钱？",
        "japanese": "ハムでお願いします。いくらですか？",
        "korean": "햄으로 주세요. 얼마예요?",
        "hindi": "हैम दीजिए। कितना पैसा लगेगा?",
        "vietnamese": "Giăm bông. Bao nhiêu tiền?",
        "arabic": "لحم من فضلك. كم يكلف؟",
    },
    {
        "line_number": 6, "speaker_name": "Mia",
        "english": "Five euros fifty.",
        "lithuanian": "Penki eurai penkiasdešimt centų.",
        "latvian": "Pieci eiro piecdesmit centi.",
        "estonian": "Viis eurot viiskümmend senti.",
        "german": "Fünf Euro fünfzig.",
        "french": "Cinq euros cinquante.",
        "spanish": "Cinco euros cincuenta.",
        "italian": "Cinque euro e cinquanta.",
        "portuguese": "Cinco euros e cinquenta.",
        "dutch": "Vijf euro vijftig.",
        "polish": "Pięć euro pięćdziesiąt.",
        "ukrainian": "П'ять євро п'ятдесят центів.",
        "russian": "Пять евро пятьдесят центов.",
        "swedish": "Fem euro femtio.",
        "norwegian": "Fem euro femti.",
        "danish": "Fem euro halvtreds.",
        "finnish": "Viisi euroa viisikymmentä senttiä.",
        "greek": "Πέντε ευρώ πενήντα.",
        "brazilian_portuguese": "Cinco euros e cinquenta.",
        "mandarin": "五欧元五十分。",
        "japanese": "五ユーロ五十セントです。",
        "korean": "오 유로 오십 센트입니다.",
        "hindi": "पाँच यूरो पचास सेंट।",
        "vietnamese": "Năm euro năm mươi xu.",
        "arabic": "خمسة يورو وخمسون سنتاً.",
    },
    {
        "line_number": 7, "speaker_name": "Alex",
        "english": "Here is ten euros.",
        "lithuanian": "Štai dešimt eurų.",
        "latvian": "Lūk, desmit eiro.",
        "estonian": "Siin on kümme eurot.",
        "german": "Hier sind zehn Euro.",
        "french": "Voici dix euros.",
        "spanish": "Aquí tiene diez euros.",
        "italian": "Ecco dieci euro.",
        "portuguese": "Aqui estão dez euros.",
        "dutch": "Hier zijn tien euro.",
        "polish": "Oto dziesięć euro.",
        "ukrainian": "Ось десять євро.",
        "russian": "Вот десять евро.",
        "swedish": "Här är tio euro.",
        "norwegian": "Her er ti euro.",
        "danish": "Her er ti euro.",
        "finnish": "Tässä on kymmenen euroa.",
        "greek": "Ορίστε δέκα ευρώ.",
        "brazilian_portuguese": "Aqui estão dez euros.",
        "mandarin": "这是十欧元。",
        "japanese": "十ユーロです。",
        "korean": "여기 십 유로 있어요.",
        "hindi": "यह लीजिए दस यूरो।",
        "vietnamese": "Đây là mười euro.",
        "arabic": "هذه عشرة يورو.",
    },
    {
        "line_number": 8, "speaker_name": "Mia",
        "english": "Your change is four euros fifty. Thank you!",
        "lithuanian": "Jūsų grąža keturi eurai penkiasdešimt centų. Ačiū!",
        "latvian": "Jūsu atlikums ir četri eiro piecdesmit centi. Paldies!",
        "estonian": "Teie vahetus on neli eurot viiskümmend senti. Tänan!",
        "german": "Ihr Wechselgeld ist vier Euro fünfzig. Danke!",
        "french": "Votre monnaie est quatre euros cinquante. Merci!",
        "spanish": "Su cambio es cuatro euros cincuenta. ¡Gracias!",
        "italian": "Il suo resto è quattro euro e cinquanta. Grazie!",
        "portuguese": "O seu troco é quatro euros e cinquenta. Obrigada!",
        "dutch": "Uw wisselgeld is vier euro vijftig. Dank u!",
        "polish": "Reszta to cztery euro pięćdziesiąt. Dziękuję!",
        "ukrainian": "Ваша решта чотири євро п'ятдесят. Дякую!",
        "russian": "Ваша сдача четыре евро пятьдесят. Спасибо!",
        "swedish": "Din växel är fyra euro femtio. Tack!",
        "norwegian": "Vekslepengene dine er fire euro femti. Takk!",
        "danish": "Din byttepenge er fire euro halvtreds. Tak!",
        "finnish": "Vaihtorahasi on neljä euroa viisikymmentä. Kiitos!",
        "greek": "Τα ρέστα σας είναι τέσσερα ευρώ πενήντα. Ευχαριστώ!",
        "brazilian_portuguese": "Seu troco é quatro euros e cinquenta. Obrigada!",
        "mandarin": "找您四欧元五十分。谢谢！",
        "japanese": "お釣りは四ユーロ五十セントです。ありがとうございます！",
        "korean": "거스름돈은 사 유로 오십 센트입니다. 감사합니다!",
        "hindi": "आपकी बाकी राशि चार यूरो पचास सेंट है। धन्यवाद!",
        "vietnamese": "Tiền thối lại của bạn là bốn euro năm mươi xu. Cảm ơn!",
        "arabic": "باقي مالك أربعة يورو وخمسون سنتاً. شكراً!",
    },
    {
        "line_number": 9, "speaker_name": "Alex",
        "english": "Is there a table near the window?",
        "lithuanian": "Ar yra stalas prie lango?",
        "latvian": "Vai ir galdiņš pie loga?",
        "estonian": "Kas akna lähedal on laud?",
        "german": "Gibt es einen Tisch am Fenster?",
        "french": "Y a-t-il une table près de la fenêtre?",
        "spanish": "¿Hay una mesa cerca de la ventana?",
        "italian": "C'è un tavolo vicino alla finestra?",
        "portuguese": "Há uma mesa perto da janela?",
        "dutch": "Is er een tafel bij het raam?",
        "polish": "Czy jest stolik przy oknie?",
        "ukrainian": "Є столик біля вікна?",
        "russian": "Есть ли столик у окна?",
        "swedish": "Finns det ett bord vid fönstret?",
        "norwegian": "Er det et bord ved vinduet?",
        "danish": "Er der et bord ved vinduet?",
        "finnish": "Onko ikkunan lähellä pöytä?",
        "greek": "Υπάρχει ένα τραπέζι κοντά στο παράθυρο;",
        "brazilian_portuguese": "Tem uma mesa perto da janela?",
        "mandarin": "窗边有桌子吗？",
        "japanese": "窓の近くにテーブルはありますか？",
        "korean": "창문 옆에 테이블이 있나요?",
        "hindi": "खिड़की के पास कोई मेज है?",
        "vietnamese": "Có bàn gần cửa sổ không?",
        "arabic": "هل يوجد طاولة بالقرب من النافذة؟",
    },
    {
        "line_number": 10, "speaker_name": "Mia",
        "english": "Yes, that table is free.",
        "lithuanian": "Taip, tas stalas laisvas.",
        "latvian": "Jā, tas galdiņš ir brīvs.",
        "estonian": "Jah, see laud on vaba.",
        "german": "Ja, dieser Tisch ist frei.",
        "french": "Oui, cette table est libre.",
        "spanish": "Sí, esa mesa está libre.",
        "italian": "Sì, quel tavolo è libero.",
        "portuguese": "Sim, essa mesa está livre.",
        "dutch": "Ja, die tafel is vrij.",
        "polish": "Tak, ten stolik jest wolny.",
        "ukrainian": "Так, той столик вільний.",
        "russian": "Да, тот столик свободен.",
        "swedish": "Ja, det bordet är ledigt.",
        "norwegian": "Ja, det bordet er ledig.",
        "danish": "Ja, det bord er ledigt.",
        "finnish": "Kyllä, se pöytä on vapaa.",
        "greek": "Ναι, αυτό το τραπέζι είναι ελεύθερο.",
        "brazilian_portuguese": "Sim, essa mesa está livre.",
        "mandarin": "是的，那张桌子是空的。",
        "japanese": "はい、あのテーブルは空いています。",
        "korean": "네, 저 테이블은 비어 있어요.",
        "hindi": "हाँ, वह मेज खाली है।",
        "vietnamese": "Vâng, cái bàn đó trống.",
        "arabic": "نعم تلك الطاولة فارغة.",
    },
    {
        "line_number": 11, "speaker_name": "Alex",
        "english": "Good. Do you have wifi here?",
        "lithuanian": "Gerai. Ar turite čia wifi?",
        "latvian": "Labi. Vai jums šeit ir wifi?",
        "estonian": "Hea. Kas siin on wifi?",
        "german": "Gut. Haben Sie hier WLAN?",
        "french": "Bien. Avez-vous le wifi ici?",
        "spanish": "Bien. ¿Tienen wifi aquí?",
        "italian": "Bene. Avete il wifi qui?",
        "portuguese": "Ótimo. Têm wifi aqui?",
        "dutch": "Goed. Heeft u hier wifi?",
        "polish": "Dobrze. Czy jest tu wifi?",
        "ukrainian": "Добре. У вас є тут вайфай?",
        "russian": "Хорошо. Есть ли здесь wifi?",
        "swedish": "Bra. Har ni wifi här?",
        "norwegian": "Bra. Har dere wifi her?",
        "danish": "Godt. Har I wifi her?",
        "finnish": "Hyvä. Onko täällä wifi?",
        "greek": "Ωραία. Έχετε wifi εδώ;",
        "brazilian_portuguese": "Ótimo. Vocês têm wifi aqui?",
        "mandarin": "好的。这里有wifi吗？",
        "japanese": "いいですね。ここはwifiがありますか？",
        "korean": "좋아요. 여기 와이파이 있나요?",
        "hindi": "अच्छा। क्या यहाँ वाईफाई है?",
        "vietnamese": "Tốt. Ở đây có wifi không?",
        "arabic": "جيد. هل لديكم واي فاي هنا؟",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "Yes. The password is on the menu.",
        "lithuanian": "Taip. Slaptažodis yra meniu.",
        "latvian": "Jā. Parole ir uz ēdienkartes.",
        "estonian": "Jah. Parool on menüül.",
        "german": "Ja. Das Passwort steht auf der Speisekarte.",
        "french": "Oui. Le mot de passe est sur le menu.",
        "spanish": "Sí. La contraseña está en el menú.",
        "italian": "Sì. La password è sul menu.",
        "portuguese": "Sim. A senha está no menu.",
        "dutch": "Ja. Het wachtwoord staat op het menu.",
        "polish": "Tak. Hasło jest na menu.",
        "ukrainian": "Так. Пароль на меню.",
        "russian": "Да. Пароль на меню.",
        "swedish": "Ja. Lösenordet finns på menyn.",
        "norwegian": "Ja. Passordet er på menyen.",
        "danish": "Ja. Koden er på menuen.",
        "finnish": "Kyllä. Salasana on menussa.",
        "greek": "Ναι. Ο κωδικός είναι στο μενού.",
        "brazilian_portuguese": "Sim. A senha está no cardápio.",
        "mandarin": "是的。密码在菜单上。",
        "japanese": "はい。パスワードはメニューに書いてあります。",
        "korean": "네. 비밀번호는 메뉴에 있어요.",
        "hindi": "हाँ। पासवर्ड मेनू पर है।",
        "vietnamese": "Vâng. Mật khẩu ở trên thực đơn.",
        "arabic": "نعم. كلمة المرور على القائمة.",
    },
    {
        "line_number": 13, "speaker_name": "Alex",
        "english": "Thank you. The coffee is very good.",
        "lithuanian": "Ačiū. Kava labai skani.",
        "latvian": "Paldies. Kafija ir ļoti laba.",
        "estonian": "Tänan. Kohv on väga hea.",
        "german": "Danke. Der Kaffee ist sehr gut.",
        "french": "Merci. Le café est très bon.",
        "spanish": "Gracias. El café es muy bueno.",
        "italian": "Grazie. Il caffè è molto buono.",
        "portuguese": "Obrigado. O café é muito bom.",
        "dutch": "Dank u. De koffie is erg goed.",
        "polish": "Dziękuję. Kawa jest bardzo dobra.",
        "ukrainian": "Дякую. Кава дуже смачна.",
        "russian": "Спасибо. Кофе очень хороший.",
        "swedish": "Tack. Kaffet är mycket gott.",
        "norwegian": "Takk. Kaffen er veldig god.",
        "danish": "Tak. Kaffen er meget god.",
        "finnish": "Kiitos. Kahvi on erittäin hyvää.",
        "greek": "Ευχαριστώ. Ο καφές είναι πολύ καλός.",
        "brazilian_portuguese": "Obrigado. O café é muito bom.",
        "mandarin": "谢谢。咖啡非常好。",
        "japanese": "ありがとう。コーヒーはとても美味しいです。",
        "korean": "감사합니다. 커피가 매우 맛있어요.",
        "hindi": "धन्यवाद। कॉफी बहुत अच्छी है।",
        "vietnamese": "Cảm ơn. Cà phê rất ngon.",
        "arabic": "شكراً. القهوة جيدة جداً.",
    },
    {
        "line_number": 14, "speaker_name": "Mia",
        "english": "I am happy. Do you want anything else?",
        "lithuanian": "Džiaugiuosi. Ar norite dar ko nors?",
        "latvian": "Esmu priecīga. Vai vēlaties vēl ko?",
        "estonian": "Mul on hea meel. Kas soovite midagi muud?",
        "german": "Das freut mich. Möchten Sie noch etwas?",
        "french": "Je suis contente. Voulez-vous autre chose?",
        "spanish": "Me alegra. ¿Quiere algo más?",
        "italian": "Sono contenta. Vuole altro?",
        "portuguese": "Que bom. Quer mais alguma coisa?",
        "dutch": "Dat is fijn. Wilt u nog iets?",
        "polish": "Cieszę się. Czy chce pan coś jeszcze?",
        "ukrainian": "Радію. Ви хочете ще щось?",
        "russian": "Рада слышать. Хотите ещё что-нибудь?",
        "swedish": "Det gläder mig. Vill du ha något mer?",
        "norwegian": "Det gleder meg. Vil du ha noe mer?",
        "danish": "Det glæder mig. Vil du have noget mere?",
        "finnish": "Olen iloinen. Haluatko jotain muuta?",
        "greek": "Χαίρομαι. Θέλετε κάτι άλλο;",
        "brazilian_portuguese": "Fico feliz. Quer mais alguma coisa?",
        "mandarin": "很高兴。您还需要别的吗？",
        "japanese": "よかったです。他に何かご要望はありますか？",
        "korean": "기쁩니다. 다른 거 필요하신 게 있으세요?",
        "hindi": "खुशी हुई। क्या आप कुछ और चाहते हैं?",
        "vietnamese": "Tôi vui lắm. Bạn có muốn thêm gì không?",
        "arabic": "يسعدني ذلك. هل تريد شيئاً آخر؟",
    },
    {
        "line_number": 15, "speaker_name": "Alex",
        "english": "No thank you. Just the bill please.",
        "lithuanian": "Ne ačiū. Tik sąskaitą prašau.",
        "latvian": "Nē paldies. Tikai rēķinu lūdzu.",
        "estonian": "Ei tänan. Ainult arve palun.",
        "german": "Nein danke. Nur die Rechnung bitte.",
        "french": "Non merci. Juste l'addition s'il vous plaît.",
        "spanish": "No gracias. Solo la cuenta por favor.",
        "italian": "No grazie. Solo il conto per favore.",
        "portuguese": "Não obrigado. Só a conta por favor.",
        "dutch": "Nee dank u. Alleen de rekening alstublieft.",
        "polish": "Nie dziękuję. Tylko rachunek proszę.",
        "ukrainian": "Ні дякую. Тільки рахунок будь ласка.",
        "russian": "Нет спасибо. Только счёт пожалуйста.",
        "swedish": "Nej tack. Bara notan tack.",
        "norwegian": "Nei takk. Bare regningen takk.",
        "danish": "Nej tak. Bare regningen tak.",
        "finnish": "Ei kiitos. Pelkkä lasku kiitos.",
        "greek": "Όχι ευχαριστώ. Μόνο τον λογαριασμό παρακαλώ.",
        "brazilian_portuguese": "Não obrigado. Só a conta por favor.",
        "mandarin": "不用了谢谢。只要账单就好。",
        "japanese": "いいえ結構です。お会計だけお願いします。",
        "korean": "아니요 괜찮습니다. 계산서만 주세요.",
        "hindi": "नहीं धन्यवाद। बस बिल चाहिए।",
        "vietnamese": "Không cảm ơn. Chỉ cần hóa đơn thôi.",
        "arabic": "لا شكراً. الفاتورة فقط من فضلك.",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="At the Coffee Shop").first()
        if existing:
            print("A1 dialogue 'At the Coffee Shop' already exists — skipping.")
            return

        dialogue = Dialogue(topic="At the Coffee Shop", lang_level="A1", length=15)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded A1 dialogue ID {dialogue.id} — 15 lines in 25 languages.")


if __name__ == '__main__':
    seed()
