import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "Good morning. I would like to send this package to Lithuania.",
        "lithuanian": "Labas rytas. Norėčiau išsiųsti šį paketą į Lietuvą.",
        "latvian": "Labrīt. Es gribētu nosūtīt šo paketi uz Lietuvu.",
        "estonian": "Tere hommikust. Sooviksin saata selle paketi Leedusse.",
        "german": "Guten Morgen. Ich möchte dieses Paket nach Litauen schicken.",
        "french": "Bonjour. Je voudrais envoyer ce colis en Lituanie.",
        "spanish": "Buenos días. Me gustaría enviar este paquete a Lituania.",
        "italian": "Buongiorno. Vorrei spedire questo pacco in Lituania.",
        "portuguese": "Bom dia. Gostaria de enviar este pacote para a Lituânia.",
        "dutch": "Goedemorgen. Ik wil dit pakket naar Litouwen sturen.",
        "polish": "Dzień dobry. Chciałbym wysłać ten pakiet do Litwy.",
        "ukrainian": "Доброго ранку. Я хотів би надіслати цей пакет до Литви.",
        "russian": "Доброе утро. Я хотел бы отправить этот пакет в Литву.",
        "swedish": "God morgon. Jag skulle vilja skicka det här paketet till Litauen.",
        "norwegian": "God morgen. Jeg vil gjerne sende denne pakken til Litauen.",
        "danish": "God morgen. Jeg vil gerne sende denne pakke til Litauen.",
        "finnish": "Hyvää huomenta. Haluaisin lähettää tämän paketin Liettuaan.",
        "greek": "Καλημέρα. Θα ήθελα να στείλω αυτό το δέμα στη Λιθουανία.",
        "brazilian_portuguese": "Bom dia. Gostaria de enviar este pacote para a Lituânia.",
        "mandarin": "早上好。我想把这个包裹寄到立陶宛。",
        "japanese": "おはようございます。このパッケージをリトアニアに送りたいのですが。",
        "korean": "안녕하세요. 이 소포를 리투아니아로 보내고 싶습니다.",
        "hindi": "सुप्रभात। मैं यह पैकेज लिथुआनिया भेजना चाहूँगा।",
        "vietnamese": "Chào buổi sáng. Tôi muốn gửi gói hàng này đến Lithuania.",
        "arabic": "صباح الخير. أود إرسال هذه الطرد إلى ليتوانيا.",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "Of course. Please put it on the scale. What is inside the package?",
        "lithuanian": "Žinoma. Prašom padėti ant svarstyklių. Kas yra paketo viduje?",
        "latvian": "Protams. Lūdzu novietojiet to uz svariem. Kas ir paketē?",
        "estonian": "Muidugi. Palun pange see kaalule. Mis on paketi sees?",
        "german": "Natürlich. Bitte legen Sie es auf die Waage. Was ist im Paket?",
        "french": "Bien sûr. Posez-le sur la balance s'il vous plaît. Qu'est-ce qu'il y a dans le colis?",
        "spanish": "Por supuesto. Póngalo en la balanza por favor. ¿Qué hay dentro del paquete?",
        "italian": "Certo. Metta il pacco sulla bilancia per favore. Cosa c'è dentro il pacco?",
        "portuguese": "Claro. Por favor coloque-o na balança. O que está dentro do pacote?",
        "dutch": "Natuurlijk. Leg het op de weegschaal alstublieft. Wat zit er in het pakket?",
        "polish": "Oczywiście. Proszę położyć to na wadze. Co jest w środku paczki?",
        "ukrainian": "Звичайно. Будь ласка покладіть на ваги. Що всередині посилки?",
        "russian": "Конечно. Пожалуйста положите на весы. Что внутри посылки?",
        "swedish": "Naturligtvis. Lägg det på vågen tack. Vad är inne i paketet?",
        "norwegian": "Selvfølgelig. Legg det på vekten takk. Hva er inni pakken?",
        "danish": "Selvfølgelig. Læg det på vægten tak. Hvad er der inde i pakken?",
        "finnish": "Tietysti. Laittakaa se vaa'alle kiitos. Mitä pakkauksessa on?",
        "greek": "Βεβαίως. Βάλτε το στη ζυγαριά παρακαλώ. Τι υπάρχει μέσα στο δέμα;",
        "brazilian_portuguese": "Claro. Por favor coloque na balança. O que tem dentro do pacote?",
        "mandarin": "当然。请把它放在称上。包裹里面是什么？",
        "japanese": "もちろんです。秤の上に置いてください。パッケージの中身は何ですか？",
        "korean": "물론이죠. 저울에 올려주세요. 소포 안에 뭐가 들어있나요?",
        "hindi": "बिल्कुल। इसे तराजू पर रखें। पैकेज के अंदर क्या है?",
        "vietnamese": "Tất nhiên. Đặt lên cân. Bên trong gói hàng có gì?",
        "arabic": "بالطبع. ضعه على الميزان من فضلك. ماذا يوجد داخل الطرد؟",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "It is some books and a few small gifts. Nothing expensive.",
        "lithuanian": "Tai kelios knygos ir kelios mažos dovanos. Nieko brangaus.",
        "latvian": "Tas ir dažas grāmatas un daži mazi dāvaniņi. Nekas dārgs.",
        "estonian": "See on mõned raamatud ja mõned väikesed kingitused. Midagi kallid pole.",
        "german": "Es sind einige Bücher und ein paar kleine Geschenke. Nichts Teures.",
        "french": "Ce sont quelques livres et quelques petits cadeaux. Rien de cher.",
        "spanish": "Son algunos libros y unos pequeños regalos. Nada caro.",
        "italian": "Sono alcuni libri e qualche piccolo regalo. Niente di costoso.",
        "portuguese": "São alguns livros e alguns pequenos presentes. Nada caro.",
        "dutch": "Het zijn wat boeken en een paar kleine cadeautjes. Niets duurs.",
        "polish": "To kilka książek i kilka małych prezentów. Nic drogiego.",
        "ukrainian": "Це кілька книг і кілька маленьких подарунків. Нічого дорогого.",
        "russian": "Это несколько книг и несколько маленьких подарков. Ничего дорогого.",
        "swedish": "Det är några böcker och några små presenter. Inget dyrt.",
        "norwegian": "Det er noen bøker og noen små gaver. Ingenting dyrt.",
        "danish": "Det er nogle bøger og nogle små gaver. Intet dyrt.",
        "finnish": "Se on muutama kirja ja muutama pieni lahja. Ei mitään kallista.",
        "greek": "Είναι μερικά βιβλία και μερικά μικρά δώρα. Τίποτα ακριβό.",
        "brazilian_portuguese": "São alguns livros e alguns presentes pequenos. Nada caro.",
        "mandarin": "是一些书和几件小礼物。没有什么贵重的东西。",
        "japanese": "本が何冊かと小さなプレゼントが少しです。高価なものは何もありません。",
        "korean": "책 몇 권과 작은 선물 몇 개예요. 비싼 건 없어요.",
        "hindi": "कुछ किताबें और कुछ छोटे उपहार हैं। कुछ महंगा नहीं।",
        "vietnamese": "Là một vài cuốn sách và một vài món quà nhỏ. Không có gì đắt tiền.",
        "arabic": "إنها بعض الكتب وبعض الهدايا الصغيرة. لا شيء باهظ الثمن.",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "The package weighs two kilos. Do you want standard or express delivery?",
        "lithuanian": "Paketas sveria du kilogramus. Ar norite standartinio ar ekspresinio pristatymo?",
        "latvian": "Paketis sver divus kilogramus. Vai vēlaties standarta vai ekspres piegādi?",
        "estonian": "Pakett kaalub kaks kilogrammi. Kas soovite tavalist või ekspresstarnet?",
        "german": "Das Paket wiegt zwei Kilo. Möchten Sie Standardlieferung oder Expresslieferung?",
        "french": "Le colis pèse deux kilos. Voulez-vous une livraison standard ou express?",
        "spanish": "El paquete pesa dos kilos. ¿Quiere entrega estándar o exprés?",
        "italian": "Il pacco pesa due chili. Vuole la consegna standard o express?",
        "portuguese": "O pacote pesa dois quilos. Quer entrega normal ou expresso?",
        "dutch": "Het pakket weegt twee kilo. Wilt u standaard of expreslevering?",
        "polish": "Paczka waży dwa kilogramy. Czy chce pan dostawę standardową czy ekspresową?",
        "ukrainian": "Посилка важить два кілограми. Ви хочете стандартну чи експрес-доставку?",
        "russian": "Посылка весит два килограмма. Вы хотите стандартную или экспресс-доставку?",
        "swedish": "Paketet väger två kilo. Vill du ha standard eller expresslevering?",
        "norwegian": "Pakken veier to kilo. Vil du ha standard eller ekspresslevering?",
        "danish": "Pakken vejer to kilo. Vil du have standard eller ekspreslevering?",
        "finnish": "Paketti painaa kaksi kiloa. Haluatteko tavallisen vai pikatoimitusen?",
        "greek": "Το δέμα ζυγίζει δύο κιλά. Θέλετε κανονική ή ταχεία παράδοση;",
        "brazilian_portuguese": "O pacote pesa dois quilos. Quer entrega padrão ou expressa?",
        "mandarin": "包裹重两公斤。您要标准配送还是快递？",
        "japanese": "荷物は二キログラムです。通常配送とエクスプレスどちらにしますか？",
        "korean": "소포가 2킬로그램이에요. 일반 배송이 좋으세요 아니면 빠른 배송이 좋으세요?",
        "hindi": "पैकेज का वज़न दो किलो है। क्या आप सामान्य या एक्सप्रेस डिलीवरी चाहते हैं?",
        "vietnamese": "Gói hàng nặng hai kilogram. Bạn muốn giao hàng tiêu chuẩn hay chuyển phát nhanh?",
        "arabic": "يزن الطرد كيلوغرامين. هل تريد التوصيل العادي أم السريع؟",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "How long does standard delivery take?",
        "lithuanian": "Kiek laiko užtrunka standartinis pristatymas?",
        "latvian": "Cik ilgi aizņem standarta piegāde?",
        "estonian": "Kui kaua tavapärane tarnimine võtab?",
        "german": "Wie lange dauert die Standardlieferung?",
        "french": "Combien de temps prend la livraison standard?",
        "spanish": "¿Cuánto tiempo tarda la entrega estándar?",
        "italian": "Quanto tempo impiega la consegna standard?",
        "portuguese": "Quanto tempo demora a entrega normal?",
        "dutch": "Hoe lang duurt de standaardlevering?",
        "polish": "Ile czasu zajmuje standardowa dostawa?",
        "ukrainian": "Скільки часу займає стандартна доставка?",
        "russian": "Сколько времени занимает стандартная доставка?",
        "swedish": "Hur lång tid tar standardleveransen?",
        "norwegian": "Hvor lang tid tar standardleveringen?",
        "danish": "Hvor lang tid tager standardleveringen?",
        "finnish": "Kuinka kauan tavallinen toimitus kestää?",
        "greek": "Πόσο καιρό παίρνει η κανονική παράδοση;",
        "brazilian_portuguese": "Quanto tempo leva a entrega padrão?",
        "mandarin": "标准配送需要多长时间？",
        "japanese": "通常配送はどのくらいかかりますか？",
        "korean": "일반 배송은 얼마나 걸리나요?",
        "hindi": "सामान्य डिलीवरी में कितना समय लगता है?",
        "vietnamese": "Giao hàng tiêu chuẩn mất bao lâu?",
        "arabic": "كم يستغرق التوصيل العادي؟",
    },
    {
        "line_number": 6, "speaker_name": "Mia",
        "english": "Standard takes about seven to ten days. Express is three to five days but it costs more.",
        "lithuanian": "Standartinis užtrunka apie septynis iki dešimties dienų. Ekspresinis — tris iki penkių dienų, bet kainuoja daugiau.",
        "latvian": "Standarta piegāde aizņem aptuveni septiņas līdz desmit dienas. Ekspresa piegāde trīs līdz piecas dienas, bet tas maksā vairāk.",
        "estonian": "Tavaline võtab umbes seitse kuni kümme päeva. Ekspress on kolm kuni viis päeva aga maksab rohkem.",
        "german": "Standard dauert etwa sieben bis zehn Tage. Express ist drei bis fünf Tage kostet aber mehr.",
        "french": "Le standard prend environ sept à dix jours. L'express c'est trois à cinq jours mais ça coûte plus cher.",
        "spanish": "El estándar tarda unos siete a diez días. El express es de tres a cinco días pero cuesta más.",
        "italian": "Lo standard richiede circa sette-dieci giorni. L'express è di tre-cinque giorni ma costa di più.",
        "portuguese": "O normal demora cerca de sete a dez dias. O expresso é de três a cinco dias mas custa mais.",
        "dutch": "Standaard duurt ongeveer zeven tot tien dagen. Express is drie tot vijf dagen maar kost meer.",
        "polish": "Standardowa zajmuje około siedmiu do dziesięciu dni. Ekspresowa to trzy do pięciu dni ale kosztuje więcej.",
        "ukrainian": "Стандартна займає близько семи-десяти днів. Експрес — три-п'ять днів, але коштує більше.",
        "russian": "Стандартная занимает около семи-десяти дней. Экспресс — три-пять дней, но стоит дороже.",
        "swedish": "Standard tar ungefär sju till tio dagar. Express är tre till fem dagar men kostar mer.",
        "norwegian": "Standard tar omtrent syv til ti dager. Express er tre til fem dager men koster mer.",
        "danish": "Standard tager cirka syv til ti dage. Express er tre til fem dage men koster mere.",
        "finnish": "Tavallinen kestää noin seitsemän kymmeneen päivään. Pikatoimitus on kolmesta viiteen päivää mutta maksaa enemmän.",
        "greek": "Η κανονική παράδοση παίρνει περίπου επτά έως δέκα μέρες. Η ταχεία είναι τρεις έως πέντε μέρες αλλά κοστίζει περισσότερο.",
        "brazilian_portuguese": "O padrão leva cerca de sete a dez dias. O expresso é de três a cinco dias mas custa mais.",
        "mandarin": "标准需要大约七到十天。快递三到五天，但费用更高。",
        "japanese": "通常は約七日から十日かかります。エクスプレスは三日から五日ですが費用がかかります。",
        "korean": "일반 배송은 약 7~10일 걸려요. 빠른 배송은 3~5일인데 더 비싸요.",
        "hindi": "सामान्य में लगभग सात से दस दिन लगते हैं। एक्सप्रेस तीन से पाँच दिन होती है लेकिन ज़्यादा महंगी है।",
        "vietnamese": "Giao hàng tiêu chuẩn mất khoảng bảy đến mười ngày. Chuyển phát nhanh ba đến năm ngày nhưng đắt hơn.",
        "arabic": "يستغرق العادي نحو سبعة إلى عشرة أيام. والسريع من ثلاثة إلى خمسة أيام لكنه يكلف أكثر.",
    },
    {
        "line_number": 7, "speaker_name": "Alex",
        "english": "I will choose express please. It is a birthday gift.",
        "lithuanian": "Pasirinkau ekspresą prašau. Tai gimtadienio dovana.",
        "latvian": "Es izvēlēšos ekspresi lūdzu. Tas ir dzimšanas dienas dāvana.",
        "estonian": "Valin ekspressitarne palun. See on sünnipäevakingitus.",
        "german": "Ich wähle Express bitte. Es ist ein Geburtstagsgeschenk.",
        "french": "Je choisis l'express s'il vous plaît. C'est un cadeau d'anniversaire.",
        "spanish": "Elegiré el express por favor. Es un regalo de cumpleaños.",
        "italian": "Scelgo l'express per favore. È un regalo di compleanno.",
        "portuguese": "Escolho o expresso por favor. É um presente de aniversário.",
        "dutch": "Ik kies voor express alstublieft. Het is een verjaardagscadeau.",
        "polish": "Wybieram ekspresową proszę. To prezent urodzinowy.",
        "ukrainian": "Обираю експрес будь ласка. Це подарунок на день народження.",
        "russian": "Я выберу экспресс пожалуйста. Это подарок на день рождения.",
        "swedish": "Jag väljer express tack. Det är en födelsedagspresent.",
        "norwegian": "Jeg velger express takk. Det er en bursdagsgave.",
        "danish": "Jeg vælger express tak. Det er en fødselsdagsgave.",
        "finnish": "Valitsen pikatoimituksen kiitos. Se on syntymäpäivälahja.",
        "greek": "Θα επιλέξω express παρακαλώ. Είναι δώρο γενεθλίων.",
        "brazilian_portuguese": "Vou escolher o expresso por favor. É um presente de aniversário.",
        "mandarin": "我选择快递。这是生日礼物。",
        "japanese": "エクスプレスにします。誕生日プレゼントなので。",
        "korean": "빠른 배송으로 할게요. 생일 선물이거든요.",
        "hindi": "मैं एक्सप्रेस चुनूँगा। यह जन्मदिन का उपहार है।",
        "vietnamese": "Tôi chọn chuyển phát nhanh. Đây là quà sinh nhật.",
        "arabic": "سأختار التوصيل السريع من فضلك. إنها هدية عيد ميلاد.",
    },
    {
        "line_number": 8, "speaker_name": "Mia",
        "english": "That is twelve euros fifty. Do you also need stamps today?",
        "lithuanian": "Tai dvylika eurų penkiasdešimt centų. Ar jums šiandien reikia ir pašto ženklų?",
        "latvian": "Tas ir divpadsmit eiro piecdesmit centi. Vai jums šodien vajag arī pastmarkas?",
        "estonian": "See on kaksteist eurot viiskümmend senti. Kas vajate täna ka marke?",
        "german": "Das sind zwölf Euro fünfzig. Brauchen Sie heute auch Briefmarken?",
        "french": "C'est douze euros cinquante. Avez-vous aussi besoin de timbres aujourd'hui?",
        "spanish": "Son doce euros cincuenta. ¿Necesita también sellos hoy?",
        "italian": "Sono dodici euro e cinquanta. Ha anche bisogno di francobolli oggi?",
        "portuguese": "São doze euros e cinquenta. Também precisa de selos hoje?",
        "dutch": "Dat is twaalf euro vijftig. Heeft u vandaag ook postzegels nodig?",
        "polish": "To dwanaście euro pięćdziesiąt. Czy potrzebuje pan dziś też znaczków?",
        "ukrainian": "Це дванадцять євро п'ятдесят. Вам сьогодні також потрібні марки?",
        "russian": "Это двенадцать евро пятьдесят. Вам также нужны марки сегодня?",
        "swedish": "Det är tolv euro femtio. Behöver du också frimärken idag?",
        "norwegian": "Det er tolv euro femti. Trenger du også frimerker i dag?",
        "danish": "Det er tolv euro halvtreds. Har du også brug for frimærker i dag?",
        "finnish": "Se on kaksitoista euroa viisikymmentä senttiä. Tarvitsetteko myös postimerkkejä tänään?",
        "greek": "Είναι δώδεκα ευρώ και πενήντα. Χρειάζεστε επίσης γραμματόσημα σήμερα;",
        "brazilian_portuguese": "São doze euros e cinquenta. Também precisa de selos hoje?",
        "mandarin": "十二欧元五十分。今天还需要邮票吗？",
        "japanese": "十二ユーロ五十セントです。今日は切手も必要ですか？",
        "korean": "십이 유로 오십 센트입니다. 오늘 우표도 필요하신가요?",
        "hindi": "बारह यूरो पचास सेंट। क्या आज आपको टिकटों की भी ज़रूरत है?",
        "vietnamese": "Mười hai euro năm mươi xu. Hôm nay bạn có cần tem không?",
        "arabic": "الثمن اثنا عشر يورو وخمسون سنتاً. هل تحتاج أيضاً إلى طوابع بريدية اليوم؟",
    },
    {
        "line_number": 9, "speaker_name": "Alex",
        "english": "Yes I need four stamps for letters to the United Kingdom.",
        "lithuanian": "Taip man reikia keturių pašto ženklų laiškams į Jungtinę Karalystę.",
        "latvian": "Jā man vajag četras pastmarkas vēstulēm uz Apvienoto Karalisti.",
        "estonian": "Jah, mul on vaja neli marka Suurbritanniasse minevate kirjade jaoks.",
        "german": "Ja ich brauche vier Briefmarken für Briefe nach Großbritannien.",
        "french": "Oui j'ai besoin de quatre timbres pour des lettres au Royaume-Uni.",
        "spanish": "Sí necesito cuatro sellos para cartas al Reino Unido.",
        "italian": "Sì ho bisogno di quattro francobolli per lettere nel Regno Unito.",
        "portuguese": "Sim preciso de quatro selos para cartas para o Reino Unido.",
        "dutch": "Ja ik heb vier postzegels nodig voor brieven naar het Verenigd Koninkrijk.",
        "polish": "Tak potrzebuję czterech znaczków na listy do Wielkiej Brytanii.",
        "ukrainian": "Так мені потрібні чотири марки для листів до Великої Британії.",
        "russian": "Да мне нужны четыре марки для писем в Великобританию.",
        "swedish": "Ja jag behöver fyra frimärken för brev till Storbritannien.",
        "norwegian": "Ja jeg trenger fire frimerker for brev til Storbritannia.",
        "danish": "Ja jeg har brug for fire frimærker til breve til Storbritannien.",
        "finnish": "Kyllä tarvitsen neljä postimerkkiä Isoon-Britanniaan meneviin kirjeisiin.",
        "greek": "Ναι χρειάζομαι τέσσερα γραμματόσημα για γράμματα στο Ηνωμένο Βασίλειο.",
        "brazilian_portuguese": "Sim preciso de quatro selos para cartas para o Reino Unido.",
        "mandarin": "是的，我需要四张寄往英国的信件邮票。",
        "japanese": "はい、イギリスへの手紙用に切手が四枚必要です。",
        "korean": "네, 영국으로 보내는 편지용 우표가 네 장 필요해요.",
        "hindi": "हाँ, मुझे यूनाइटेड किंगडम को पत्र भेजने के लिए चार टिकट चाहिए।",
        "vietnamese": "Vâng, tôi cần bốn con tem cho thư gửi đến Vương quốc Anh.",
        "arabic": "نعم أحتاج إلى أربعة طوابع لرسائل إلى المملكة المتحدة.",
    },
    {
        "line_number": 10, "speaker_name": "Mia",
        "english": "Here are the stamps. Each one is ninety cents. That is three euros sixty total.",
        "lithuanian": "Štai pašto ženklai. Kiekvienas kainuoja devyniasdešimt centų. Iš viso trys eurai šešiasdešimt.",
        "latvian": "Lūk pastmarkas. Katra ir deviņdesmit centi. Kopā trīs eiro sešdesmit.",
        "estonian": "Siin on margid. Iga mark on üheksakümmend senti. Kokku kolm eurot kuuskümmend.",
        "german": "Hier sind die Briefmarken. Jede kostet neunzig Cent. Das sind insgesamt drei Euro sechzig.",
        "french": "Voici les timbres. Chacun coûte quatre-vingt-dix centimes. Ça fait trois euros soixante en tout.",
        "spanish": "Aquí están los sellos. Cada uno vale noventa céntimos. Son tres euros sesenta en total.",
        "italian": "Ecco i francobolli. Ognuno costa novanta centesimi. Fanno tre euro e sessanta in tutto.",
        "portuguese": "Aqui estão os selos. Cada um custa noventa cêntimos. São três euros e sessenta no total.",
        "dutch": "Hier zijn de postzegels. Elk kost negentig cent. Dat is in totaal drie euro zestig.",
        "polish": "Oto znaczki. Każdy kosztuje dziewięćdziesiąt centów. To razem trzy euro sześćdziesiąt.",
        "ukrainian": "Ось марки. Кожна коштує дев'яносто центів. Разом три євро шістдесят.",
        "russian": "Вот марки. Каждая стоит девяносто центов. Итого три евро шестьдесят.",
        "swedish": "Här är frimärkena. Var och en kostar nittio cent. Det är tre euro sextio totalt.",
        "norwegian": "Her er frimerket. Hvert er nitti cent. Det er tre euro seksti totalt.",
        "danish": "Her er frimærkerne. Hvert koster halvfems øre. Det er i alt tre euro tres.",
        "finnish": "Tässä ovat postimerkit. Jokainen maksaa yhdeksänkymmentä senttiä. Se on kolme euroa kuusikymmentä yhteensä.",
        "greek": "Ορίστε τα γραμματόσημα. Το καθένα κοστίζει ενενήντα λεπτά. Είναι τρία ευρώ εξήντα συνολικά.",
        "brazilian_portuguese": "Aqui estão os selos. Cada um custa noventa centavos. São três euros e sessenta no total.",
        "mandarin": "这是邮票。每张九十分。总共三欧元六十分。",
        "japanese": "こちらが切手です。一枚九十セントです。合計で三ユーロ六十セントです。",
        "korean": "여기 우표입니다. 하나에 구십 센트예요. 총 삼 유로 육십 센트입니다.",
        "hindi": "यह रहे टिकट। प्रत्येक नब्बे सेंट का है। कुल तीन यूरो साठ सेंट।",
        "vietnamese": "Đây là tem. Mỗi cái chín mươi xu. Tổng cộng ba euro sáu mươi xu.",
        "arabic": "هذه الطوابع. كل واحدة بتسعين سنتاً. المجموع ثلاثة يورو وستون سنتاً.",
    },
    {
        "line_number": 11, "speaker_name": "Alex",
        "english": "Can I also buy a padded envelope here?",
        "lithuanian": "Ar galiu čia taip pat nusipirkti voką su apsauga?",
        "latvian": "Vai es šeit varu arī iegādāties polsterētu aploksni?",
        "estonian": "Kas ma saan siit ka polsterdatud ümbriku osta?",
        "german": "Kann ich hier auch einen gepolsterten Umschlag kaufen?",
        "french": "Puis-je aussi acheter une enveloppe matelassée ici?",
        "spanish": "¿Puedo comprar también un sobre acolchado aquí?",
        "italian": "Posso anche comprare una busta imbottita qui?",
        "portuguese": "Posso também comprar um envelope acolchoado aqui?",
        "dutch": "Kan ik hier ook een gewatteerde envelop kopen?",
        "polish": "Czy mogę tu też kupić kopertę bąbelkową?",
        "ukrainian": "Чи можу я також купити тут м'який конверт?",
        "russian": "Могу ли я также купить здесь мягкий конверт?",
        "swedish": "Kan jag också köpa ett stoppat kuvert här?",
        "norwegian": "Kan jeg også kjøpe en polstret konvolutt her?",
        "danish": "Kan jeg også købe en polstret konvolut her?",
        "finnish": "Voinko ostaa täältä myös pehmustetun kirjekuoren?",
        "greek": "Μπορώ επίσης να αγοράσω εδώ ένα επενδυμένο φάκελο;",
        "brazilian_portuguese": "Posso também comprar um envelope acolchoado aqui?",
        "mandarin": "我也可以在这里买气泡信封吗？",
        "japanese": "ここでクッション封筒も買えますか？",
        "korean": "여기서 버블 봉투도 살 수 있나요?",
        "hindi": "क्या मैं यहाँ एक पैडेड लिफाफा भी खरीद सकता हूँ?",
        "vietnamese": "Tôi có thể mua phong bì có lớp đệm ở đây không?",
        "arabic": "هل يمكنني أيضاً شراء مظروف مبطن هنا؟",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "Yes we have small medium and large sizes. Which do you need?",
        "lithuanian": "Taip turime mažą vidutinį ir didelį dydžius. Kokio jums reikia?",
        "latvian": "Jā mums ir mazs vidējs un liels izmērs. Kādu jums vajag?",
        "estonian": "Jah meil on väike keskmise ja suur suurus. Millist vajate?",
        "german": "Ja wir haben kleine mittlere und große Größen. Welche brauchen Sie?",
        "french": "Oui nous avons des tailles petites moyennes et grandes. Laquelle vous faut-il?",
        "spanish": "Sí tenemos tamaños pequeño mediano y grande. ¿Cuál necesita?",
        "italian": "Sì abbiamo taglie piccole medie e grandi. Quale le serve?",
        "portuguese": "Sim temos tamanhos pequeno médio e grande. Qual precisa?",
        "dutch": "Ja we hebben kleine middelgrote en grote maten. Welke heeft u nodig?",
        "polish": "Tak mamy rozmiary małe średnie i duże. Którego pan potrzebuje?",
        "ukrainian": "Так у нас є малий середній та великий розміри. Який вам потрібен?",
        "russian": "Да у нас есть маленький средний и большой размеры. Какой вам нужен?",
        "swedish": "Ja vi har liten medelstor och stor storlek. Vilken behöver du?",
        "norwegian": "Ja vi har liten middels og stor størrelse. Hvilken trenger du?",
        "danish": "Ja vi har lille medium og stor størrelse. Hvilken har du brug for?",
        "finnish": "Kyllä meillä on pieniä keskikokoisia ja suuria. Mitä kokoa tarvitsette?",
        "greek": "Ναι έχουμε μικρά μεσαία και μεγάλα μεγέθη. Ποιο χρειάζεστε;",
        "brazilian_portuguese": "Sim temos tamanhos pequeno médio e grande. Qual você precisa?",
        "mandarin": "是的，我们有小号、中号和大号。您需要哪种？",
        "japanese": "はい、小中大のサイズがございます。どれが必要ですか？",
        "korean": "네, 소중대 사이즈가 있어요. 어떤 사이즈가 필요하세요?",
        "hindi": "हाँ, हमारे पास छोटे, मध्यम और बड़े आकार हैं। आपको कौन सा चाहिए?",
        "vietnamese": "Vâng, chúng tôi có cỡ nhỏ, vừa và lớn. Bạn cần cỡ nào?",
        "arabic": "نعم لدينا أحجام صغيرة ومتوسطة وكبيرة. أيها تحتاج؟",
    },
    {
        "line_number": 13, "speaker_name": "Alex",
        "english": "A medium one please. How much is it?",
        "lithuanian": "Vidutinį prašau. Kiek kainuoja?",
        "latvian": "Vidējo lūdzu. Cik tas maksā?",
        "estonian": "Keskmist palun. Kui palju see maksab?",
        "german": "Einen mittleren bitte. Wie viel kostet er?",
        "french": "Un moyen s'il vous plaît. Combien ça coûte?",
        "spanish": "Uno mediano por favor. ¿Cuánto cuesta?",
        "italian": "Uno medio per favore. Quanto costa?",
        "portuguese": "Um médio por favor. Quanto custa?",
        "dutch": "Een middelgrote alstublieft. Hoeveel kost die?",
        "polish": "Średni proszę. Ile kosztuje?",
        "ukrainian": "Середній будь ласка. Скільки він коштує?",
        "russian": "Средний пожалуйста. Сколько он стоит?",
        "swedish": "En mellanstor tack. Hur mycket kostar den?",
        "norwegian": "En medium takk. Hvor mye koster den?",
        "danish": "En medium tak. Hvor meget koster den?",
        "finnish": "Keskikokoinen kiitos. Kuinka paljon se maksaa?",
        "greek": "Ένα μεσαίο παρακαλώ. Πόσο κοστίζει;",
        "brazilian_portuguese": "Um médio por favor. Quanto custa?",
        "mandarin": "中号的。多少钱？",
        "japanese": "中サイズをください。いくらですか？",
        "korean": "중간 사이즈로 주세요. 얼마예요?",
        "hindi": "मध्यम वाला दीजिए। कितने का है?",
        "vietnamese": "Cỡ vừa. Bao nhiêu tiền?",
        "arabic": "متوسط من فضلك. كم سعره؟",
    },
    {
        "line_number": 14, "speaker_name": "Mia",
        "english": "One euro twenty. So your total today is sixteen euros thirty.",
        "lithuanian": "Vienas euras dvidešimt centų. Taigi jūsų bendra suma šiandien yra šešiolika eurų trisdešimt.",
        "latvian": "Viens eiro divdesmit centi. Tātad jūsu kopējā summa šodien ir sešpadsmit eiro trīsdesmit.",
        "estonian": "Üks euro kakskümmend senti. Seega on teie tänane kogu summa kuusteist eurot kolmkümmend.",
        "german": "Einen Euro zwanzig. Ihr heutiger Gesamtbetrag beträgt also sechzehn Euro dreißig.",
        "french": "Un euro vingt. Donc votre total d'aujourd'hui est seize euros trente.",
        "spanish": "Un euro veinte. Entonces su total de hoy es dieciséis euros treinta.",
        "italian": "Un euro e venti. Quindi il suo totale di oggi è sedici euro e trenta.",
        "portuguese": "Um euro e vinte. Portanto o seu total hoje é dezasseis euros e trinta.",
        "dutch": "Één euro twintig. Uw totaal van vandaag is dus zestien euro dertig.",
        "polish": "Jedno euro dwadzieścia. Pana dzisiejsza suma to szesnaście euro trzydzieści.",
        "ukrainian": "Одне євро двадцять. Тож ваша загальна сума сьогодні — шістнадцять євро тридцять.",
        "russian": "Один евро двадцать. Ваш итоговый счёт сегодня — шестнадцать евро тридцать.",
        "swedish": "En euro tjugo. Så ditt totala belopp idag är sexton euro trettio.",
        "norwegian": "En euro tjue. Så din totale sum i dag er seksten euro tretti.",
        "danish": "En euro tyve. Så din samlede total i dag er seksten euro tredive.",
        "finnish": "Yksi euro kaksikymmentä senttiä. Tänään maksettavanne on siis kuusitoista euroa kolmekymmentä.",
        "greek": "Ένα ευρώ είκοσι. Άρα το συνολικό σας ποσό σήμερα είναι δεκαέξι ευρώ τριάντα.",
        "brazilian_portuguese": "Um euro e vinte. Então o seu total hoje é dezesseis euros e trinta.",
        "mandarin": "一欧元二十分。所以您今天的总计是十六欧元三十分。",
        "japanese": "一ユーロ二十セントです。本日の合計は十六ユーロ三十セントです。",
        "korean": "일 유로 이십 센트예요. 오늘 총 십육 유로 삼십 센트입니다.",
        "hindi": "एक यूरो बीस सेंट। तो आज का कुल सोलह यूरो तीस सेंट है।",
        "vietnamese": "Một euro hai mươi xu. Vậy tổng của bạn hôm nay là mười sáu euro ba mươi xu.",
        "arabic": "يورو واحد وعشرون سنتاً. إذن مجموعك اليوم هو ستة عشر يورو وثلاثون سنتاً.",
    },
    {
        "line_number": 15, "speaker_name": "Alex",
        "english": "Here is twenty euros.",
        "lithuanian": "Štai dvidešimt eurų.",
        "latvian": "Lūk divdesmit eiro.",
        "estonian": "Siin on kakskümmend eurot.",
        "german": "Hier sind zwanzig Euro.",
        "french": "Voici vingt euros.",
        "spanish": "Aquí tiene veinte euros.",
        "italian": "Ecco venti euro.",
        "portuguese": "Aqui estão vinte euros.",
        "dutch": "Hier zijn twintig euro.",
        "polish": "Oto dwadzieścia euro.",
        "ukrainian": "Ось двадцять євро.",
        "russian": "Вот двадцать евро.",
        "swedish": "Här är tjugo euro.",
        "norwegian": "Her er tjue euro.",
        "danish": "Her er tyve euro.",
        "finnish": "Tässä on kaksikymmentä euroa.",
        "greek": "Ορίστε είκοσι ευρώ.",
        "brazilian_portuguese": "Aqui estão vinte euros.",
        "mandarin": "这是二十欧元。",
        "japanese": "二十ユーロです。",
        "korean": "이십 유로 여기요.",
        "hindi": "यह लीजिए बीस यूरो।",
        "vietnamese": "Đây là hai mươi euro.",
        "arabic": "هذه عشرون يورو.",
    },
    {
        "line_number": 16, "speaker_name": "Mia",
        "english": "Your change is three euros seventy. Here is your receipt.",
        "lithuanian": "Jūsų grąža yra trys eurai septyniasdešimt. Štai jūsų kvitas.",
        "latvian": "Jūsu atlikums ir trīs eiro septiņdesmit. Lūk jūsu čeks.",
        "estonian": "Teie vahetus on kolm eurot seitsekümmend. Siin on teie kviitung.",
        "german": "Ihr Wechselgeld beträgt drei Euro siebzig. Hier ist Ihre Quittung.",
        "french": "Votre monnaie est trois euros soixante-dix. Voici votre reçu.",
        "spanish": "Su cambio es tres euros setenta. Aquí tiene su recibo.",
        "italian": "Il suo resto è tre euro e settanta. Ecco la sua ricevuta.",
        "portuguese": "O seu troco é três euros e setenta. Aqui está o seu recibo.",
        "dutch": "Uw wisselgeld is drie euro zeventig. Hier is uw bon.",
        "polish": "Reszta to trzy euro siedemdziesiąt. Oto pana paragon.",
        "ukrainian": "Ваша решта три євро сімдесят. Ось ваша квитанція.",
        "russian": "Ваша сдача три евро семьдесят. Вот ваш чек.",
        "swedish": "Din växel är tre euro sjuttio. Här är ditt kvitto.",
        "norwegian": "Din veksel er tre euro sytti. Her er kvitteringen din.",
        "danish": "Din byttepenge er tre euro halvfjerds. Her er din kvittering.",
        "finnish": "Vaihtorahasi on kolme euroa seitsemänkymmentä senttiä. Tässä on kuittisi.",
        "greek": "Τα ρέστα σας είναι τρία ευρώ εβδομήντα. Ορίστε η απόδειξή σας.",
        "brazilian_portuguese": "Seu troco é três euros e setenta. Aqui está o seu recibo.",
        "mandarin": "找您三欧元七十分。这是您的收据。",
        "japanese": "お釣りは三ユーロ七十セントです。レシートです。",
        "korean": "거스름돈 삼 유로 칠십 센트입니다. 영수증 여기 있어요.",
        "hindi": "आपकी बाकी राशि तीन यूरो सत्तर सेंट है। यह रहा आपका रसीद।",
        "vietnamese": "Tiền thối lại ba euro bảy mươi xu. Đây là biên lai của bạn.",
        "arabic": "باقي مالك ثلاثة يورو وسبعون سنتاً. هذا إيصالك.",
    },
    {
        "line_number": 17, "speaker_name": "Alex",
        "english": "Can I track my package online?",
        "lithuanian": "Ar galiu sekti savo paketą internetu?",
        "latvian": "Vai es varu izsekot savu paketi tiešsaistē?",
        "estonian": "Kas ma saan oma paketti veebis jälgida?",
        "german": "Kann ich mein Paket online verfolgen?",
        "french": "Puis-je suivre mon colis en ligne?",
        "spanish": "¿Puedo rastrear mi paquete en línea?",
        "italian": "Posso tracciare il mio pacco online?",
        "portuguese": "Posso rastrear o meu pacote online?",
        "dutch": "Kan ik mijn pakket online volgen?",
        "polish": "Czy mogę śledzić moją paczkę online?",
        "ukrainian": "Чи можу я відстежити свою посилку онлайн?",
        "russian": "Могу ли я отслеживать свою посылку онлайн?",
        "swedish": "Kan jag spåra mitt paket online?",
        "norwegian": "Kan jeg spore pakken min på nettet?",
        "danish": "Kan jeg spore min pakke online?",
        "finnish": "Voinko seurata pakettiaan verkossa?",
        "greek": "Μπορώ να παρακολουθώ το δέμα μου διαδικτυακά;",
        "brazilian_portuguese": "Posso rastrear meu pacote online?",
        "mandarin": "我可以在网上追踪我的包裹吗？",
        "japanese": "荷物をオンラインで追跡できますか？",
        "korean": "온라인으로 소포를 추적할 수 있나요?",
        "hindi": "क्या मैं अपना पैकेज ऑनलाइन ट्रैक कर सकता हूँ?",
        "vietnamese": "Tôi có thể theo dõi gói hàng của mình trực tuyến không?",
        "arabic": "هل يمكنني تتبع طردي عبر الإنترنت؟",
    },
    {
        "line_number": 18, "speaker_name": "Mia",
        "english": "Yes. Your tracking number is on the receipt. Use our website to check.",
        "lithuanian": "Taip. Jūsų sekimo numeris yra ant kvito. Naudokite mūsų svetainę patikrinti.",
        "latvian": "Jā. Jūsu izsekošanas numurs ir uz čeka. Izmantojiet mūsu vietni, lai pārbaudītu.",
        "estonian": "Jah. Teie jälgimisnumber on kviitungil. Kasutage kontrollimiseks meie veebisaiti.",
        "german": "Ja. Ihre Sendungsnummer steht auf der Quittung. Nutzen Sie unsere Website zur Überprüfung.",
        "french": "Oui. Votre numéro de suivi est sur le reçu. Utilisez notre site web pour vérifier.",
        "spanish": "Sí. Su número de rastreo está en el recibo. Use nuestro sitio web para comprobar.",
        "italian": "Sì. Il suo numero di tracciamento è sulla ricevuta. Usi il nostro sito web per controllare.",
        "portuguese": "Sim. O seu número de rastreamento está no recibo. Use o nosso website para verificar.",
        "dutch": "Ja. Uw trackingnummer staat op de bon. Gebruik onze website om te controleren.",
        "polish": "Tak. Numer śledzenia jest na paragonie. Użyj naszej strony internetowej aby sprawdzić.",
        "ukrainian": "Так. Ваш номер відстеження є на квитанції. Використайте наш сайт для перевірки.",
        "russian": "Да. Ваш номер отслеживания указан на чеке. Используйте наш сайт для проверки.",
        "swedish": "Ja. Ditt spårningsnummer finns på kvittot. Använd vår webbplats för att kontrollera.",
        "norwegian": "Ja. Sporingsnummeret ditt er på kvitteringen. Bruk nettsiden vår for å sjekke.",
        "danish": "Ja. Dit sporingsnummer er på kvitteringen. Brug vores hjemmeside til at tjekke.",
        "finnish": "Kyllä. Seurantanumerosi on kuitissa. Käytä verkkosivustoamme tarkistaaksesi.",
        "greek": "Ναι. Ο αριθμός παρακολούθησής σας βρίσκεται στην απόδειξη. Χρησιμοποιήστε την ιστοσελίδα μας για έλεγχο.",
        "brazilian_portuguese": "Sim. Seu número de rastreamento está no recibo. Use nosso site para verificar.",
        "mandarin": "是的。您的追踪号码在收据上。使用我们的网站查询。",
        "japanese": "はい。追跡番号はレシートに記載されています。当社ウェブサイトでご確認ください。",
        "korean": "네. 추적 번호는 영수증에 있어요. 저희 웹사이트에서 확인하세요.",
        "hindi": "हाँ। आपका ट्रैकिंग नंबर रसीद पर है। जाँच के लिए हमारी वेबसाइट का उपयोग करें।",
        "vietnamese": "Vâng. Số theo dõi của bạn ở trên biên lai. Sử dụng trang web của chúng tôi để kiểm tra.",
        "arabic": "نعم. رقم التتبع الخاص بك على الإيصال. استخدم موقعنا للتحقق.",
    },
    {
        "line_number": 19, "speaker_name": "Alex",
        "english": "What are your opening hours?",
        "lithuanian": "Kokie jūsų darbo laikas?",
        "latvian": "Kāds ir jūsu darba laiks?",
        "estonian": "Millised on teie lahtiolekuajad?",
        "german": "Was sind Ihre Öffnungszeiten?",
        "french": "Quelles sont vos heures d'ouverture?",
        "spanish": "¿Cuál es su horario de apertura?",
        "italian": "Quali sono i vostri orari di apertura?",
        "portuguese": "Quais são os seus horários de abertura?",
        "dutch": "Wat zijn uw openingstijden?",
        "polish": "Jakie są godziny otwarcia?",
        "ukrainian": "Які у вас години роботи?",
        "russian": "Каковы ваши часы работы?",
        "swedish": "Vilka är era öppettider?",
        "norwegian": "Hva er åpningstidene deres?",
        "danish": "Hvad er jeres åbningstider?",
        "finnish": "Mitkä ovat aukioloaikanne?",
        "greek": "Ποιες είναι οι ώρες λειτουργίας σας;",
        "brazilian_portuguese": "Quais são os horários de funcionamento?",
        "mandarin": "你们的营业时间是什么？",
        "japanese": "営業時間はいつですか？",
        "korean": "영업 시간이 어떻게 되나요?",
        "hindi": "आपके खुलने के समय क्या हैं?",
        "vietnamese": "Giờ mở cửa của bạn là gì?",
        "arabic": "ما هي ساعات عملكم؟",
    },
    {
        "line_number": 20, "speaker_name": "Mia",
        "english": "We are open Monday to Friday from eight to six and Saturday from nine to one. We are closed on Sunday. Have a good day!",
        "lithuanian": "Dirbame nuo pirmadienio iki penktadienio nuo aštuonių iki šešių ir šeštadienį nuo devynių iki vieno. Sekmadieniais nedirbame. Geros dienos!",
        "latvian": "Mēs esam atvērti no pirmdienas līdz piektdienai no astoņiem līdz sešiem un sestdienā no deviņiem līdz vienam. Svētdien esam slēgti. Labu dienu!",
        "estonian": "Oleme avatud esmaspäevast reedeni kaheksast kuueni ja laupäeval üheksast üheni. Pühapäeval oleme suletud. Ilusat päeva!",
        "german": "Wir haben Montag bis Freitag von acht bis sechs Uhr geöffnet und Samstag von neun bis eins. Sonntags sind wir geschlossen. Einen schönen Tag!",
        "french": "Nous sommes ouverts du lundi au vendredi de huit heures à dix-huit heures et le samedi de neuf heures à treize heures. Nous sommes fermés le dimanche. Bonne journée!",
        "spanish": "Estamos abiertos de lunes a viernes de ocho a seis y el sábado de nueve a uno. Los domingos estamos cerrados. ¡Que tenga un buen día!",
        "italian": "Siamo aperti dal lunedì al venerdì dalle otto alle sei e il sabato dalle nove all'una. La domenica siamo chiusi. Buona giornata!",
        "portuguese": "Estamos abertos de segunda a sexta das oito às seis e ao sábado das nove à uma. Ao domingo estamos fechados. Tenha um bom dia!",
        "dutch": "We zijn open maandag tot vrijdag van acht tot zes en zaterdag van negen tot één. Zondag zijn we gesloten. Prettige dag!",
        "polish": "Jesteśmy otwarci od poniedziałku do piątku od ósmej do szóstej i w sobotę od dziewiątej do pierwszej. W niedzielę jesteśmy zamknięci. Miłego dnia!",
        "ukrainian": "Ми відкриті з понеділка по п'ятницю з восьмої до шостої і в суботу з дев'ятої до першої. В неділю ми зачинені. Гарного дня!",
        "russian": "Мы работаем с понедельника по пятницу с восьми до шести и в субботу с девяти до часу. В воскресенье мы закрыты. Хорошего дня!",
        "swedish": "Vi är öppna måndag till fredag från åtta till sex och lördag från nio till ett. Vi är stängda på söndag. Ha en bra dag!",
        "norwegian": "Vi er åpne mandag til fredag fra åtte til seks og lørdag fra ni til ett. Vi er stengt på søndag. Ha en fin dag!",
        "danish": "Vi er åbne mandag til fredag fra otte til seks og lørdag fra ni til et. Vi er lukket om søndagen. Hav en god dag!",
        "finnish": "Olemme auki maanantaista perjantaihin kahdeksasta kuuteen ja lauantaisin yhdeksästä yhteen. Sunnuntaisin olemme suljettu. Hyvää päivää!",
        "greek": "Είμαστε ανοιχτοί Δευτέρα έως Παρασκευή από τις οκτώ έως τις έξι και Σάββατο από τις εννέα έως τη μία. Κυριακή είμαστε κλειστοί. Καλή σας μέρα!",
        "brazilian_portuguese": "Estamos abertos de segunda a sexta das oito às seis e no sábado das nove à uma. No domingo estamos fechados. Tenha um bom dia!",
        "mandarin": "我们周一到周五早八点到下午六点开放，周六早九点到下午一点。周日休息。祝您有美好的一天！",
        "japanese": "月曜から金曜は八時から六時まで、土曜は九時から一時まで営業しています。日曜は休業です。よい一日を！",
        "korean": "월요일부터 금요일은 여덟 시부터 여섯 시까지, 토요일은 아홉 시부터 한 시까지 영업합니다. 일요일은 휴무예요. 좋은 하루 되세요!",
        "hindi": "हम सोमवार से शुक्रवार आठ से छह बजे तक और शनिवार को नौ से एक बजे तक खुले रहते हैं। रविवार को बंद रहते हैं। आपका दिन शुभ हो!",
        "vietnamese": "Chúng tôi mở cửa từ thứ hai đến thứ sáu từ tám giờ đến sáu giờ và thứ bảy từ chín giờ đến một giờ. Chủ nhật đóng cửa. Chúc bạn một ngày tốt lành!",
        "arabic": "نفتح من الاثنين إلى الجمعة من الثامنة حتى السادسة ومن التاسعة حتى الواحدة يوم السبت. نغلق يوم الأحد. أتمنى لك يوماً سعيداً!",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="At the Post Office").first()
        if existing:
            print("A2 dialogue 'At the Post Office' already exists — skipping.")
            return

        dialogue = Dialogue(topic="At the Post Office", lang_level="A2", length=20)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded A2 dialogue ID {dialogue.id} — 20 lines in 25 languages.")


if __name__ == '__main__':
    seed()
