import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "I am planning a trip to Japan next spring. Have you ever been there?",
        "lithuanian": "Planuoju kelionę į Japoniją kitą pavasarį. Ar tu ten buvai?",
        "latvian": "Es plānoju ceļojumu uz Japānu nākamajā pavasarī. Vai tu tur esi bijis?",
        "estonian": "Planeerin reisi Jaapanisse järgmisel kevadel. Kas sa oled seal olnud?",
        "german": "Ich plane eine Reise nach Japan im nächsten Frühling. Warst du jemals dort?",
        "french": "Je planifie un voyage au Japon le printemps prochain. Tu y es déjà allé?",
        "spanish": "Estoy planeando un viaje a Japón la próxima primavera. ¿Has estado alguna vez allí?",
        "italian": "Sto pianificando un viaggio in Giappone la prossima primavera. Ci sei mai stato?",
        "portuguese": "Estou a planear uma viagem ao Japão na próxima primavera. Já lá estiveste?",
        "dutch": "Ik plan een reis naar Japan volgend voorjaar. Ben jij er ooit geweest?",
        "polish": "Planuję wycieczkę do Japonii następnej wiosny. Czy byłeś tam kiedyś?",
        "ukrainian": "Я планую поїздку до Японії наступної весни. Ти там коли-небудь бував?",
        "russian": "Я планирую поездку в Японию следующей весной. Ты когда-нибудь там бывал?",
        "swedish": "Jag planerar en resa till Japan nästa vår. Har du någonsin varit där?",
        "norwegian": "Jeg planlegger en tur til Japan neste vår. Har du noen gang vært der?",
        "danish": "Jeg planlægger en tur til Japan næste forår. Har du nogensinde været der?",
        "finnish": "Suunnittelen matkaa Japaniin ensi keväänä. Oletko koskaan ollut siellä?",
        "greek": "Σχεδιάζω ταξίδι στην Ιαπωνία την επόμενη άνοιξη. Έχεις πάει ποτέ εκεί;",
        "brazilian_portuguese": "Estou planejando uma viagem ao Japão na próxima primavera. Você já foi lá?",
        "mandarin": "我计划明年春天去日本旅行。你去过那里吗？",
        "japanese": "来年の春に日本旅行を計画しています。行ったことがありますか？",
        "korean": "저는 내년 봄에 일본 여행을 계획하고 있어요. 거기 가본 적 있나요?",
        "hindi": "मैं अगले वसंत में जापान की यात्रा की योजना बना रहा हूँ। क्या तुम वहाँ कभी गए हो?",
        "vietnamese": "Tôi đang lên kế hoạch đi Nhật Bản vào mùa xuân năm sau. Bạn đã từng đến đó chưa?",
        "arabic": "أخطط لرحلة إلى اليابان في الربيع القادم. هل زرتها من قبل؟",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "Yes I went two years ago. It was one of the best trips of my life.",
        "lithuanian": "Taip, buvau prieš dvejus metus. Tai buvo viena geriausių mano gyvenimo kelionių.",
        "latvian": "Jā, es braucu pirms diviem gadiem. Tā bija viena no labākajām manā dzīvē.",
        "estonian": "Jah, käisin seal kaks aastat tagasi. See oli üks parimaid reise minu elus.",
        "german": "Ja, ich war vor zwei Jahren dort. Es war eine der besten Reisen meines Lebens.",
        "french": "Oui j'y suis allé il y a deux ans. C'était l'un des meilleurs voyages de ma vie.",
        "spanish": "Sí fui hace dos años. Fue uno de los mejores viajes de mi vida.",
        "italian": "Sì ci sono andato due anni fa. È stato uno dei migliori viaggi della mia vita.",
        "portuguese": "Sim fui há dois anos. Foi uma das melhores viagens da minha vida.",
        "dutch": "Ja ik ging twee jaar geleden. Het was een van de beste reizen van mijn leven.",
        "polish": "Tak byłem dwa lata temu. To była jedna z najlepszych podróży w moim życiu.",
        "ukrainian": "Так, я їздив два роки тому. Це була одна з найкращих подорожей мого життя.",
        "russian": "Да, я ездил два года назад. Это было одно из лучших путешествий в моей жизни.",
        "swedish": "Ja jag åkte för två år sedan. Det var en av de bästa resorna i mitt liv.",
        "norwegian": "Ja jeg dro for to år siden. Det var en av de beste turene i mitt liv.",
        "danish": "Ja jeg tog derover for to år siden. Det var en af de bedste rejser i mit liv.",
        "finnish": "Kyllä, kävin siellä kaksi vuotta sitten. Se oli yksi elämäni parhaista matkoista.",
        "greek": "Ναι πήγα πριν δύο χρόνια. Ήταν ένα από τα καλύτερα ταξίδια της ζωής μου.",
        "brazilian_portuguese": "Sim fui há dois anos. Foi uma das melhores viagens da minha vida.",
        "mandarin": "是的，我两年前去了。那是我生命中最好的旅行之一。",
        "japanese": "はい、二年前に行きました。人生で最高の旅行の一つでした。",
        "korean": "네, 2년 전에 갔었어요. 제 인생 최고의 여행 중 하나였어요.",
        "hindi": "हाँ, मैं दो साल पहले गया था। यह मेरे जीवन की सबसे अच्छी यात्राओं में से एक थी।",
        "vietnamese": "Vâng, tôi đã đi hai năm trước. Đó là một trong những chuyến đi tuyệt vời nhất cuộc đời tôi.",
        "arabic": "نعم ذهبت قبل عامين. كانت من أفضل رحلات حياتي.",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "What was your favourite part of the trip?",
        "lithuanian": "Kuri kelionės dalis patiko labiausiai?",
        "latvian": "Kura bija tava iecienītākā daļa no ceļojuma?",
        "estonian": "Mis oli sinu lemmik osa reisist?",
        "german": "Was war dein Lieblingsteil der Reise?",
        "french": "Quelle était ta partie préférée du voyage?",
        "spanish": "¿Cuál fue tu parte favorita del viaje?",
        "italian": "Qual era la tua parte preferita del viaggio?",
        "portuguese": "Qual foi a tua parte favorita da viagem?",
        "dutch": "Wat was jouw favoriete deel van de reis?",
        "polish": "Która część podróży była twoją ulubioną?",
        "ukrainian": "Яка була твоя улюблена частина подорожі?",
        "russian": "Какая была твоя любимая часть поездки?",
        "swedish": "Vilken var din favoritdel av resan?",
        "norwegian": "Hva var din favorittdel av turen?",
        "danish": "Hvad var din favoritdel af rejsen?",
        "finnish": "Mikä oli matkan lempiosa?",
        "greek": "Ποιο ήταν το αγαπημένο σου μέρος του ταξιδιού;",
        "brazilian_portuguese": "Qual foi a sua parte favorita da viagem?",
        "mandarin": "旅行中你最喜欢的部分是什么？",
        "japanese": "旅行でどの部分が一番好きでしたか？",
        "korean": "여행에서 가장 좋았던 부분이 뭐였나요?",
        "hindi": "यात्रा का आपका सबसे पसंदीदा हिस्सा कौन सा था?",
        "vietnamese": "Phần yêu thích nhất của chuyến đi của bạn là gì?",
        "arabic": "ما كان الجزء المفضل لديك في الرحلة؟",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "Kyoto was incredible. The temples and gardens are beautiful and very peaceful.",
        "lithuanian": "Kioto buvo nuostabios. Šventyklos ir sodai yra gražūs ir labai ramūs.",
        "latvian": "Kioto bija neticama. Tempļi un dārzi ir skaisti un ļoti mierīgi.",
        "estonian": "Kyoto oli hämmastav. Templid ja aiad on ilusad ja väga rahulikud.",
        "german": "Kyoto war unglaublich. Die Tempel und Gärten sind wunderschön und sehr friedlich.",
        "french": "Kyoto était incroyable. Les temples et les jardins sont magnifiques et très paisibles.",
        "spanish": "Kioto era increíble. Los templos y jardines son hermosos y muy tranquilos.",
        "italian": "Kyoto era incredibile. I templi e i giardini sono bellissimi e molto tranquilli.",
        "portuguese": "Kyoto era incrível. Os templos e jardins são bonitos e muito tranquilos.",
        "dutch": "Kyoto was ongelooflijk. De tempels en tuinen zijn prachtig en erg vredig.",
        "polish": "Kioto było niesamowite. Świątynie i ogrody są piękne i bardzo spokojne.",
        "ukrainian": "Кіото було неймовірним. Храми і сади прекрасні та дуже спокійні.",
        "russian": "Киото было невероятным. Храмы и сады прекрасны и очень умиротворены.",
        "swedish": "Kyoto var otroligt. Templen och trädgårdarna är vackra och mycket fridfullt.",
        "norwegian": "Kyoto var utrolig. Templene og hagene er vakre og veldig fredelige.",
        "danish": "Kyoto var utroligt. Templerne og haverne er smukke og meget fredelige.",
        "finnish": "Kyoto oli uskomaton. Temppelit ja puutarhat ovat kauniita ja hyvin rauhallisia.",
        "greek": "Το Κιότο ήταν απίστευτο. Οι ναοί και οι κήποι είναι υπέροχοι και πολύ ήρεμοι.",
        "brazilian_portuguese": "Kyoto era incrível. Os templos e jardins são lindos e muito tranquilos.",
        "mandarin": "京都太令人难以置信了。寺庙和花园非常美丽，非常宁静。",
        "japanese": "京都は素晴らしかった。お寺と庭園が美しくてとても穏やかです。",
        "korean": "교토는 정말 놀라웠어요. 사원과 정원이 아름답고 매우 평화로웠어요.",
        "hindi": "क्योटो अविश्वसनीय था। मंदिर और बगीचे सुंदर और बहुत शांत हैं।",
        "vietnamese": "Kyoto thật tuyệt vời. Các đền chùa và khu vườn đẹp và rất thanh bình.",
        "arabic": "كيوتو كانت رائعة. المعابد والحدائق جميلة وهادئة جداً.",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "How many weeks did you stay in Japan?",
        "lithuanian": "Kiek savaičių praleidai Japonijoje?",
        "latvian": "Cik nedēļas tu uzturējies Japānā?",
        "estonian": "Mitu nädalat sa Jaapanis viibisid?",
        "german": "Wie viele Wochen bist du in Japan geblieben?",
        "french": "Combien de semaines es-tu resté au Japon?",
        "spanish": "¿Cuántas semanas estuviste en Japón?",
        "italian": "Quante settimane sei rimasto in Giappone?",
        "portuguese": "Quantas semanas ficaste no Japão?",
        "dutch": "Hoeveel weken ben je in Japan gebleven?",
        "polish": "Ile tygodni spędziłeś w Japonii?",
        "ukrainian": "Скільки тижнів ти пробув у Японії?",
        "russian": "Сколько недель ты провёл в Японии?",
        "swedish": "Hur många veckor stannade du i Japan?",
        "norwegian": "Hvor mange uker ble du i Japan?",
        "danish": "Hvor mange uger var du i Japan?",
        "finnish": "Kuinka monta viikkoa olit Japanissa?",
        "greek": "Πόσες εβδομάδες έμεινες στην Ιαπωνία;",
        "brazilian_portuguese": "Quantas semanas você ficou no Japão?",
        "mandarin": "你在日本待了几个星期？",
        "japanese": "日本に何週間滞在しましたか？",
        "korean": "일본에 몇 주 동안 있었나요?",
        "hindi": "तुमने जापान में कितने हफ्ते बिताए?",
        "vietnamese": "Bạn ở Nhật Bản bao nhiêu tuần?",
        "arabic": "كم أسبوعاً قضيت في اليابان؟",
    },
    {
        "line_number": 6, "speaker_name": "Mia",
        "english": "Three weeks. I visited Tokyo, Kyoto, Osaka and a few smaller towns.",
        "lithuanian": "Tris savaites. Aplankiau Tokiją, Kiotą, Osakę ir kelis mažesnius miestus.",
        "latvian": "Trīs nedēļas. Es apmeklēju Tokiju, Kjoto, Osaku un dažas mazākas pilsētas.",
        "estonian": "Kolm nädalat. Külastasin Tokyot, Kyotot, Osakas ja mõnda väiksemat linna.",
        "german": "Drei Wochen. Ich besuchte Tokio, Kyoto, Osaka und ein paar kleinere Städte.",
        "french": "Trois semaines. J'ai visité Tokyo Kyoto Osaka et quelques petites villes.",
        "spanish": "Tres semanas. Visité Tokio Kioto Osaka y algunos pueblos más pequeños.",
        "italian": "Tre settimane. Ho visitato Tokyo Kyoto Osaka e alcune città più piccole.",
        "portuguese": "Três semanas. Visitei Tóquio, Quioto, Osaka e algumas cidades mais pequenas.",
        "dutch": "Drie weken. Ik bezocht Tokio, Kyoto, Osaka en een paar kleinere steden.",
        "polish": "Trzy tygodnie. Odwiedziłem Tokio, Kioto, Osakę i kilka mniejszych miast.",
        "ukrainian": "Три тижні. Я відвідав Токіо, Кіото, Осаку та кілька менших міст.",
        "russian": "Три недели. Я посетил Токио, Киото, Осаку и несколько небольших городов.",
        "swedish": "Tre veckor. Jag besökte Tokyo, Kyoto, Osaka och några mindre städer.",
        "norwegian": "Tre uker. Jeg besøkte Tokyo, Kyoto, Osaka og noen mindre byer.",
        "danish": "Tre uger. Jeg besøgte Tokyo, Kyoto, Osaka og nogle mindre byer.",
        "finnish": "Kolme viikkoa. Kävin Tokiossa, Kiotossa, Osakassa ja muutamassa pienemmässä kaupungissa.",
        "greek": "Τρεις εβδομάδες. Επισκέφθηκα το Τόκιο, το Κιότο, την Οσάκα και μερικές μικρότερες πόλεις.",
        "brazilian_portuguese": "Três semanas. Visitei Tóquio, Kyoto, Osaka e algumas cidades menores.",
        "mandarin": "三个星期。我游览了东京、京都、大阪和几个小城镇。",
        "japanese": "三週間です。東京、京都、大阪といくつかの小さな町を訪れました。",
        "korean": "3주요. 도쿄, 교토, 오사카, 그리고 몇 개의 작은 마을을 방문했어요.",
        "hindi": "तीन हफ्ते। मैंने टोक्यो, क्योटो, ओसाका और कुछ छोटे शहरों का दौरा किया।",
        "vietnamese": "Ba tuần. Tôi đã thăm Tokyo, Kyoto, Osaka và một vài thị trấn nhỏ.",
        "arabic": "ثلاثة أسابيع. زرت طوكيو وكيوتو وأوساكا وبعض المدن الصغيرة.",
    },
    {
        "line_number": 7, "speaker_name": "Alex",
        "english": "I am thinking of going for two weeks. Is that enough time?",
        "lithuanian": "Galvoju vykti dviems savaitėms. Ar to pakanka laiko?",
        "latvian": "Es domāju doties uz divām nedēļām. Vai tas ir pietiekami daudz laika?",
        "estonian": "Mõtlen minna kaheks nädalaks. Kas see on piisavalt aega?",
        "german": "Ich denke daran, für zwei Wochen zu gehen. Ist das genug Zeit?",
        "french": "Je pense y aller pour deux semaines. Est-ce suffisant?",
        "spanish": "Estoy pensando en ir dos semanas. ¿Es suficiente tiempo?",
        "italian": "Sto pensando di andare per due settimane. È abbastanza tempo?",
        "portuguese": "Estou a pensar ir por duas semanas. É tempo suficiente?",
        "dutch": "Ik denk eraan om voor twee weken te gaan. Is dat genoeg tijd?",
        "polish": "Myślę o wyjeździe na dwa tygodnie. Czy to wystarczająco dużo czasu?",
        "ukrainian": "Я думаю поїхати на два тижні. Цього достатньо часу?",
        "russian": "Я думаю поехать на две недели. Этого достаточно?",
        "swedish": "Jag tänker åka i två veckor. Är det tillräckligt med tid?",
        "norwegian": "Jeg tenker å dra i to uker. Er det nok tid?",
        "danish": "Jeg tænker på at tage af sted i to uger. Er det nok tid?",
        "finnish": "Ajattelen mennä kahdeksi viikoksi. Onko se tarpeeksi aikaa?",
        "greek": "Σκέφτομαι να πάω για δύο εβδομάδες. Είναι αρκετός χρόνος;",
        "brazilian_portuguese": "Estou pensando em ir por duas semanas. É tempo suficiente?",
        "mandarin": "我在考虑去两个星期。那够吗？",
        "japanese": "二週間行くことを考えています。それで十分ですか？",
        "korean": "2주 동안 가는 것을 생각하고 있어요. 그게 충분할까요?",
        "hindi": "मैं दो हफ्ते के लिए जाने के बारे में सोच रहा हूँ। क्या यह पर्याप्त समय है?",
        "vietnamese": "Tôi đang nghĩ đi hai tuần. Thế có đủ thời gian không?",
        "arabic": "أفكر في الذهاب لأسبوعين. هل هذا وقت كافٍ؟",
    },
    {
        "line_number": 8, "speaker_name": "Mia",
        "english": "Two weeks is enough to see the main cities. But you will want to come back for more.",
        "lithuanian": "Dviejų savaičių pakanka pamatyti pagrindinius miestus. Bet norėsite grįžti daugiau.",
        "latvian": "Divas nedēļas pietiek, lai redzētu galvenās pilsētas. Bet jūs vēlēsieties atgriezties vairāk.",
        "estonian": "Kaks nädalat on piisavalt, et peamisi linnu näha. Kuid soovite rohkema jaoks tagasi tulla.",
        "german": "Zwei Wochen reichen aus, um die Hauptstädte zu sehen. Aber du wirst mehr wollen.",
        "french": "Deux semaines suffisent pour voir les villes principales. Mais tu voudras revenir pour en voir plus.",
        "spanish": "Dos semanas son suficientes para ver las ciudades principales. Pero querrás volver por más.",
        "italian": "Due settimane bastano per vedere le città principali. Ma vorrai tornare per di più.",
        "portuguese": "Duas semanas chegam para ver as cidades principais. Mas vais querer voltar para mais.",
        "dutch": "Twee weken is genoeg om de grote steden te zien. Maar je wilt terugkomen voor meer.",
        "polish": "Dwa tygodnie wystarczą żeby zobaczyć główne miasta. Ale będziesz chciał wrócić po więcej.",
        "ukrainian": "Двох тижнів достатньо, щоб побачити основні міста. Але ти захочеш повернутися за більшим.",
        "russian": "Двух недель достаточно, чтобы увидеть основные города. Но тебе захочется вернуться за большим.",
        "swedish": "Två veckor räcker för att se de stora städerna. Men du kommer vilja komma tillbaka för mer.",
        "norwegian": "To uker er nok til å se de viktigste byene. Men du vil ønske å komme tilbake for mer.",
        "danish": "To uger er nok til at se de vigtigste byer. Men du vil ønske at komme tilbage for mere.",
        "finnish": "Kaksi viikkoa riittää tärkeimpien kaupunkien näkemiseen. Mutta haluat tulla takaisin lisää varten.",
        "greek": "Δύο εβδομάδες αρκούν για να δεις τις κύριες πόλεις. Αλλά θα θέλεις να ξαναέρθεις για περισσότερα.",
        "brazilian_portuguese": "Duas semanas são suficientes para ver as principais cidades. Mas você vai querer voltar para mais.",
        "mandarin": "两周足够看主要城市了。但你会想回来看更多的。",
        "japanese": "主要な都市を見るには二週間で十分です。でも、もっと見たくなりますよ。",
        "korean": "주요 도시를 보기에는 2주면 충분해요. 하지만 더 많이 보고 싶어질 거예요.",
        "hindi": "मुख्य शहरों को देखने के लिए दो हफ्ते काफी हैं। लेकिन आप और देखने के लिए वापस आना चाहेंगे।",
        "vietnamese": "Hai tuần đủ để thăm các thành phố chính. Nhưng bạn sẽ muốn quay lại để xem thêm.",
        "arabic": "أسبوعان كافيان لرؤية المدن الرئيسية. لكنك ستريد العودة لرؤية المزيد.",
    },
    {
        "line_number": 9, "speaker_name": "Alex",
        "english": "What is the best way to travel between cities there?",
        "lithuanian": "Koks geriausias būdas keliauti tarp miestų ten?",
        "latvian": "Kāds ir labākais veids, kā ceļot starp pilsētām tur?",
        "estonian": "Mis on parim viis seal linnade vahel reisida?",
        "german": "Was ist der beste Weg, um dort zwischen den Städten zu reisen?",
        "french": "Quel est le meilleur moyen de voyager entre les villes là-bas?",
        "spanish": "¿Cuál es la mejor manera de viajar entre ciudades allí?",
        "italian": "Qual è il modo migliore per viaggiare tra le città là?",
        "portuguese": "Qual é a melhor forma de viajar entre cidades lá?",
        "dutch": "Wat is de beste manier om tussen steden daar te reizen?",
        "polish": "Jaki jest najlepszy sposób podróżowania między miastami?",
        "ukrainian": "Який найкращий спосіб подорожувати між містами там?",
        "russian": "Какой лучший способ путешествовать между городами там?",
        "swedish": "Vad är det bästa sättet att resa mellan städerna där?",
        "norwegian": "Hva er den beste måten å reise mellom byene der?",
        "danish": "Hvad er den bedste måde at rejse mellem byerne der?",
        "finnish": "Mikä on paras tapa matkustaa kaupunkien välillä siellä?",
        "greek": "Ποιος είναι ο καλύτερος τρόπος να ταξιδεύεις μεταξύ των πόλεων εκεί;",
        "brazilian_portuguese": "Qual é a melhor forma de viajar entre as cidades lá?",
        "mandarin": "在那里城市之间旅行的最佳方式是什么？",
        "japanese": "そこで都市間を移動する一番いい方法は何ですか？",
        "korean": "도시 사이를 이동하는 가장 좋은 방법은 무엇인가요?",
        "hindi": "वहाँ शहरों के बीच यात्रा करने का सबसे अच्छा तरीका क्या है?",
        "vietnamese": "Cách tốt nhất để đi lại giữa các thành phố ở đó là gì?",
        "arabic": "ما هي أفضل طريقة للتنقل بين المدن هناك؟",
    },
    {
        "line_number": 10, "speaker_name": "Mia",
        "english": "The bullet train is amazing. It is fast, comfortable and very punctual.",
        "lithuanian": "Greitasis traukinys yra nuostabus. Jis greitas, patogus ir labai punktualus.",
        "latvian": "Ātrvilciens ir pārsteidzošs. Tas ir ātrs, ērts un ļoti precīzs.",
        "estonian": "Kiirong on hämmastav. See on kiire, mugav ja väga täpne.",
        "german": "Der Hochgeschwindigkeitszug ist unglaublich. Er ist schnell, komfortabel und sehr pünktlich.",
        "french": "Le train à grande vitesse est incroyable. Il est rapide confortable et très ponctuel.",
        "spanish": "El tren de alta velocidad es increíble. Es rápido cómodo y muy puntual.",
        "italian": "Il treno ad alta velocità è straordinario. È veloce comodo e molto puntuale.",
        "portuguese": "O comboio de alta velocidade é incrível. É rápido confortável e muito pontual.",
        "dutch": "De hogesnelheidstrein is geweldig. Hij is snel, comfortabel en erg op tijd.",
        "polish": "Pociąg Shinkansen jest niesamowity. Jest szybki, wygodny i bardzo punktualny.",
        "ukrainian": "Швидкісний поїзд дивовижний. Він швидкий, комфортний і дуже пунктуальний.",
        "russian": "Скоростной поезд потрясающий. Он быстрый, удобный и очень пунктуальный.",
        "swedish": "Snabbtåget är fantastiskt. Det är snabbt, bekvämt och mycket punktligt.",
        "norwegian": "Høyhastighetstooget er utrolig. Det er raskt, komfortabelt og svært punktlig.",
        "danish": "Højhastighedstoget er fantastisk. Det er hurtigt, komfortabelt og meget punktligt.",
        "finnish": "Nopea juna on hämmästyttävä. Se on nopea, mukava ja erittäin täsmällinen.",
        "greek": "Το τρένο υψηλής ταχύτητας είναι καταπληκτικό. Είναι γρήγορο, άνετο και πολύ ακριβές.",
        "brazilian_portuguese": "O trem-bala é incrível. É rápido, confortável e muito pontual.",
        "mandarin": "子弹头列车太棒了。它快速、舒适、非常准时。",
        "japanese": "新幹線は素晴らしいです。速くて、快適で、とても時間通りです。",
        "korean": "신칸센이 정말 대단해요. 빠르고, 편안하고, 매우 정시에 운행돼요.",
        "hindi": "बुलेट ट्रेन शानदार है। यह तेज़, आरामदायक और बहुत समयनिष्ठ है।",
        "vietnamese": "Tàu cao tốc thật tuyệt vời. Nó nhanh, thoải mái và rất đúng giờ.",
        "arabic": "القطار فائق السرعة رائع. إنه سريع ومريح وفي موعده تماماً.",
    },
    {
        "line_number": 11, "speaker_name": "Alex",
        "english": "Is Japan an expensive country to travel in?",
        "lithuanian": "Ar Japonija yra brangi šalis keliauti?",
        "latvian": "Vai Japāna ir dārga valsts ceļošanai?",
        "estonian": "Kas Jaapan on kallis riik reisimiseks?",
        "german": "Ist Japan ein teures Reiseland?",
        "french": "Le Japon est-il un pays cher où voyager?",
        "spanish": "¿Es Japón un país caro para viajar?",
        "italian": "Il Giappone è un paese costoso in cui viaggiare?",
        "portuguese": "O Japão é um país caro para viajar?",
        "dutch": "Is Japan een duur land om in te reizen?",
        "polish": "Czy Japonia jest drogim krajem do podróżowania?",
        "ukrainian": "Чи дорога Японія для подорожей?",
        "russian": "Япония — дорогая страна для путешествий?",
        "swedish": "Är Japan ett dyrt land att resa i?",
        "norwegian": "Er Japan et dyrt land å reise i?",
        "danish": "Er Japan et dyrt land at rejse i?",
        "finnish": "Onko Japani kallis maa matkustaa?",
        "greek": "Είναι η Ιαπωνία ακριβή χώρα για ταξίδι;",
        "brazilian_portuguese": "O Japão é um país caro para viajar?",
        "mandarin": "日本是个旅游费用高的国家吗？",
        "japanese": "日本は旅行するのに高い国ですか？",
        "korean": "일본은 여행하기에 비싼 나라인가요?",
        "hindi": "क्या जापान यात्रा के लिए महंगा देश है?",
        "vietnamese": "Nhật Bản có phải là nước đắt đỏ để du lịch không?",
        "arabic": "هل اليابان دولة مكلفة للسفر إليها؟",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "It can be. Hotels and transport are pricey. But food from local restaurants and markets is quite cheap.",
        "lithuanian": "Gali būti. Viešbučiai ir transportas yra brangūs. Bet maistas iš vietinių restoranų ir turgų yra gana pigus.",
        "latvian": "Tā var būt. Viesnīcas un transports ir dārgi. Bet ēdiens no vietējiem restorāniem un tirgiem ir diezgan lēts.",
        "estonian": "Võib olla. Hotellid ja transport on kallid. Kuid toit kohalikest restoranidest ja turgudest on üsna odav.",
        "german": "Es kann sein. Hotels und Transport sind teuer. Aber Essen in lokalen Restaurants und Märkten ist ziemlich günstig.",
        "french": "Ça peut l'être. Les hôtels et les transports sont chers. Mais la nourriture dans les restaurants et marchés locaux est assez bon marché.",
        "spanish": "Puede serlo. Los hoteles y el transporte son caros. Pero la comida de los restaurantes y mercados locales es bastante barata.",
        "italian": "Può esserlo. Gli hotel e i trasporti sono costosi. Ma il cibo dei ristoranti e mercati locali è abbastanza economico.",
        "portuguese": "Pode ser. Hotéis e transporte são caros. Mas a comida de restaurantes e mercados locais é bastante barata.",
        "dutch": "Het kan zijn. Hotels en transport zijn duur. Maar eten van lokale restaurants en markten is vrij goedkoop.",
        "polish": "Może być. Hotele i transport są drogie. Ale jedzenie w lokalnych restauracjach i na targach jest dość tanie.",
        "ukrainian": "Може бути. Готелі та транспорт дорогі. Але їжа з місцевих ресторанів і ринків досить дешева.",
        "russian": "Бывает. Отели и транспорт дорогие. Но еда в местных ресторанах и на рынках довольно дешёвая.",
        "swedish": "Det kan vara. Hotell och transport är dyrt. Men mat från lokala restauranger och marknader är ganska billig.",
        "norwegian": "Det kan det være. Hoteller og transport er dyrt. Men mat fra lokale restauranter og markeder er ganske billig.",
        "danish": "Det kan det være. Hoteller og transport er dyrt. Men mad fra lokale restauranter og markeder er ganske billig.",
        "finnish": "Se voi olla. Hotellit ja liikenne ovat kalliita. Mutta ruoka paikallisista ravintoloista ja markkinoilta on melko halpaa.",
        "greek": "Μπορεί. Τα ξενοδοχεία και οι μεταφορές είναι ακριβά. Αλλά το φαγητό από τοπικά εστιατόρια και αγορές είναι αρκετά φθηνό.",
        "brazilian_portuguese": "Pode ser. Hotéis e transporte são caros. Mas a comida de restaurantes e mercados locais é bem barata.",
        "mandarin": "可以的。酒店和交通比较贵。但当地餐厅和市场的食物相当便宜。",
        "japanese": "高い場合があります。ホテルと交通費は高いです。でも地元のレストランや市場の食べ物はかなり安いです。",
        "korean": "비쌀 수 있어요. 호텔과 교통은 비싸요. 하지만 현지 식당이나 시장 음식은 꽤 저렴해요.",
        "hindi": "हो सकता है। होटल और परिवहन महंगे हैं। लेकिन स्थानीय रेस्टोरेंट और बाज़ारों का खाना काफी सस्ता है।",
        "vietnamese": "Có thể vậy. Khách sạn và phương tiện đi lại khá đắt. Nhưng đồ ăn từ nhà hàng địa phương và chợ khá rẻ.",
        "arabic": "قد يكون كذلك. الفنادق والنقل مكلفان. لكن الطعام من المطاعم المحلية والأسواق رخيص جداً.",
    },
    {
        "line_number": 13, "speaker_name": "Alex",
        "english": "What food should I definitely try when I am there?",
        "lithuanian": "Kokio maisto tikrai reikia pabandyti ten būnant?",
        "latvian": "Kādu ēdienu man noteikti vajadzētu izmēģināt, atrodoties tur?",
        "estonian": "Millist toitu peaksin seal olles kindlasti proovima?",
        "german": "Welches Essen sollte ich dort unbedingt probieren?",
        "french": "Quelle nourriture devrais-je absolument essayer là-bas?",
        "spanish": "¿Qué comida debo probar definitivamente cuando esté allí?",
        "italian": "Quale cibo devo assolutamente provare quando sono lì?",
        "portuguese": "Que comida devo definitivamente experimentar quando estiver lá?",
        "dutch": "Welk eten moet ik zeker proberen als ik daar ben?",
        "polish": "Jakie jedzenie powinienem koniecznie spróbować gdy tam będę?",
        "ukrainian": "Яку їжу мені обов'язково слід спробувати, коли я там?",
        "russian": "Какую еду я обязательно должен попробовать, когда буду там?",
        "swedish": "Vilken mat borde jag absolut prova när jag är där?",
        "norwegian": "Hvilken mat bør jeg absolutt prøve når jeg er der?",
        "danish": "Hvilken mad bør jeg absolut prøve når jeg er der?",
        "finnish": "Mitä ruokaa minun pitäisi ehdottomasti maistaa siellä ollessani?",
        "greek": "Τι φαγητό πρέπει οπωσδήποτε να δοκιμάσω όταν είμαι εκεί;",
        "brazilian_portuguese": "Que comida eu definitivamente devo experimentar quando estiver lá?",
        "mandarin": "到那里后我一定要尝试什么食物？",
        "japanese": "そこにいる間に絶対に試すべき食べ物は何ですか？",
        "korean": "거기 있을 때 꼭 먹어봐야 할 음식이 뭐가 있나요?",
        "hindi": "वहाँ रहते हुए मुझे किस खाने की जरूर कोशिश करनी चाहिए?",
        "vietnamese": "Tôi nhất định phải thử món ăn gì khi ở đó?",
        "arabic": "ما الطعام الذي يجب عليّ تجربته بالتأكيد عندما أكون هناك؟",
    },
    {
        "line_number": 14, "speaker_name": "Mia",
        "english": "Ramen is absolutely delicious. Also try sushi from a proper sushi bar, not a supermarket.",
        "lithuanian": "Ramen yra tiesiog skanus. Taip pat paragaukite sushi iš tikro sushi baro, o ne parduotuvės.",
        "latvian": "Ramens ir absolūti garšīgs. Izmēģini arī suši no īsta suši bāra, nevis lielveikala.",
        "estonian": "Ramen on absoluutselt maitsev. Proovi ka sushit pärisest sushi barist, mitte supermarketist.",
        "german": "Ramen ist absolut köstlich. Probiere auch Sushi in einer echten Sushibar, nicht in einem Supermarkt.",
        "french": "Le ramen est absolument délicieux. Essaie aussi les sushis dans un vrai bar à sushis pas dans un supermarché.",
        "spanish": "El ramen está absolutamente delicioso. También prueba el sushi en un bar de sushi de verdad no en un supermercado.",
        "italian": "Il ramen è assolutamente delizioso. Prova anche il sushi in un vero sushi bar non in un supermercato.",
        "portuguese": "O ramen é absolutamente delicioso. Experimenta também o sushi num bar de sushi a sério não num supermercado.",
        "dutch": "Ramen is absoluut heerlijk. Probeer ook sushi in een echte sushibar niet in een supermarkt.",
        "polish": "Ramen jest absolutnie pyszny. Spróbuj też sushi w prawdziwym barze sushi nie w supermarkecie.",
        "ukrainian": "Рамен абсолютно смачний. Також спробуй суші в справжньому суші-барі, а не в супермаркеті.",
        "russian": "Рамен абсолютно вкусный. Также попробуй суши в настоящем суши-баре, а не в супермаркете.",
        "swedish": "Ramen är absolut utsökt. Prova också sushi på en riktig sushibar inte i en supermarket.",
        "norwegian": "Ramen er absolutt deilig. Prøv også sushi på en skikkelig sushibar ikke i en supermarked.",
        "danish": "Ramen er absolut lækkert. Prøv også sushi på en rigtig sushibar ikke i et supermarked.",
        "finnish": "Ramen on ehdottomasti herkullinen. Kokeile myös sushia oikeasta sushi-baarista ei supermarketista.",
        "greek": "Το ράμεν είναι απολύτως νόστιμο. Δοκίμασε επίσης σούσι από αληθινό μπαρ σούσι όχι από σούπερ μάρκετ.",
        "brazilian_portuguese": "O ramen é absolutamente delicioso. Experimente também o sushi em um sushi bar de verdade não no supermercado.",
        "mandarin": "拉面绝对美味。还要在正宗的寿司店而不是超市里尝试寿司。",
        "japanese": "ラーメンは絶対においしいです。スーパーではなく、ちゃんとした寿司バーで寿司も試してみてください。",
        "korean": "라멘은 정말 맛있어요. 슈퍼마켓이 아닌 제대로 된 스시 바에서 스시도 꼭 먹어보세요.",
        "hindi": "रामेन बिल्कुल स्वादिष्ट है। सुपरमार्केट नहीं बल्कि एक असली सुशी बार से सुशी भी ज़रूर आज़माएँ।",
        "vietnamese": "Ramen thật sự ngon tuyệt. Cũng hãy thử sushi ở quán sushi thực sự chứ không phải siêu thị.",
        "arabic": "الرامن لذيذ للغاية. جرّب أيضاً السوشي من مطعم سوشي حقيقي لا من سوبرماركت.",
    },
    {
        "line_number": 15, "speaker_name": "Alex",
        "english": "Do I need to book accommodation far in advance?",
        "lithuanian": "Ar reikia iš anksto rezervuoti apgyvendinimą?",
        "latvian": "Vai man jārezervē izmitināšana daudz iepriekš?",
        "estonian": "Kas pean majutust palju ette broneerima?",
        "german": "Muss ich die Unterkunft weit im Voraus buchen?",
        "french": "Dois-je réserver l'hébergement longtemps à l'avance?",
        "spanish": "¿Necesito reservar el alojamiento con mucha antelación?",
        "italian": "Devo prenotare l'alloggio molto in anticipo?",
        "portuguese": "Preciso de reservar o alojamento com muita antecedência?",
        "dutch": "Moet ik ver van tevoren accommodatie boeken?",
        "polish": "Czy muszę rezerwować zakwaterowanie z dużym wyprzedzeniem?",
        "ukrainian": "Чи потрібно бронювати житло заздалегідь?",
        "russian": "Нужно ли бронировать жильё заблаговременно?",
        "swedish": "Behöver jag boka boende långt i förväg?",
        "norwegian": "Må jeg bestille overnatting langt i forveien?",
        "danish": "Skal jeg booke overnatning lang tid i forvejen?",
        "finnish": "Pitääkö majoitus varata kauas etukäteen?",
        "greek": "Χρειάζεται να κλείσω κατάλυμα πολύ μπροστά;",
        "brazilian_portuguese": "Preciso reservar acomodação com muita antecedência?",
        "mandarin": "我需要提前很久预订住宿吗？",
        "japanese": "宿泊先をかなり前に予約する必要がありますか？",
        "korean": "숙박을 아주 미리 예약해야 하나요?",
        "hindi": "क्या मुझे बहुत पहले से आवास बुक करना होगा?",
        "vietnamese": "Tôi có cần đặt chỗ ở trước rất lâu không?",
        "arabic": "هل أحتاج إلى حجز الإقامة قبل وقت طويل؟",
    },
    {
        "line_number": 16, "speaker_name": "Mia",
        "english": "Yes definitely. Spring is cherry blossom season so hotels fill up very quickly.",
        "lithuanian": "Taip, tikrai. Pavasaris yra sakurų žydėjimo sezonas, todėl viešbučiai užsipildo labai greitai.",
        "latvian": "Jā, noteikti. Pavasaris ir ķiršu ziedēšanas sezona, tāpēc viesnīcas aizpildās ļoti ātri.",
        "estonian": "Jah kindlasti. Kevad on kirsipuu õitsemise hooaeg nii et hotellid täituvad väga kiiresti.",
        "german": "Ja auf jeden Fall. Der Frühling ist die Kirschblütensaison, also sind Hotels sehr schnell ausgebucht.",
        "french": "Oui absolument. Le printemps est la saison des cerisiers en fleurs donc les hôtels se remplissent très vite.",
        "spanish": "Sí definitivamente. La primavera es la temporada de los cerezos en flor así que los hoteles se llenan muy rápido.",
        "italian": "Sì assolutamente. La primavera è la stagione dei fiori di ciliegio quindi gli hotel si riempiono molto rapidamente.",
        "portuguese": "Sim definitivamente. A primavera é a época das flores de cerejeira por isso os hotéis enchem-se muito depressa.",
        "dutch": "Ja zeker. De lente is het kersenbloesemseizoen dus hotels raken heel snel vol.",
        "polish": "Tak zdecydowanie. Wiosna to sezon kwitnienia wiśni więc hotele zapełniają się bardzo szybko.",
        "ukrainian": "Так, однозначно. Весна — сезон цвітіння сакури, тому готелі заповнюються дуже швидко.",
        "russian": "Да, однозначно. Весна — сезон цветения сакуры, поэтому отели очень быстро заполняются.",
        "swedish": "Ja definitivt. Våren är körsbärsblomningens säsong så hotell fylls väldigt snabbt.",
        "norwegian": "Ja absolutt. Våren er kirsebærblomstringsesongen så hotellene fylles veldig raskt.",
        "danish": "Ja bestemt. Forår er kirsebærblomstrings sæsonen så hoteller fylder op meget hurtigt.",
        "finnish": "Kyllä ehdottomasti. Kevät on kirsikankukkien kausi joten hotellit täyttyvät hyvin nopeasti.",
        "greek": "Ναι σίγουρα. Η άνοιξη είναι η εποχή των ανθισμένων κερασιών οπότε τα ξενοδοχεία γεμίζουν πολύ γρήγορα.",
        "brazilian_portuguese": "Sim com certeza. A primavera é a época das flores de cerejeira então os hotéis ficam lotados muito rápido.",
        "mandarin": "是的，一定要。春天是樱花季，所以酒店很快就会订满。",
        "japanese": "はい、絶対に。春は桜の季節なのでホテルはすぐに満室になります。",
        "korean": "네, 꼭요. 봄은 벚꽃 시즌이라 호텔이 아주 빨리 차요.",
        "hindi": "हाँ, जरूर। वसंत चेरी ब्लॉसम का मौसम है इसलिए होटल बहुत जल्दी भर जाते हैं।",
        "vietnamese": "Vâng chắc chắn rồi. Mùa xuân là mùa hoa anh đào nên khách sạn đặt kín rất nhanh.",
        "arabic": "نعم بالتأكيد. الربيع موسم أزهار الكرز لذلك تمتلئ الفنادق بسرعة كبيرة.",
    },
    {
        "line_number": 17, "speaker_name": "Alex",
        "english": "That sounds beautiful. I should probably book everything soon.",
        "lithuanian": "Tai skamba gražiai. Turbūt turėčiau greitai viską rezervuoti.",
        "latvian": "Tas izklausās skaisti. Man droši vien vajadzētu drīz visu rezervēt.",
        "estonian": "See kõlab kaunilt. Peaksin ilmselt varsti kõik broneerima.",
        "german": "Das klingt wunderschön. Ich sollte wahrscheinlich bald alles buchen.",
        "french": "Ça a l'air magnifique. Je devrais probablement tout réserver bientôt.",
        "spanish": "Eso suena hermoso. Probablemente debería reservar todo pronto.",
        "italian": "Sembra bellissimo. Dovrei probabilmente prenotare tutto presto.",
        "portuguese": "Isso soa lindo. Provavelmente devia reservar tudo em breve.",
        "dutch": "Dat klinkt prachtig. Ik zou waarschijnlijk snel alles moeten boeken.",
        "polish": "To brzmi pięknie. Powinienem chyba wkrótce zarezerwować wszystko.",
        "ukrainian": "Це звучить чудово. Мабуть, мені слід незабаром все забронювати.",
        "russian": "Это звучит великолепно. Наверное, мне стоит скоро всё забронировать.",
        "swedish": "Det låter vackert. Jag borde nog boka allt snart.",
        "norwegian": "Det høres vakkert ut. Jeg bør nok bestille alt snart.",
        "danish": "Det lyder smukt. Jeg bør nok booke alt snart.",
        "finnish": "Kuulostaa kauniilta. Minun pitäisi luultavasti varata kaikki pian.",
        "greek": "Αυτό ακούγεται υπέροχο. Μάλλον πρέπει να κλείσω τα πάντα σύντομα.",
        "brazilian_portuguese": "Isso soa lindo. Provavelmente devo reservar tudo em breve.",
        "mandarin": "听起来很美。我可能应该很快预订所有的东西。",
        "japanese": "それは素晴らしいですね。すぐに全部予約した方がいいかもしれません。",
        "korean": "정말 아름답게 들리네요. 곧 모든 것을 예약해야 할 것 같아요.",
        "hindi": "यह सुंदर लगता है। मुझे शायद जल्द ही सब कुछ बुक कर लेना चाहिए।",
        "vietnamese": "Nghe thật đẹp. Tôi nên đặt mọi thứ sớm thôi.",
        "arabic": "يبدو ذلك رائعاً. ينبغي لي على الأرجح حجز كل شيء قريباً.",
    },
    {
        "line_number": 18, "speaker_name": "Mia",
        "english": "I recommend booking hotels at least four months before. Flights too.",
        "lithuanian": "Rekomenduoju rezervuoti viešbučius bent keturis mėnesius iš anksto. Ir skrydžius taip pat.",
        "latvian": "Es iesaku rezervēt viesnīcas vismaz četrus mēnešus iepriekš. Arī lidojumus.",
        "estonian": "Soovitan broneerida hotellid vähemalt neli kuud ette. Ka lennud.",
        "german": "Ich empfehle, Hotels mindestens vier Monate im Voraus zu buchen. Auch Flüge.",
        "french": "Je recommande de réserver les hôtels au moins quatre mois à l'avance. Les vols aussi.",
        "spanish": "Recomiendo reservar hoteles al menos cuatro meses antes. Los vuelos también.",
        "italian": "Consiglio di prenotare gli hotel almeno quattro mesi prima. Anche i voli.",
        "portuguese": "Recomendo reservar hotéis pelo menos quatro meses antes. Voos também.",
        "dutch": "Ik raad aan hotels minstens vier maanden van tevoren te boeken. Vluchten ook.",
        "polish": "Polecam rezerwować hotele co najmniej cztery miesiące wcześniej. Loty też.",
        "ukrainian": "Рекомендую бронювати готелі щонайменше за чотири місяці. Рейси теж.",
        "russian": "Рекомендую бронировать отели минимум за четыре месяца. Рейсы тоже.",
        "swedish": "Jag rekommenderar att boka hotell minst fyra månader i förväg. Flyg också.",
        "norwegian": "Jeg anbefaler å bestille hoteller minst fire måneder i forveien. Fly også.",
        "danish": "Jeg anbefaler at booke hoteller mindst fire måneder i forvejen. Fly også.",
        "finnish": "Suosittelen varaamaan hotellit vähintään neljä kuukautta etukäteen. Lennot myös.",
        "greek": "Συνιστώ να κλείνεις ξενοδοχεία τουλάχιστον τέσσερις μήνες νωρίτερα. Και τα αεροπορικά.",
        "brazilian_portuguese": "Recomendo reservar hotéis pelo menos quatro meses antes. Voos também.",
        "mandarin": "我建议至少提前四个月预订酒店。还有机票。",
        "japanese": "ホテルは少なくとも四ヶ月前に予約することをお勧めします。フライトも。",
        "korean": "최소 4개월 전에 호텔을 예약하는 것을 추천해요. 항공권도요.",
        "hindi": "मैं कम से कम चार महीने पहले होटल बुक करने की सलाह देता हूँ। उड़ानें भी।",
        "vietnamese": "Tôi khuyên nên đặt khách sạn ít nhất bốn tháng trước. Cả vé máy bay nữa.",
        "arabic": "أوصي بحجز الفنادق قبل أربعة أشهر على الأقل. وكذلك الرحلات الجوية.",
    },
    {
        "line_number": 19, "speaker_name": "Alex",
        "english": "Do you need a visa to visit Japan as a European?",
        "lithuanian": "Ar europieciui reikia vizos lankytis Japonijoje?",
        "latvian": "Vai eiropietim ir nepieciešama vīza, lai apmeklētu Japānu?",
        "estonian": "Kas eurooplasena on Jaapanisse külastamiseks vaja viisat?",
        "german": "Braucht man als Europäer ein Visum für Japan?",
        "french": "A-t-on besoin d'un visa pour visiter le Japon en tant qu'Européen?",
        "spanish": "¿Necesitas un visado para visitar Japón siendo europeo?",
        "italian": "Hai bisogno di un visto per visitare il Giappone come europeo?",
        "portuguese": "Precisas de visto para visitar o Japão sendo europeu?",
        "dutch": "Heb je als Europeaan een visum nodig voor Japan?",
        "polish": "Czy Europejczyk potrzebuje wizy do Japonii?",
        "ukrainian": "Чи потрібна віза для відвідування Японії як громадянину Європи?",
        "russian": "Нужна ли европейцу виза для посещения Японии?",
        "swedish": "Behöver man visum för att besöka Japan som europé?",
        "norwegian": "Trenger man visum for å besøke Japan som europeer?",
        "danish": "Har man brug for visum til Japan som europæer?",
        "finnish": "Tarvitseeko eurooppalainen viisumin Japaniin?",
        "greek": "Χρειάζεσαι βίζα για να επισκεφθείς την Ιαπωνία ως Ευρωπαίος;",
        "brazilian_portuguese": "Você precisa de visto para visitar o Japão como europeu?",
        "mandarin": "欧洲人去日本需要签证吗？",
        "japanese": "ヨーロッパ人として日本を訪問するためにビザが必要ですか？",
        "korean": "유럽인으로서 일본을 방문하려면 비자가 필요한가요?",
        "hindi": "क्या यूरोपीय के रूप में जापान जाने के लिए वीजा चाहिए?",
        "vietnamese": "Người châu Âu có cần visa để thăm Nhật Bản không?",
        "arabic": "هل تحتاج إلى تأشيرة لزيارة اليابان كمواطن أوروبي؟",
    },
    {
        "line_number": 20, "speaker_name": "Mia",
        "english": "No you do not. Most European countries have a visa-free agreement with Japan. You can stay for ninety days. Just bring your passport and enjoy the trip!",
        "lithuanian": "Ne, nereikia. Dauguma Europos šalių turi bevizį susitarimą su Japonija. Galite likti devyniasdešimt dienų. Tiesiog pasiimkite pasą ir mėgaukitės kelione!",
        "latvian": "Nē, nevajag. Lielākajai daļai Eiropas valstu ir bezvīzu vienošanās ar Japānu. Varat uzturēties deviņdesmit dienas. Vienkārši paņem pasi un baudi ceļojumu!",
        "estonian": "Ei, pole vaja. Enamikul Euroopa riikidest on Jaapaniga viisavaba kokkulepe. Sa saad seal viibida üheksakümmend päeva. Lihtsalt võta pass kaasa ja naudi reisi!",
        "german": "Nein, das musst du nicht. Die meisten europäischen Länder haben ein visumfreies Abkommen mit Japan. Du kannst neunzig Tage bleiben. Nimm einfach deinen Pass mit und genieße die Reise!",
        "french": "Non tu n'en as pas besoin. La plupart des pays européens ont un accord sans visa avec le Japon. Tu peux rester quatre-vingt-dix jours. Prends juste ton passeport et profite du voyage!",
        "spanish": "No no necesitas. La mayoría de los países europeos tienen un acuerdo de exención de visado con Japón. Puedes quedarte noventa días. ¡Solo lleva tu pasaporte y disfruta el viaje!",
        "italian": "No non ne hai bisogno. La maggior parte dei paesi europei ha un accordo senza visto con il Giappone. Puoi restare novanta giorni. Porta solo il passaporto e goditi il viaggio!",
        "portuguese": "Não não precisas. A maioria dos países europeus tem um acordo de isenção de visto com o Japão. Podes ficar noventa dias. Leva só o passaporte e aproveita a viagem!",
        "dutch": "Nee dat is niet nodig. De meeste Europese landen hebben een visumvrij akkoord met Japan. Je kunt negentig dagen blijven. Neem gewoon je paspoort mee en geniet van de reis!",
        "polish": "Nie, nie potrzebujesz. Większość krajów europejskich ma umowę bezwizową z Japonią. Możesz zostać dziewięćdziesiąt dni. Po prostu weź paszport i ciesz się podróżą!",
        "ukrainian": "Ні, не потрібна. Більшість європейських країн мають безвізовий договір з Японією. Ти можеш залишитися на дев'яносто днів. Просто візьми паспорт і насолоджуйся поїздкою!",
        "russian": "Нет, не нужна. У большинства европейских стран есть безвизовое соглашение с Японией. Ты можешь оставаться девяносто дней. Просто возьми паспорт и наслаждайся поездкой!",
        "swedish": "Nej det behöver du inte. De flesta europeiska länder har ett visumfritt avtal med Japan. Du kan stanna i nittio dagar. Ta bara med ditt pass och njut av resan!",
        "norwegian": "Nei det trenger du ikke. De fleste europeiske land har en visumfri avtale med Japan. Du kan bli i nitti dager. Ta bare med passet og nyt turen!",
        "danish": "Nej det behøver du ikke. De fleste europæiske lande har en visumfri aftale med Japan. Du kan blive i halvfems dage. Tag bare dit pas og nyd turen!",
        "finnish": "Ei tarvita. Useimmilla Euroopan mailla on viisumivapaasopimus Japanin kanssa. Voit viipyä yhdeksänkymmentä päivää. Ota vain passi mukaan ja nauti matkasta!",
        "greek": "Όχι δεν χρειάζεσαι. Τα περισσότερα ευρωπαϊκά χώρα έχουν συμφωνία χωρίς βίζα με την Ιαπωνία. Μπορείς να μείνεις ενενήντα μέρες. Πάρε μόνο το διαβατήριό σου και απόλαυσε το ταξίδι!",
        "brazilian_portuguese": "Não você não precisa. A maioria dos países europeus tem um acordo de isenção de visto com o Japão. Você pode ficar noventa dias. Só leve o passaporte e aproveite a viagem!",
        "mandarin": "不，不需要。大多数欧洲国家与日本有免签协议。你可以停留九十天。只需带上护照，享受旅程！",
        "japanese": "いいえ、必要ありません。ほとんどのヨーロッパの国々は日本とビザ免除協定を結んでいます。九十日間滞在できます。パスポートを持って旅を楽しんでください！",
        "korean": "아니요, 필요 없어요. 대부분의 유럽 국가는 일본과 무비자 협정이 있어요. 90일 동안 있을 수 있어요. 여권만 챙기고 여행 즐기세요!",
        "hindi": "नहीं, नहीं चाहिए। अधिकांश यूरोपीय देशों का जापान के साथ वीजा-मुक्त समझौता है। आप नब्बे दिनों तक रह सकते हैं। बस पासपोर्ट लाएँ और यात्रा का आनंद लें!",
        "vietnamese": "Không, bạn không cần. Hầu hết các nước châu Âu có thỏa thuận miễn visa với Nhật Bản. Bạn có thể ở lại chín mươi ngày. Chỉ cần mang theo hộ chiếu và tận hưởng chuyến đi!",
        "arabic": "لا لست بحاجة إليها. تمتلك معظم الدول الأوروبية اتفاقية إعفاء من التأشيرة مع اليابان. يمكنك البقاء تسعين يوماً. فقط أحضر جواز سفرك واستمتع بالرحلة!",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="Planning a Trip Abroad").first()
        if existing:
            print("B1 dialogue 'Planning a Trip Abroad' already exists — skipping.")
            return

        dialogue = Dialogue(topic="Planning a Trip Abroad", lang_level="B1", length=20)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded B1 dialogue ID {dialogue.id} — 20 lines in 25 languages.")


if __name__ == '__main__':
    seed()
