import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from hello_world import app, db, Dialogue, DialogueLine

lines_data = [
    {
        "line_number": 1, "speaker_name": "Alex",
        "english": "Excuse me. Where is the bread?",
        "lithuanian": "Atsiprašau. Kur yra duona?",
        "latvian": "Atvainojiet. Kur ir maize?",
        "estonian": "Vabandage. Kus on leib?",
        "german": "Entschuldigung. Wo ist das Brot?",
        "french": "Excusez-moi. Où est le pain?",
        "spanish": "Perdone. ¿Dónde está el pan?",
        "italian": "Scusi. Dov'è il pane?",
        "portuguese": "Com licença. Onde está o pão?",
        "dutch": "Excuseer mij. Waar is het brood?",
        "polish": "Przepraszam. Gdzie jest chleb?",
        "ukrainian": "Вибачте. Де хліб?",
        "russian": "Извините. Где хлеб?",
        "swedish": "Ursäkta mig. Var är brödet?",
        "norwegian": "Unnskyld. Hvor er brødet?",
        "danish": "Undskyld. Hvor er brødet?",
        "finnish": "Anteeksi. Missä on leipä?",
        "greek": "Συγγνώμη. Πού είναι το ψωμί;",
        "brazilian_portuguese": "Com licença. Onde fica o pão?",
        "mandarin": "打扰一下。面包在哪里？",
        "japanese": "すみません。パンはどこですか？",
        "korean": "저기요. 빵이 어디 있어요?",
        "hindi": "माफ़ कीजिए। ब्रेड कहाँ है?",
        "vietnamese": "Xin lỗi. Bánh mì ở đâu?",
        "arabic": "عفواً. أين الخبز؟",
    },
    {
        "line_number": 2, "speaker_name": "Mia",
        "english": "It is in aisle three on the left.",
        "lithuanian": "Ji yra trečiame koridoriuje kairėje.",
        "latvian": "Tas ir trešajā ejā pa kreisi.",
        "estonian": "See on kolmandas käigus vasakul.",
        "german": "Es ist in Gang drei auf der linken Seite.",
        "french": "C'est dans l'allée trois à gauche.",
        "spanish": "Está en el pasillo tres a la izquierda.",
        "italian": "È nella corsia tre a sinistra.",
        "portuguese": "Está na coxia três à esquerda.",
        "dutch": "Het is in gangpad drie aan de linkerkant.",
        "polish": "Jest w alejce trzeciej po lewej.",
        "ukrainian": "Він у третьому проході зліва.",
        "russian": "Он в третьем ряду слева.",
        "swedish": "Det är i gång tre till vänster.",
        "norwegian": "Det er i gang tre til venstre.",
        "danish": "Det er i gang tre til venstre.",
        "finnish": "Se on käytävällä kolme vasemmalla.",
        "greek": "Είναι στο διάδρομο τρία στα αριστερά.",
        "brazilian_portuguese": "Está no corredor três à esquerda.",
        "mandarin": "在第三排左边。",
        "japanese": "三番通路の左側です。",
        "korean": "세 번째 통로 왼쪽에 있어요.",
        "hindi": "यह तीसरे गलियारे में बाईं तरफ है।",
        "vietnamese": "Ở hành lang thứ ba bên trái.",
        "arabic": "إنه في الممر الثالث على اليسار.",
    },
    {
        "line_number": 3, "speaker_name": "Alex",
        "english": "Thank you. Do you have fresh milk?",
        "lithuanian": "Ačiū. Ar turite šviežio pieno?",
        "latvian": "Paldies. Vai jums ir svaigs piens?",
        "estonian": "Tänan. Kas teil on värsket piima?",
        "german": "Danke. Haben Sie frische Milch?",
        "french": "Merci. Avez-vous du lait frais?",
        "spanish": "Gracias. ¿Tienen leche fresca?",
        "italian": "Grazie. Avete latte fresco?",
        "portuguese": "Obrigado. Têm leite fresco?",
        "dutch": "Dank u. Heeft u verse melk?",
        "polish": "Dziękuję. Czy macie świeże mleko?",
        "ukrainian": "Дякую. У вас є свіже молоко?",
        "russian": "Спасибо. У вас есть свежее молоко?",
        "swedish": "Tack. Har ni färsk mjölk?",
        "norwegian": "Takk. Har dere fersk melk?",
        "danish": "Tak. Har I frisk mælk?",
        "finnish": "Kiitos. Onko teillä tuoretta maitoa?",
        "greek": "Ευχαριστώ. Έχετε φρέσκο γάλα;",
        "brazilian_portuguese": "Obrigado. Vocês têm leite fresco?",
        "mandarin": "谢谢。你们有新鲜牛奶吗？",
        "japanese": "ありがとう。新鮮な牛乳はありますか？",
        "korean": "감사합니다. 신선한 우유 있나요?",
        "hindi": "धन्यवाद। क्या आपके पास ताज़ा दूध है?",
        "vietnamese": "Cảm ơn. Có sữa tươi không?",
        "arabic": "شكراً. هل لديكم حليب طازج؟",
    },
    {
        "line_number": 4, "speaker_name": "Mia",
        "english": "Yes. The milk is next to the eggs.",
        "lithuanian": "Taip. Pienas yra šalia kiaušinių.",
        "latvian": "Jā. Piens ir blakus olām.",
        "estonian": "Jah. Piim on munade kõrval.",
        "german": "Ja. Die Milch ist neben den Eiern.",
        "french": "Oui. Le lait est à côté des œufs.",
        "spanish": "Sí. La leche está junto a los huevos.",
        "italian": "Sì. Il latte è accanto alle uova.",
        "portuguese": "Sim. O leite está ao lado dos ovos.",
        "dutch": "Ja. De melk staat naast de eieren.",
        "polish": "Tak. Mleko jest obok jajek.",
        "ukrainian": "Так. Молоко поруч з яйцями.",
        "russian": "Да. Молоко стоит рядом с яйцами.",
        "swedish": "Ja. Mjölken är bredvid äggen.",
        "norwegian": "Ja. Melken er ved siden av eggene.",
        "danish": "Ja. Mælken er ved siden af æggene.",
        "finnish": "Kyllä. Maito on munien vieressä.",
        "greek": "Ναι. Το γάλα είναι δίπλα στα αυγά.",
        "brazilian_portuguese": "Sim. O leite fica ao lado dos ovos.",
        "mandarin": "是的。牛奶在鸡蛋旁边。",
        "japanese": "はい。牛乳は卵の隣にあります。",
        "korean": "네. 우유는 달걀 옆에 있어요.",
        "hindi": "हाँ। दूध अंडों के पास है।",
        "vietnamese": "Vâng. Sữa ở cạnh trứng.",
        "arabic": "نعم. الحليب بجانب البيض.",
    },
    {
        "line_number": 5, "speaker_name": "Alex",
        "english": "How much is this cheese?",
        "lithuanian": "Kiek kainuoja šis sūris?",
        "latvian": "Cik maksā šis siers?",
        "estonian": "Kui palju see juust maksab?",
        "german": "Wie viel kostet dieser Käse?",
        "french": "Combien coûte ce fromage?",
        "spanish": "¿Cuánto cuesta este queso?",
        "italian": "Quanto costa questo formaggio?",
        "portuguese": "Quanto custa este queijo?",
        "dutch": "Hoeveel kost deze kaas?",
        "polish": "Ile kosztuje ten ser?",
        "ukrainian": "Скільки коштує цей сир?",
        "russian": "Сколько стоит этот сыр?",
        "swedish": "Hur mycket kostar den här osten?",
        "norwegian": "Hvor mye koster denne osten?",
        "danish": "Hvor meget koster denne ost?",
        "finnish": "Kuinka paljon tämä juusto maksaa?",
        "greek": "Πόσο κοστίζει αυτό το τυρί;",
        "brazilian_portuguese": "Quanto custa esse queijo?",
        "mandarin": "这个奶酪多少钱？",
        "japanese": "このチーズはいくらですか？",
        "korean": "이 치즈 얼마예요?",
        "hindi": "यह पनीर कितने का है?",
        "vietnamese": "Phô mai này bao nhiêu tiền?",
        "arabic": "كم سعر هذا الجبن؟",
    },
    {
        "line_number": 6, "speaker_name": "Mia",
        "english": "It is three euros per kilo.",
        "lithuanian": "Tai tris eurai už kilogramą.",
        "latvian": "Tas ir trīs eiro par kilogramu.",
        "estonian": "See on kolm eurot kilogramm.",
        "german": "Es ist drei Euro pro Kilo.",
        "french": "C'est trois euros le kilo.",
        "spanish": "Son tres euros el kilo.",
        "italian": "Sono tre euro al chilo.",
        "portuguese": "São três euros por quilo.",
        "dutch": "Het is drie euro per kilo.",
        "polish": "Trzy euro za kilogram.",
        "ukrainian": "Три євро за кілограм.",
        "russian": "Три евро за килограмм.",
        "swedish": "Det är tre euro per kilo.",
        "norwegian": "Det er tre euro per kilo.",
        "danish": "Det er tre euro per kilo.",
        "finnish": "Se on kolme euroa kilolta.",
        "greek": "Είναι τρία ευρώ το κιλό.",
        "brazilian_portuguese": "São três euros por quilo.",
        "mandarin": "每公斤三欧元。",
        "japanese": "一キロ三ユーロです。",
        "korean": "킬로당 삼 유로입니다.",
        "hindi": "तीन यूरो प्रति किलो।",
        "vietnamese": "Ba euro một kilogram.",
        "arabic": "ثلاثة يورو للكيلو.",
    },
    {
        "line_number": 7, "speaker_name": "Alex",
        "english": "I will take half a kilo please.",
        "lithuanian": "Paimsiu pusę kilogramo prašau.",
        "latvian": "Es ņemšu pus kilogramu lūdzu.",
        "estonian": "Võtan pool kilogrammi palun.",
        "german": "Ich nehme ein halbes Kilo bitte.",
        "french": "Je prends un demi-kilo s'il vous plaît.",
        "spanish": "Tomaré medio kilo por favor.",
        "italian": "Prendo mezzo chilo per favore.",
        "portuguese": "Vou levar meio quilo por favor.",
        "dutch": "Ik neem een halve kilo alstublieft.",
        "polish": "Wezmę pół kilograma proszę.",
        "ukrainian": "Візьму пів кілограма будь ласка.",
        "russian": "Я возьму полкилограмма пожалуйста.",
        "swedish": "Jag tar ett halvt kilo tack.",
        "norwegian": "Jeg tar et halvt kilo takk.",
        "danish": "Jeg tager et halvt kilo tak.",
        "finnish": "Otan puoli kiloa kiitos.",
        "greek": "Θα πάρω μισό κιλό παρακαλώ.",
        "brazilian_portuguese": "Vou levar meio quilo por favor.",
        "mandarin": "请给我半公斤。",
        "japanese": "半キロください。",
        "korean": "반 킬로 주세요.",
        "hindi": "आधा किलो दीजिए।",
        "vietnamese": "Cho tôi nửa kilogram.",
        "arabic": "سآخذ نصف كيلو من فضلك.",
    },
    {
        "line_number": 8, "speaker_name": "Mia",
        "english": "Is that everything?",
        "lithuanian": "Ar tai viskas?",
        "latvian": "Vai tas ir viss?",
        "estonian": "Kas see on kõik?",
        "german": "Ist das alles?",
        "french": "C'est tout?",
        "spanish": "¿Es todo?",
        "italian": "È tutto?",
        "portuguese": "É tudo?",
        "dutch": "Is dat alles?",
        "polish": "Czy to wszystko?",
        "ukrainian": "Це все?",
        "russian": "Это всё?",
        "swedish": "Är det allt?",
        "norwegian": "Er det alt?",
        "danish": "Er det alt?",
        "finnish": "Onko siinä kaikki?",
        "greek": "Είναι όλα;",
        "brazilian_portuguese": "É tudo?",
        "mandarin": "就这些吗？",
        "japanese": "以上でよろしいですか？",
        "korean": "다른 건 없으세요?",
        "hindi": "क्या बस इतना ही है?",
        "vietnamese": "Chỉ vậy thôi à?",
        "arabic": "هل هذا كل شيء؟",
    },
    {
        "line_number": 9, "speaker_name": "Alex",
        "english": "Also one bag of apples please.",
        "lithuanian": "Ir vieną maišelį obuolių prašau.",
        "latvian": "Arī vienu maisiņu ābolu lūdzu.",
        "estonian": "Ja üks kott õunu palun.",
        "german": "Auch eine Tüte Äpfel bitte.",
        "french": "Aussi un sac de pommes s'il vous plaît.",
        "spanish": "También una bolsa de manzanas por favor.",
        "italian": "Anche un sacchetto di mele per favore.",
        "portuguese": "Também um saco de maçãs por favor.",
        "dutch": "Ook een zak appels alstublieft.",
        "polish": "Jeszcze torbę jabłek proszę.",
        "ukrainian": "Ще один пакет яблук будь ласка.",
        "russian": "Ещё пакет яблок пожалуйста.",
        "swedish": "Också en påse äpplen tack.",
        "norwegian": "Også en pose epler takk.",
        "danish": "Også en pose æbler tak.",
        "finnish": "Myös yksi pussi omenoita kiitos.",
        "greek": "Επίσης μια σακούλα μήλα παρακαλώ.",
        "brazilian_portuguese": "Também um saco de maçãs por favor.",
        "mandarin": "还要一袋苹果。",
        "japanese": "リンゴの袋も一つください。",
        "korean": "사과 한 봉지도 주세요.",
        "hindi": "एक थैला सेब भी चाहिए।",
        "vietnamese": "Thêm một túi táo nữa.",
        "arabic": "وأيضاً كيس تفاح من فضلك.",
    },
    {
        "line_number": 10, "speaker_name": "Mia",
        "english": "That is eight euros twenty in total.",
        "lithuanian": "Iš viso aštuoni eurai dvidešimt centų.",
        "latvian": "Kopā tas ir astoņi eiro divdesmit centi.",
        "estonian": "Kokku on see kaheksa eurot kakskümmend senti.",
        "german": "Das sind insgesamt acht Euro zwanzig.",
        "french": "Ça fait huit euros vingt en tout.",
        "spanish": "Son ocho euros veinte en total.",
        "italian": "Sono otto euro e venti in totale.",
        "portuguese": "São oito euros e vinte no total.",
        "dutch": "Dat is acht euro twintig in totaal.",
        "polish": "Razem to osiem euro dwadzieścia.",
        "ukrainian": "Разом вісім євро двадцять.",
        "russian": "Итого восемь евро двадцать.",
        "swedish": "Det är åtta euro tjugo totalt.",
        "norwegian": "Det blir åtte euro tjue totalt.",
        "danish": "Det er otte euro tyve i alt.",
        "finnish": "Se on yhteensä kahdeksan euroa kaksikymmentä senttiä.",
        "greek": "Συνολικά είναι οκτώ ευρώ είκοσι.",
        "brazilian_portuguese": "São oito euros e vinte no total.",
        "mandarin": "总共八欧元二十分。",
        "japanese": "合計で八ユーロ二十セントです。",
        "korean": "총 팔 유로 이십 센트입니다.",
        "hindi": "कुल मिलाकर आठ यूरो बीस सेंट।",
        "vietnamese": "Tổng cộng là tám euro hai mươi xu.",
        "arabic": "المجموع ثمانية يورو وعشرون سنتاً.",
    },
    {
        "line_number": 11, "speaker_name": "Alex",
        "english": "Can I pay by card?",
        "lithuanian": "Ar galiu mokėti kortele?",
        "latvian": "Vai es varu maksāt ar karti?",
        "estonian": "Kas ma saan maksta kaardiga?",
        "german": "Kann ich mit Karte bezahlen?",
        "french": "Puis-je payer par carte?",
        "spanish": "¿Puedo pagar con tarjeta?",
        "italian": "Posso pagare con carta?",
        "portuguese": "Posso pagar com cartão?",
        "dutch": "Kan ik met kaart betalen?",
        "polish": "Czy mogę zapłacić kartą?",
        "ukrainian": "Можна оплатити карткою?",
        "russian": "Можно оплатить картой?",
        "swedish": "Kan jag betala med kort?",
        "norwegian": "Kan jeg betale med kort?",
        "danish": "Kan jeg betale med kort?",
        "finnish": "Voinko maksaa kortilla?",
        "greek": "Μπορώ να πληρώσω με κάρτα;",
        "brazilian_portuguese": "Posso pagar com cartão?",
        "mandarin": "可以刷卡吗？",
        "japanese": "カードで支払えますか？",
        "korean": "카드로 결제할 수 있나요?",
        "hindi": "क्या मैं कार्ड से भुगतान कर सकता हूँ?",
        "vietnamese": "Tôi có thể trả bằng thẻ không?",
        "arabic": "هل يمكنني الدفع بالبطاقة؟",
    },
    {
        "line_number": 12, "speaker_name": "Mia",
        "english": "Yes of course. Have a good day!",
        "lithuanian": "Taip žinoma. Geros dienos!",
        "latvian": "Jā protams. Labu dienu!",
        "estonian": "Jah muidugi. Head päeva!",
        "german": "Ja natürlich. Einen schönen Tag!",
        "french": "Oui bien sûr. Bonne journée!",
        "spanish": "Sí por supuesto. ¡Que tenga buen día!",
        "italian": "Sì certo. Buona giornata!",
        "portuguese": "Sim claro. Tenha um bom dia!",
        "dutch": "Ja natuurlijk. Prettige dag!",
        "polish": "Tak oczywiście. Miłego dnia!",
        "ukrainian": "Так звичайно. Гарного дня!",
        "russian": "Да конечно. Хорошего дня!",
        "swedish": "Ja självklart. Ha en bra dag!",
        "norwegian": "Ja selvfølgelig. Ha en god dag!",
        "danish": "Ja selvfølgelig. Hav en god dag!",
        "finnish": "Kyllä tietysti. Hyvää päivää!",
        "greek": "Ναι φυσικά. Καλή σας μέρα!",
        "brazilian_portuguese": "Sim claro. Tenha um bom dia!",
        "mandarin": "当然可以。祝您有美好的一天！",
        "japanese": "はいもちろんです。よい一日を！",
        "korean": "네 물론이죠. 좋은 하루 되세요!",
        "hindi": "हाँ बिल्कुल। आपका दिन शुभ हो!",
        "vietnamese": "Vâng tất nhiên. Chúc bạn một ngày tốt lành!",
        "arabic": "نعم بالطبع. أتمنى لك يوماً سعيداً!",
    },
]


def seed():
    with app.app_context():
        db.create_all()
        existing = Dialogue.query.filter_by(topic="At the Supermarket").first()
        if existing:
            print("A1 dialogue 'At the Supermarket' already exists — skipping.")
            return

        dialogue = Dialogue(topic="At the Supermarket", lang_level="A1", length=12)
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(dialogue_id=dialogue.id, **line_data)
            db.session.add(line)

        db.session.commit()
        print(f"Seeded A1 dialogue ID {dialogue.id} — 12 lines in 25 languages.")


if __name__ == '__main__':
    seed()
