import sys
import os

# Add your project folder to the path
sys.path.insert(0, os.path.dirname(__file__))

from hello_world import app, db, Dialogue, DialogueLine

# -------------------------------------------------------
# A1 Dialogue — "Meeting a New Friend"
# 30 sentences, 2 speakers: Alex and Mia
# Same names used across all languages
# -------------------------------------------------------

lines_data = [
    {
        "line_number": 1,
        "speaker_name": "Alex",
        "lithuanian": "Labas! Aš esu Aleksas.",
        "latvian": "Sveiks! Es esmu Alekss.",
        "estonian": "Tere! Mina olen Alex.",
        "english": "Hello! I am Alex.",
        "german": "Hallo! Ich bin Alex.",
        "french": "Bonjour! Je suis Alex.",
        "spanish": "¡Hola! Soy Alex.",
        "italian": "Ciao! Sono Alex.",
        "portuguese": "Olá! Eu sou Alex.",
        "dutch": "Hallo! Ik ben Alex.",
        "polish": "Cześć! Jestem Alex.",
        "ukrainian": "Привіт! Я Алекс.",
        "russian": "Привет! Я Алекс.",
        "swedish": "Hej! Jag heter Alex.",
        "norwegian": "Hei! Jeg heter Alex.",
        "danish": "Hej! Jeg hedder Alex.",
        "finnish": "Hei! Olen Alex.",
        "greek": "Γεια! Είμαι ο Άλεξ.",
        "brazilian_portuguese": "Olá! Eu sou Alex.",
        "mandarin": "你好！我叫亚历克斯。",
        "japanese": "こんにちは！私はアレックスです。",
        "korean": "안녕하세요! 저는 알렉스입니다.",
        "hindi": "नमस्ते! मेरा नाम एलेक्स है।",
        "vietnamese": "Xin chào! Tôi là Alex.",
        "arabic": "مرحباً! أنا أليكس.",
    },
    {
        "line_number": 2,
        "speaker_name": "Mia",
        "lithuanian": "Labas, Aleksai! Aš esu Mia. Malonu susipažinti.",
        "latvian": "Sveiks, Alekss! Es esmu Mia. Prieks iepazīties.",
        "estonian": "Tere, Alex! Mina olen Mia. Meeldiv tutvuda.",
        "english": "Hello, Alex! I am Mia. Nice to meet you.",
        "german": "Hallo, Alex! Ich bin Mia. Schön, dich kennenzulernen.",
        "french": "Bonjour, Alex! Je suis Mia. Enchanté.",
        "spanish": "¡Hola, Alex! Soy Mia. Mucho gusto.",
        "italian": "Ciao, Alex! Sono Mia. Piacere di conoscerti.",
        "portuguese": "Olá, Alex! Sou a Mia. Prazer em conhecê-lo.",
        "dutch": "Hallo, Alex! Ik ben Mia. Aangenaam.",
        "polish": "Cześć, Alex! Jestem Mia. Miło cię poznać.",
        "ukrainian": "Привіт, Алексе! Я Міа. Приємно познайомитись.",
        "russian": "Привет, Алекс! Я Миа. Приятно познакомиться.",
        "swedish": "Hej, Alex! Jag heter Mia. Trevligt att träffas.",
        "norwegian": "Hei, Alex! Jeg heter Mia. Hyggelig å møte deg.",
        "danish": "Hej, Alex! Jeg hedder Mia. Rart at møde dig.",
        "finnish": "Hei, Alex! Olen Mia. Hauska tutustua.",
        "greek": "Γεια, Άλεξ! Είμαι η Μία. Χαίρομαι που σε γνωρίζω.",
        "brazilian_portuguese": "Olá, Alex! Sou a Mia. Prazer em te conhecer.",
        "mandarin": "你好，亚历克斯！我叫米亚。很高兴认识你。",
        "japanese": "こんにちは、アレックス！私はミアです。よろしくお願いします。",
        "korean": "안녕하세요, 알렉스! 저는 미아입니다. 만나서 반갑습니다.",
        "hindi": "नमस्ते, एलेक्स! मेरा नाम मिया है। आपसे मिलकर खुशी हुई।",
        "vietnamese": "Xin chào, Alex! Tôi là Mia. Rất vui được gặp bạn.",
        "arabic": "مرحباً يا أليكس! أنا ميا. يسعدني لقاءك.",
    },
    {
        "line_number": 3,
        "speaker_name": "Alex",
        "lithuanian": "Iš kur tu esi, Mia?",
        "latvian": "No kurienes tu esi, Mia?",
        "estonian": "Kust sa pärit oled, Mia?",
        "english": "Where are you from, Mia?",
        "german": "Woher kommst du, Mia?",
        "french": "Tu viens d'où, Mia?",
        "spanish": "¿De dónde eres, Mia?",
        "italian": "Di dove sei, Mia?",
        "portuguese": "De onde és, Mia?",
        "dutch": "Waar kom jij vandaan, Mia?",
        "polish": "Skąd jesteś, Mia?",
        "ukrainian": "Звідки ти, Міа?",
        "russian": "Откуда ты, Миа?",
        "swedish": "Var kommer du ifrån, Mia?",
        "norwegian": "Hvor er du fra, Mia?",
        "danish": "Hvor er du fra, Mia?",
        "finnish": "Mistä olet kotoisin, Mia?",
        "greek": "Από πού είσαι, Μία;",
        "brazilian_portuguese": "De onde você é, Mia?",
        "mandarin": "米亚，你来自哪里？",
        "japanese": "ミア、どこから来ましたか？",
        "korean": "미아, 어디서 왔어요?",
        "hindi": "मिया, आप कहाँ से हैं?",
        "vietnamese": "Mia, bạn đến từ đâu?",
        "arabic": "من أين أنتِ يا ميا؟",
    },
    {
        "line_number": 4,
        "speaker_name": "Mia",
        "lithuanian": "Aš esu iš Ispanijos. O tu?",
        "latvian": "Es esmu no Spānijas. Un tu?",
        "estonian": "Olen Hispaaniast. Aga sina?",
        "english": "I am from Spain. And you?",
        "german": "Ich komme aus Spanien. Und du?",
        "french": "Je viens d'Espagne. Et toi?",
        "spanish": "Soy de España. ¿Y tú?",
        "italian": "Sono della Spagna. E tu?",
        "portuguese": "Sou de Espanha. E tu?",
        "dutch": "Ik kom uit Spanje. En jij?",
        "polish": "Jestem z Hiszpanii. A ty?",
        "ukrainian": "Я з Іспанії. А ти?",
        "russian": "Я из Испании. А ты?",
        "swedish": "Jag kommer från Spanien. Och du?",
        "norwegian": "Jeg er fra Spania. Og du?",
        "danish": "Jeg er fra Spanien. Hvad med dig?",
        "finnish": "Olen Espanjasta. Entä sinä?",
        "greek": "Είμαι από την Ισπανία. Κι εσύ;",
        "brazilian_portuguese": "Sou da Espanha. E você?",
        "mandarin": "我来自西班牙。你呢？",
        "japanese": "私はスペイン出身です。あなたは？",
        "korean": "저는 스페인 출신이에요. 당신은요?",
        "hindi": "मैं स्पेन से हूँ। और आप?",
        "vietnamese": "Tôi đến từ Tây Ban Nha. Còn bạn?",
        "arabic": "أنا من إسبانيا. وأنت؟",
    },
    {
        "line_number": 5,
        "speaker_name": "Alex",
        "lithuanian": "Aš esu iš Lietuvos.",
        "latvian": "Es esmu no Lietuvas.",
        "estonian": "Olen Leedust.",
        "english": "I am from Lithuania.",
        "german": "Ich komme aus Litauen.",
        "french": "Je viens de Lituanie.",
        "spanish": "Soy de Lituania.",
        "italian": "Sono della Lituania.",
        "portuguese": "Sou da Lituânia.",
        "dutch": "Ik kom uit Litouwen.",
        "polish": "Jestem z Litwy.",
        "ukrainian": "Я з Литви.",
        "russian": "Я из Литвы.",
        "swedish": "Jag kommer från Litauen.",
        "norwegian": "Jeg er fra Litauen.",
        "danish": "Jeg er fra Litauen.",
        "finnish": "Olen Liettuasta.",
        "greek": "Είμαι από τη Λιθουανία.",
        "brazilian_portuguese": "Sou da Lituânia.",
        "mandarin": "我来自立陶宛。",
        "japanese": "私はリトアニア出身です。",
        "korean": "저는 리투아니아 출신이에요.",
        "hindi": "मैं लिथुआनिया से हूँ।",
        "vietnamese": "Tôi đến từ Lithuania.",
        "arabic": "أنا من ليتوانيا.",
    },
    {
        "line_number": 6,
        "speaker_name": "Mia",
        "lithuanian": "Ar tu kalbi angliškai?",
        "latvian": "Vai tu runā angliski?",
        "estonian": "Kas sa räägid inglise keelt?",
        "english": "Do you speak English?",
        "german": "Sprichst du Englisch?",
        "french": "Tu parles anglais?",
        "spanish": "¿Hablas inglés?",
        "italian": "Parli inglese?",
        "portuguese": "Falas inglês?",
        "dutch": "Spreek jij Engels?",
        "polish": "Czy mówisz po angielsku?",
        "ukrainian": "Ти розмовляєш англійською?",
        "russian": "Ты говоришь по-английски?",
        "swedish": "Talar du engelska?",
        "norwegian": "Snakker du engelsk?",
        "danish": "Taler du engelsk?",
        "finnish": "Puhutko englantia?",
        "greek": "Μιλάς αγγλικά;",
        "brazilian_portuguese": "Você fala inglês?",
        "mandarin": "你会说英语吗？",
        "japanese": "英語を話せますか？",
        "korean": "영어 할 줄 알아요?",
        "hindi": "क्या आप अंग्रेज़ी बोलते हैं?",
        "vietnamese": "Bạn có nói tiếng Anh không?",
        "arabic": "هل تتكلم الإنجليزية؟",
    },
    {
        "line_number": 7,
        "speaker_name": "Alex",
        "lithuanian": "Taip, šiek tiek. Aš mokausi anglų kalbos.",
        "latvian": "Jā, nedaudz. Es mācos angļu valodu.",
        "estonian": "Jah, natuke. Ma õpin inglise keelt.",
        "english": "Yes, a little. I am learning English.",
        "german": "Ja, ein bisschen. Ich lerne Englisch.",
        "french": "Oui, un peu. J'apprends l'anglais.",
        "spanish": "Sí, un poco. Estoy aprendiendo inglés.",
        "italian": "Sì, un po'. Sto imparando l'inglese.",
        "portuguese": "Sim, um pouco. Estou a aprender inglês.",
        "dutch": "Ja, een beetje. Ik leer Engels.",
        "polish": "Tak, trochę. Uczę się angielskiego.",
        "ukrainian": "Так, трохи. Я вивчаю англійську.",
        "russian": "Да, немного. Я учу английский.",
        "swedish": "Ja, lite. Jag lär mig engelska.",
        "norwegian": "Ja, litt. Jeg lærer engelsk.",
        "danish": "Ja, lidt. Jeg lærer engelsk.",
        "finnish": "Kyllä, vähän. Opiskelen englantia.",
        "greek": "Ναι, λίγο. Μαθαίνω αγγλικά.",
        "brazilian_portuguese": "Sim, um pouco. Estou aprendendo inglês.",
        "mandarin": "是的，一点点。我在学英语。",
        "japanese": "はい、少し。英語を勉強しています。",
        "korean": "네, 조금요. 저는 영어를 배우고 있어요.",
        "hindi": "हाँ, थोड़ा। मैं अंग्रेज़ी सीख रहा हूँ।",
        "vietnamese": "Có, một chút. Tôi đang học tiếng Anh.",
        "arabic": "نعم، قليلاً. أنا أتعلم الإنجليزية.",
    },
    {
        "line_number": 8,
        "speaker_name": "Mia",
        "lithuanian": "Kiek tau metų?",
        "latvian": "Cik tev gadu?",
        "estonian": "Kui vana sa oled?",
        "english": "How old are you?",
        "german": "Wie alt bist du?",
        "french": "Tu as quel âge?",
        "spanish": "¿Cuántos años tienes?",
        "italian": "Quanti anni hai?",
        "portuguese": "Quantos anos tens?",
        "dutch": "Hoe oud ben jij?",
        "polish": "Ile masz lat?",
        "ukrainian": "Скільки тобі років?",
        "russian": "Сколько тебе лет?",
        "swedish": "Hur gammal är du?",
        "norwegian": "Hvor gammel er du?",
        "danish": "Hvor gammel er du?",
        "finnish": "Kuinka vanha olet?",
        "greek": "Πόσο χρονών είσαι;",
        "brazilian_portuguese": "Quantos anos você tem?",
        "mandarin": "你多大了？",
        "japanese": "何歳ですか？",
        "korean": "몇 살이에요?",
        "hindi": "आपकी उम्र कितनी है?",
        "vietnamese": "Bạn bao nhiêu tuổi?",
        "arabic": "كم عمرك؟",
    },
    {
        "line_number": 9,
        "speaker_name": "Alex",
        "lithuanian": "Man yra dvidešimt metų. O tau?",
        "latvian": "Man ir divdesmit gadu. Un tev?",
        "estonian": "Mul on kakskümmend aastat. Aga sul?",
        "english": "I am twenty years old. And you?",
        "german": "Ich bin zwanzig Jahre alt. Und du?",
        "french": "J'ai vingt ans. Et toi?",
        "spanish": "Tengo veinte años. ¿Y tú?",
        "italian": "Ho vent'anni. E tu?",
        "portuguese": "Tenho vinte anos. E tu?",
        "dutch": "Ik ben twintig jaar oud. En jij?",
        "polish": "Mam dwadzieścia lat. A ty?",
        "ukrainian": "Мені двадцять років. А тобі?",
        "russian": "Мне двадцать лет. А тебе?",
        "swedish": "Jag är tjugo år gammal. Och du?",
        "norwegian": "Jeg er tjue år gammel. Og du?",
        "danish": "Jeg er tyve år gammel. Hvad med dig?",
        "finnish": "Olen kaksikymmentä vuotta vanha. Entä sinä?",
        "greek": "Είμαι είκοσι χρονών. Κι εσύ;",
        "brazilian_portuguese": "Tenho vinte anos. E você?",
        "mandarin": "我二十岁。你呢？",
        "japanese": "私は二十歳です。あなたは？",
        "korean": "저는 스무 살이에요. 당신은요?",
        "hindi": "मैं बीस साल का हूँ। और आप?",
        "vietnamese": "Tôi hai mươi tuổi. Còn bạn?",
        "arabic": "عمري عشرون عاماً. وأنت؟",
    },
    {
        "line_number": 10,
        "speaker_name": "Mia",
        "lithuanian": "Man yra aštuoniolika metų.",
        "latvian": "Man ir astoņpadsmit gadu.",
        "estonian": "Mul on kaheksateist aastat.",
        "english": "I am eighteen years old.",
        "german": "Ich bin achtzehn Jahre alt.",
        "french": "J'ai dix-huit ans.",
        "spanish": "Tengo dieciocho años.",
        "italian": "Ho diciotto anni.",
        "portuguese": "Tenho dezoito anos.",
        "dutch": "Ik ben achttien jaar oud.",
        "polish": "Mam osiemnaście lat.",
        "ukrainian": "Мені вісімнадцять років.",
        "russian": "Мне восемнадцать лет.",
        "swedish": "Jag är arton år gammal.",
        "norwegian": "Jeg er atten år gammel.",
        "danish": "Jeg er atten år gammel.",
        "finnish": "Olen kahdeksantoista vuotta vanha.",
        "greek": "Είμαι δεκαοχτώ χρονών.",
        "brazilian_portuguese": "Tenho dezoito anos.",
        "mandarin": "我十八岁。",
        "japanese": "私は十八歳です。",
        "korean": "저는 열여덟 살이에요.",
        "hindi": "मैं अठारह साल की हूँ।",
        "vietnamese": "Tôi mười tám tuổi.",
        "arabic": "عمري ثمانية عشر عاماً.",
    },
    {
        "line_number": 11,
        "speaker_name": "Alex",
        "lithuanian": "Ką tu veiki?",
        "latvian": "Ko tu dari?",
        "estonian": "Mis sa teed?",
        "english": "What do you do?",
        "german": "Was machst du?",
        "french": "Qu'est-ce que tu fais?",
        "spanish": "¿A qué te dedicas?",
        "italian": "Cosa fai?",
        "portuguese": "O que fazes?",
        "dutch": "Wat doe jij?",
        "polish": "Czym się zajmujesz?",
        "ukrainian": "Чим ти займаєшся?",
        "russian": "Чем ты занимаешься?",
        "swedish": "Vad gör du?",
        "norwegian": "Hva gjør du?",
        "danish": "Hvad laver du?",
        "finnish": "Mitä teet?",
        "greek": "Τι κάνεις;",
        "brazilian_portuguese": "O que você faz?",
        "mandarin": "你是做什么的？",
        "japanese": "何をしていますか？",
        "korean": "무슨 일을 해요?",
        "hindi": "आप क्या करते हैं?",
        "vietnamese": "Bạn làm gì?",
        "arabic": "ماذا تفعل؟",
    },
    {
        "line_number": 12,
        "speaker_name": "Mia",
        "lithuanian": "Aš esu studentė. Studijuoju kalbas.",
        "latvian": "Es esmu studente. Studēju valodas.",
        "estonian": "Olen üliõpilane. Õpin keeli.",
        "english": "I am a student. I study languages.",
        "german": "Ich bin Studentin. Ich studiere Sprachen.",
        "french": "Je suis étudiante. J'étudie les langues.",
        "spanish": "Soy estudiante. Estudio idiomas.",
        "italian": "Sono studentessa. Studio le lingue.",
        "portuguese": "Sou estudante. Estudo línguas.",
        "dutch": "Ik ben studente. Ik studeer talen.",
        "polish": "Jestem studentką. Studiuję języki.",
        "ukrainian": "Я студентка. Я вивчаю мови.",
        "russian": "Я студентка. Я изучаю языки.",
        "swedish": "Jag är student. Jag studerar språk.",
        "norwegian": "Jeg er student. Jeg studerer språk.",
        "danish": "Jeg er studerende. Jeg studerer sprog.",
        "finnish": "Olen opiskelija. Opiskelen kieliä.",
        "greek": "Είμαι φοιτήτρια. Σπουδάζω γλώσσες.",
        "brazilian_portuguese": "Sou estudante. Estudo idiomas.",
        "mandarin": "我是学生。我学习语言。",
        "japanese": "私は学生です。言語を勉強しています。",
        "korean": "저는 학생이에요. 언어를 공부해요.",
        "hindi": "मैं एक छात्रा हूँ। मैं भाषाएँ पढ़ती हूँ।",
        "vietnamese": "Tôi là sinh viên. Tôi học ngôn ngữ.",
        "arabic": "أنا طالبة. أدرس اللغات.",
    },
    {
        "line_number": 13,
        "speaker_name": "Alex",
        "lithuanian": "Tai įdomu! Kokias kalbas tu kalbi?",
        "latvian": "Tas ir interesanti! Kādas valodas tu runā?",
        "estonian": "See on huvitav! Mis keeli sa räägid?",
        "english": "That is interesting! What languages do you speak?",
        "german": "Das ist interessant! Welche Sprachen sprichst du?",
        "french": "C'est intéressant! Quelles langues parles-tu?",
        "spanish": "¡Qué interesante! ¿Qué idiomas hablas?",
        "italian": "Che interessante! Quali lingue parli?",
        "portuguese": "Que interessante! Que línguas falas?",
        "dutch": "Dat is interessant! Welke talen spreek jij?",
        "polish": "To ciekawe! Jakimi językami mówisz?",
        "ukrainian": "Це цікаво! Якими мовами ти розмовляєш?",
        "russian": "Это интересно! На каких языках ты говоришь?",
        "swedish": "Det är intressant! Vilka språk talar du?",
        "norwegian": "Det er interessant! Hvilke språk snakker du?",
        "danish": "Det er interessant! Hvilke sprog taler du?",
        "finnish": "Se on mielenkiintoista! Mitä kieliä puhut?",
        "greek": "Αυτό είναι ενδιαφέρον! Τι γλώσσες μιλάς;",
        "brazilian_portuguese": "Que interessante! Que idiomas você fala?",
        "mandarin": "真有趣！你会说哪些语言？",
        "japanese": "面白いですね！どんな言語を話しますか？",
        "korean": "흥미롭네요! 어떤 언어를 할 줄 알아요?",
        "hindi": "यह दिलचस्प है! आप कौन सी भाषाएँ बोलते हैं?",
        "vietnamese": "Thú vị quá! Bạn nói được những ngôn ngữ nào?",
        "arabic": "هذا مثير للاهتمام! ما اللغات التي تتحدثها؟",
    },
    {
        "line_number": 14,
        "speaker_name": "Mia",
        "lithuanian": "Aš kalbu ispaniškai, angliškai ir šiek tiek prancūziškai.",
        "latvian": "Es runāju spāniski, angliski un nedaudz franciski.",
        "estonian": "Räägin hispaania, inglise ja natuke prantsuse keelt.",
        "english": "I speak Spanish, English and a little French.",
        "german": "Ich spreche Spanisch, Englisch und ein bisschen Französisch.",
        "french": "Je parle espagnol, anglais et un peu français.",
        "spanish": "Hablo español, inglés y un poco de francés.",
        "italian": "Parlo spagnolo, inglese e un po' di francese.",
        "portuguese": "Falo espanhol, inglês e um pouco de francês.",
        "dutch": "Ik spreek Spaans, Engels en een beetje Frans.",
        "polish": "Mówię po hiszpańsku, angielsku i trochę po francusku.",
        "ukrainian": "Я розмовляю іспанською, англійською та трохи французькою.",
        "russian": "Я говорю по-испански, по-английски и немного по-французски.",
        "swedish": "Jag talar spanska, engelska och lite franska.",
        "norwegian": "Jeg snakker spansk, engelsk og litt fransk.",
        "danish": "Jeg taler spansk, engelsk og lidt fransk.",
        "finnish": "Puhun espanjaa, englantia ja vähän ranskaa.",
        "greek": "Μιλώ ισπανικά, αγγλικά και λίγο γαλλικά.",
        "brazilian_portuguese": "Falo espanhol, inglês e um pouco de francês.",
        "mandarin": "我会说西班牙语、英语，还会一点法语。",
        "japanese": "スペイン語、英語、そして少しフランス語を話します。",
        "korean": "저는 스페인어, 영어, 그리고 조금 프랑스어를 해요.",
        "hindi": "मैं स्पेनिश, अंग्रेज़ी और थोड़ी फ्रेंच बोलती हूँ।",
        "vietnamese": "Tôi nói tiếng Tây Ban Nha, tiếng Anh và một chút tiếng Pháp.",
        "arabic": "أتحدث الإسبانية والإنجليزية وقليلاً من الفرنسية.",
    },
    {
        "line_number": 15,
        "speaker_name": "Alex",
        "lithuanian": "Ar tu mėgsti keliauti?",
        "latvian": "Vai tev patīk ceļot?",
        "estonian": "Kas sulle meeldib reisida?",
        "english": "Do you like to travel?",
        "german": "Reist du gerne?",
        "french": "Tu aimes voyager?",
        "spanish": "¿Te gusta viajar?",
        "italian": "Ti piace viaggiare?",
        "portuguese": "Gostas de viajar?",
        "dutch": "Hou jij van reizen?",
        "polish": "Czy lubisz podróżować?",
        "ukrainian": "Ти любиш подорожувати?",
        "russian": "Ты любишь путешествовать?",
        "swedish": "Gillar du att resa?",
        "norwegian": "Liker du å reise?",
        "danish": "Kan du lide at rejse?",
        "finnish": "Pidätkö matkustamisesta?",
        "greek": "Σου αρέσει να ταξιδεύεις;",
        "brazilian_portuguese": "Você gosta de viajar?",
        "mandarin": "你喜欢旅行吗？",
        "japanese": "旅行が好きですか？",
        "korean": "여행을 좋아해요?",
        "hindi": "क्या आपको यात्रा करना पसंद है?",
        "vietnamese": "Bạn có thích du lịch không?",
        "arabic": "هل تحب السفر؟",
    },
    {
        "line_number": 16,
        "speaker_name": "Mia",
        "lithuanian": "Taip, labai! Aš jau buvau daugelyje šalių.",
        "latvian": "Jā, ļoti! Esmu bijusi daudzās valstīs.",
        "estonian": "Jah, väga! Olen olnud paljudes riikides.",
        "english": "Yes, very much! I have been to many countries.",
        "german": "Ja, sehr! Ich war schon in vielen Ländern.",
        "french": "Oui, beaucoup! J'ai visité beaucoup de pays.",
        "spanish": "¡Sí, mucho! He viajado a muchos países.",
        "italian": "Sì, molto! Sono stata in molti paesi.",
        "portuguese": "Sim, muito! Já fui a muitos países.",
        "dutch": "Ja, heel erg! Ik ben al in veel landen geweest.",
        "polish": "Tak, bardzo! Byłam w wielu krajach.",
        "ukrainian": "Так, дуже! Я була в багатьох країнах.",
        "russian": "Да, очень! Я была во многих странах.",
        "swedish": "Ja, väldigt mycket! Jag har besökt många länder.",
        "norwegian": "Ja, veldig mye! Jeg har vært i mange land.",
        "danish": "Ja, rigtig meget! Jeg har været i mange lande.",
        "finnish": "Kyllä, todella! Olen käynyt monissa maissa.",
        "greek": "Ναι, πολύ! Έχω πάει σε πολλές χώρες.",
        "brazilian_portuguese": "Sim, muito! Já estive em muitos países.",
        "mandarin": "是的，非常喜欢！我去过很多国家。",
        "japanese": "はい、とても好きです！多くの国に行ったことがあります。",
        "korean": "네, 아주 좋아해요! 많은 나라에 가봤어요.",
        "hindi": "हाँ, बहुत! मैं कई देशों में जा चुकी हूँ।",
        "vietnamese": "Có, rất thích! Tôi đã đến nhiều quốc gia.",
        "arabic": "نعم، كثيراً! لقد زرت دولاً كثيرة.",
    },
    {
        "line_number": 17,
        "speaker_name": "Alex",
        "lithuanian": "Kokia yra tavo mėgstamiausia šalis?",
        "latvian": "Kura ir tava mīļākā valsts?",
        "estonian": "Mis on sinu lemmikribik?",
        "english": "What is your favourite country?",
        "german": "Was ist dein Lieblingsland?",
        "french": "Quel est ton pays préféré?",
        "spanish": "¿Cuál es tu país favorito?",
        "italian": "Qual è il tuo paese preferito?",
        "portuguese": "Qual é o teu país favorito?",
        "dutch": "Wat is jouw favoriete land?",
        "polish": "Jaki jest twój ulubiony kraj?",
        "ukrainian": "Яка твоя улюблена країна?",
        "russian": "Какая твоя любимая страна?",
        "swedish": "Vilket är ditt favoritland?",
        "norwegian": "Hva er ditt favorittland?",
        "danish": "Hvad er dit yndlingsland?",
        "finnish": "Mikä on suosikkimaasi?",
        "greek": "Ποια είναι η αγαπημένη σου χώρα;",
        "brazilian_portuguese": "Qual é o seu país favorito?",
        "mandarin": "你最喜欢哪个国家？",
        "japanese": "あなたの好きな国はどこですか？",
        "korean": "가장 좋아하는 나라가 어디예요?",
        "hindi": "आपका पसंदीदा देश कौन सा है?",
        "vietnamese": "Đất nước yêu thích của bạn là gì?",
        "arabic": "ما هي دولتك المفضلة؟",
    },
    {
        "line_number": 18,
        "speaker_name": "Mia",
        "lithuanian": "Man labai patinka Japonija. Ji yra nuostabi.",
        "latvian": "Man ļoti patīk Japāna. Tā ir brīnišķīga.",
        "estonian": "Mulle meeldib väga Jaapan. See on imeline.",
        "english": "I really like Japan. It is wonderful.",
        "german": "Ich mag Japan sehr. Es ist wunderbar.",
        "french": "J'aime vraiment le Japon. C'est magnifique.",
        "spanish": "Me gusta mucho Japón. Es maravilloso.",
        "italian": "Mi piace molto il Giappone. È meraviglioso.",
        "portuguese": "Gosto muito do Japão. É maravilhoso.",
        "dutch": "Ik hou heel veel van Japan. Het is geweldig.",
        "polish": "Bardzo lubię Japonię. Jest wspaniała.",
        "ukrainian": "Мені дуже подобається Японія. Вона чудова.",
        "russian": "Мне очень нравится Япония. Она замечательная.",
        "swedish": "Jag gillar Japan verkligen. Det är underbart.",
        "norwegian": "Jeg liker virkelig Japan. Det er vidunderlig.",
        "danish": "Jeg kan virkelig godt lide Japan. Det er vidunderligt.",
        "finnish": "Pidän todella paljon Japanista. Se on ihana.",
        "greek": "Μου αρέσει πολύ η Ιαπωνία. Είναι υπέροχη.",
        "brazilian_portuguese": "Eu gosto muito do Japão. É maravilhoso.",
        "mandarin": "我非常喜欢日本。它太美妙了。",
        "japanese": "日本がとても好きです。素晴らしいです。",
        "korean": "저는 일본을 정말 좋아해요. 멋져요.",
        "hindi": "मुझे जापान बहुत पसंद है। यह अद्भुत है।",
        "vietnamese": "Tôi rất thích Nhật Bản. Thật tuyệt vời.",
        "arabic": "أحب اليابان كثيراً. إنها رائعة.",
    },
    {
        "line_number": 19,
        "speaker_name": "Alex",
        "lithuanian": "Ar tu mėgsti maistą?",
        "latvian": "Vai tev patīk ēdiens?",
        "estonian": "Kas sulle meeldib toit?",
        "english": "Do you like food?",
        "german": "Magst du Essen?",
        "french": "Tu aimes la nourriture?",
        "spanish": "¿Te gusta la comida?",
        "italian": "Ti piace il cibo?",
        "portuguese": "Gostas de comida?",
        "dutch": "Hou jij van eten?",
        "polish": "Czy lubisz jedzenie?",
        "ukrainian": "Ти любиш їжу?",
        "russian": "Ты любишь еду?",
        "swedish": "Gillar du mat?",
        "norwegian": "Liker du mat?",
        "danish": "Kan du lide mad?",
        "finnish": "Pidätkö ruoasta?",
        "greek": "Σου αρέσει το φαγητό;",
        "brazilian_portuguese": "Você gosta de comida?",
        "mandarin": "你喜欢美食吗？",
        "japanese": "食べ物が好きですか？",
        "korean": "음식을 좋아해요?",
        "hindi": "क्या आपको खाना पसंद है?",
        "vietnamese": "Bạn có thích ăn uống không?",
        "arabic": "هل تحب الطعام؟",
    },
    {
        "line_number": 20,
        "speaker_name": "Mia",
        "lithuanian": "Taip! Aš ypač mėgstu itališką maistą.",
        "latvian": "Jā! Es īpaši mīlu itāļu ēdienu.",
        "estonian": "Jah! Eriti meeldib mulle Itaalia toit.",
        "english": "Yes! I especially love Italian food.",
        "german": "Ja! Ich liebe besonders italienisches Essen.",
        "french": "Oui! J'adore surtout la cuisine italienne.",
        "spanish": "¡Sí! Me encanta especialmente la comida italiana.",
        "italian": "Sì! Adoro soprattutto il cibo italiano.",
        "portuguese": "Sim! Adoro especialmente a comida italiana.",
        "dutch": "Ja! Ik hou especially van Italiaans eten.",
        "polish": "Tak! Szczególnie uwielbiam włoskie jedzenie.",
        "ukrainian": "Так! Особливо люблю італійську їжу.",
        "russian": "Да! Особенно люблю итальянскую кухню.",
        "swedish": "Ja! Jag älskar särskilt italiensk mat.",
        "norwegian": "Ja! Jeg elsker spesielt italiensk mat.",
        "danish": "Ja! Jeg elsker især italiensk mad.",
        "finnish": "Kyllä! Erityisesti rakastan italialaista ruokaa.",
        "greek": "Ναι! Αγαπώ ιδιαίτερα την ιταλική κουζίνα.",
        "brazilian_portuguese": "Sim! Adoro especialmente a comida italiana.",
        "mandarin": "是的！我特别喜欢意大利食物。",
        "japanese": "はい！特にイタリア料理が大好きです。",
        "korean": "네! 특히 이탈리아 음식을 좋아해요.",
        "hindi": "हाँ! मुझे खासतौर पर इटालियन खाना बहुत पसंद है।",
        "vietnamese": "Có! Tôi đặc biệt thích đồ ăn Ý.",
        "arabic": "نعم! أحب الطعام الإيطالي بشكل خاص.",
    },
    {
        "line_number": 21,
        "speaker_name": "Alex",
        "lithuanian": "Ar tu turi brolių ar seserų?",
        "latvian": "Vai tev ir brāļi vai māsas?",
        "estonian": "Kas sul on õdesid-vendasid?",
        "english": "Do you have brothers or sisters?",
        "german": "Hast du Geschwister?",
        "french": "Tu as des frères ou des sœurs?",
        "spanish": "¿Tienes hermanos o hermanas?",
        "italian": "Hai fratelli o sorelle?",
        "portuguese": "Tens irmãos ou irmãs?",
        "dutch": "Heb jij broers of zussen?",
        "polish": "Czy masz rodzeństwo?",
        "ukrainian": "У тебе є брати чи сестри?",
        "russian": "У тебя есть братья или сёстры?",
        "swedish": "Har du syskon?",
        "norwegian": "Har du søsken?",
        "danish": "Har du søskende?",
        "finnish": "Onko sinulla sisaruksia?",
        "greek": "Έχεις αδέρφια;",
        "brazilian_portuguese": "Você tem irmãos ou irmãs?",
        "mandarin": "你有兄弟姐妹吗？",
        "japanese": "兄弟や姉妹はいますか？",
        "korean": "형제자매가 있어요?",
        "hindi": "क्या आपके भाई-बहन हैं?",
        "vietnamese": "Bạn có anh chị em không?",
        "arabic": "هل لديك إخوة أو أخوات؟",
    },
    {
        "line_number": 22,
        "speaker_name": "Mia",
        "lithuanian": "Taip, turiu vieną brolį ir vieną seserį.",
        "latvian": "Jā, man ir viens brālis un viena māsa.",
        "estonian": "Jah, mul on üks vend ja üks õde.",
        "english": "Yes, I have one brother and one sister.",
        "german": "Ja, ich habe einen Bruder und eine Schwester.",
        "french": "Oui, j'ai un frère et une sœur.",
        "spanish": "Sí, tengo un hermano y una hermana.",
        "italian": "Sì, ho un fratello e una sorella.",
        "portuguese": "Sim, tenho um irmão e uma irmã.",
        "dutch": "Ja, ik heb één broer en één zus.",
        "polish": "Tak, mam jednego brata i jedną siostrę.",
        "ukrainian": "Так, у мене є один брат і одна сестра.",
        "russian": "Да, у меня есть один брат и одна сестра.",
        "swedish": "Ja, jag har en bror och en syster.",
        "norwegian": "Ja, jeg har en bror og en søster.",
        "danish": "Ja, jeg har en bror og en søster.",
        "finnish": "Kyllä, minulla on yksi veli ja yksi sisar.",
        "greek": "Ναι, έχω έναν αδερφό και μία αδερφή.",
        "brazilian_portuguese": "Sim, tenho um irmão e uma irmã.",
        "mandarin": "是的，我有一个兄弟和一个姐妹。",
        "japanese": "はい、兄が一人と姉が一人います。",
        "korean": "네, 남동생 한 명과 여동생 한 명이 있어요.",
        "hindi": "हाँ, मेरा एक भाई और एक बहन है।",
        "vietnamese": "Có, tôi có một anh trai và một chị gái.",
        "arabic": "نعم، لدي أخ واحد وأخت واحدة.",
    },
    {
        "line_number": 23,
        "speaker_name": "Alex",
        "lithuanian": "Kur tu gyveni?",
        "latvian": "Kur tu dzīvo?",
        "estonian": "Kus sa elad?",
        "english": "Where do you live?",
        "german": "Wo wohnst du?",
        "french": "Où habites-tu?",
        "spanish": "¿Dónde vives?",
        "italian": "Dove vivi?",
        "portuguese": "Onde moras?",
        "dutch": "Waar woon jij?",
        "polish": "Gdzie mieszkasz?",
        "ukrainian": "Де ти живеш?",
        "russian": "Где ты живёшь?",
        "swedish": "Var bor du?",
        "norwegian": "Hvor bor du?",
        "danish": "Hvor bor du?",
        "finnish": "Missä asut?",
        "greek": "Πού μένεις;",
        "brazilian_portuguese": "Onde você mora?",
        "mandarin": "你住在哪里？",
        "japanese": "どこに住んでいますか？",
        "korean": "어디 살아요?",
        "hindi": "आप कहाँ रहते हैं?",
        "vietnamese": "Bạn sống ở đâu?",
        "arabic": "أين تعيش؟",
    },
    {
        "line_number": 24,
        "speaker_name": "Mia",
        "lithuanian": "Aš gyvenu Madride. Tai didelis miestas.",
        "latvian": "Es dzīvoju Madridē. Tā ir liela pilsēta.",
        "estonian": "Elan Madridis. See on suur linn.",
        "english": "I live in Madrid. It is a big city.",
        "german": "Ich wohne in Madrid. Es ist eine große Stadt.",
        "french": "J'habite à Madrid. C'est une grande ville.",
        "spanish": "Vivo en Madrid. Es una ciudad grande.",
        "italian": "Vivo a Madrid. È una grande città.",
        "portuguese": "Moro em Madrid. É uma cidade grande.",
        "dutch": "Ik woon in Madrid. Het is een grote stad.",
        "polish": "Mieszkam w Madrycie. To duże miasto.",
        "ukrainian": "Я живу в Мадриді. Це велике місто.",
        "russian": "Я живу в Мадриде. Это большой город.",
        "swedish": "Jag bor i Madrid. Det är en stor stad.",
        "norwegian": "Jeg bor i Madrid. Det er en stor by.",
        "danish": "Jeg bor i Madrid. Det er en stor by.",
        "finnish": "Asun Madridissa. Se on iso kaupunki.",
        "greek": "Μένω στη Μαδρίτη. Είναι μια μεγάλη πόλη.",
        "brazilian_portuguese": "Moro em Madri. É uma cidade grande.",
        "mandarin": "我住在马德里。这是一座大城市。",
        "japanese": "マドリードに住んでいます。大きな街です。",
        "korean": "저는 마드리드에 살아요. 큰 도시예요.",
        "hindi": "मैं मैड्रिड में रहती हूँ। यह एक बड़ा शहर है।",
        "vietnamese": "Tôi sống ở Madrid. Đó là một thành phố lớn.",
        "arabic": "أعيش في مدريد. إنها مدينة كبيرة.",
    },
    {
        "line_number": 25,
        "speaker_name": "Alex",
        "lithuanian": "Ar tau patinka gyventi Madride?",
        "latvian": "Vai tev patīk dzīvot Madridē?",
        "estonian": "Kas sulle meeldib Madridis elada?",
        "english": "Do you like living in Madrid?",
        "german": "Magst du es, in Madrid zu wohnen?",
        "french": "Tu aimes vivre à Madrid?",
        "spanish": "¿Te gusta vivir en Madrid?",
        "italian": "Ti piace vivere a Madrid?",
        "portuguese": "Gostas de viver em Madrid?",
        "dutch": "Woon jij graag in Madrid?",
        "polish": "Czy lubisz mieszkać w Madrycie?",
        "ukrainian": "Тобі подобається жити в Мадриді?",
        "russian": "Тебе нравится жить в Мадриде?",
        "swedish": "Gillar du att bo i Madrid?",
        "norwegian": "Liker du å bo i Madrid?",
        "danish": "Kan du lide at bo i Madrid?",
        "finnish": "Pidätkö Madridissa asumisesta?",
        "greek": "Σου αρέσει να μένεις στη Μαδρίτη;",
        "brazilian_portuguese": "Você gosta de morar em Madri?",
        "mandarin": "你喜欢住在马德里吗？",
        "japanese": "マドリードに住むのは好きですか？",
        "korean": "마드리드에서 사는 것이 좋아요?",
        "hindi": "क्या आपको मैड्रिड में रहना पसंद है?",
        "vietnamese": "Bạn có thích sống ở Madrid không?",
        "arabic": "هل تحب العيش في مدريد؟",
    },
    {
        "line_number": 26,
        "speaker_name": "Mia",
        "lithuanian": "Taip, labai! Oras čia visada geras.",
        "latvian": "Jā, ļoti! Laiks šeit vienmēr ir labs.",
        "estonian": "Jah, väga! Ilm on siin alati hea.",
        "english": "Yes, very much! The weather is always nice here.",
        "german": "Ja, sehr! Das Wetter ist hier immer schön.",
        "french": "Oui, beaucoup! Le temps est toujours beau ici.",
        "spanish": "¡Sí, mucho! El tiempo siempre es bueno aquí.",
        "italian": "Sì, molto! Il tempo è sempre bello qui.",
        "portuguese": "Sim, muito! O tempo é sempre bom aqui.",
        "dutch": "Ja, heel erg! Het weer is hier altijd mooi.",
        "polish": "Tak, bardzo! Pogoda jest tu zawsze dobra.",
        "ukrainian": "Так, дуже! Погода тут завжди гарна.",
        "russian": "Да, очень! Погода здесь всегда хорошая.",
        "swedish": "Ja, väldigt mycket! Vädret är alltid fint här.",
        "norwegian": "Ja, veldig mye! Været er alltid fint her.",
        "danish": "Ja, rigtig meget! Vejret er altid godt her.",
        "finnish": "Kyllä, todella! Sää on täällä aina hyvä.",
        "greek": "Ναι, πολύ! Ο καιρός εδώ είναι πάντα ωραίος.",
        "brazilian_portuguese": "Sim, muito! O tempo aqui é sempre bom.",
        "mandarin": "是的，非常喜欢！这里的天气总是很好。",
        "japanese": "はい、とても！ここはいつも天気がいいです。",
        "korean": "네, 아주요! 여기는 날씨가 항상 좋아요.",
        "hindi": "हाँ, बहुत! यहाँ का मौसम हमेशा अच्छा रहता है।",
        "vietnamese": "Có, rất thích! Thời tiết ở đây luôn đẹp.",
        "arabic": "نعم، كثيراً! الطقس هنا دائماً جميل.",
    },
    {
        "line_number": 27,
        "speaker_name": "Alex",
        "lithuanian": "Ką tu veiki laisvalaikiu?",
        "latvian": "Ko tu dari brīvajā laikā?",
        "estonian": "Mida sa vabal ajal teed?",
        "english": "What do you do in your free time?",
        "german": "Was machst du in deiner Freizeit?",
        "french": "Que fais-tu pendant ton temps libre?",
        "spanish": "¿Qué haces en tu tiempo libre?",
        "italian": "Cosa fai nel tempo libero?",
        "portuguese": "O que fazes nos teus tempos livres?",
        "dutch": "Wat doe jij in je vrije tijd?",
        "polish": "Co robisz w wolnym czasie?",
        "ukrainian": "Що ти робиш у вільний час?",
        "russian": "Что ты делаешь в свободное время?",
        "swedish": "Vad gör du på din fritid?",
        "norwegian": "Hva gjør du på fritiden?",
        "danish": "Hvad laver du i din fritid?",
        "finnish": "Mitä teet vapaa-ajalla?",
        "greek": "Τι κάνεις στον ελεύθερο χρόνο σου;",
        "brazilian_portuguese": "O que você faz no seu tempo livre?",
        "mandarin": "你空闲时间做什么？",
        "japanese": "自由な時間に何をしますか？",
        "korean": "자유 시간에 뭐 해요?",
        "hindi": "आप खाली समय में क्या करते हैं?",
        "vietnamese": "Bạn làm gì trong thời gian rảnh?",
        "arabic": "ماذا تفعل في وقت فراغك؟",
    },
    {
        "line_number": 28,
        "speaker_name": "Mia",
        "lithuanian": "Aš mėgstu skaityti knygas ir klausytis muzikos.",
        "latvian": "Man patīk lasīt grāmatas un klausīties mūziku.",
        "estonian": "Mulle meeldib lugeda raamatuid ja kuulata muusikat.",
        "english": "I like to read books and listen to music.",
        "german": "Ich lese gerne Bücher und höre Musik.",
        "french": "J'aime lire des livres et écouter de la musique.",
        "spanish": "Me gusta leer libros y escuchar música.",
        "italian": "Mi piace leggere libri e ascoltare musica.",
        "portuguese": "Gosto de ler livros e ouvir música.",
        "dutch": "Ik lees graag boeken en luister naar muziek.",
        "polish": "Lubię czytać książki i słuchać muzyki.",
        "ukrainian": "Я люблю читати книги та слухати музику.",
        "russian": "Я люблю читать книги и слушать музыку.",
        "swedish": "Jag läser gärna böcker och lyssnar på musik.",
        "norwegian": "Jeg liker å lese bøker og høre på musikk.",
        "danish": "Jeg kan godt lide at læse bøger og lytte til musik.",
        "finnish": "Pidän kirjojen lukemisesta ja musiikin kuuntelusta.",
        "greek": "Μου αρέσει να διαβάζω βιβλία και να ακούω μουσική.",
        "brazilian_portuguese": "Gosto de ler livros e ouvir música.",
        "mandarin": "我喜欢读书和听音乐。",
        "japanese": "本を読んだり音楽を聴いたりするのが好きです。",
        "korean": "저는 책을 읽고 음악을 듣는 것을 좋아해요.",
        "hindi": "मुझे किताबें पढ़ना और संगीत सुनना पसंद है।",
        "vietnamese": "Tôi thích đọc sách và nghe nhạc.",
        "arabic": "أحب قراءة الكتب والاستماع إلى الموسيقى.",
    },
    {
        "line_number": 29,
        "speaker_name": "Alex",
        "lithuanian": "Ar tu turi gyvūną?",
        "latvian": "Vai tev ir mājdzīvnieks?",
        "estonian": "Kas sul on lemmikloom?",
        "english": "Do you have a pet?",
        "german": "Hast du ein Haustier?",
        "french": "Tu as un animal de compagnie?",
        "spanish": "¿Tienes una mascota?",
        "italian": "Hai un animale domestico?",
        "portuguese": "Tens um animal de estimação?",
        "dutch": "Heb jij een huisdier?",
        "polish": "Czy masz zwierzę domowe?",
        "ukrainian": "У тебе є домашня тварина?",
        "russian": "У тебя есть домашнее животное?",
        "swedish": "Har du ett husdjur?",
        "norwegian": "Har du et kjæledyr?",
        "danish": "Har du et kæledyr?",
        "finnish": "Onko sinulla lemmikki?",
        "greek": "Έχεις κατοικίδιο;",
        "brazilian_portuguese": "Você tem um animal de estimação?",
        "mandarin": "你有宠物吗？",
        "japanese": "ペットはいますか？",
        "korean": "반려동물이 있어요?",
        "hindi": "क्या आपके पास कोई पालतू जानवर है?",
        "vietnamese": "Bạn có nuôi thú cưng không?",
        "arabic": "هل لديك حيوان أليف؟",
    },
    {
        "line_number": 30,
        "speaker_name": "Mia",
        "lithuanian": "Taip! Turiu mažą katę. Jos vardas Luna. Labai malonu buvo susipažinti, Aleksai!",
        "latvian": "Jā! Man ir maza kaķe. Viņas vārds ir Luna. Ļoti patīkami iepazīties, Alekss!",
        "estonian": "Jah! Mul on väike kass. Tema nimi on Luna. Väga tore oli sinuga tutvuda, Alex!",
        "english": "Yes! I have a small cat. Her name is Luna. It was really nice to meet you, Alex!",
        "german": "Ja! Ich habe eine kleine Katze. Ihr Name ist Luna. Es war wirklich schön, dich kennenzulernen, Alex!",
        "french": "Oui! J'ai un petit chat. Elle s'appelle Luna. C'était vraiment sympa de te rencontrer, Alex!",
        "spanish": "¡Sí! Tengo una gata pequeña. Se llama Luna. ¡Fue muy agradable conocerte, Alex!",
        "italian": "Sì! Ho una piccola gatta. Si chiama Luna. È stato davvero bello conoscerti, Alex!",
        "portuguese": "Sim! Tenho uma gatinha. Chama-se Luna. Foi muito bom conhecer-te, Alex!",
        "dutch": "Ja! Ik heb een kleine kat. Ze heet Luna. Het was echt fijn om je te ontmoeten, Alex!",
        "polish": "Tak! Mam małego kota. Ma na imię Luna. Bardzo miło było cię poznać, Alex!",
        "ukrainian": "Так! У мене є маленьке кошеня. Її звати Луна. Було дуже приємно познайомитись, Алексе!",
        "russian": "Да! У меня есть маленькая кошка. Её зовут Луна. Было очень приятно познакомиться, Алекс!",
        "swedish": "Ja! Jag har en liten katt. Hon heter Luna. Det var verkligen trevligt att träffa dig, Alex!",
        "norwegian": "Ja! Jeg har en liten katt. Hun heter Luna. Det var virkelig hyggelig å møte deg, Alex!",
        "danish": "Ja! Jeg har en lille kat. Hun hedder Luna. Det var virkelig rart at møde dig, Alex!",
        "finnish": "Kyllä! Minulla on pieni kissa. Hänen nimensä on Luna. Oli todella mukava tutustua sinuun, Alex!",
        "greek": "Ναι! Έχω μια μικρή γάτα. Το όνομά της είναι Luna. Ήταν πολύ ωραίο να σε γνωρίσω, Άλεξ!",
        "brazilian_portuguese": "Sim! Tenho uma gatinha. O nome dela é Luna. Foi muito bom te conhecer, Alex!",
        "mandarin": "是的！我有一只小猫。她的名字叫露娜。很高兴认识你，亚历克斯！",
        "japanese": "はい！小さな猫がいます。名前はルナです。会えて本当によかったです、アレックス！",
        "korean": "네! 작은 고양이가 있어요. 이름은 루나예요. 만나서 정말 반가웠어요, 알렉스!",
        "hindi": "हाँ! मेरे पास एक छोटी बिल्ली है। उसका नाम लूना है। आपसे मिलकर बहुत अच्छा लगा, एलेक्स!",
        "vietnamese": "Có! Tôi có một con mèo nhỏ. Tên nó là Luna. Rất vui được gặp bạn, Alex!",
        "arabic": "نعم! لدي قطة صغيرة. اسمها لونا. كان من الجميل جداً مقابلتك يا أليكس!",
    },
]


def seed():
    with app.app_context():
        db.create_all()

        # Check if already seeded
        existing = Dialogue.query.filter_by(topic="Meeting a New Friend").first()
        if existing:
            print("Dialogue already exists — skipping.")
            return

        # Create dialogue record
        dialogue = Dialogue(
            topic="Meeting a New Friend",
            lang_level="A1",
            length=30
        )
        db.session.add(dialogue)
        db.session.flush()

        # Add all lines
        for line_data in lines_data:
            line = DialogueLine(
                dialogue_id=dialogue.id,
                **line_data
            )
            db.session.add(line)

        db.session.commit()
        print(f"Successfully seeded dialogue ID {dialogue.id} with {len(lines_data)} lines in 25 languages.")


if __name__ == '__main__':
    seed()
