import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from hello_world import app, db, Dialogue, DialogueLine

# -------------------------------------------------------
# A2 Dialogue — "Planning a Weekend Trip"
# 30 sentences, 2 speakers: Alex and Mia
# Same names used across all languages
# -------------------------------------------------------

lines_data = [
    {
        "line_number": 1,
        "speaker_name": "Alex",
        "lithuanian": "Labas, Mia! Ar tu turi planų šiam savaitgaliui?",
        "latvian": "Sveika, Mia! Vai tev ir plāni šai nedēļas nogalei?",
        "estonian": "Tere, Mia! Kas sul on nädalavahetuseks plaane?",
        "english": "Hi Mia! Do you have any plans for this weekend?",
        "german": "Hallo Mia! Hast du Pläne für dieses Wochenende?",
        "french": "Salut Mia! Tu as des projets pour ce week-end?",
        "spanish": "¡Hola Mia! ¿Tienes planes para este fin de semana?",
        "italian": "Ciao Mia! Hai piani per questo fine settimana?",
        "portuguese": "Olá Mia! Tens planos para este fim de semana?",
        "dutch": "Hoi Mia! Heb jij plannen voor dit weekend?",
        "polish": "Cześć Mia! Czy masz plany na ten weekend?",
        "ukrainian": "Привіт, Міа! У тебе є плани на цей вихідний?",
        "russian": "Привет, Миа! У тебя есть планы на эти выходные?",
        "swedish": "Hej Mia! Har du några planer för den här helgen?",
        "norwegian": "Hei Mia! Har du noen planer for denne helgen?",
        "danish": "Hej Mia! Har du planer for denne weekend?",
        "finnish": "Hei Mia! Onko sinulla suunnitelmia tälle viikonlopulle?",
        "greek": "Γεια Μία! Έχεις σχέδια για αυτό το Σαββατοκύριακο;",
        "brazilian_portuguese": "Oi Mia! Você tem planos para esse fim de semana?",
        "mandarin": "嗨，米亚！你这个周末有计划吗？",
        "japanese": "こんにちは、ミア！今週末は何か予定がありますか？",
        "korean": "안녕 미아! 이번 주말에 계획 있어요?",
        "hindi": "नमस्ते मिया! क्या इस वीकेंड के लिए कोई योजना है?",
        "vietnamese": "Chào Mia! Bạn có kế hoạch gì cho cuối tuần này không?",
        "arabic": "مرحباً ميا! هل لديكِ خطط لهذا الأسبوع؟",
    },
    {
        "line_number": 2,
        "speaker_name": "Mia",
        "lithuanian": "Dar neturiu planų. Gal galime ką nors padaryti kartu?",
        "latvian": "Vēl nav plānu. Varbūt mēs kaut ko varētu darīt kopā?",
        "estonian": "Pole veel plaane. Võib-olla saame midagi koos teha?",
        "english": "I don't have plans yet. Maybe we can do something together?",
        "german": "Ich habe noch keine Pläne. Vielleicht können wir etwas zusammen machen?",
        "french": "Je n'ai pas encore de projets. On pourrait peut-être faire quelque chose ensemble?",
        "spanish": "Todavía no tengo planes. ¿Quizás podamos hacer algo juntos?",
        "italian": "Non ho ancora piani. Forse possiamo fare qualcosa insieme?",
        "portuguese": "Ainda não tenho planos. Talvez possamos fazer algo juntos?",
        "dutch": "Ik heb nog geen plannen. Misschien kunnen we iets samen doen?",
        "polish": "Jeszcze nie mam planów. Może moglibyśmy coś zrobić razem?",
        "ukrainian": "У мене ще немає планів. Може, ми могли б щось зробити разом?",
        "russian": "У меня пока нет планов. Может, мы могли бы что-нибудь сделать вместе?",
        "swedish": "Jag har inga planer än. Kanske kan vi göra något tillsammans?",
        "norwegian": "Jeg har ingen planer ennå. Kanskje vi kan gjøre noe sammen?",
        "danish": "Jeg har ikke planer endnu. Måske kan vi gøre noget sammen?",
        "finnish": "Minulla ei ole vielä suunnitelmia. Ehkä voimme tehdä jotain yhdessä?",
        "greek": "Δεν έχω ακόμα σχέδια. Ίσως να μπορούμε να κάνουμε κάτι μαζί;",
        "brazilian_portuguese": "Ainda não tenho planos. Talvez possamos fazer algo juntos?",
        "mandarin": "我还没有计划。也许我们可以一起做些什么？",
        "japanese": "まだ予定はありません。一緒に何かできるかもしれませんね？",
        "korean": "아직 계획이 없어요. 우리 같이 뭔가 할 수 있을까요?",
        "hindi": "अभी कोई योजना नहीं है। शायद हम साथ कुछ कर सकते हैं?",
        "vietnamese": "Tôi chưa có kế hoạch. Có lẽ chúng ta có thể làm gì đó cùng nhau?",
        "arabic": "ليس لديّ خطط بعد. ربما نستطيع فعل شيء معاً؟",
    },
    {
        "line_number": 3,
        "speaker_name": "Alex",
        "lithuanian": "Puiku! Aš galvojau apie trumpą kelionę į kaimą.",
        "latvian": "Lieliski! Es domāju par īsu braucienu uz laukiem.",
        "estonian": "Suurepärane! Mõtlesin lühikesele reisile maapiirkonda.",
        "english": "Great! I was thinking about a short trip to the countryside.",
        "german": "Toll! Ich dachte an einen kurzen Ausflug aufs Land.",
        "french": "Super! Je pensais à un court voyage à la campagne.",
        "spanish": "¡Genial! Estaba pensando en un corto viaje al campo.",
        "italian": "Ottimo! Stavo pensando a una breve gita in campagna.",
        "portuguese": "Ótimo! Estava a pensar numa curta viagem ao campo.",
        "dutch": "Geweldig! Ik dacht aan een kort uitstapje naar het platteland.",
        "polish": "Świetnie! Myślałem o krótkim wyjeździe na wieś.",
        "ukrainian": "Чудово! Я думав про коротку поїздку в село.",
        "russian": "Отлично! Я думал о короткой поездке за город.",
        "swedish": "Bra! Jag tänkte på en kort resa till landsbygden.",
        "norwegian": "Flott! Jeg tenkte på en kort tur til landsbygda.",
        "danish": "Fantastisk! Jeg tænkte på en kort tur til landet.",
        "finnish": "Hienoa! Ajattelin lyhyttä matkaa maaseudulle.",
        "greek": "Υπέροχα! Σκεφτόμουν μια σύντομη εκδρομή στην εξοχή.",
        "brazilian_portuguese": "Ótimo! Estava pensando em uma viagem curta para o campo.",
        "mandarin": "太好了！我在想去乡下短途旅行。",
        "japanese": "いいですね！田舎への短い旅行を考えていました。",
        "korean": "좋아요! 시골로 짧은 여행을 생각하고 있었어요.",
        "hindi": "बढ़िया! मैं ग्रामीण इलाके में एक छोटी यात्रा के बारे में सोच रहा था।",
        "vietnamese": "Tuyệt! Tôi đang nghĩ đến một chuyến đi ngắn về nông thôn.",
        "arabic": "رائع! كنت أفكر في رحلة قصيرة إلى الريف.",
    },
    {
        "line_number": 4,
        "speaker_name": "Mia",
        "lithuanian": "Skamba gerai! Kaip toli yra tas kaimas?",
        "latvian": "Izklausās labi! Cik tālu ir tas ciems?",
        "estonian": "Kõlab hästi! Kui kaugel see küla on?",
        "english": "Sounds good! How far is that village?",
        "german": "Klingt gut! Wie weit ist das Dorf?",
        "french": "Ça semble bien! Le village est à quelle distance?",
        "spanish": "¡Suena bien! ¿Qué tan lejos está ese pueblo?",
        "italian": "Sembra bello! Quanto è lontano quel villaggio?",
        "portuguese": "Soa bem! Qual é a distância até essa aldeia?",
        "dutch": "Klinkt goed! Hoe ver is dat dorp?",
        "polish": "Brzmi dobrze! Jak daleko jest ta wioska?",
        "ukrainian": "Звучить добре! Як далеко це село?",
        "russian": "Звучит хорошо! Как далеко эта деревня?",
        "swedish": "Låter bra! Hur långt är det till byn?",
        "norwegian": "Høres bra ut! Hvor langt er det til den landsbyen?",
        "danish": "Lyder godt! Hvor langt er det til den landsby?",
        "finnish": "Kuulostaa hyvältä! Kuinka kaukana se kylä on?",
        "greek": "Ακούγεται ωραία! Πόσο μακριά είναι εκείνο το χωριό;",
        "brazilian_portuguese": "Parece bom! Qual a distância até aquela cidade?",
        "mandarin": "听起来不错！那个村子有多远？",
        "japanese": "いいですね！その村はどのくらい遠いですか？",
        "korean": "좋아요! 그 마을이 얼마나 멀어요?",
        "hindi": "अच्छा लगता है! वह गाँव कितना दूर है?",
        "vietnamese": "Nghe hay đó! Làng đó cách đây bao xa?",
        "arabic": "يبدو جيداً! كم يبعد ذلك القرية؟",
    },
    {
        "line_number": 5,
        "speaker_name": "Alex",
        "lithuanian": "Apie dvi valandas nuo miesto. Galime važiuoti traukiniu.",
        "latvian": "Apmēram divas stundas no pilsētas. Mēs varam braukt ar vilcienu.",
        "estonian": "Umbes kaks tundi linnast. Saame rongiga sõita.",
        "english": "About two hours from the city. We can go by train.",
        "german": "Etwa zwei Stunden von der Stadt. Wir können mit dem Zug fahren.",
        "french": "Environ deux heures de la ville. On peut y aller en train.",
        "spanish": "Unas dos horas desde la ciudad. Podemos ir en tren.",
        "italian": "Circa due ore dalla città. Possiamo andare in treno.",
        "portuguese": "Cerca de duas horas da cidade. Podemos ir de comboio.",
        "dutch": "Ongeveer twee uur van de stad. We kunnen met de trein gaan.",
        "polish": "Około dwóch godzin od miasta. Możemy jechać pociągiem.",
        "ukrainian": "Приблизно дві години від міста. Можемо поїхати потягом.",
        "russian": "Около двух часов от города. Мы можем поехать на поезде.",
        "swedish": "Ungefär två timmar från staden. Vi kan åka med tåget.",
        "norwegian": "Omtrent to timer fra byen. Vi kan reise med tog.",
        "danish": "Cirka to timer fra byen. Vi kan tage toget.",
        "finnish": "Noin kaksi tuntia kaupungista. Voimme mennä junalla.",
        "greek": "Περίπου δύο ώρες από την πόλη. Μπορούμε να πάμε με το τρένο.",
        "brazilian_portuguese": "Cerca de duas horas da cidade. Podemos ir de trem.",
        "mandarin": "距离城市大约两个小时。我们可以坐火车去。",
        "japanese": "市内から約2時間です。電車で行けます。",
        "korean": "도시에서 약 두 시간이에요. 기차로 갈 수 있어요.",
        "hindi": "शहर से लगभग दो घंटे। हम ट्रेन से जा सकते हैं।",
        "vietnamese": "Khoảng hai giờ từ thành phố. Chúng ta có thể đi tàu hỏa.",
        "arabic": "حوالي ساعتين من المدينة. يمكننا الذهاب بالقطار.",
    },
    {
        "line_number": 6,
        "speaker_name": "Mia",
        "lithuanian": "Ar traukinys brangus?",
        "latvian": "Vai vilciens ir dārgs?",
        "estonian": "Kas rong on kallis?",
        "english": "Is the train expensive?",
        "german": "Ist der Zug teuer?",
        "french": "Le train est cher?",
        "spanish": "¿El tren es caro?",
        "italian": "Il treno è costoso?",
        "portuguese": "O comboio é caro?",
        "dutch": "Is de trein duur?",
        "polish": "Czy pociąg jest drogi?",
        "ukrainian": "Потяг дорогий?",
        "russian": "Поезд дорогой?",
        "swedish": "Är tåget dyrt?",
        "norwegian": "Er toget dyrt?",
        "danish": "Er toget dyrt?",
        "finnish": "Onko juna kallis?",
        "greek": "Είναι ακριβό το τρένο;",
        "brazilian_portuguese": "O trem é caro?",
        "mandarin": "火车贵吗？",
        "japanese": "電車は高いですか？",
        "korean": "기차가 비싸요?",
        "hindi": "क्या ट्रेन महंगी है?",
        "vietnamese": "Tàu hỏa có đắt không?",
        "arabic": "هل القطار غالٍ؟",
    },
    {
        "line_number": 7,
        "speaker_name": "Alex",
        "lithuanian": "Ne, bilietas kainuoja tik dešimt eurų į vieną pusę.",
        "latvian": "Nē, biļete maksā tikai desmit eiro vienā virzienā.",
        "estonian": "Ei, pilet maksab ainult kümme eurot ühe suuna kohta.",
        "english": "No, the ticket costs only ten euros one way.",
        "german": "Nein, die Fahrkarte kostet nur zehn Euro einfach.",
        "french": "Non, le billet coûte seulement dix euros en aller simple.",
        "spanish": "No, el billete cuesta solo diez euros de ida.",
        "italian": "No, il biglietto costa solo dieci euro di sola andata.",
        "portuguese": "Não, o bilhete custa apenas dez euros de ida.",
        "dutch": "Nee, het kaartje kost maar tien euro enkele reis.",
        "polish": "Nie, bilet kosztuje tylko dziesięć euro w jedną stronę.",
        "ukrainian": "Ні, квиток коштує лише десять євро в одну сторону.",
        "russian": "Нет, билет стоит всего десять евро в одну сторону.",
        "swedish": "Nej, biljetten kostar bara tio euro enkel.",
        "norwegian": "Nei, billetten koster bare ti euro en vei.",
        "danish": "Nej, billetten koster kun ti euro enkeltbillet.",
        "finnish": "Ei, lippu maksaa vain kymmenen euroa suuntaansa.",
        "greek": "Όχι, το εισιτήριο κοστίζει μόνο δέκα ευρώ απλό.",
        "brazilian_portuguese": "Não, a passagem custa apenas dez euros de ida.",
        "mandarin": "不，单程票只需十欧元。",
        "japanese": "いいえ、片道チケットはたった10ユーロです。",
        "korean": "아니요, 편도 티켓이 10유로밖에 안 해요.",
        "hindi": "नहीं, टिकट केवल दस यूरो एकतरफा है।",
        "vietnamese": "Không, vé một chiều chỉ mười euro thôi.",
        "arabic": "لا، تكلفة التذكرة ذهاباً فقط عشرة يوروهات.",
    },
    {
        "line_number": 8,
        "speaker_name": "Mia",
        "lithuanian": "Tai nebrangu. Kokiu laiku išvyksta pirmasis traukinys?",
        "latvian": "Tas nav dārgi. Cikos atiet pirmais vilciens?",
        "estonian": "See pole kallis. Mis ajal esimene rong väljub?",
        "english": "That is not expensive. What time does the first train leave?",
        "german": "Das ist nicht teuer. Um wie viel Uhr fährt der erste Zug ab?",
        "french": "Ce n'est pas cher. À quelle heure part le premier train?",
        "spanish": "No es caro. ¿A qué hora sale el primer tren?",
        "italian": "Non è costoso. A che ora parte il primo treno?",
        "portuguese": "Não é caro. A que horas parte o primeiro comboio?",
        "dutch": "Dat is niet duur. Hoe laat vertrekt de eerste trein?",
        "polish": "To nie jest drogie. O której godzinie odjeżdża pierwszy pociąg?",
        "ukrainian": "Це не дорого. О котрій годині відправляється перший потяг?",
        "russian": "Это недорого. В котором часу отправляется первый поезд?",
        "swedish": "Det är inte dyrt. Hur dags går första tåget?",
        "norwegian": "Det er ikke dyrt. Når går det første toget?",
        "danish": "Det er ikke dyrt. Hvad tid kører det første tog?",
        "finnish": "Se ei ole kallista. Mihin aikaan ensimmäinen juna lähtee?",
        "greek": "Δεν είναι ακριβό. Τι ώρα φεύγει το πρώτο τρένο;",
        "brazilian_portuguese": "Não é caro. Que horas sai o primeiro trem?",
        "mandarin": "这不贵。第一班火车几点出发？",
        "japanese": "それは高くないですね。最初の電車は何時に出発しますか？",
        "korean": "비싸지 않네요. 첫 번째 기차가 몇 시에 출발해요?",
        "hindi": "यह महंगा नहीं है। पहली ट्रेन कितने बजे निकलती है?",
        "vietnamese": "Không đắt lắm. Chuyến tàu đầu tiên khởi hành lúc mấy giờ?",
        "arabic": "هذا ليس غالياً. في أي وقت يغادر القطار الأول؟",
    },
    {
        "line_number": 9,
        "speaker_name": "Alex",
        "lithuanian": "Pirmasis traukinys išvyksta devintą valandą ryto.",
        "latvian": "Pirmais vilciens atiet deviņos no rīta.",
        "estonian": "Esimene rong väljub kell üheksa hommikul.",
        "english": "The first train leaves at nine in the morning.",
        "german": "Der erste Zug fährt um neun Uhr morgens ab.",
        "french": "Le premier train part à neuf heures du matin.",
        "spanish": "El primer tren sale a las nueve de la mañana.",
        "italian": "Il primo treno parte alle nove di mattina.",
        "portuguese": "O primeiro comboio parte às nove da manhã.",
        "dutch": "De eerste trein vertrekt om negen uur 's ochtends.",
        "polish": "Pierwszy pociąg odjeżdża o dziewiątej rano.",
        "ukrainian": "Перший потяг відправляється о дев'ятій ранку.",
        "russian": "Первый поезд отправляется в девять утра.",
        "swedish": "Första tåget går klockan nio på morgonen.",
        "norwegian": "Det første toget går klokken ni om morgenen.",
        "danish": "Det første tog afgår klokken ni om morgenen.",
        "finnish": "Ensimmäinen juna lähtee kello yhdeksän aamulla.",
        "greek": "Το πρώτο τρένο φεύγει στις εννέα το πρωί.",
        "brazilian_portuguese": "O primeiro trem sai às nove da manhã.",
        "mandarin": "第一班火车早上九点出发。",
        "japanese": "最初の電車は朝9時に出発します。",
        "korean": "첫 번째 기차는 오전 9시에 출발해요.",
        "hindi": "पहली ट्रेन सुबह नौ बजे निकलती है।",
        "vietnamese": "Chuyến tàu đầu tiên khởi hành lúc chín giờ sáng.",
        "arabic": "يغادر القطار الأول الساعة التاسعة صباحاً.",
    },
    {
        "line_number": 10,
        "speaker_name": "Mia",
        "lithuanian": "Gerai, bet aš nemėgstu keltis anksti. Ar yra vėlesnis traukinys?",
        "latvian": "Labi, bet man nepatīk agri celties. Vai ir vēlāks vilciens?",
        "estonian": "Okei, aga ma ei armasta vara ärgata. Kas on hilisem rong?",
        "english": "OK, but I don't like to wake up early. Is there a later train?",
        "german": "OK, aber ich stehe nicht gerne früh auf. Gibt es einen späteren Zug?",
        "french": "OK, mais je n'aime pas me lever tôt. Il y a un train plus tard?",
        "spanish": "De acuerdo, pero no me gusta levantarme temprano. ¿Hay un tren más tarde?",
        "italian": "OK, ma non mi piace svegliarmi presto. C'è un treno più tardi?",
        "portuguese": "OK, mas não gosto de me levantar cedo. Há um comboio mais tarde?",
        "dutch": "Oké, maar ik hou er niet van om vroeg op te staan. Is er een latere trein?",
        "polish": "OK, ale nie lubię wstawać wcześnie. Czy jest późniejszy pociąg?",
        "ukrainian": "Добре, але я не люблю прокидатися рано. Є пізніший потяг?",
        "russian": "Хорошо, но я не люблю рано вставать. Есть более поздний поезд?",
        "swedish": "OK, men jag gillar inte att vakna tidigt. Finns det ett senare tåg?",
        "norwegian": "OK, men jeg liker ikke å stå opp tidlig. Er det et senere tog?",
        "danish": "OK, men jeg kan ikke lide at stå tidligt op. Er der et senere tog?",
        "finnish": "OK, mutta en pidä aikaisin heräämisestä. Onko myöhempi juna?",
        "greek": "Εντάξει, αλλά δεν μου αρέσει να ξυπνώ νωρίς. Υπάρχει αργότερο τρένο;",
        "brazilian_portuguese": "OK, mas não gosto de acordar cedo. Tem um trem mais tarde?",
        "mandarin": "好的，但我不喜欢早起。有晚些的火车吗？",
        "japanese": "わかりました、でも早起きは苦手です。もっと遅い電車はありますか？",
        "korean": "알겠어요, 하지만 일찍 일어나는 건 싫어요. 더 늦은 기차가 있어요?",
        "hindi": "ठीक है, लेकिन मुझे जल्दी उठना पसंद नहीं। क्या कोई बाद की ट्रेन है?",
        "vietnamese": "Được, nhưng tôi không thích dậy sớm. Có chuyến tàu muộn hơn không?",
        "arabic": "حسناً، لكنني لا أحب الاستيقاظ مبكراً. هل هناك قطار في وقت متأخر؟",
    },
    {
        "line_number": 11,
        "speaker_name": "Alex",
        "lithuanian": "Taip, yra traukinys vienuoliktą valandą. Ar tau tinka?",
        "latvian": "Jā, ir vilciens vienpadsmitos. Vai tev tas der?",
        "estonian": "Jah, on rong kell üksteist. Kas see sobib sulle?",
        "english": "Yes, there is a train at eleven. Does that work for you?",
        "german": "Ja, es gibt einen Zug um elf Uhr. Passt das für dich?",
        "french": "Oui, il y a un train à onze heures. Ça te convient?",
        "spanish": "Sí, hay un tren a las once. ¿Te viene bien?",
        "italian": "Sì, c'è un treno alle undici. Va bene per te?",
        "portuguese": "Sim, há um comboio às onze. Está bem para ti?",
        "dutch": "Ja, er is een trein om elf uur. Werkt dat voor jou?",
        "polish": "Tak, jest pociąg o jedenastej. Czy to ci odpowiada?",
        "ukrainian": "Так, є потяг об одинадцятій. Тобі підходить?",
        "russian": "Да, есть поезд в одиннадцать. Тебе подходит?",
        "swedish": "Ja, det finns ett tåg klockan elva. Passar det dig?",
        "norwegian": "Ja, det er et tog klokken elleve. Passer det for deg?",
        "danish": "Ja, der er et tog klokken elleve. Passer det for dig?",
        "finnish": "Kyllä, on juna kello yksitoista. Sopiiko se sinulle?",
        "greek": "Ναι, υπάρχει τρένο στις έντεκα. Σου βολεύει;",
        "brazilian_portuguese": "Sim, tem um trem às onze. Funciona para você?",
        "mandarin": "是的，十一点有一班火车。这对你方便吗？",
        "japanese": "はい、11時に電車があります。それで大丈夫ですか？",
        "korean": "네, 11시에 기차가 있어요. 괜찮아요?",
        "hindi": "हाँ, ग्यारह बजे एक ट्रेन है। क्या यह आपके लिए ठीक है?",
        "vietnamese": "Có, có chuyến tàu lúc mười một giờ. Bạn thấy ổn không?",
        "arabic": "نعم، هناك قطار الساعة الحادية عشرة. هل يناسبك ذلك؟",
    },
    {
        "line_number": 12,
        "speaker_name": "Mia",
        "lithuanian": "Taip, puikiai tinka! Ką mes veiksime atvykę ten?",
        "latvian": "Jā, lieliski der! Ko mēs darīsim, kad tur nonāksim?",
        "estonian": "Jah, sobib suurepäraselt! Mida me seal teeme?",
        "english": "Yes, that works perfectly! What will we do when we get there?",
        "german": "Ja, das passt perfekt! Was werden wir machen, wenn wir ankommen?",
        "french": "Oui, c'est parfait! Qu'est-ce qu'on fera quand on arrivera?",
        "spanish": "¡Sí, perfecto! ¿Qué haremos cuando lleguemos?",
        "italian": "Sì, perfetto! Cosa faremo quando arriveremo?",
        "portuguese": "Sim, perfeito! O que vamos fazer quando chegarmos?",
        "dutch": "Ja, dat werkt perfect! Wat doen we als we er zijn?",
        "polish": "Tak, to idealnie pasuje! Co będziemy robić, gdy tam dojedziemy?",
        "ukrainian": "Так, чудово підходить! Що ми будемо робити, коли приїдемо?",
        "russian": "Да, отлично подходит! Что мы будем делать, когда приедем?",
        "swedish": "Ja, det passar perfekt! Vad ska vi göra när vi kommer dit?",
        "norwegian": "Ja, det passer perfekt! Hva skal vi gjøre når vi kommer dit?",
        "danish": "Ja, det passer perfekt! Hvad vil vi gøre, når vi kommer der?",
        "finnish": "Kyllä, sopii täydellisesti! Mitä teemme kun pääsemme perille?",
        "greek": "Ναι, τέλεια ταιριάζει! Τι θα κάνουμε όταν φτάσουμε;",
        "brazilian_portuguese": "Sim, perfeito! O que vamos fazer quando chegarmos lá?",
        "mandarin": "是的，太好了！我们到了之后要做什么？",
        "japanese": "はい、完璧です！着いたら何をしますか？",
        "korean": "네, 완벽해요! 거기 도착하면 무엇을 할 거예요?",
        "hindi": "हाँ, बिल्कुल सही! वहाँ पहुँचने पर हम क्या करेंगे?",
        "vietnamese": "Có, hoàn hảo! Khi đến nơi chúng ta sẽ làm gì?",
        "arabic": "نعم، ممتاز! ماذا سنفعل عندما نصل؟",
    },
    {
        "line_number": 13,
        "speaker_name": "Alex",
        "lithuanian": "Yra gražus ežeras netoli. Galime pasivaikščioti ir valgyti piknike.",
        "latvian": "Netālu ir skaists ezers. Mēs varam pastaigāties un ēst piknikā.",
        "estonian": "Lähedal on kaunis järv. Saame jalutada ja piknikul süüa.",
        "english": "There is a beautiful lake nearby. We can walk and have a picnic.",
        "german": "Es gibt einen schönen See in der Nähe. Wir können spazieren gehen und picknicken.",
        "french": "Il y a un beau lac tout près. On peut se promener et faire un pique-nique.",
        "spanish": "Hay un lago hermoso cerca. Podemos caminar y hacer un picnic.",
        "italian": "C'è un bel lago vicino. Possiamo passeggiare e fare un picnic.",
        "portuguese": "Há um lago bonito perto. Podemos caminhar e fazer um piquenique.",
        "dutch": "Er is een mooi meer in de buurt. We kunnen wandelen en picknicken.",
        "polish": "Jest piękne jezioro w pobliżu. Możemy się przejść i zjeść piknik.",
        "ukrainian": "Поруч є гарне озеро. Ми можемо погуляти та влаштувати пікнік.",
        "russian": "Рядом есть красивое озеро. Мы можем погулять и устроить пикник.",
        "swedish": "Det finns en vacker sjö i närheten. Vi kan promenera och ha picknick.",
        "norwegian": "Det er en vakker innsjø i nærheten. Vi kan gå tur og ha piknik.",
        "danish": "Der er en smuk sø i nærheden. Vi kan gå en tur og have picnic.",
        "finnish": "Lähellä on kaunis järvi. Voimme kävellä ja pitää piknikkiä.",
        "greek": "Υπάρχει μια όμορφη λίμνη κοντά. Μπορούμε να περπατήσουμε και να κάνουμε πικνίκ.",
        "brazilian_portuguese": "Tem um lago lindo por perto. Podemos caminhar e fazer um piquenique.",
        "mandarin": "附近有一个美丽的湖泊。我们可以散步和野餐。",
        "japanese": "近くに美しい湖があります。散歩してピクニックができます。",
        "korean": "근처에 아름다운 호수가 있어요. 산책하고 소풍을 할 수 있어요.",
        "hindi": "पास में एक सुंदर झील है। हम टहल सकते हैं और पिकनिक कर सकते हैं।",
        "vietnamese": "Có một hồ đẹp gần đó. Chúng ta có thể đi bộ và có bữa picnic.",
        "arabic": "هناك بحيرة جميلة في القريب. يمكننا المشي والقيام بنزهة.",
    },
    {
        "line_number": 14,
        "speaker_name": "Mia",
        "lithuanian": "Tai skamba nuostabiai! Ar turėsime atsivežti maisto?",
        "latvian": "Tas izklausās brīnišķīgi! Vai mums vajadzēs ņemt līdzi ēdienu?",
        "estonian": "See kõlab suurepäraselt! Kas peame toitu kaasa võtma?",
        "english": "That sounds wonderful! Will we need to bring food?",
        "german": "Das klingt wunderbar! Müssen wir Essen mitbringen?",
        "french": "Ça semble merveilleux! On devra apporter de la nourriture?",
        "spanish": "¡Eso suena maravilloso! ¿Necesitaremos traer comida?",
        "italian": "Sembra meraviglioso! Dovremo portare del cibo?",
        "portuguese": "Isso soa maravilhoso! Precisaremos de trazer comida?",
        "dutch": "Dat klinkt geweldig! Moeten we eten meenemen?",
        "polish": "To brzmi cudownie! Czy będziemy musieli przynieść jedzenie?",
        "ukrainian": "Це звучить чудово! Нам потрібно буде принести їжу?",
        "russian": "Это звучит замечательно! Нам нужно будет принести еду?",
        "swedish": "Det låter underbart! Måste vi ta med mat?",
        "norwegian": "Det høres vidunderlig ut! Må vi ta med mat?",
        "danish": "Det lyder vidunderligt! Skal vi tage mad med?",
        "finnish": "Se kuulostaa ihanalta! Pitääkö meidän ottaa ruokaa mukaan?",
        "greek": "Αυτό ακούγεται υπέροχο! Θα χρειαστεί να φέρουμε φαγητό;",
        "brazilian_portuguese": "Isso soa maravilhoso! Vamos precisar trazer comida?",
        "mandarin": "听起来太棒了！我们需要带食物吗？",
        "japanese": "素晴らしいですね！食べ物を持っていく必要がありますか？",
        "korean": "정말 멋지겠네요! 음식을 가져가야 하나요?",
        "hindi": "यह अद्भुत लगता है! क्या हमें खाना लाना होगा?",
        "vietnamese": "Nghe tuyệt vời quá! Chúng ta có cần mang thức ăn không?",
        "arabic": "يبدو رائعاً! هل سنحتاج إلى إحضار طعام؟",
    },
    {
        "line_number": 15,
        "speaker_name": "Alex",
        "lithuanian": "Taip, galime nusipirkti maisto parduotuvėje prieš išvykstant.",
        "latvian": "Jā, mēs varam nopirkt pārtiku veikalā pirms izbraukšanas.",
        "estonian": "Jah, saame osta toitu poest enne lahkumist.",
        "english": "Yes, we can buy food at the shop before we leave.",
        "german": "Ja, wir können Essen im Laden kaufen, bevor wir losfahren.",
        "french": "Oui, on peut acheter de la nourriture au magasin avant de partir.",
        "spanish": "Sí, podemos comprar comida en la tienda antes de salir.",
        "italian": "Sì, possiamo comprare il cibo al negozio prima di partire.",
        "portuguese": "Sim, podemos comprar comida na loja antes de partir.",
        "dutch": "Ja, we kunnen eten kopen in de winkel voordat we vertrekken.",
        "polish": "Tak, możemy kupić jedzenie w sklepie przed wyjazdem.",
        "ukrainian": "Так, ми можемо купити їжу в магазині перед від'їздом.",
        "russian": "Да, мы можем купить еду в магазине перед отъездом.",
        "swedish": "Ja, vi kan köpa mat i butiken innan vi åker.",
        "norwegian": "Ja, vi kan kjøpe mat i butikken før vi drar.",
        "danish": "Ja, vi kan købe mad i butikken, inden vi tager af sted.",
        "finnish": "Kyllä, voimme ostaa ruokaa kaupasta ennen lähtöä.",
        "greek": "Ναι, μπορούμε να αγοράσουμε φαγητό στο μαγαζί πριν φύγουμε.",
        "brazilian_portuguese": "Sim, podemos comprar comida na loja antes de sair.",
        "mandarin": "是的，我们可以在出发前在商店买食物。",
        "japanese": "はい、出発前にお店で食べ物を買えます。",
        "korean": "네, 출발 전에 가게에서 음식을 살 수 있어요.",
        "hindi": "हाँ, हम निकलने से पहले दुकान से खाना खरीद सकते हैं।",
        "vietnamese": "Có, chúng ta có thể mua thức ăn ở cửa hàng trước khi đi.",
        "arabic": "نعم، يمكننا شراء الطعام من المتجر قبل المغادرة.",
    },
    {
        "line_number": 16,
        "speaker_name": "Mia",
        "lithuanian": "Gera mintis. Aš atsivešiu antklodę piknikui.",
        "latvian": "Laba ideja. Es paņemšu līdzi segu piknikam.",
        "estonian": "Hea mõte. Ma toon piknikuks teki.",
        "english": "Good idea. I will bring a blanket for the picnic.",
        "german": "Gute Idee. Ich bringe eine Decke für das Picknick mit.",
        "french": "Bonne idée. J'apporterai une couverture pour le pique-nique.",
        "spanish": "Buena idea. Traeré una manta para el picnic.",
        "italian": "Buona idea. Porterò una coperta per il picnic.",
        "portuguese": "Boa ideia. Vou trazer um cobertor para o piquenique.",
        "dutch": "Goed idee. Ik neem een deken mee voor de picknick.",
        "polish": "Dobry pomysł. Przyniosę koc na piknik.",
        "ukrainian": "Гарна ідея. Я принесу ковдру для пікніка.",
        "russian": "Хорошая идея. Я принесу одеяло для пикника.",
        "swedish": "Bra idé. Jag tar med en filt till picknicken.",
        "norwegian": "God idé. Jeg tar med et teppe til piknik.",
        "danish": "God idé. Jeg tager et tæppe med til picnic.",
        "finnish": "Hyvä idea. Otan peitto mukaan piknikille.",
        "greek": "Καλή ιδέα. Θα φέρω μια κουβέρτα για το πικνίκ.",
        "brazilian_portuguese": "Boa ideia. Vou trazer uma manta para o piquenique.",
        "mandarin": "好主意。我会带一条毯子去野餐。",
        "japanese": "いいですね。ピクニック用に毛布を持っていきます。",
        "korean": "좋은 생각이에요. 피크닉을 위해 담요를 가져올게요.",
        "hindi": "अच्छा विचार है। मैं पिकनिक के लिए एक कंबल लाऊँगी।",
        "vietnamese": "Ý hay đó. Tôi sẽ mang theo một chiếc chăn cho buổi picnic.",
        "arabic": "فكرة جيدة. سأحضر بطانية للنزهة.",
    },
    {
        "line_number": 17,
        "speaker_name": "Alex",
        "lithuanian": "Aš atsivešiu gėrimų ir vaisių.",
        "latvian": "Es paņemšu līdzi dzērienus un augļus.",
        "estonian": "Ma toon jooke ja puuvilju.",
        "english": "I will bring drinks and fruit.",
        "german": "Ich bringe Getränke und Obst mit.",
        "french": "J'apporterai des boissons et des fruits.",
        "spanish": "Traeré bebidas y frutas.",
        "italian": "Porterò bevande e frutta.",
        "portuguese": "Vou trazer bebidas e frutas.",
        "dutch": "Ik neem dranken en fruit mee.",
        "polish": "Przyniosę napoje i owoce.",
        "ukrainian": "Я принесу напої та фрукти.",
        "russian": "Я принесу напитки и фрукты.",
        "swedish": "Jag tar med drycker och frukt.",
        "norwegian": "Jeg tar med drikke og frukt.",
        "danish": "Jeg tager drikkevarer og frugt med.",
        "finnish": "Otan juomia ja hedelmiä mukaan.",
        "greek": "Θα φέρω ποτά και φρούτα.",
        "brazilian_portuguese": "Vou trazer bebidas e frutas.",
        "mandarin": "我会带饮料和水果。",
        "japanese": "飲み物と果物を持っていきます。",
        "korean": "음료와 과일을 가져올게요.",
        "hindi": "मैं पेय और फल लाऊँगा।",
        "vietnamese": "Tôi sẽ mang theo đồ uống và trái cây.",
        "arabic": "سأحضر مشروبات وفواكه.",
    },
    {
        "line_number": 18,
        "speaker_name": "Mia",
        "lithuanian": "Tobula! Ar oras bus geras šeštadienį?",
        "latvian": "Lieliski! Vai sestdien būs labs laiks?",
        "estonian": "Suurepärane! Kas laupäeval on ilus ilm?",
        "english": "Perfect! Will the weather be good on Saturday?",
        "german": "Perfekt! Wird das Wetter am Samstag gut sein?",
        "french": "Parfait! Est-ce que le temps sera beau samedi?",
        "spanish": "¡Perfecto! ¿Hará buen tiempo el sábado?",
        "italian": "Perfetto! Il tempo sarà bello sabato?",
        "portuguese": "Perfeito! O tempo vai ser bom no sábado?",
        "dutch": "Perfect! Wordt het weer goed op zaterdag?",
        "polish": "Idealnie! Czy w sobotę będzie dobra pogoda?",
        "ukrainian": "Чудово! Чи буде гарна погода в суботу?",
        "russian": "Отлично! Погода будет хорошей в субботу?",
        "swedish": "Perfekt! Kommer vädret att vara bra på lördag?",
        "norwegian": "Perfekt! Vil været bli bra på lørdag?",
        "danish": "Perfekt! Bliver vejret godt på lørdag?",
        "finnish": "Täydellinen! Onko sää hyvä lauantaina?",
        "greek": "Τέλεια! Θα είναι καλός ο καιρός το Σάββατο;",
        "brazilian_portuguese": "Perfeito! O tempo vai estar bom no sábado?",
        "mandarin": "完美！周六天气会好吗？",
        "japanese": "完璧！土曜日は天気がいいですか？",
        "korean": "완벽해요! 토요일 날씨가 좋을까요?",
        "hindi": "परफेक्ट! क्या शनिवार को मौसम अच्छा रहेगा?",
        "vietnamese": "Tuyệt vời! Thứ Bảy thời tiết có đẹp không?",
        "arabic": "ممتاز! هل سيكون الطقس جيداً يوم السبت؟",
    },
    {
        "line_number": 19,
        "speaker_name": "Alex",
        "lithuanian": "Patikrinau orų prognozę. Saulėta ir dvidešimt penki laipsniai.",
        "latvian": "Es pārbaudīju laika prognozi. Saulains un divdesmit pieci grādi.",
        "estonian": "Vaatasin ilmaprognoosi. Päikseline ja kakskümmend viis kraadi.",
        "english": "I checked the weather forecast. Sunny and twenty-five degrees.",
        "german": "Ich habe die Wettervorhersage gecheckt. Sonnig und fünfundzwanzig Grad.",
        "french": "J'ai vérifié la météo. Ensoleillé et vingt-cinq degrés.",
        "spanish": "Revisé el pronóstico del tiempo. Soleado y veinticinco grados.",
        "italian": "Ho controllato le previsioni del tempo. Soleggiato e venticinque gradi.",
        "portuguese": "Verifiquei a previsão do tempo. Ensolarado e vinte e cinco graus.",
        "dutch": "Ik heb de weersvoorspelling gecheckt. Zonnig en vijfentwintig graden.",
        "polish": "Sprawdziłem prognozę pogody. Słonecznie i dwadzieścia pięć stopni.",
        "ukrainian": "Я перевірив прогноз погоди. Сонячно і двадцять п'ять градусів.",
        "russian": "Я проверил прогноз погоды. Солнечно и двадцать пять градусов.",
        "swedish": "Jag kollade väderprognosen. Soligt och tjugofem grader.",
        "norwegian": "Jeg sjekket værmeldingen. Solrikt og tjuefem grader.",
        "danish": "Jeg tjekkede vejrudsigten. Solrigt og femogtyve grader.",
        "finnish": "Tarkistin sääennusteen. Aurinkoinen ja kaksikymmentäviisi astetta.",
        "greek": "Έλεγξα την πρόγνωση καιρού. Ηλιόλουστο και εικοσιπέντε βαθμοί.",
        "brazilian_portuguese": "Verifiquei a previsão do tempo. Ensolarado e vinte e cinco graus.",
        "mandarin": "我查了天气预报。晴天，二十五度。",
        "japanese": "天気予報を確認しました。晴れで25度です。",
        "korean": "날씨 예보를 확인했어요. 맑고 25도래요.",
        "hindi": "मैंने मौसम का पूर्वानुमान देखा। धूप वाला और पच्चीस डिग्री।",
        "vietnamese": "Tôi đã kiểm tra dự báo thời tiết. Nắng và hai mươi lăm độ.",
        "arabic": "تحققت من توقعات الطقس. مشمس وخمسة وعشرون درجة.",
    },
    {
        "line_number": 20,
        "speaker_name": "Mia",
        "lithuanian": "Puiku! Turėsiu atsivežti saulės kremą.",
        "latvian": "Lieliski! Man jāpaņem sauļošanās krēms.",
        "estonian": "Suurepärane! Pean päikesekreemi kaasa võtma.",
        "english": "Excellent! I will need to bring sunscreen.",
        "german": "Ausgezeichnet! Ich muss Sonnencreme mitbringen.",
        "french": "Excellent! Je devrai apporter de la crème solaire.",
        "spanish": "¡Excelente! Tendré que traer protector solar.",
        "italian": "Eccellente! Dovrò portare la crema solare.",
        "portuguese": "Excelente! Vou precisar de trazer protetor solar.",
        "dutch": "Uitstekend! Ik moet zonnebrandcrème meenemen.",
        "polish": "Doskonale! Będę musiała zabrać krem przeciwsłoneczny.",
        "ukrainian": "Відмінно! Мені треба буде взяти сонцезахисний крем.",
        "russian": "Отлично! Мне нужно будет взять солнцезащитный крем.",
        "swedish": "Utmärkt! Jag måste ta med solkräm.",
        "norwegian": "Utmerket! Jeg må ta med solkrem.",
        "danish": "Fremragende! Jeg bliver nødt til at tage solcreme med.",
        "finnish": "Erinomainen! Minun täytyy ottaa aurinkovoide mukaan.",
        "greek": "Εξαιρετικά! Θα χρειαστεί να φέρω αντηλιακό.",
        "brazilian_portuguese": "Excelente! Vou precisar trazer protetor solar.",
        "mandarin": "太好了！我需要带防晒霜。",
        "japanese": "素晴らしい！日焼け止めを持っていく必要があります。",
        "korean": "훌륭해요! 선크림을 가져가야 할 것 같아요.",
        "hindi": "बेहतरीन! मुझे सनस्क्रीन लाना होगा।",
        "vietnamese": "Tuyệt vời! Tôi sẽ cần mang kem chống nắng.",
        "arabic": "ممتاز! سأحتاج إلى إحضار واقٍ من الشمس.",
    },
    {
        "line_number": 21,
        "speaker_name": "Alex",
        "lithuanian": "Taip pat patartina atsivežti vandeniui atsparius batelius.",
        "latvian": "Ieteicams arī paņemt līdzi ūdensizturīgus apavus.",
        "estonian": "Samuti on soovitatav kaasa võtta veekindlad kingad.",
        "english": "It is also a good idea to bring waterproof shoes.",
        "german": "Es ist auch eine gute Idee, wasserfeste Schuhe mitzubringen.",
        "french": "C'est aussi une bonne idée d'apporter des chaussures imperméables.",
        "spanish": "También es buena idea traer zapatos impermeables.",
        "italian": "È anche una buona idea portare scarpe impermeabili.",
        "portuguese": "Também é boa ideia trazer sapatos impermeáveis.",
        "dutch": "Het is ook een goed idee om waterdichte schoenen mee te nemen.",
        "polish": "Dobrym pomysłem jest też zabranie wodoodpornych butów.",
        "ukrainian": "Також гарна ідея взяти водонепроникне взуття.",
        "russian": "Также хорошая идея взять водонепроницаемую обувь.",
        "swedish": "Det är också en bra idé att ta med vattentäta skor.",
        "norwegian": "Det er også en god idé å ta med vanntette sko.",
        "danish": "Det er også en god idé at tage vandtætte sko med.",
        "finnish": "On myös hyvä idea ottaa vedenpitävät kengät mukaan.",
        "greek": "Είναι επίσης καλή ιδέα να φέρετε αδιάβροχα παπούτσια.",
        "brazilian_portuguese": "Também é uma boa ideia trazer sapatos impermeáveis.",
        "mandarin": "带防水鞋也是个好主意。",
        "japanese": "防水シューズを持っていくのも良いアイデアです。",
        "korean": "방수 신발을 가져가는 것도 좋은 생각이에요.",
        "hindi": "वाटरप्रूफ जूते लाना भी अच्छा विचार है।",
        "vietnamese": "Mang giày chống nước cũng là ý hay.",
        "arabic": "من الجيد أيضاً إحضار أحذية مقاومة للماء.",
    },
    {
        "line_number": 22,
        "speaker_name": "Mia",
        "lithuanian": "Ar ežere bus galima maudytis?",
        "latvian": "Vai ezerā varēs peldēties?",
        "estonian": "Kas järves saab ujuda?",
        "english": "Will it be possible to swim in the lake?",
        "german": "Wird es möglich sein, im See zu schwimmen?",
        "french": "Sera-t-il possible de nager dans le lac?",
        "spanish": "¿Será posible nadar en el lago?",
        "italian": "Sarà possibile nuotare nel lago?",
        "portuguese": "Será possível nadar no lago?",
        "dutch": "Zal het mogelijk zijn om in het meer te zwemmen?",
        "polish": "Czy będzie można pływać w jeziorze?",
        "ukrainian": "Чи можна буде купатися в озері?",
        "russian": "Можно ли будет купаться в озере?",
        "swedish": "Kommer det vara möjligt att simma i sjön?",
        "norwegian": "Vil det være mulig å svømme i innsjøen?",
        "danish": "Vil det være muligt at svømme i søen?",
        "finnish": "Voiko järvessä uida?",
        "greek": "Θα είναι δυνατόν να κολυμπήσουμε στη λίμνη;",
        "brazilian_portuguese": "Será possível nadar no lago?",
        "mandarin": "可以在湖里游泳吗？",
        "japanese": "湖で泳ぐことはできますか？",
        "korean": "호수에서 수영할 수 있을까요?",
        "hindi": "क्या झील में तैरना संभव होगा?",
        "vietnamese": "Có thể bơi trong hồ không?",
        "arabic": "هل سيكون ممكناً السباحة في البحيرة؟",
    },
    {
        "line_number": 23,
        "speaker_name": "Alex",
        "lithuanian": "Taip! Vanduo ten labai švarus ir šiltas vasarą.",
        "latvian": "Jā! Ūdens tur ir ļoti tīrs un silts vasarā.",
        "estonian": "Jah! Vesi on seal väga puhas ja soe suvel.",
        "english": "Yes! The water there is very clean and warm in summer.",
        "german": "Ja! Das Wasser dort ist sehr sauber und im Sommer warm.",
        "french": "Oui! L'eau y est très propre et chaude en été.",
        "spanish": "¡Sí! El agua allí es muy limpia y cálida en verano.",
        "italian": "Sì! L'acqua lì è molto pulita e calda in estate.",
        "portuguese": "Sim! A água lá é muito limpa e quente no verão.",
        "dutch": "Ja! Het water daar is heel schoon en warm in de zomer.",
        "polish": "Tak! Woda tam jest bardzo czysta i ciepła latem.",
        "ukrainian": "Так! Вода там дуже чиста і тепла влітку.",
        "russian": "Да! Вода там очень чистая и тёплая летом.",
        "swedish": "Ja! Vattnet där är mycket rent och varmt på sommaren.",
        "norwegian": "Ja! Vannet der er veldig rent og varmt om sommeren.",
        "danish": "Ja! Vandet der er meget rent og varmt om sommeren.",
        "finnish": "Kyllä! Vesi on siellä erittäin puhdasta ja lämmintä kesällä.",
        "greek": "Ναι! Το νερό εκεί είναι πολύ καθαρό και ζεστό το καλοκαίρι.",
        "brazilian_portuguese": "Sim! A água lá é muito limpa e quente no verão.",
        "mandarin": "是的！那里的水夏天非常干净温暖。",
        "japanese": "はい！そこの水は夏にとてもきれいで温かいです。",
        "korean": "네! 거기 물은 여름에 아주 깨끗하고 따뜻해요.",
        "hindi": "हाँ! वहाँ का पानी गर्मियों में बहुत साफ और गर्म होता है।",
        "vietnamese": "Có! Nước ở đó rất trong sạch và ấm vào mùa hè.",
        "arabic": "نعم! الماء هناك نظيف جداً ودافئ في الصيف.",
    },
    {
        "line_number": 24,
        "speaker_name": "Mia",
        "lithuanian": "Tada reikės atsivežti maudymosi kostiumėlį!",
        "latvian": "Tad man jāpaņem peldkostīms!",
        "estonian": "Siis pean ujumisriided kaasa võtma!",
        "english": "Then I will need to bring my swimsuit!",
        "german": "Dann muss ich meinen Badeanzug mitbringen!",
        "french": "Alors je devrai apporter mon maillot de bain!",
        "spanish": "¡Entonces tendré que traer mi traje de baño!",
        "italian": "Allora dovrò portare il mio costume da bagno!",
        "portuguese": "Então vou precisar de trazer o meu fato de banho!",
        "dutch": "Dan moet ik mijn zwemkleding meenemen!",
        "polish": "Zatem będę musiała zabrać strój kąpielowy!",
        "ukrainian": "Тоді мені потрібно буде взяти купальник!",
        "russian": "Тогда мне нужно будет взять купальник!",
        "swedish": "Då måste jag ta med min baddräkt!",
        "norwegian": "Da må jeg ta med badedrakt!",
        "danish": "Så skal jeg tage min badetøj med!",
        "finnish": "Sitten minun täytyy ottaa uimapuku mukaan!",
        "greek": "Τότε θα χρειαστεί να φέρω το μαγιό μου!",
        "brazilian_portuguese": "Então vou precisar trazer meu maiô!",
        "mandarin": "那我需要带泳衣！",
        "japanese": "では水着を持っていく必要があります！",
        "korean": "그럼 수영복을 가져가야겠어요!",
        "hindi": "तो मुझे अपना स्विमसूट लाना होगा!",
        "vietnamese": "Vậy tôi sẽ cần mang đồ bơi!",
        "arabic": "إذن سأحتاج إلى إحضار ملابس السباحة!",
    },
    {
        "line_number": 25,
        "speaker_name": "Alex",
        "lithuanian": "Ir aš! Taip pat galime išsinuomoti valtį.",
        "latvian": "Es arī! Mēs arī varam iznomāt laivu.",
        "estonian": "Mina ka! Võiksime ka paati rentida.",
        "english": "Me too! We could also rent a boat.",
        "german": "Ich auch! Wir könnten auch ein Boot mieten.",
        "french": "Moi aussi! On pourrait aussi louer un bateau.",
        "spanish": "¡Yo también! También podríamos alquilar un bote.",
        "italian": "Anch'io! Potremmo anche noleggiare una barca.",
        "portuguese": "Eu também! Poderíamos também alugar um barco.",
        "dutch": "Ik ook! We zouden ook een boot kunnen huren.",
        "polish": "Ja też! Moglibyśmy też wynająć łódkę.",
        "ukrainian": "Я теж! Ми також могли б орендувати човен.",
        "russian": "Я тоже! Мы могли бы также взять лодку напрокат.",
        "swedish": "Jag med! Vi skulle också kunna hyra en båt.",
        "norwegian": "Jeg også! Vi kunne også leie en båt.",
        "danish": "Jeg også! Vi kunne også leje en båd.",
        "finnish": "Minäkin! Voisimme myös vuokrata veneen.",
        "greek": "Κι εγώ! Θα μπορούσαμε επίσης να νοικιάσουμε μια βάρκα.",
        "brazilian_portuguese": "Eu também! Poderíamos também alugar um barco.",
        "mandarin": "我也是！我们也可以租一条船。",
        "japanese": "私もです！ボートを借りることもできます。",
        "korean": "저도요! 보트를 빌릴 수도 있어요.",
        "hindi": "मैं भी! हम एक नाव भी किराये पर ले सकते हैं।",
        "vietnamese": "Tôi cũng vậy! Chúng ta cũng có thể thuê thuyền.",
        "arabic": "أنا أيضاً! يمكننا أيضاً استئجار قارب.",
    },
    {
        "line_number": 26,
        "speaker_name": "Mia",
        "lithuanian": "Tai būtų labai smagu! Kiek kainuoja valties nuoma?",
        "latvian": "Tas būtu ļoti jautri! Cik maksā laivas noma?",
        "estonian": "See oleks väga lõbus! Kui palju maksab paadi rent?",
        "english": "That would be so much fun! How much does it cost to rent a boat?",
        "german": "Das wäre so viel Spaß! Wie viel kostet es, ein Boot zu mieten?",
        "french": "Ce serait tellement amusant! Combien ça coûte de louer un bateau?",
        "spanish": "¡Sería muy divertido! ¿Cuánto cuesta alquilar un bote?",
        "italian": "Sarebbe molto divertente! Quanto costa noleggiare una barca?",
        "portuguese": "Seria muito divertido! Quanto custa alugar um barco?",
        "dutch": "Dat zou zo leuk zijn! Hoeveel kost het om een boot te huren?",
        "polish": "To byłoby bardzo zabawne! Ile kosztuje wynajem łódki?",
        "ukrainian": "Це було б так весело! Скільки коштує оренда човна?",
        "russian": "Это было бы так весело! Сколько стоит аренда лодки?",
        "swedish": "Det skulle vara så roligt! Hur mycket kostar det att hyra en båt?",
        "norwegian": "Det ville vært så gøy! Hvor mye koster det å leie en båt?",
        "danish": "Det ville være så sjovt! Hvor meget koster det at leje en båd?",
        "finnish": "Se olisi niin hauskaa! Kuinka paljon veneen vuokraaminen maksaa?",
        "greek": "Θα ήταν τόσο διασκεδαστικό! Πόσο κοστίζει η ενοικίαση μιας βάρκας;",
        "brazilian_portuguese": "Seria tão divertido! Quanto custa alugar um barco?",
        "mandarin": "那会很有趣！租一条船要多少钱？",
        "japanese": "それはとても楽しそう！ボートを借りるのはいくらかかりますか？",
        "korean": "정말 재미있겠어요! 보트 빌리는 데 얼마예요?",
        "hindi": "यह बहुत मजेदार होगा! नाव किराये पर लेने में कितना खर्च होता है?",
        "vietnamese": "Thật thú vị! Thuê thuyền tốn bao nhiêu tiền?",
        "arabic": "سيكون ذلك ممتعاً جداً! كم تكلفة استئجار قارب؟",
    },
    {
        "line_number": 27,
        "speaker_name": "Alex",
        "lithuanian": "Manau, apie penkiolika eurų per valandą.",
        "latvian": "Es domāju, apmēram piecpadsmit eiro stundā.",
        "estonian": "Ma arvan, umbes viisteist eurot tunnis.",
        "english": "I think around fifteen euros per hour.",
        "german": "Ich glaube, etwa fünfzehn Euro pro Stunde.",
        "french": "Je pense environ quinze euros par heure.",
        "spanish": "Creo que alrededor de quince euros por hora.",
        "italian": "Penso intorno ai quindici euro all'ora.",
        "portuguese": "Acho que cerca de quinze euros por hora.",
        "dutch": "Ik denk zo'n vijftien euro per uur.",
        "polish": "Myślę, że około piętnaście euro za godzinę.",
        "ukrainian": "Думаю, приблизно п'ятнадцять євро на годину.",
        "russian": "Думаю, около пятнадцати евро в час.",
        "swedish": "Jag tror ungefär femton euro per timme.",
        "norwegian": "Jeg tror rundt femten euro per time.",
        "danish": "Jeg tror omkring femten euro i timen.",
        "finnish": "Luulen noin viisitoista euroa tunnissa.",
        "greek": "Νομίζω περίπου δεκαπέντε ευρώ την ώρα.",
        "brazilian_portuguese": "Acho que cerca de quinze euros por hora.",
        "mandarin": "我想大约每小时十五欧元。",
        "japanese": "1時間あたり約15ユーロだと思います。",
        "korean": "시간당 약 15유로인 것 같아요.",
        "hindi": "मुझे लगता है लगभग पंद्रह यूरो प्रति घंटा।",
        "vietnamese": "Tôi nghĩ khoảng mười lăm euro mỗi giờ.",
        "arabic": "أعتقد حوالي خمسة عشر يورو في الساعة.",
    },
    {
        "line_number": 28,
        "speaker_name": "Mia",
        "lithuanian": "Tai priimtina. Galime išsinuomoti valtį vienai valandai.",
        "latvian": "Tas ir pieņemami. Mēs varam iznomāt laivu uz vienu stundu.",
        "estonian": "See on mõistlik. Võime paadi rentida üheks tunniks.",
        "english": "That is reasonable. We can rent the boat for one hour.",
        "german": "Das ist vernünftig. Wir können das Boot für eine Stunde mieten.",
        "french": "C'est raisonnable. On peut louer le bateau pour une heure.",
        "spanish": "Es razonable. Podemos alquilar el bote por una hora.",
        "italian": "È ragionevole. Possiamo noleggiare la barca per un'ora.",
        "portuguese": "É razoável. Podemos alugar o barco por uma hora.",
        "dutch": "Dat is redelijk. We kunnen de boot voor een uur huren.",
        "polish": "To rozsądne. Możemy wynająć łódkę na godzinę.",
        "ukrainian": "Це розумно. Ми можемо орендувати човен на одну годину.",
        "russian": "Это разумно. Мы можем взять лодку напрокат на один час.",
        "swedish": "Det är rimligt. Vi kan hyra båten i en timme.",
        "norwegian": "Det er rimelig. Vi kan leie båten i en time.",
        "danish": "Det er rimeligt. Vi kan leje båden i en time.",
        "finnish": "Se on kohtuullista. Voimme vuokrata veneen tunnin ajaksi.",
        "greek": "Είναι λογικό. Μπορούμε να νοικιάσουμε τη βάρκα για μία ώρα.",
        "brazilian_portuguese": "É razoável. Podemos alugar o barco por uma hora.",
        "mandarin": "这很合理。我们可以租一个小时的船。",
        "japanese": "それは妥当ですね。1時間ボートを借りましょう。",
        "korean": "합리적이네요. 한 시간 동안 보트를 빌릴 수 있어요.",
        "hindi": "यह उचित है। हम एक घंटे के लिए नाव किराये पर ले सकते हैं।",
        "vietnamese": "Đó là hợp lý. Chúng ta có thể thuê thuyền trong một giờ.",
        "arabic": "هذا معقول. يمكننا استئجار القارب لمدة ساعة.",
    },
    {
        "line_number": 29,
        "speaker_name": "Alex",
        "lithuanian": "Puiku! Labai laukiu šios kelionės.",
        "latvian": "Lieliski! Es ļoti gaidu šo braucienu.",
        "estonian": "Suurepärane! Ootan seda reisi väga.",
        "english": "Great! I am really looking forward to this trip.",
        "german": "Super! Ich freue mich wirklich auf diese Reise.",
        "french": "Super! J'ai vraiment hâte de faire ce voyage.",
        "spanish": "¡Genial! Estoy muy emocionado por este viaje.",
        "italian": "Ottimo! Non vedo l'ora di fare questo viaggio.",
        "portuguese": "Óptimo! Estou mesmo ansioso por esta viagem.",
        "dutch": "Geweldig! Ik kijk echt uit naar deze reis.",
        "polish": "Świetnie! Naprawdę czekam na tę podróż.",
        "ukrainian": "Чудово! Я дуже чекаю на цю поїздку.",
        "russian": "Отлично! Я очень жду этой поездки.",
        "swedish": "Bra! Jag ser verkligen fram emot den här resan.",
        "norwegian": "Flott! Jeg gleder meg virkelig til denne turen.",
        "danish": "Fantastisk! Jeg glæder mig virkelig til denne tur.",
        "finnish": "Hienoa! Odotan tätä matkaa todella paljon.",
        "greek": "Υπέροχα! Ανυπομονώ πραγματικά για αυτό το ταξίδι.",
        "brazilian_portuguese": "Ótimo! Estou muito animado com essa viagem.",
        "mandarin": "太好了！我真的很期待这次旅行。",
        "japanese": "素晴らしい！この旅行がとても楽しみです。",
        "korean": "좋아요! 이 여행이 정말 기대돼요.",
        "hindi": "बढ़िया! मैं इस यात्रा का बेसब्री से इंतजार कर रहा हूँ।",
        "vietnamese": "Tuyệt! Tôi thực sự mong chờ chuyến đi này.",
        "arabic": "رائع! أتطلع حقاً إلى هذه الرحلة.",
    },
    {
        "line_number": 30,
        "speaker_name": "Mia",
        "lithuanian": "Aš irgi! Susitinkame šeštadienio rytą stotyje. Iki pasimatymo, Aleksai!",
        "latvian": "Es arī! Tiekamies sestdienas rītā stacijā. Uz redzēšanos, Alekss!",
        "estonian": "Mina ka! Kohtume laupäeva hommikul jaamas. Nägemiseni, Alex!",
        "english": "Me too! Let us meet at the station on Saturday morning. See you then, Alex!",
        "german": "Ich auch! Treffen wir uns am Samstagmorgen am Bahnhof. Bis dann, Alex!",
        "french": "Moi aussi! On se retrouve à la gare samedi matin. À bientôt, Alex!",
        "spanish": "¡Yo también! Quedamos en la estación el sábado por la mañana. ¡Hasta entonces, Alex!",
        "italian": "Anch'io! Ci incontriamo alla stazione sabato mattina. A presto, Alex!",
        "portuguese": "Eu também! Vemo-nos na estação no sábado de manhã. Até lá, Alex!",
        "dutch": "Ik ook! Laten we zaterdag ochtend op het station afspreken. Tot dan, Alex!",
        "polish": "Ja też! Spotkajmy się w sobotę rano na dworcu. Do zobaczenia, Alex!",
        "ukrainian": "Я теж! Зустрінемось у суботу вранці на станції. До побачення, Алексе!",
        "russian": "Я тоже! Встретимся в субботу утром на станции. До встречи, Алекс!",
        "swedish": "Jag med! Låt oss träffas på stationen lördag morgon. Vi ses, Alex!",
        "norwegian": "Jeg også! La oss møtes på stasjonen lørdag morgen. Vi sees, Alex!",
        "danish": "Jeg også! Lad os mødes på stationen lørdag morgen. Vi ses, Alex!",
        "finnish": "Minäkin! Tavataan asemalla lauantaiaamuna. Nähdään, Alex!",
        "greek": "Κι εγώ! Ας συναντηθούμε στο σταθμό το Σάββατο πρωί. Τα λέμε, Άλεξ!",
        "brazilian_portuguese": "Eu também! Vamos nos encontrar na estação no sábado de manhã. Até lá, Alex!",
        "mandarin": "我也是！星期六早上在车站见面吧。回头见，亚历克斯！",
        "japanese": "私もです！土曜日の朝に駅で会いましょう。またね、アレックス！",
        "korean": "저도요! 토요일 아침에 역에서 만나요. 그때 봐요, 알렉스!",
        "hindi": "मैं भी! शनिवार की सुबह स्टेशन पर मिलते हैं। फिर मिलेंगे, एलेक्स!",
        "vietnamese": "Tôi cũng vậy! Hãy gặp nhau tại ga vào sáng thứ Bảy. Hẹn gặp lại, Alex!",
        "arabic": "أنا أيضاً! لنلتقِ في المحطة صباح السبت. إلى اللقاء يا أليكس!",
    },
]


def seed():
    with app.app_context():
        db.create_all()

        # Check if already seeded
        existing = Dialogue.query.filter_by(topic="Planning a Weekend Trip").first()
        if existing:
            print("A2 dialogue already exists — skipping.")
            return

        # Create dialogue record
        dialogue = Dialogue(
            topic="Planning a Weekend Trip",
            lang_level="A2",
            length=30
        )
        db.session.add(dialogue)
        db.session.flush()

        # Add all lines
        for line_data in lines_data:
            line = DialogueLine(
                dialogue_id=dialogue.id,
                **line_data
            )
            db.session.add(line)

        db.session.commit()
        print(f"Successfully seeded A2 dialogue ID {dialogue.id} with {len(lines_data)} lines in 25 languages.")


if __name__ == '__main__':
    seed()
