import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from hello_world import app, db, Dialogue, DialogueLine

# -------------------------------------------------------
# B1 Dialogue — "Starting a New Job"
# 30 sentences, 2 speakers: Alex and Mia
# Same names used across all languages
# -------------------------------------------------------

lines_data = [
    {
        "line_number": 1,
        "speaker_name": "Alex",
        "lithuanian": "Sveika, Mia! Girdėjau, kad pradedi naują darbą kitą savaitę. Kaip jautiesi?",
        "latvian": "Sveika, Mia! Dzirdēju, ka nākamnedēļ sāc jaunu darbu. Kā tu jūties?",
        "estonian": "Tere, Mia! Kuulsin, et alustad järgmisel nädalal uut tööd. Kuidas sa end tunned?",
        "english": "Hi Mia! I heard you are starting a new job next week. How do you feel?",
        "german": "Hallo Mia! Ich habe gehört, dass du nächste Woche einen neuen Job anfängst. Wie fühlst du dich?",
        "french": "Salut Mia! J'ai entendu dire que tu commences un nouveau travail la semaine prochaine. Comment tu te sens?",
        "spanish": "¡Hola Mia! He escuchado que empiezas un nuevo trabajo la semana que viene. ¿Cómo te sientes?",
        "italian": "Ciao Mia! Ho sentito che la settimana prossima inizi un nuovo lavoro. Come ti senti?",
        "portuguese": "Olá Mia! Soube que começas um novo emprego na semana que vem. Como te sentes?",
        "dutch": "Hoi Mia! Ik hoorde dat je volgende week een nieuwe baan begint. Hoe voel jij je?",
        "polish": "Cześć Mia! Słyszałam, że w przyszłym tygodniu zaczynasz nową pracę. Jak się czujesz?",
        "ukrainian": "Привіт, Міа! Я чула, що наступного тижня ти починаєш нову роботу. Як ти себе почуваєш?",
        "russian": "Привет, Миа! Я слышал, что на следующей неделе ты начинаешь новую работу. Как ты себя чувствуешь?",
        "swedish": "Hej Mia! Jag hörde att du börjar ett nytt jobb nästa vecka. Hur känner du dig?",
        "norwegian": "Hei Mia! Jeg hørte at du begynner i ny jobb neste uke. Hvordan føler du deg?",
        "danish": "Hej Mia! Jeg hørte, at du starter et nyt job næste uge. Hvordan har du det?",
        "finnish": "Hei Mia! Kuulin, että aloitat uuden työn ensi viikolla. Miltä sinusta tuntuu?",
        "greek": "Γεια Μία! Άκουσα ότι την επόμενη εβδομάδα αρχίζεις νέα δουλειά. Πώς νιώθεις;",
        "brazilian_portuguese": "Oi Mia! Soube que você vai começar um novo emprego na semana que vem. Como você está se sentindo?",
        "mandarin": "嗨，米亚！我听说你下周要开始新工作了。你感觉怎么样？",
        "japanese": "こんにちは、ミア！来週新しい仕事を始めると聞きました。どんな気持ちですか？",
        "korean": "안녕 미아! 다음 주에 새 직장을 시작한다고 들었어요. 기분이 어때요?",
        "hindi": "नमस्ते मिया! मैंने सुना कि तुम अगले हफ्ते नई नौकरी शुरू कर रही हो। कैसा महसूस हो रहा है?",
        "vietnamese": "Chào Mia! Tôi nghe nói bạn sẽ bắt đầu công việc mới vào tuần tới. Bạn cảm thấy thế nào?",
        "arabic": "مرحباً ميا! سمعت أنك ستبدأين وظيفة جديدة الأسبوع القادم. كيف تشعرين؟",
    },
    {
        "line_number": 2,
        "speaker_name": "Mia",
        "lithuanian": "Esu labai susijaudinusi, bet kartu ir šiek tiek nervinuosi. Tai didelė kompanija.",
        "latvian": "Esmu ļoti satraukta, bet arī nedaudz nervozēju. Tas ir liels uzņēmums.",
        "estonian": "Olen väga põnevil, aga ka natuke närviline. See on suur ettevõte.",
        "english": "I am very excited but also a little nervous. It is a big company.",
        "german": "Ich bin sehr aufgeregt, aber auch ein bisschen nervös. Es ist ein großes Unternehmen.",
        "french": "Je suis très excitée mais aussi un peu nerveuse. C'est une grande entreprise.",
        "spanish": "Estoy muy emocionada pero también un poco nerviosa. Es una empresa grande.",
        "italian": "Sono molto entusiasta ma anche un po' nervosa. È una grande azienda.",
        "portuguese": "Estou muito entusiasmada mas também um pouco nervosa. É uma empresa grande.",
        "dutch": "Ik ben heel opgewonden maar ook een beetje nerveus. Het is een groot bedrijf.",
        "polish": "Jestem bardzo podekscytowana, ale też trochę zdenerwowana. To duża firma.",
        "ukrainian": "Я дуже схвильована, але й трохи нервуюся. Це велика компанія.",
        "russian": "Я очень взволнована, но и немного нервничаю. Это большая компания.",
        "swedish": "Jag är väldigt upphetsad men också lite nervös. Det är ett stort företag.",
        "norwegian": "Jeg er veldig spent men også litt nervøs. Det er et stort selskap.",
        "danish": "Jeg er meget begejstret men også lidt nervøs. Det er en stor virksomhed.",
        "finnish": "Olen todella innostunut mutta myös hieman hermostunut. Se on iso yritys.",
        "greek": "Είμαι πολύ ενθουσιασμένη αλλά και λίγο νευρική. Είναι μεγάλη εταιρεία.",
        "brazilian_portuguese": "Estou muito animada mas também um pouco nervosa. É uma empresa grande.",
        "mandarin": "我非常兴奋，但也有点紧张。这是一家大公司。",
        "japanese": "とても楽しみですが、少し緊張もしています。大きな会社です。",
        "korean": "정말 설레지만 조금 떨리기도 해요. 큰 회사거든요.",
        "hindi": "मैं बहुत उत्साहित हूँ लेकिन थोड़ा घबराहट भी हो रही है। यह एक बड़ी कंपनी है।",
        "vietnamese": "Tôi rất hào hứng nhưng cũng hơi hồi hộp. Đó là một công ty lớn.",
        "arabic": "أنا متحمسة جداً ولكن أيضاً متوترة قليلاً. إنها شركة كبيرة.",
    },
    {
        "line_number": 3,
        "speaker_name": "Alex",
        "lithuanian": "Suprantu tave. Kokias pareigas tu eisi?",
        "latvian": "Es tevi saprotu. Kādas būs tavas pienākumi?",
        "estonian": "Ma saan sinust aru. Millised on sinu tööülesanded?",
        "english": "I understand you. What will your responsibilities be?",
        "german": "Ich verstehe dich. Was werden deine Aufgaben sein?",
        "french": "Je te comprends. Quelles seront tes responsabilités?",
        "spanish": "Te entiendo. ¿Cuáles serán tus responsabilidades?",
        "italian": "Ti capisco. Quali saranno le tue responsabilità?",
        "portuguese": "Percebo-te. Quais serão as tuas responsabilidades?",
        "dutch": "Ik begrijp je. Wat zullen jouw verantwoordelijkheden zijn?",
        "polish": "Rozumiem cię. Jakie będą twoje obowiązki?",
        "ukrainian": "Я тебе розумію. Які будуть твої обов'язки?",
        "russian": "Я тебя понимаю. Какими будут твои обязанности?",
        "swedish": "Jag förstår dig. Vad kommer dina ansvarsområden att vara?",
        "norwegian": "Jeg forstår deg. Hva vil dine ansvarsområder være?",
        "danish": "Jeg forstår dig. Hvad vil dine ansvarsområder være?",
        "finnish": "Ymmärrän sinut. Mitä vastuualueitasi tulee olemaan?",
        "greek": "Σε καταλαβαίνω. Ποιες θα είναι οι ευθύνες σου;",
        "brazilian_portuguese": "Eu te entendo. Quais serão suas responsabilidades?",
        "mandarin": "我理解你。你的工作职责是什么？",
        "japanese": "わかります。あなたの責任は何になりますか？",
        "korean": "이해해요. 어떤 업무를 맡게 되나요?",
        "hindi": "मैं समझ सकता हूँ। आपकी जिम्मेदारियाँ क्या होंगी?",
        "vietnamese": "Tôi hiểu bạn. Trách nhiệm của bạn sẽ là gì?",
        "arabic": "أفهمك. ما هي مسؤولياتك؟",
    },
    {
        "line_number": 4,
        "speaker_name": "Mia",
        "lithuanian": "Dirbu rinkodaros vadybininke. Turėsiu valdyti socialinės medijos paskyras ir kurti turinį.",
        "latvian": "Es strādāšu par mārketinga menedžeri. Man būs jāpārvalda sociālo mediju konti un jāveido saturs.",
        "estonian": "Töötan turundusmanagerina. Pean haldama sotsiaalmeedia kontosid ja looma sisu.",
        "english": "I will be working as a marketing manager. I will need to manage social media accounts and create content.",
        "german": "Ich werde als Marketing-Managerin arbeiten. Ich werde Social-Media-Konten verwalten und Inhalte erstellen müssen.",
        "french": "Je vais travailler en tant que responsable marketing. Je devrai gérer les comptes de réseaux sociaux et créer du contenu.",
        "spanish": "Voy a trabajar como gerente de marketing. Tendré que gestionar las cuentas de redes sociales y crear contenido.",
        "italian": "Lavorerò come responsabile marketing. Dovrò gestire gli account sui social media e creare contenuti.",
        "portuguese": "Vou trabalhar como gestora de marketing. Terei de gerir as contas de redes sociais e criar conteúdo.",
        "dutch": "Ik ga werken als marketingmanager. Ik moet sociale media-accounts beheren en content maken.",
        "polish": "Będę pracować jako menedżer marketingu. Będę musiała zarządzać kontami w mediach społecznościowych i tworzyć treści.",
        "ukrainian": "Я буду працювати менеджером з маркетингу. Мені потрібно буде керувати акаунтами в соціальних мережах та створювати контент.",
        "russian": "Я буду работать менеджером по маркетингу. Мне нужно будет управлять аккаунтами в социальных сетях и создавать контент.",
        "swedish": "Jag ska arbeta som marknadsföringschef. Jag kommer att behöva hantera konton i sociala medier och skapa innehåll.",
        "norwegian": "Jeg skal jobbe som markedssjef. Jeg må administrere sosiale medier-kontoer og lage innhold.",
        "danish": "Jeg skal arbejde som marketingchef. Jeg skal administrere sociale mediekonti og skabe indhold.",
        "finnish": "Tulen työskentelemään markkinointipäällikkönä. Minun täytyy hallita sosiaalisen median tilejä ja luoda sisältöä.",
        "greek": "Θα εργαστώ ως υπεύθυνη μάρκετινγκ. Θα χρειαστεί να διαχειρίζομαι λογαριασμούς κοινωνικών δικτύων και να δημιουργώ περιεχόμενο.",
        "brazilian_portuguese": "Vou trabalhar como gerente de marketing. Terei que gerenciar contas de redes sociais e criar conteúdo.",
        "mandarin": "我将担任市场营销经理。我需要管理社交媒体账户并创建内容。",
        "japanese": "マーケティングマネージャーとして働きます。ソーシャルメディアのアカウントを管理してコンテンツを作成する必要があります。",
        "korean": "마케팅 매니저로 일하게 돼요. SNS 계정을 관리하고 콘텐츠를 만들어야 해요.",
        "hindi": "मैं मार्केटिंग मैनेजर के रूप में काम करूँगी। मुझे सोशल मीडिया अकाउंट मैनेज करने और कंटेंट बनाने की जरूरत होगी।",
        "vietnamese": "Tôi sẽ làm quản lý marketing. Tôi sẽ cần quản lý các tài khoản mạng xã hội và tạo nội dung.",
        "arabic": "سأعمل مديرةً للتسويق. سأحتاج إلى إدارة حسابات التواصل الاجتماعي وإنشاء المحتوى.",
    },
    {
        "line_number": 5,
        "speaker_name": "Alex",
        "lithuanian": "Tai skamba kaip labai kūrybiškas darbas. Ar turi ankstesnės patirties šioje srityje?",
        "latvian": "Tas izklausās kā ļoti radošs darbs. Vai tev ir iepriekšēja pieredze šajā jomā?",
        "estonian": "See tundub väga loominguline töö. Kas sul on selles valdkonnas varasem kogemus?",
        "english": "That sounds like a very creative job. Do you have previous experience in this field?",
        "german": "Das klingt nach einer sehr kreativen Arbeit. Hast du Erfahrung in diesem Bereich?",
        "french": "Ça semble être un travail très créatif. Tu as de l'expérience dans ce domaine?",
        "spanish": "Parece un trabajo muy creativo. ¿Tienes experiencia previa en este campo?",
        "italian": "Sembra un lavoro molto creativo. Hai esperienza precedente in questo settore?",
        "portuguese": "Parece um trabalho muito criativo. Tens experiência anterior nesta área?",
        "dutch": "Dat klinkt als een heel creatief werk. Heb jij ervaring in dit vakgebied?",
        "polish": "To brzmi jak bardzo kreatywna praca. Czy masz wcześniejsze doświadczenie w tej dziedzinie?",
        "ukrainian": "Це звучить як дуже творча робота. У тебе є попередній досвід у цій сфері?",
        "russian": "Это звучит как очень творческая работа. У тебя есть предыдущий опыт в этой области?",
        "swedish": "Det låter som ett väldigt kreativt jobb. Har du tidigare erfarenhet inom detta område?",
        "norwegian": "Det høres ut som et veldig kreativt jobbt. Har du tidligere erfaring innen dette feltet?",
        "danish": "Det lyder som et meget kreativt arbejde. Har du tidligere erfaring inden for dette felt?",
        "finnish": "Se kuulostaa todella luovalta työltä. Onko sinulla aikaisempaa kokemusta tällä alalla?",
        "greek": "Ακούγεται πολύ δημιουργική δουλειά. Έχεις προηγούμενη εμπειρία σε αυτόν τον τομέα;",
        "brazilian_portuguese": "Parece um trabalho muito criativo. Você tem experiência anterior nessa área?",
        "mandarin": "这听起来是一份非常有创意的工作。你在这个领域有之前的经验吗？",
        "japanese": "とてもクリエイティブな仕事ですね。この分野で以前の経験はありますか？",
        "korean": "정말 창의적인 일 같아요. 이 분야에서 이전 경험이 있나요?",
        "hindi": "यह बहुत रचनात्मक काम लगता है। क्या इस क्षेत्र में आपका पहले कोई अनुभव है?",
        "vietnamese": "Nghe có vẻ là một công việc rất sáng tạo. Bạn có kinh nghiệm trước đây trong lĩnh vực này không?",
        "arabic": "يبدو أنه عمل إبداعي جداً. هل لديك خبرة سابقة في هذا المجال؟",
    },
    {
        "line_number": 6,
        "speaker_name": "Mia",
        "lithuanian": "Taip, dirbau mažesnėje įmonėje dvejus metus, bet tai buvo gerokai mažesnė komanda.",
        "latvian": "Jā, es strādāju mazākā uzņēmumā divus gadus, bet tur bija daudz mazāka komanda.",
        "estonian": "Jah, töötasin väiksemas ettevõttes kaks aastat, aga seal oli palju väiksem meeskond.",
        "english": "Yes, I worked at a smaller company for two years but the team was much smaller there.",
        "german": "Ja, ich habe zwei Jahre bei einem kleineren Unternehmen gearbeitet, aber das Team war dort viel kleiner.",
        "french": "Oui, j'ai travaillé dans une plus petite entreprise pendant deux ans, mais l'équipe était beaucoup plus petite.",
        "spanish": "Sí, trabajé en una empresa más pequeña durante dos años, pero el equipo era mucho más pequeño allí.",
        "italian": "Sì, ho lavorato in un'azienda più piccola per due anni, ma il team era molto più piccolo lì.",
        "portuguese": "Sim, trabalhei numa empresa mais pequena durante dois anos, mas a equipa era muito mais pequena lá.",
        "dutch": "Ja, ik heb twee jaar bij een kleiner bedrijf gewerkt, maar het team was daar veel kleiner.",
        "polish": "Tak, pracowałam w mniejszej firmie przez dwa lata, ale zespół był tam znacznie mniejszy.",
        "ukrainian": "Так, я працювала в меншій компанії два роки, але команда там була набагато менша.",
        "russian": "Да, я работала в небольшой компании два года, но там команда была намного меньше.",
        "swedish": "Ja, jag jobbade på ett mindre företag i två år men teamet var mycket mindre där.",
        "norwegian": "Ja, jeg jobbet i et mindre selskap i to år, men teamet var mye mindre der.",
        "danish": "Ja, jeg arbejdede i en mindre virksomhed i to år, men teamet var meget mindre der.",
        "finnish": "Kyllä, työskentelin pienemmässä yrityksessä kaksi vuotta, mutta tiimi oli siellä paljon pienempi.",
        "greek": "Ναι, εργαζόμουν σε μικρότερη εταιρεία για δύο χρόνια αλλά η ομάδα ήταν πολύ μικρότερη εκεί.",
        "brazilian_portuguese": "Sim, trabalhei em uma empresa menor por dois anos, mas a equipe era muito menor lá.",
        "mandarin": "是的，我在一家较小的公司工作了两年，但那里的团队要小得多。",
        "japanese": "はい、2年間小さな会社で働いていましたが、チームはずっと小さかったです。",
        "korean": "네, 더 작은 회사에서 2년 일했는데 그곳은 팀이 훨씬 작았어요.",
        "hindi": "हाँ, मैंने दो साल एक छोटी कंपनी में काम किया, लेकिन वहाँ टीम काफी छोटी थी।",
        "vietnamese": "Có, tôi đã làm ở một công ty nhỏ hơn trong hai năm nhưng nhóm ở đó nhỏ hơn nhiều.",
        "arabic": "نعم، عملت في شركة أصغر لمدة سنتين لكن الفريق كان أصغر بكثير هناك.",
    },
    {
        "line_number": 7,
        "speaker_name": "Alex",
        "lithuanian": "Ar žinai, kiek žmonių bus tavo komandoje?",
        "latvian": "Vai tu zini, cik cilvēku būs tavā komandā?",
        "estonian": "Kas tead, kui palju inimesi on sinu meeskonnas?",
        "english": "Do you know how many people will be in your team?",
        "german": "Weißt du, wie viele Leute in deinem Team sein werden?",
        "french": "Tu sais combien de personnes il y aura dans ton équipe?",
        "spanish": "¿Sabes cuántas personas habrá en tu equipo?",
        "italian": "Sai quante persone ci saranno nel tuo team?",
        "portuguese": "Sabes quantas pessoas vão estar na tua equipa?",
        "dutch": "Weet je hoeveel mensen er in jouw team zullen zijn?",
        "polish": "Czy wiesz, ile osób będzie w twoim zespole?",
        "ukrainian": "Ти знаєш, скільки людей буде в твоїй команді?",
        "russian": "Ты знаешь, сколько людей будет в твоей команде?",
        "swedish": "Vet du hur många personer som kommer att vara i ditt team?",
        "norwegian": "Vet du hvor mange som vil være i teamet ditt?",
        "danish": "Ved du, hvor mange der vil være i dit team?",
        "finnish": "Tiedätkö kuinka monta ihmistä tiimissäsi on?",
        "greek": "Ξέρεις πόσα άτομα θα είναι στην ομάδα σου;",
        "brazilian_portuguese": "Você sabe quantas pessoas estarão na sua equipe?",
        "mandarin": "你知道你的团队会有多少人吗？",
        "japanese": "チームに何人いるか知っていますか？",
        "korean": "팀에 몇 명이 있을지 알고 있나요?",
        "hindi": "क्या आप जानती हैं कि आपकी टीम में कितने लोग होंगे?",
        "vietnamese": "Bạn có biết nhóm của bạn sẽ có bao nhiêu người không?",
        "arabic": "هل تعرفين كم شخصاً سيكون في فريقك؟",
    },
    {
        "line_number": 8,
        "speaker_name": "Mia",
        "lithuanian": "Mano vadovas sakė, kad komandoje bus apie penkiolika žmonių. Tai gerokai daugiau nei buvau įpratusi.",
        "latvian": "Mans vadītājs teica, ka komandā būs apmēram piecpadsmit cilvēku. Tas ir daudz vairāk nekā esmu pieradusi.",
        "estonian": "Minu juht ütles, et meeskonnas on umbes viisteist inimest. See on palju rohkem kui olen harjunud.",
        "english": "My manager said there will be around fifteen people in the team. That is a lot more than I was used to.",
        "german": "Mein Manager sagte, es werden etwa fünfzehn Leute im Team sein. Das ist viel mehr als ich gewohnt war.",
        "french": "Mon manager a dit qu'il y aurait environ quinze personnes dans l'équipe. C'est beaucoup plus que j'avais l'habitude.",
        "spanish": "Mi gerente dijo que habrá alrededor de quince personas en el equipo. Es mucho más de lo que estaba acostumbrada.",
        "italian": "Il mio manager ha detto che ci saranno circa quindici persone nel team. È molto di più di quello a cui ero abituata.",
        "portuguese": "O meu gestor disse que haverá cerca de quinze pessoas na equipa. É muito mais do que estava habituada.",
        "dutch": "Mijn manager zei dat er ongeveer vijftien mensen in het team zullen zijn. Dat is veel meer dan ik gewend was.",
        "polish": "Mój menedżer powiedział, że w zespole będzie około piętnastu osób. To znacznie więcej niż byłam przyzwyczajona.",
        "ukrainian": "Мій менеджер сказав, що в команді буде приблизно п'ятнадцять людей. Це набагато більше, ніж я звикла.",
        "russian": "Мой менеджер сказал, что в команде будет около пятнадцати человек. Это намного больше, чем я привыкла.",
        "swedish": "Min chef sa att det kommer att vara ungefär femton personer i teamet. Det är mycket mer än jag var van vid.",
        "norwegian": "Sjefen min sa at det vil være rundt femten i teamet. Det er mye mer enn jeg var vant til.",
        "danish": "Min leder sagde, at der vil være omkring femten mennesker i teamet. Det er meget mere end jeg var vant til.",
        "finnish": "Johtajani sanoi, että tiimissä on noin viisitoista henkilöä. Se on paljon enemmän kuin olin tottunut.",
        "greek": "Ο διευθυντής μου είπε ότι θα υπάρχουν περίπου δεκαπέντε άτομα στην ομάδα. Αυτό είναι πολύ περισσότερο από ό,τι ήμουν συνηθισμένη.",
        "brazilian_portuguese": "Meu gerente disse que haverá cerca de quinze pessoas na equipe. É muito mais do que eu estava acostumada.",
        "mandarin": "我的经理说团队里大约有十五个人。这比我习惯的要多得多。",
        "japanese": "マネージャーがチームには約15人いると言っていました。それは私が慣れていたよりずっと多いです。",
        "korean": "매니저님이 팀에 약 15명이 있을 거라고 했어요. 제가 익숙했던 것보다 훨씬 많네요.",
        "hindi": "मेरे मैनेजर ने कहा कि टीम में लगभग पंद्रह लोग होंगे। यह मुझे जितना आदत थी उससे काफी ज्यादा है।",
        "vietnamese": "Quản lý của tôi nói rằng sẽ có khoảng mười lăm người trong nhóm. Đó là nhiều hơn nhiều so với những gì tôi quen.",
        "arabic": "قال مديري إنه سيكون هناك حوالي خمسة عشر شخصاً في الفريق. هذا أكثر بكثير مما اعتدت عليه.",
    },
    {
        "line_number": 9,
        "speaker_name": "Alex",
        "lithuanian": "Nesijaudink. Esu tikras, kad greitai prisitaikysi. Ar jau susitikai su savo nauju viršininku?",
        "latvian": "Neuztraucies. Esmu pārliecināts, ka tu ātri pielāgosies. Vai tu jau esi tikies ar savu jauno priekšnieku?",
        "estonian": "Ära muretse. Olen kindel, et kohanet kiiresti. Kas oled oma uue ülemusega juba kohtunud?",
        "english": "Don't worry. I am sure you will adapt quickly. Have you already met your new boss?",
        "german": "Mach dir keine Sorgen. Ich bin sicher, dass du dich schnell anpassen wirst. Hast du deinen neuen Chef schon getroffen?",
        "french": "Ne t'inquiète pas. Je suis sûr que tu t'adapteras vite. Tu as déjà rencontré ton nouveau patron?",
        "spanish": "No te preocupes. Estoy seguro de que te adaptarás rápidamente. ¿Ya has conocido a tu nuevo jefe?",
        "italian": "Non preoccuparti. Sono sicuro che ti adatterai velocemente. Hai già incontrato il tuo nuovo capo?",
        "portuguese": "Não te preocupes. Tenho a certeza que te vais adaptar rapidamente. Já conheceste o teu novo chefe?",
        "dutch": "Maak je geen zorgen. Ik weet zeker dat je je snel aanpast. Heb je je nieuwe baas al ontmoet?",
        "polish": "Nie martw się. Jestem pewien, że szybko się przystosujesz. Czy poznałaś już swojego nowego szefa?",
        "ukrainian": "Не хвилюйся. Я впевнений, що ти швидко адаптуєшся. Ти вже зустрічалась зі своїм новим начальником?",
        "russian": "Не волнуйся. Я уверен, что ты быстро адаптируешься. Ты уже встречалась со своим новым боссом?",
        "swedish": "Oroa dig inte. Jag är säker på att du kommer att anpassa dig snabbt. Har du redan träffat din nya chef?",
        "norwegian": "Ikke bekymre deg. Jeg er sikker på at du tilpasser deg raskt. Har du allerede møtt den nye sjefen din?",
        "danish": "Bekymre dig ikke. Jeg er sikker på, at du tilpasser dig hurtigt. Har du allerede mødt din nye chef?",
        "finnish": "Älä huoli. Olen varma, että sopeudut nopeasti. Oletko jo tavannut uuden esimiehesi?",
        "greek": "Μην ανησυχείς. Είμαι σίγουρος ότι θα προσαρμοστείς γρήγορα. Έχεις ήδη γνωρίσει τον νέο σου αφεντικό;",
        "brazilian_portuguese": "Não se preocupe. Tenho certeza que você vai se adaptar rapidamente. Você já conheceu seu novo chefe?",
        "mandarin": "别担心。我相信你会很快适应的。你已经见过你的新老板了吗？",
        "japanese": "心配しないで。すぐに慣れると思います。もう新しい上司に会いましたか？",
        "korean": "걱정 마요. 금방 적응할 거예요. 새 상사는 벌써 만났나요?",
        "hindi": "चिंता मत करो। मुझे यकीन है तुम जल्दी ढल जाओगी। क्या तुम अपने नए बॉस से पहले ही मिल चुकी हो?",
        "vietnamese": "Đừng lo lắng. Tôi chắc chắn bạn sẽ thích nghi nhanh thôi. Bạn đã gặp sếp mới chưa?",
        "arabic": "لا تقلقي. أنا متأكد أنك ستتأقلمين بسرعة. هل قابلت مديرك الجديد بالفعل؟",
    },
    {
        "line_number": 10,
        "speaker_name": "Mia",
        "lithuanian": "Taip, turėjome pokalbį prieš dvi savaites. Ji atrodė labai kompetentinga ir maloni.",
        "latvian": "Jā, mums bija saruna pirms divām nedēļām. Viņa šķita ļoti kompetenta un patīkama.",
        "estonian": "Jah, meil oli vestlus kaks nädalat tagasi. Ta tundus väga pädev ja sõbralik.",
        "english": "Yes, we had an interview two weeks ago. She seemed very competent and friendly.",
        "german": "Ja, wir hatten vor zwei Wochen ein Gespräch. Sie wirkte sehr kompetent und freundlich.",
        "french": "Oui, nous avons eu un entretien il y a deux semaines. Elle semblait très compétente et sympathique.",
        "spanish": "Sí, tuvimos una entrevista hace dos semanas. Parecía muy competente y amable.",
        "italian": "Sì, abbiamo avuto un colloquio due settimane fa. Sembrava molto competente e simpatica.",
        "portuguese": "Sim, tivemos uma entrevista há duas semanas. Ela parecia muito competente e simpática.",
        "dutch": "Ja, we hadden twee weken geleden een gesprek. Ze leek erg competent en vriendelijk.",
        "polish": "Tak, mieliśmy rozmowę dwa tygodnie temu. Wydawała się bardzo kompetentna i miła.",
        "ukrainian": "Так, у нас була розмова два тижні тому. Вона здалася дуже компетентною і приємною.",
        "russian": "Да, у нас было собеседование две недели назад. Она казалась очень компетентной и дружелюбной.",
        "swedish": "Ja, vi hade en intervju för två veckor sedan. Hon verkade väldigt kompetent och trevlig.",
        "norwegian": "Ja, vi hadde et intervju for to uker siden. Hun virket veldig kompetent og hyggelig.",
        "danish": "Ja, vi havde et interview for to uger siden. Hun virkede meget kompetent og venlig.",
        "finnish": "Kyllä, meillä oli haastattelu kaksi viikkoa sitten. Hän vaikutti todella pätevältä ja ystävälliseltä.",
        "greek": "Ναι, είχαμε συνέντευξη πριν από δύο εβδομάδες. Φαινόταν πολύ ικανή και φιλική.",
        "brazilian_portuguese": "Sim, tivemos uma entrevista há duas semanas. Ela parecia muito competente e simpática.",
        "mandarin": "是的，两周前我们进行了面试。她看起来非常能干且友善。",
        "japanese": "はい、2週間前に面接がありました。彼女はとても有能で親切そうでした。",
        "korean": "네, 2주 전에 면접이 있었어요. 그분은 매우 유능하고 친절해 보였어요.",
        "hindi": "हाँ, दो हफ्ते पहले हमारा इंटरव्यू हुआ था। वह बहुत सक्षम और मिलनसार लगीं।",
        "vietnamese": "Có, chúng tôi đã có buổi phỏng vấn hai tuần trước. Cô ấy có vẻ rất có năng lực và thân thiện.",
        "arabic": "نعم، أجرينا مقابلة قبل أسبوعين. بدت مختصة جداً وودودة.",
    },
    {
        "line_number": 11,
        "speaker_name": "Alex",
        "lithuanian": "Tai labai svarbu turėti gerą santykį su viršininku. Ar žinai, koks bus tavo darbo grafikas?",
        "latvian": "Tas ir ļoti svarīgi, ka ir labas attiecības ar priekšnieku. Vai tu zini, kāds būs tavs darba grafiks?",
        "estonian": "On väga oluline, et sul oleks hea suhe ülemusega. Kas tead, milline on sinu töögraafik?",
        "english": "It is very important to have a good relationship with your boss. Do you know what your work schedule will be?",
        "german": "Es ist sehr wichtig, eine gute Beziehung zum Chef zu haben. Weißt du, wie dein Arbeitsplan aussehen wird?",
        "french": "Il est très important d'avoir une bonne relation avec son patron. Tu sais quel sera ton emploi du temps?",
        "spanish": "Es muy importante tener una buena relación con tu jefe. ¿Sabes cuál será tu horario de trabajo?",
        "italian": "È molto importante avere un buon rapporto con il proprio capo. Sai qual sarà il tuo orario di lavoro?",
        "portuguese": "É muito importante ter uma boa relação com o chefe. Sabes qual será o teu horário de trabalho?",
        "dutch": "Het is heel belangrijk om een goede relatie met je baas te hebben. Weet je wat je werkrooster zal zijn?",
        "polish": "Bardzo ważne jest utrzymanie dobrej relacji z szefem. Czy wiesz, jaki będzie twój harmonogram pracy?",
        "ukrainian": "Дуже важливо мати гарні стосунки з начальником. Ти знаєш, який буде твій робочий графік?",
        "russian": "Очень важно иметь хорошие отношения с начальником. Ты знаешь, каким будет твой рабочий график?",
        "swedish": "Det är mycket viktigt att ha ett bra förhållande med sin chef. Vet du hur ditt arbetsschema kommer att se ut?",
        "norwegian": "Det er veldig viktig å ha et godt forhold til sjefen. Vet du hva arbeidsplanen din vil være?",
        "danish": "Det er meget vigtigt at have et godt forhold til sin chef. Ved du, hvad din arbejdsplan vil være?",
        "finnish": "On erittäin tärkeää, että sinulla on hyvä suhde esimieheesi. Tiedätkö millainen työaikataulusi tulee olemaan?",
        "greek": "Είναι πολύ σημαντικό να έχεις καλή σχέση με τον προϊστάμενό σου. Ξέρεις ποιο θα είναι το πρόγραμμα εργασίας σου;",
        "brazilian_portuguese": "É muito importante ter uma boa relação com o chefe. Você sabe qual será seu horário de trabalho?",
        "mandarin": "与老板保持良好关系非常重要。你知道你的工作时间表是什么吗？",
        "japanese": "上司と良い関係を持つことはとても重要です。勤務スケジュールはどのようになるか知っていますか？",
        "korean": "상사와 좋은 관계를 유지하는 것이 매우 중요해요. 근무 일정이 어떻게 될지 알고 있나요?",
        "hindi": "बॉस के साथ अच्छे संबंध रखना बहुत जरूरी है। क्या आप जानती हैं कि आपका काम का शेड्यूल क्या होगा?",
        "vietnamese": "Việc có mối quan hệ tốt với sếp rất quan trọng. Bạn có biết lịch làm việc của bạn sẽ như thế nào không?",
        "arabic": "من المهم جداً أن تكوني على علاقة جيدة مع رئيسك. هل تعرفين ما سيكون جدول عملك؟",
    },
    {
        "line_number": 12,
        "speaker_name": "Mia",
        "lithuanian": "Darbo laikas nuo devynių iki šešių, bet galiu dirbti iš namų du kartus per savaitę.",
        "latvian": "Darba laiks no deviņiem līdz sešiem, bet es varu strādāt no mājām divas reizes nedēļā.",
        "estonian": "Tööaeg on üheksast kuueni, aga saan kaks korda nädalas kodust töötada.",
        "english": "Working hours are from nine to six, but I can work from home twice a week.",
        "german": "Die Arbeitszeiten sind von neun bis sechs, aber ich kann zweimal pro Woche von zu Hause arbeiten.",
        "french": "Les heures de travail sont de neuf heures à dix-huit heures, mais je peux travailler à domicile deux fois par semaine.",
        "spanish": "El horario de trabajo es de nueve a seis, pero puedo trabajar desde casa dos veces a la semana.",
        "italian": "L'orario di lavoro è dalle nove alle sei, ma posso lavorare da casa due volte a settimana.",
        "portuguese": "O horário de trabalho é das nove às seis, mas posso trabalhar em casa duas vezes por semana.",
        "dutch": "De werktijden zijn van negen tot zes, maar ik kan twee keer per week vanuit huis werken.",
        "polish": "Godziny pracy są od dziewiątej do szóstej, ale mogę pracować z domu dwa razy w tygodniu.",
        "ukrainian": "Робочий час з дев'ятої до шостої, але я можу працювати вдома двічі на тиждень.",
        "russian": "Рабочие часы с девяти до шести, но я могу работать из дома дважды в неделю.",
        "swedish": "Arbetstiderna är från nio till sex, men jag kan jobba hemifrån två gånger i veckan.",
        "norwegian": "Arbeidstiden er fra ni til seks, men jeg kan jobbe hjemmefra to ganger i uken.",
        "danish": "Arbejdstiderne er fra ni til seks, men jeg kan arbejde hjemmefra to gange om ugen.",
        "finnish": "Työajat ovat yhdeksästä kuuteen, mutta voin tehdä etätöitä kahdesti viikossa.",
        "greek": "Οι ώρες εργασίας είναι από εννέα μέχρι έξι, αλλά μπορώ να δουλεύω από το σπίτι δύο φορές την εβδομάδα.",
        "brazilian_portuguese": "O horário de trabalho é das nove às seis, mas posso trabalhar de casa duas vezes por semana.",
        "mandarin": "工作时间从九点到六点，但我每周可以在家工作两次。",
        "japanese": "勤務時間は9時から6時ですが、週2回在宅勤務できます。",
        "korean": "근무 시간은 9시부터 6시까지인데, 주 2회 재택근무가 가능해요.",
        "hindi": "काम का समय नौ से छह बजे तक है, लेकिन मैं हफ्ते में दो बार घर से काम कर सकती हूँ।",
        "vietnamese": "Giờ làm việc là từ chín đến sáu giờ, nhưng tôi có thể làm việc từ nhà hai lần mỗi tuần.",
        "arabic": "ساعات العمل من التاسعة حتى السادسة، لكن يمكنني العمل من المنزل مرتين في الأسبوع.",
    },
    {
        "line_number": 13,
        "speaker_name": "Alex",
        "lithuanian": "Tai puiku! Lankstus darbo grafikas tikrai padeda išlaikyti gerą darbo ir gyvenimo balansą.",
        "latvian": "Tas ir lieliski! Elastīgs darba grafiks tiešām palīdz uzturēt labu darba un dzīves balansu.",
        "estonian": "See on suurepärane! Paindlik tööaeg aitab tõesti säilitada head töö ja elu tasakaalu.",
        "english": "That is great! A flexible schedule really helps to maintain a good work-life balance.",
        "german": "Das ist toll! Ein flexibler Zeitplan hilft wirklich, eine gute Work-Life-Balance zu halten.",
        "french": "C'est super! Un horaire flexible aide vraiment à maintenir un bon équilibre travail-vie personnelle.",
        "spanish": "¡Eso es genial! Un horario flexible realmente ayuda a mantener un buen equilibrio entre trabajo y vida personal.",
        "italian": "È fantastico! Un orario flessibile aiuta davvero a mantenere un buon equilibrio tra lavoro e vita privata.",
        "portuguese": "Isso é ótimo! Um horário flexível ajuda mesmo a manter um bom equilíbrio entre trabalho e vida pessoal.",
        "dutch": "Dat is geweldig! Een flexibel schema helpt echt om een goede werk-privébalans te bewaren.",
        "polish": "To świetne! Elastyczny harmonogram naprawdę pomaga utrzymać dobry balans między pracą a życiem prywatnym.",
        "ukrainian": "Це чудово! Гнучкий графік справді допомагає підтримувати хороший баланс між роботою та особистим життям.",
        "russian": "Это замечательно! Гибкий график действительно помогает поддерживать хороший баланс между работой и личной жизнью.",
        "swedish": "Det är bra! Ett flexibelt schema hjälper verkligen att upprätthålla en bra balans mellan arbete och privatliv.",
        "norwegian": "Det er flott! En fleksibel timeplan hjelper virkelig med å opprettholde en god balanse mellom jobb og privatliv.",
        "danish": "Det er fantastisk! En fleksibel tidsplan hjælper virkelig med at opretholde en god balance mellem arbejde og privatliv.",
        "finnish": "Se on hienoa! Joustava aikataulu auttaa todella ylläpitämään hyvää työ- ja yksityiselämän tasapainoa.",
        "greek": "Αυτό είναι υπέροχο! Ένα ευέλικτο πρόγραμμα βοηθάει πραγματικά στη διατήρηση καλής ισορροπίας μεταξύ εργασίας και προσωπικής ζωής.",
        "brazilian_portuguese": "Isso é ótimo! Um horário flexível realmente ajuda a manter um bom equilíbrio entre trabalho e vida pessoal.",
        "mandarin": "太好了！灵活的时间表确实有助于保持良好的工作与生活平衡。",
        "japanese": "それは素晴らしいですね！柔軟なスケジュールはワークライフバランスを保つのに本当に役立ちます。",
        "korean": "정말 좋네요! 유연한 스케줄은 일과 생활의 균형을 유지하는 데 정말 도움이 돼요.",
        "hindi": "यह बढ़िया है! लचीला शेड्यूल वाकई काम और जीवन के बीच अच्छा संतुलन बनाए रखने में मदद करता है।",
        "vietnamese": "Thật tuyệt! Lịch làm việc linh hoạt thực sự giúp duy trì sự cân bằng tốt giữa công việc và cuộc sống.",
        "arabic": "هذا رائع! يساعد الجدول المرن حقاً في الحفاظ على توازن جيد بين العمل والحياة.",
    },
    {
        "line_number": 14,
        "speaker_name": "Mia",
        "lithuanian": "Visiškai sutinku. Buvusiame darbe dirbau per daug viršvalandžių ir tai buvo labai sunku.",
        "latvian": "Es pilnīgi piekrītu. Iepriekšējā darbā es strādāju pārāk daudz virsstundas un tas bija ļoti grūti.",
        "estonian": "Nõustun täiesti. Eelmises töökohas tegin liiga palju ületunde ja see oli väga raske.",
        "english": "I completely agree. In my previous job I worked too many overtime hours and it was very difficult.",
        "german": "Ich stimme vollkommen zu. In meinem vorherigen Job habe ich zu viele Überstunden gemacht und das war sehr schwierig.",
        "french": "Je suis tout à fait d'accord. Dans mon précédent travail, je faisais trop d'heures supplémentaires et c'était très difficile.",
        "spanish": "Estoy completamente de acuerdo. En mi trabajo anterior hacía demasiadas horas extra y era muy difícil.",
        "italian": "Sono completamente d'accordo. Nel mio lavoro precedente facevo troppe ore di straordinario ed era molto difficile.",
        "portuguese": "Concordo completamente. No meu emprego anterior fazia demasiadas horas extra e era muito difícil.",
        "dutch": "Ik ben het er helemaal mee eens. Bij mijn vorige baan maakte ik te veel overuren en dat was erg moeilijk.",
        "polish": "Całkowicie się zgadzam. W poprzedniej pracy robiłam zbyt dużo nadgodzin i to było bardzo trudne.",
        "ukrainian": "Повністю згодна. На попередній роботі я працювала занадто багато понаднормово, і це було дуже важко.",
        "russian": "Полностью согласна. На предыдущей работе я работала слишком много сверхурочно, и это было очень тяжело.",
        "swedish": "Jag håller med helt. På mitt tidigare jobb jobbade jag för mycket övertid och det var väldigt svårt.",
        "norwegian": "Jeg er helt enig. I min forrige jobb jobbet jeg for mye overtid og det var veldig vanskelig.",
        "danish": "Jeg er fuldstændig enig. I mit tidligere job arbejdede jeg for mange overarbejdstimer, og det var meget svært.",
        "finnish": "Olen täysin samaa mieltä. Edellisessä työssäni tein liikaa ylitöitä ja se oli todella vaikeaa.",
        "greek": "Συμφωνώ απόλυτα. Στην προηγούμενη δουλειά μου έκανα πάρα πολλές υπερωρίες και ήταν πολύ δύσκολο.",
        "brazilian_portuguese": "Concordo completamente. No meu trabalho anterior eu fazia horas extras demais e era muito difícil.",
        "mandarin": "我完全同意。在我之前的工作中，我加班太多了，非常辛苦。",
        "japanese": "完全に同意します。前の仕事では残業が多すぎてとても大変でした。",
        "korean": "완전히 동의해요. 이전 직장에서 너무 많은 초과 근무를 했고 정말 힘들었어요.",
        "hindi": "मैं पूरी तरह सहमत हूँ। पिछली नौकरी में मैंने बहुत ज्यादा ओवरटाइम किया और यह बहुत कठिन था।",
        "vietnamese": "Tôi hoàn toàn đồng ý. Ở công việc trước tôi làm thêm giờ quá nhiều và điều đó rất khó khăn.",
        "arabic": "أوافق تماماً. في عملي السابق كنت أعمل ساعات إضافية كثيرة جداً وكان ذلك صعباً جداً.",
    },
    {
        "line_number": 15,
        "speaker_name": "Alex",
        "lithuanian": "Ar žinai, kokia bus tavo alga naujame darbe?",
        "latvian": "Vai tu zini, kāda būs tava alga jaunajā darbā?",
        "estonian": "Kas tead, milline on sinu palk uues töökohas?",
        "english": "Do you know what your salary will be in the new job?",
        "german": "Weißt du, wie hoch dein Gehalt in der neuen Stelle sein wird?",
        "french": "Tu sais quel sera ton salaire dans le nouveau travail?",
        "spanish": "¿Sabes cuál será tu salario en el nuevo trabajo?",
        "italian": "Sai quale sarà il tuo stipendio nel nuovo lavoro?",
        "portuguese": "Sabes qual será o teu salário no novo emprego?",
        "dutch": "Weet jij wat je salaris in de nieuwe baan zal zijn?",
        "polish": "Czy wiesz, jakie będzie twoje wynagrodzenie w nowej pracy?",
        "ukrainian": "Ти знаєш, яка буде твоя зарплата на новій роботі?",
        "russian": "Ты знаешь, какая будет твоя зарплата на новой работе?",
        "swedish": "Vet du vad din lön kommer att vara i det nya jobbet?",
        "norwegian": "Vet du hva lønnen din vil være i den nye jobben?",
        "danish": "Ved du, hvad din løn vil være i det nye job?",
        "finnish": "Tiedätkö mikä palkkasi tulee olemaan uudessa työssä?",
        "greek": "Ξέρεις ποιος θα είναι ο μισθός σου στη νέα δουλειά;",
        "brazilian_portuguese": "Você sabe qual será seu salário no novo emprego?",
        "mandarin": "你知道你在新工作中的薪水会是多少吗？",
        "japanese": "新しい仕事での給料はいくらになるか知っていますか？",
        "korean": "새 직장에서 급여가 얼마인지 알고 있나요?",
        "hindi": "क्या आप जानती हैं कि नई नौकरी में आपकी सैलरी क्या होगी?",
        "vietnamese": "Bạn có biết mức lương của bạn sẽ là bao nhiêu ở công việc mới không?",
        "arabic": "هل تعرفين ما سيكون راتبك في الوظيفة الجديدة؟",
    },
    {
        "line_number": 16,
        "speaker_name": "Mia",
        "lithuanian": "Taip, gaunu trisdešimt procentų daugiau nei ankstesniame darbe. Esu labai patenkinta.",
        "latvian": "Jā, es saņemšu trīsdesmit procentus vairāk nekā iepriekšējā darbā. Esmu ļoti apmierināta.",
        "estonian": "Jah, saan kolmkümmend protsenti rohkem kui eelmises töökohas. Olen väga rahul.",
        "english": "Yes, I will be earning thirty percent more than in my previous job. I am very pleased.",
        "german": "Ja, ich werde dreißig Prozent mehr als in meinem vorherigen Job verdienen. Ich bin sehr zufrieden.",
        "french": "Oui, je vais gagner trente pour cent de plus que dans mon précédent emploi. Je suis très satisfaite.",
        "spanish": "Sí, ganaré un treinta por ciento más que en mi trabajo anterior. Estoy muy contenta.",
        "italian": "Sì, guadagnerò il trenta percento in più rispetto al mio lavoro precedente. Sono molto contenta.",
        "portuguese": "Sim, vou ganhar trinta por cento mais do que no meu trabalho anterior. Estou muito satisfeita.",
        "dutch": "Ja, ik ga dertig procent meer verdienen dan in mijn vorige baan. Ik ben erg blij.",
        "polish": "Tak, będę zarabiać trzydzieści procent więcej niż w poprzedniej pracy. Jestem bardzo zadowolona.",
        "ukrainian": "Так, я буду заробляти на тридцять відсотків більше, ніж на попередній роботі. Я дуже задоволена.",
        "russian": "Да, я буду зарабатывать на тридцать процентов больше, чем на предыдущей работе. Я очень довольна.",
        "swedish": "Ja, jag kommer att tjäna trettio procent mer än i mitt tidigare jobb. Jag är mycket nöjd.",
        "norwegian": "Ja, jeg vil tjene tretti prosent mer enn i forrige jobb. Jeg er veldig fornøyd.",
        "danish": "Ja, jeg vil tjene tredive procent mere end i mit tidligere job. Jeg er meget tilfreds.",
        "finnish": "Kyllä, tulen ansaitsemaan kolmekymmentä prosenttia enemmän kuin edellisessä työssä. Olen erittäin tyytyväinen.",
        "greek": "Ναι, θα κερδίζω τριάντα τοις εκατό περισσότερο από ό,τι στην προηγούμενη δουλειά μου. Είμαι πολύ ευχαριστημένη.",
        "brazilian_portuguese": "Sim, vou ganhar trinta por cento a mais do que no emprego anterior. Estou muito satisfeita.",
        "mandarin": "是的，我将比以前的工作多赚百分之三十。我非常满意。",
        "japanese": "はい、前の仕事より30%多く稼ぐことになります。とても嬉しいです。",
        "korean": "네, 이전 직장보다 30% 더 많이 받게 돼요. 매우 만족스러워요.",
        "hindi": "हाँ, मैं अपनी पिछली नौकरी से तीस प्रतिशत ज्यादा कमाऊँगी। मैं बहुत खुश हूँ।",
        "vietnamese": "Có, tôi sẽ kiếm được nhiều hơn ba mươi phần trăm so với công việc trước. Tôi rất hài lòng.",
        "arabic": "نعم، سأكسب ثلاثين بالمئة أكثر مما كنت أكسبه في عملي السابق. أنا سعيدة جداً.",
    },
    {
        "line_number": 17,
        "speaker_name": "Alex",
        "lithuanian": "Tai nuostabu! Ar kompanija siūlo kokių nors papildomų išmokų?",
        "latvian": "Tas ir brīnišķīgi! Vai uzņēmums piedāvā kādus papildu labumus?",
        "estonian": "See on imeline! Kas ettevõte pakub mingeid lisahüvesid?",
        "english": "That is wonderful! Does the company offer any additional benefits?",
        "german": "Das ist wunderbar! Bietet das Unternehmen zusätzliche Leistungen an?",
        "french": "C'est merveilleux! L'entreprise offre-t-elle des avantages supplémentaires?",
        "spanish": "¡Eso es maravilloso! ¿La empresa ofrece algún beneficio adicional?",
        "italian": "È meraviglioso! L'azienda offre qualche beneficio aggiuntivo?",
        "portuguese": "Isso é maravilhoso! A empresa oferece algum benefício adicional?",
        "dutch": "Dat is geweldig! Biedt het bedrijf extra voordelen aan?",
        "polish": "To wspaniałe! Czy firma oferuje jakieś dodatkowe benefity?",
        "ukrainian": "Це чудово! Чи пропонує компанія якісь додаткові пільги?",
        "russian": "Это замечательно! Предлагает ли компания какие-либо дополнительные льготы?",
        "swedish": "Det är underbart! Erbjuder företaget några ytterligare förmåner?",
        "norwegian": "Det er vidunderlig! Tilbyr selskapet noen ekstra fordeler?",
        "danish": "Det er vidunderligt! Tilbyder virksomheden yderligere fordele?",
        "finnish": "Se on ihanaa! Tarjoaako yritys lisäetuja?",
        "greek": "Είναι υπέροχο! Προσφέρει η εταιρεία επιπλέον παροχές;",
        "brazilian_portuguese": "Isso é maravilhoso! A empresa oferece algum benefício adicional?",
        "mandarin": "太好了！公司是否提供额外福利？",
        "japanese": "それは素晴らしい！会社は追加の福利厚生を提供していますか？",
        "korean": "정말 훌륭해요! 회사에서 추가 복리후생을 제공하나요?",
        "hindi": "यह अद्भुत है! क्या कंपनी कोई अतिरिक्त लाभ प्रदान करती है?",
        "vietnamese": "Thật tuyệt vời! Công ty có cung cấp thêm phúc lợi nào không?",
        "arabic": "هذا رائع! هل تقدم الشركة أي مزايا إضافية؟",
    },
    {
        "line_number": 18,
        "speaker_name": "Mia",
        "lithuanian": "Taip! Jie apmoka sveikatos draudimą, duoda dvidešimt penkias atostogų dienas ir siūlo mokymo programas.",
        "latvian": "Jā! Viņi apmaksā veselības apdrošināšanu, dod divdesmit piecas atvaļinājuma dienas un piedāvā mācību programmas.",
        "estonian": "Jah! Nad katavad tervisekindlustuse, annavad kakskümmend viis puhkusepäeva ja pakuvad koolitusprogramme.",
        "english": "Yes! They cover health insurance, give twenty-five days of holiday and offer training programmes.",
        "german": "Ja! Sie übernehmen die Krankenversicherung, geben fünfundzwanzig Urlaubstage und bieten Schulungsprogramme an.",
        "french": "Oui! Ils couvrent l'assurance maladie, donnent vingt-cinq jours de congés et proposent des programmes de formation.",
        "spanish": "¡Sí! Cubren el seguro médico, dan veinticinco días de vacaciones y ofrecen programas de formación.",
        "italian": "Sì! Coprono l'assicurazione sanitaria, danno venticinque giorni di ferie e offrono programmi di formazione.",
        "portuguese": "Sim! Cobrem o seguro de saúde, dão vinte e cinco dias de férias e oferecem programas de formação.",
        "dutch": "Ja! Ze dekken de ziektekostenverzekering, geven vijfentwintig vakantiedagen en bieden opleidingsprogramma's aan.",
        "polish": "Tak! Pokrywają ubezpieczenie zdrowotne, dają dwadzieścia pięć dni urlopu i oferują programy szkoleniowe.",
        "ukrainian": "Так! Вони покривають медичну страховку, дають двадцять п'ять днів відпустки та пропонують навчальні програми.",
        "russian": "Да! Они покрывают медицинскую страховку, дают двадцать пять дней отпуска и предлагают обучающие программы.",
        "swedish": "Ja! De täcker sjukförsäkringen, ger tjugofem semesterdagar och erbjuder utbildningsprogram.",
        "norwegian": "Ja! De dekker helseforsikring, gir tjuefem feriedager og tilbyr opplæringsprogrammer.",
        "danish": "Ja! De dækker sygeforsikring, giver femogtyve feriedage og tilbyder uddannelsesprogrammer.",
        "finnish": "Kyllä! He kattavat sairausvakuutuksen, antavat kaksikymmentäviisi lomapäivää ja tarjoavat koulutusohjelmia.",
        "greek": "Ναι! Καλύπτουν ασφάλεια υγείας, δίνουν εικοσιπέντε μέρες διακοπών και προσφέρουν εκπαιδευτικά προγράμματα.",
        "brazilian_portuguese": "Sim! Eles cobrem plano de saúde, dão vinte e cinco dias de férias e oferecem programas de treinamento.",
        "mandarin": "是的！他们提供健康保险，给二十五天假期，还提供培训项目。",
        "japanese": "はい！健康保険をカバーし、25日間の休暇を与え、研修プログラムを提供しています。",
        "korean": "네! 건강 보험을 지원하고, 25일의 휴가를 주고, 교육 프로그램도 제공해요.",
        "hindi": "हाँ! वे स्वास्थ्य बीमा कवर करते हैं, पच्चीस दिन की छुट्टियाँ देते हैं और प्रशिक्षण कार्यक्रम प्रदान करते हैं।",
        "vietnamese": "Có! Họ bao gồm bảo hiểm y tế, cho hai mươi lăm ngày nghỉ phép và cung cấp các chương trình đào tạo.",
        "arabic": "نعم! يغطون التأمين الصحي، ويعطون خمسة وعشرين يوم إجازة، ويقدمون برامج تدريبية.",
    },
    {
        "line_number": 19,
        "speaker_name": "Alex",
        "lithuanian": "Tai labai gerai! Mokymo programos ypač svarbios, nes padeda profesiškai augti.",
        "latvian": "Tas ir ļoti labi! Mācību programmas ir īpaši svarīgas, jo tās palīdz profesionāli augt.",
        "estonian": "See on väga hea! Koolitusprogrammid on eriti olulised, kuna need aitavad professionaalselt kasvada.",
        "english": "That is very good! Training programmes are especially important because they help you grow professionally.",
        "german": "Das ist sehr gut! Schulungsprogramme sind besonders wichtig, weil sie einem helfen, beruflich zu wachsen.",
        "french": "C'est très bien! Les programmes de formation sont particulièrement importants car ils aident à grandir professionnellement.",
        "spanish": "¡Eso es muy bueno! Los programas de formación son especialmente importantes porque ayudan a crecer profesionalmente.",
        "italian": "È molto bello! I programmi di formazione sono particolarmente importanti perché aiutano a crescere professionalmente.",
        "portuguese": "Isso é muito bom! Os programas de formação são especialmente importantes porque ajudam a crescer profissionalmente.",
        "dutch": "Dat is heel goed! Opleidingsprogramma's zijn bijzonder belangrijk omdat ze helpen professioneel te groeien.",
        "polish": "To bardzo dobrze! Programy szkoleniowe są szczególnie ważne, ponieważ pomagają w profesjonalnym rozwoju.",
        "ukrainian": "Це дуже добре! Навчальні програми особливо важливі, тому що вони допомагають рости професійно.",
        "russian": "Это очень хорошо! Обучающие программы особенно важны, потому что они помогают расти профессионально.",
        "swedish": "Det är mycket bra! Utbildningsprogram är särskilt viktiga eftersom de hjälper dig att växa professionellt.",
        "norwegian": "Det er veldig bra! Opplæringsprogrammer er spesielt viktige fordi de hjelper deg å vokse profesjonelt.",
        "danish": "Det er meget godt! Uddannelsesprogrammer er særligt vigtige, fordi de hjælper dig med at vokse professionelt.",
        "finnish": "Se on erittäin hyvää! Koulutusohjelmat ovat erityisen tärkeitä, koska ne auttavat kasvamaan ammatillisesti.",
        "greek": "Αυτό είναι πολύ καλό! Τα εκπαιδευτικά προγράμματα είναι ιδιαίτερα σημαντικά γιατί βοηθούν στην επαγγελματική ανάπτυξη.",
        "brazilian_portuguese": "Isso é muito bom! Os programas de treinamento são especialmente importantes porque ajudam a crescer profissionalmente.",
        "mandarin": "太好了！培训项目特别重要，因为它们帮助你专业成长。",
        "japanese": "それは非常に良いですね！研修プログラムは特に重要です。なぜなら専門的に成長するのに役立つからです。",
        "korean": "정말 좋네요! 교육 프로그램은 특히 중요해요. 전문적으로 성장하는 데 도움이 되니까요.",
        "hindi": "यह बहुत अच्छा है! प्रशिक्षण कार्यक्रम विशेष रूप से महत्वपूर्ण हैं क्योंकि वे पेशेवर विकास में मदद करते हैं।",
        "vietnamese": "Điều đó rất tốt! Các chương trình đào tạo đặc biệt quan trọng vì chúng giúp bạn phát triển chuyên nghiệp.",
        "arabic": "هذا جيد جداً! برامج التدريب مهمة بشكل خاص لأنها تساعدك على النمو المهني.",
    },
    {
        "line_number": 20,
        "speaker_name": "Mia",
        "lithuanian": "Sutinku. Planuoju mokytis ir tobulinti savo įgūdžius, kiek tik galima.",
        "latvian": "Piekrītu. Es plānoju mācīties un uzlabot savas prasmes, cik vien iespējams.",
        "estonian": "Nõustun. Planen õppida ja oma oskusi nii palju kui võimalik täiustada.",
        "english": "I agree. I plan to learn and improve my skills as much as possible.",
        "german": "Ich stimme zu. Ich plane, so viel wie möglich zu lernen und meine Fähigkeiten zu verbessern.",
        "french": "Je suis d'accord. Je prévois d'apprendre et d'améliorer mes compétences autant que possible.",
        "spanish": "Estoy de acuerdo. Planeo aprender y mejorar mis habilidades tanto como sea posible.",
        "italian": "Sono d'accordo. Ho intenzione di imparare e migliorare le mie competenze il più possibile.",
        "portuguese": "Concordo. Planeio aprender e melhorar as minhas competências o máximo possível.",
        "dutch": "Ik ben het ermee eens. Ik ben van plan zo veel mogelijk te leren en mijn vaardigheden te verbeteren.",
        "polish": "Zgadzam się. Planuję uczyć się i doskonalić swoje umiejętności tak bardzo, jak to możliwe.",
        "ukrainian": "Погоджуюся. Я планую вчитися та вдосконалювати свої навички якомога більше.",
        "russian": "Согласна. Я планирую учиться и улучшать свои навыки настолько, насколько возможно.",
        "swedish": "Jag håller med. Jag planerar att lära mig och förbättra mina färdigheter så mycket som möjligt.",
        "norwegian": "Jeg er enig. Jeg planlegger å lære og forbedre ferdighetene mine så mye som mulig.",
        "danish": "Jeg er enig. Jeg planlægger at lære og forbedre mine færdigheder så meget som muligt.",
        "finnish": "Olen samaa mieltä. Aion oppia ja parantaa taitojani niin paljon kuin mahdollista.",
        "greek": "Συμφωνώ. Σχεδιάζω να μάθω και να βελτιώσω τις δεξιότητές μου όσο το δυνατόν περισσότερο.",
        "brazilian_portuguese": "Concordo. Planejo aprender e melhorar minhas habilidades ao máximo.",
        "mandarin": "我同意。我计划尽可能多地学习和提高我的技能。",
        "japanese": "同意します。できる限りスキルを学び向上させる予定です。",
        "korean": "동의해요. 최대한 많이 배우고 실력을 향상시킬 계획이에요.",
        "hindi": "मैं सहमत हूँ। मैं जितना हो सके उतना सीखने और अपने कौशल को बेहतर बनाने की योजना बना रही हूँ।",
        "vietnamese": "Tôi đồng ý. Tôi có kế hoạch học hỏi và cải thiện kỹ năng của mình càng nhiều càng tốt.",
        "arabic": "أوافق. أخطط للتعلم وتحسين مهاراتي قدر الإمكان.",
    },
    {
        "line_number": 21,
        "speaker_name": "Alex",
        "lithuanian": "Ar tau reikia dėvėti tam tikrą aprangą darbe?",
        "latvian": "Vai tev darbā ir jāvalkā noteikts apģērbs?",
        "estonian": "Kas pead tööl teatud riideid kandma?",
        "english": "Do you need to wear a certain dress code at work?",
        "german": "Musst du bei der Arbeit eine bestimmte Kleiderordnung einhalten?",
        "french": "Tu dois respecter un code vestimentaire au travail?",
        "spanish": "¿Necesitas seguir un código de vestimenta en el trabajo?",
        "italian": "Devi seguire un codice di abbigliamento al lavoro?",
        "portuguese": "Precisas de seguir um código de vestuário no trabalho?",
        "dutch": "Moet jij je op het werk aan een kledingvoorschrift houden?",
        "polish": "Czy musisz przestrzegać określonego dress code'u w pracy?",
        "ukrainian": "Чи потрібно тобі дотримуватись певного дрес-коду на роботі?",
        "russian": "Нужно ли тебе соблюдать дресс-код на работе?",
        "swedish": "Behöver du ha en viss klädkod på jobbet?",
        "norwegian": "Må du følge en bestemt kleskode på jobb?",
        "danish": "Skal du overholde en bestemt dresscode på arbejdet?",
        "finnish": "Pitääkö sinun noudattaa tiettyä pukukoodia töissä?",
        "greek": "Χρειάζεται να ακολουθείς έναν συγκεκριμένο κώδικα ένδυσης στη δουλειά;",
        "brazilian_portuguese": "Você precisa seguir um código de vestimenta no trabalho?",
        "mandarin": "你在工作中需要穿特定的服装吗？",
        "japanese": "仕事でドレスコードはありますか？",
        "korean": "직장에서 특별한 복장 규정이 있나요?",
        "hindi": "क्या आपको काम पर एक निश्चित ड्रेस कोड पहनना होगा?",
        "vietnamese": "Bạn có cần tuân thủ quy định trang phục tại nơi làm việc không?",
        "arabic": "هل تحتاجين إلى اتباع قواعد لباس معينة في العمل؟",
    },
    {
        "line_number": 22,
        "speaker_name": "Mia",
        "lithuanian": "Aprangos kodas yra verslo atsitiktinis stilius. Tai man labiau patinka nei oficialus kostiumas.",
        "latvian": "Apģērba kods ir biznesa gadījuma stils. Tas man patīk labāk nekā formāls tērps.",
        "estonian": "Riietumisstiil on äriline casual. See meeldib mulle rohkem kui formaalne ülikond.",
        "english": "The dress code is business casual. I prefer that to a formal suit.",
        "german": "Der Dresscode ist Business Casual. Das bevorzuge ich gegenüber einem formellen Anzug.",
        "french": "Le code vestimentaire est business casual. Je préfère ça à un costume formel.",
        "spanish": "El código de vestimenta es business casual. Lo prefiero a un traje formal.",
        "italian": "Il codice di abbigliamento è business casual. Lo preferisco a un completo formale.",
        "portuguese": "O código de vestuário é business casual. Prefiro isso a um fato formal.",
        "dutch": "De kledingcode is business casual. Dat geef ik de voorkeur aan een formeel pak.",
        "polish": "Dress code to business casual. Wolę to od formalnego garnituru.",
        "ukrainian": "Дрес-код — бізнес-кежуал. Я це волію, ніж формальний костюм.",
        "russian": "Дресс-код — бизнес-кэжуал. Я предпочитаю это официальному костюму.",
        "swedish": "Klädkoden är business casual. Jag föredrar det framför en formell kostym.",
        "norwegian": "Kleskoden er business casual. Jeg foretrekker det fremfor en formell dress.",
        "danish": "Dresscoden er business casual. Det foretrækker jeg frem for et formelt jakkesæt.",
        "finnish": "Pukukoodi on business casual. Pidän siitä enemmän kuin virallisesta puvusta.",
        "greek": "Ο κώδικας ένδυσης είναι business casual. Το προτιμώ από επίσημο κοστούμι.",
        "brazilian_portuguese": "O código de vestimenta é business casual. Prefiro isso a um terno formal.",
        "mandarin": "着装规范是商务休闲风。我比正式西装更喜欢这个。",
        "japanese": "ドレスコードはビジネスカジュアルです。フォーマルスーツよりも好みです。",
        "korean": "복장 규정은 비즈니스 캐주얼이에요. 격식 있는 정장보다 더 좋아요.",
        "hindi": "ड्रेस कोड बिजनेस कैजुअल है। मैं इसे फॉर्मल सूट से ज्यादा पसंद करती हूँ।",
        "vietnamese": "Quy định trang phục là business casual. Tôi thích điều đó hơn là bộ vest trang trọng.",
        "arabic": "قواعد اللباس هي الأناقة غير الرسمية للأعمال. أفضل ذلك على البدلة الرسمية.",
    },
    {
        "line_number": 23,
        "speaker_name": "Alex",
        "lithuanian": "Sutinku! Ar žinai, kaip atrodyti ypač gerai pirmąją darbo dieną?",
        "latvian": "Piekrītu! Vai tu zini, kā izskatīties īpaši labi pirmajā darba dienā?",
        "estonian": "Nõustun! Kas tead, kuidas esimesel tööpäeval eriti hästi välja näha?",
        "english": "I agree! Do you know how to look particularly good on your first day?",
        "german": "Ich stimme zu! Weißt du, wie du an deinem ersten Tag besonders gut aussehen kannst?",
        "french": "Je suis d'accord! Tu sais comment être particulièrement bien habillée le premier jour?",
        "spanish": "¡De acuerdo! ¿Sabes cómo verte especialmente bien tu primer día?",
        "italian": "Sono d'accordo! Sai come apparire particolarmente bene il primo giorno?",
        "portuguese": "Concordo! Sabes como parecer especialmente bem no teu primeiro dia?",
        "dutch": "Eens! Weet jij hoe je er op je eerste dag bijzonder goed uit kunt zien?",
        "polish": "Zgadzam się! Czy wiesz, jak wyglądać szczególnie dobrze pierwszego dnia?",
        "ukrainian": "Погоджуюся! Ти знаєш, як виглядати особливо добре в перший день?",
        "russian": "Согласен! Ты знаешь, как выглядеть особенно хорошо в первый день?",
        "swedish": "Jag håller med! Vet du hur du kan se särskilt bra ut din första dag?",
        "norwegian": "Jeg er enig! Vet du hvordan du kan se spesielt bra ut på første dag?",
        "danish": "Enig! Ved du, hvordan du kan se særlig godt ud på din første dag?",
        "finnish": "Olen samaa mieltä! Tiedätkö miten näyttää erityisen hyvältä ensimmäisenä päivänä?",
        "greek": "Συμφωνώ! Ξέρεις πώς να φαίνεσαι ιδιαίτερα καλά την πρώτη μέρα;",
        "brazilian_portuguese": "Concordo! Você sabe como parecer especialmente bem no primeiro dia?",
        "mandarin": "我同意！你知道如何在第一天看起来特别好吗？",
        "japanese": "同意します！初日に特に良く見せる方法を知っていますか？",
        "korean": "동의해요! 첫날 특히 좋아 보이는 방법을 알고 있나요?",
        "hindi": "मैं सहमत हूँ! क्या आप जानती हैं कि पहले दिन खास तौर पर अच्छा दिखने का तरीका क्या है?",
        "vietnamese": "Tôi đồng ý! Bạn có biết cách trông đặc biệt tốt vào ngày đầu tiên không?",
        "arabic": "أوافق! هل تعرفين كيف تبدين رائعة بشكل خاص في يومك الأول؟",
    },
    {
        "line_number": 24,
        "speaker_name": "Mia",
        "lithuanian": "Manau, svarbiausia yra pasirinkti švarius, gerai tinkančius drabužius ir atrodyti profesionaliai, tačiau patogiai.",
        "latvian": "Es domāju, ka vissvarīgākais ir izvēlēties tīras, labi pieguļošas drēbes un izskatīties profesionāli, bet ērti.",
        "estonian": "Ma arvan, et kõige tähtsam on valida puhtad, hästi istuvad riided ja näha välja professionaalselt, kuid mugavalt.",
        "english": "I think the most important thing is to choose clean, well-fitting clothes and look professional but comfortable.",
        "german": "Ich denke, das Wichtigste ist, saubere, gut sitzende Kleidung zu wählen und professionell, aber bequem auszusehen.",
        "french": "Je pense que le plus important c'est de choisir des vêtements propres et bien coupés et d'avoir l'air professionnel mais à l'aise.",
        "spanish": "Creo que lo más importante es elegir ropa limpia y bien ajustada y parecer profesional pero cómoda.",
        "italian": "Penso che la cosa più importante sia scegliere abiti puliti e ben aderenti e sembrare professionale ma a proprio agio.",
        "portuguese": "Acho que o mais importante é escolher roupa limpa e bem ajustada e parecer profissional mas confortável.",
        "dutch": "Ik denk dat het belangrijkste is om schone, goed passende kleding te kiezen en er professioneel maar comfortabel uit te zien.",
        "polish": "Myślę, że najważniejsze jest wybranie czystych, dobrze dopasowanych ubrań i wyglądanie profesjonalnie, ale wygodnie.",
        "ukrainian": "Я думаю, що найважливіше — вибрати чистий, добре підібраний одяг і виглядати професійно, але комфортно.",
        "russian": "Думаю, самое важное — выбрать чистую, хорошо сидящую одежду и выглядеть профессионально, но комфортно.",
        "swedish": "Jag tror att det viktigaste är att välja rena, välpassade kläder och se professionell men bekväm ut.",
        "norwegian": "Jeg tror det viktigste er å velge rene, velpassende klær og se profesjonell men komfortabel ut.",
        "danish": "Jeg tror, det vigtigste er at vælge rene, velpassende tøj og se professionel men behagelig ud.",
        "finnish": "Luulen, että tärkeintä on valita puhtaat, hyvin istuvat vaatteet ja näyttää ammattimaiselta mutta mukavalta.",
        "greek": "Νομίζω ότι το πιο σημαντικό είναι να διαλέξεις καθαρά, καλά εφαρμοσμένα ρούχα και να φαίνεσαι επαγγελματίας αλλά άνετα.",
        "brazilian_portuguese": "Acho que o mais importante é escolher roupas limpas e bem ajustadas e parecer profissional mas confortável.",
        "mandarin": "我认为最重要的是选择干净、合身的衣服，看起来专业但舒适。",
        "japanese": "清潔でよく似合う服を選んで、プロフェッショナルだが快適に見えることが最も重要だと思います。",
        "korean": "깨끗하고 잘 맞는 옷을 선택하고 전문적이지만 편안하게 보이는 것이 가장 중요하다고 생각해요.",
        "hindi": "मुझे लगता है कि सबसे महत्वपूर्ण बात यह है कि साफ, अच्छी तरह से फिट होने वाले कपड़े चुनें और पेशेवर लेकिन आरामदायक दिखें।",
        "vietnamese": "Tôi nghĩ điều quan trọng nhất là chọn quần áo sạch sẽ, vừa vặn và trông chuyên nghiệp nhưng thoải mái.",
        "arabic": "أعتقد أن الأهم هو اختيار ملابس نظيفة ومناسبة والظهور بمظهر مهني لكن مريح.",
    },
    {
        "line_number": 25,
        "speaker_name": "Alex",
        "lithuanian": "Taip, pirmas įspūdis labai svarbus. Ar planuoji susipažinti su kolegomis pirmą dieną?",
        "latvian": "Jā, pirmais iespaids ir ļoti svarīgs. Vai tu plāno iepazīties ar kolēģiem pirmajā dienā?",
        "estonian": "Jah, esmamulje on väga oluline. Kas plaanid esimesel päeval kolleegidega tutvuda?",
        "english": "Yes, the first impression is very important. Do you plan to introduce yourself to your colleagues on the first day?",
        "german": "Ja, der erste Eindruck ist sehr wichtig. Planst du, dich am ersten Tag deinen Kollegen vorzustellen?",
        "french": "Oui, la première impression est très importante. Tu prévois de te présenter à tes collègues le premier jour?",
        "spanish": "Sí, la primera impresión es muy importante. ¿Planeas presentarte a tus colegas el primer día?",
        "italian": "Sì, la prima impressione è molto importante. Hai intenzione di presentarti ai tuoi colleghi il primo giorno?",
        "portuguese": "Sim, a primeira impressão é muito importante. Planeias apresentar-te aos teus colegas no primeiro dia?",
        "dutch": "Ja, de eerste indruk is heel belangrijk. Plan jij om je op de eerste dag voor te stellen aan je collega's?",
        "polish": "Tak, pierwsze wrażenie jest bardzo ważne. Czy planujesz przedstawić się współpracownikom pierwszego dnia?",
        "ukrainian": "Так, перше враження дуже важливе. Ти плануєш познайомитись з колегами в перший день?",
        "russian": "Да, первое впечатление очень важно. Ты планируешь познакомиться с коллегами в первый день?",
        "swedish": "Ja, det första intrycket är väldigt viktigt. Planerar du att presentera dig för dina kollegor den första dagen?",
        "norwegian": "Ja, det første inntrykket er veldig viktig. Planlegger du å introdusere deg for kollegene dine den første dagen?",
        "danish": "Ja, det første indtryk er meget vigtigt. Planlægger du at introducere dig for dine kolleger den første dag?",
        "finnish": "Kyllä, ensivaikutelma on erittäin tärkeä. Aiotko esitellä itsesi kollegoillesi ensimmäisenä päivänä?",
        "greek": "Ναι, η πρώτη εντύπωση είναι πολύ σημαντική. Σκοπεύεις να συστηθείς στους συναδέλφους σου την πρώτη μέρα;",
        "brazilian_portuguese": "Sim, a primeira impressão é muito importante. Você planeja se apresentar aos colegas no primeiro dia?",
        "mandarin": "是的，第一印象非常重要。你打算在第一天向同事们介绍自己吗？",
        "japanese": "はい、第一印象はとても重要です。初日に同僚に自己紹介する予定ですか？",
        "korean": "네, 첫인상이 매우 중요해요. 첫날 동료들에게 자기소개를 할 계획인가요?",
        "hindi": "हाँ, पहली छाप बहुत महत्वपूर्ण होती है। क्या आप पहले दिन अपने सहकर्मियों से खुद को मिलवाने की योजना बना रही हैं?",
        "vietnamese": "Vâng, ấn tượng đầu tiên rất quan trọng. Bạn có kế hoạch tự giới thiệu với các đồng nghiệp vào ngày đầu tiên không?",
        "arabic": "نعم، الانطباع الأول مهم جداً. هل تخططين للتعريف بنفسك لزملائك في اليوم الأول؟",
    },
    {
        "line_number": 26,
        "speaker_name": "Mia",
        "lithuanian": "Žinoma! Manau, svarbu būti draugiška ir atvira nuo pat pradžių. Noriu sukurti gerus santykius su komanda.",
        "latvian": "Protams! Es domāju, ka ir svarīgi būt draudzīgai un atvērtai no paša sākuma. Es gribu veidot labas attiecības ar komandu.",
        "estonian": "Muidugi! Arvan, et on oluline olla sõbralik ja avatud algusest peale. Tahan luua häid suhteid meeskonnaga.",
        "english": "Of course! I think it is important to be friendly and open from the beginning. I want to build good relationships with the team.",
        "german": "Natürlich! Ich denke, es ist wichtig, von Anfang an freundlich und offen zu sein. Ich möchte gute Beziehungen zum Team aufbauen.",
        "french": "Bien sûr! Je pense qu'il est important d'être amical et ouvert dès le début. Je veux établir de bonnes relations avec l'équipe.",
        "spanish": "¡Por supuesto! Creo que es importante ser amable y abierta desde el principio. Quiero construir buenas relaciones con el equipo.",
        "italian": "Certo! Penso che sia importante essere amichevole e aperta fin dall'inizio. Voglio costruire buone relazioni con il team.",
        "portuguese": "Claro! Acho que é importante ser simpática e aberta desde o início. Quero criar boas relações com a equipa.",
        "dutch": "Natuurlijk! Ik denk dat het belangrijk is om vanaf het begin vriendelijk en open te zijn. Ik wil goede relaties opbouwen met het team.",
        "polish": "Oczywiście! Myślę, że ważne jest, aby być przyjazną i otwartą od samego początku. Chcę budować dobre relacje z zespołem.",
        "ukrainian": "Звичайно! Я думаю, важливо бути дружелюбною та відкритою з самого початку. Хочу побудувати гарні стосунки з командою.",
        "russian": "Конечно! Я думаю, важно быть дружелюбной и открытой с самого начала. Я хочу построить хорошие отношения с командой.",
        "swedish": "Självklart! Jag tror att det är viktigt att vara vänlig och öppen från början. Jag vill bygga goda relationer med teamet.",
        "norwegian": "Selvfølgelig! Jeg tror det er viktig å være vennlig og åpen fra begynnelsen. Jeg vil bygge gode relasjoner med teamet.",
        "danish": "Selvfølgelig! Jeg tror, det er vigtigt at være venlig og åben fra begyndelsen. Jeg vil opbygge gode relationer med teamet.",
        "finnish": "Tottakai! Mielestäni on tärkeää olla ystävällinen ja avoin alusta alkaen. Haluan rakentaa hyvät suhteet tiimin kanssa.",
        "greek": "Φυσικά! Νομίζω ότι είναι σημαντικό να είσαι φιλική και ανοιχτή από την αρχή. Θέλω να χτίσω καλές σχέσεις με την ομάδα.",
        "brazilian_portuguese": "Claro! Acho que é importante ser amigável e aberta desde o início. Quero construir boas relações com a equipe.",
        "mandarin": "当然！我认为从一开始就要友好和开放是很重要的。我想与团队建立良好的关系。",
        "japanese": "もちろん！最初から友好的でオープンであることが大切だと思います。チームとの良い関係を築きたいです。",
        "korean": "물론이죠! 처음부터 친절하고 열린 태도를 갖는 것이 중요하다고 생각해요. 팀과 좋은 관계를 쌓고 싶어요.",
        "hindi": "बिल्कुल! मुझे लगता है कि शुरुआत से ही मिलनसार और खुले रहना जरूरी है। मैं टीम के साथ अच्छे संबंध बनाना चाहती हूँ।",
        "vietnamese": "Tất nhiên! Tôi nghĩ điều quan trọng là phải thân thiện và cởi mở ngay từ đầu. Tôi muốn xây dựng mối quan hệ tốt với nhóm.",
        "arabic": "بالطبع! أعتقد أنه من المهم أن تكوني ودودة ومنفتحة من البداية. أريد بناء علاقات جيدة مع الفريق.",
    },
    {
        "line_number": 27,
        "speaker_name": "Alex",
        "lithuanian": "Tai labai gera nuostata. Ar jau pagalvojai, ko norėtum pasiekti per pirmuosius tris mėnesius?",
        "latvian": "Tā ir ļoti laba attieksme. Vai esi jau padomājusi, ko vēlies sasniegt pirmajos trijos mēnešos?",
        "estonian": "See on väga hea suhtumine. Kas oled juba mõelnud, mida soovid esimese kolme kuuga saavutada?",
        "english": "That is a very good attitude. Have you already thought about what you want to achieve in the first three months?",
        "german": "Das ist eine sehr gute Einstellung. Hast du schon darüber nachgedacht, was du in den ersten drei Monaten erreichen möchtest?",
        "french": "C'est une très bonne attitude. Tu as déjà pensé à ce que tu veux accomplir dans les trois premiers mois?",
        "spanish": "Esa es una muy buena actitud. ¿Ya has pensado en lo que quieres lograr en los primeros tres meses?",
        "italian": "È un ottimo atteggiamento. Hai già pensato a cosa vuoi ottenere nei primi tre mesi?",
        "portuguese": "Isso é uma atitude muito boa. Já pensaste no que queres alcançar nos primeiros três meses?",
        "dutch": "Dat is een heel goede instelling. Heb je al nagedacht over wat je in de eerste drie maanden wilt bereiken?",
        "polish": "To bardzo dobra postawa. Czy już pomyślałaś o tym, co chcesz osiągnąć w pierwszych trzech miesiącach?",
        "ukrainian": "Це дуже гарне ставлення. Ти вже думала про те, чого хочеш досягти за перші три місяці?",
        "russian": "Это очень хорошее отношение. Ты уже думала о том, чего хочешь достичь за первые три месяца?",
        "swedish": "Det är en väldigt bra attityd. Har du redan tänkt på vad du vill uppnå under de första tre månaderna?",
        "norwegian": "Det er en veldig god holdning. Har du allerede tenkt på hva du vil oppnå i de første tre månedene?",
        "danish": "Det er en meget god holdning. Har du allerede tænkt over, hvad du vil opnå i de første tre måneder?",
        "finnish": "Se on erittäin hyvä asenne. Oletko jo ajatellut mitä haluat saavuttaa ensimmäisten kolmen kuukauden aikana?",
        "greek": "Αυτή είναι πολύ καλή στάση. Έχεις ήδη σκεφτεί τι θέλεις να πετύχεις τους πρώτους τρεις μήνες;",
        "brazilian_portuguese": "Essa é uma atitude muito boa. Você já pensou no que quer alcançar nos primeiros três meses?",
        "mandarin": "这是非常好的态度。你已经想过在前三个月要实现什么了吗？",
        "japanese": "それは非常に良い姿勢ですね。最初の3ヶ月で何を達成したいか、もう考えましたか？",
        "korean": "정말 좋은 태도네요. 첫 3개월 동안 무엇을 이루고 싶은지 이미 생각해봤나요?",
        "hindi": "यह बहुत अच्छा दृष्टिकोण है। क्या आपने पहले तीन महीनों में क्या हासिल करना चाहती हैं, इसके बारे में सोचा है?",
        "vietnamese": "Đó là thái độ rất tốt. Bạn đã nghĩ về những gì muốn đạt được trong ba tháng đầu chưa?",
        "arabic": "هذا موقف جيد جداً. هل فكرت بالفعل فيما تريدين تحقيقه في الأشهر الثلاثة الأولى؟",
    },
    {
        "line_number": 28,
        "speaker_name": "Mia",
        "lithuanian": "Taip! Noriu išmokti visus darbo procesus, sukurti stiprų socialinės medijos planą ir pradėti rodyti rezultatus.",
        "latvian": "Jā! Es gribu apgūt visus darba procesus, izveidot spēcīgu sociālo mediju plānu un sākt rādīt rezultātus.",
        "estonian": "Jah! Tahan selgeks saada kõik tööprotsessid, luua tugeva sotsiaalmeedia plaani ja hakata tulemusi näitama.",
        "english": "Yes! I want to learn all the work processes, create a strong social media plan and start showing results.",
        "german": "Ja! Ich möchte alle Arbeitsprozesse kennenlernen, einen starken Social-Media-Plan erstellen und beginnen, Ergebnisse zu zeigen.",
        "french": "Oui! Je veux apprendre tous les processus de travail, créer un plan solide pour les réseaux sociaux et commencer à montrer des résultats.",
        "spanish": "¡Sí! Quiero aprender todos los procesos de trabajo, crear un plan sólido de redes sociales y empezar a mostrar resultados.",
        "italian": "Sì! Voglio imparare tutti i processi lavorativi, creare un solido piano per i social media e iniziare a mostrare risultati.",
        "portuguese": "Sim! Quero aprender todos os processos de trabalho, criar um plano sólido de redes sociais e começar a mostrar resultados.",
        "dutch": "Ja! Ik wil alle werkprocessen leren, een sterk social media-plan maken en resultaten beginnen te laten zien.",
        "polish": "Tak! Chcę nauczyć się wszystkich procesów pracy, stworzyć solidny plan mediów społecznościowych i zacząć pokazywać wyniki.",
        "ukrainian": "Так! Хочу вивчити всі робочі процеси, створити сильний план для соціальних мереж та почати показувати результати.",
        "russian": "Да! Я хочу изучить все рабочие процессы, создать сильный план для социальных сетей и начать показывать результаты.",
        "swedish": "Ja! Jag vill lära mig alla arbetsprocesser, skapa en stark plan för sociala medier och börja visa resultat.",
        "norwegian": "Ja! Jeg vil lære alle arbeidsprosessene, lage en solid plan for sosiale medier og begynne å vise resultater.",
        "danish": "Ja! Jeg vil lære alle arbejdsprocesser, skabe en stærk plan for sociale medier og begynde at vise resultater.",
        "finnish": "Kyllä! Haluan oppia kaikki työnprosessit, luoda vahvan sosiaalisen median suunnitelman ja alkaa näyttää tuloksia.",
        "greek": "Ναι! Θέλω να μάθω όλες τις εργασιακές διαδικασίες, να δημιουργήσω ένα ισχυρό πλάνο κοινωνικών δικτύων και να αρχίσω να δείχνω αποτελέσματα.",
        "brazilian_portuguese": "Sim! Quero aprender todos os processos de trabalho, criar um plano forte de redes sociais e começar a mostrar resultados.",
        "mandarin": "是的！我想学习所有工作流程，制定强有力的社交媒体计划，并开始展示成果。",
        "japanese": "はい！すべての作業プロセスを学び、強力なソーシャルメディア計画を作成し、結果を出し始めたいです。",
        "korean": "네! 모든 업무 프로세스를 배우고, 강력한 소셜 미디어 계획을 만들고, 결과를 보여주기 시작하고 싶어요.",
        "hindi": "हाँ! मैं सभी काम की प्रक्रियाएँ सीखना चाहती हूँ, एक मजबूत सोशल मीडिया प्लान बनाना चाहती हूँ और परिणाम दिखाना शुरू करना चाहती हूँ।",
        "vietnamese": "Có! Tôi muốn học tất cả các quy trình làm việc, tạo một kế hoạch mạng xã hội vững chắc và bắt đầu cho thấy kết quả.",
        "arabic": "نعم! أريد تعلم جميع عمليات العمل وإنشاء خطة قوية لوسائل التواصل الاجتماعي والبدء في إظهار النتائج.",
    },
    {
        "line_number": 29,
        "speaker_name": "Alex",
        "lithuanian": "Su tokiu entuziazmu ir aiškiais tikslais tikrai pasiseks. Aš tikiu tavimi, Mia!",
        "latvian": "Ar tādu entuziasmu un skaidriem mērķiem tu noteikti gūsi panākumus. Es ticu tev, Mia!",
        "estonian": "Sellise entusiasmi ja selgete eesmärkidega õnnestub sul kindlasti. Ma usun sinusse, Mia!",
        "english": "With that enthusiasm and clear goals you will definitely succeed. I believe in you, Mia!",
        "german": "Mit diesem Enthusiasmus und klaren Zielen wirst du definitiv erfolgreich sein. Ich glaube an dich, Mia!",
        "french": "Avec cet enthousiasme et ces objectifs clairs tu vas certainement réussir. Je crois en toi, Mia!",
        "spanish": "Con ese entusiasmo y metas claras definitivamente tendrás éxito. ¡Creo en ti, Mia!",
        "italian": "Con tale entusiasmo e obiettivi chiari avrai sicuramente successo. Credo in te, Mia!",
        "portuguese": "Com esse entusiasmo e objetivos claros vais definitivamente ter sucesso. Acredito em ti, Mia!",
        "dutch": "Met dat enthousiasme en duidelijke doelen zul je zeker slagen. Ik geloof in jou, Mia!",
        "polish": "Z takim entuzjazmem i jasnymi celami na pewno odniesiesz sukces. Wierzę w ciebie, Mia!",
        "ukrainian": "З таким ентузіазмом та чіткими цілями ти точно досягнеш успіху. Я вірю в тебе, Міа!",
        "russian": "С таким энтузиазмом и чёткими целями ты точно добьёшься успеха. Я верю в тебя, Миа!",
        "swedish": "Med det entusiasmen och tydliga mål kommer du definitivt att lyckas. Jag tror på dig, Mia!",
        "norwegian": "Med den entusiasmen og klare mål vil du definitivt lykkes. Jeg tror på deg, Mia!",
        "danish": "Med den entusiasme og klare mål vil du helt sikkert lykkes. Jeg tror på dig, Mia!",
        "finnish": "Sellaisella innostuksella ja selkeillä tavoitteilla tulet varmasti menestymään. Uskon sinuun, Mia!",
        "greek": "Με αυτόν τον ενθουσιασμό και τους σαφείς στόχους θα πετύχεις σίγουρα. Πιστεύω σε σένα, Μία!",
        "brazilian_portuguese": "Com esse entusiasmo e metas claras você vai definitivamente ter sucesso. Acredito em você, Mia!",
        "mandarin": "凭借这种热情和明确的目标，你一定会成功的。我相信你，米亚！",
        "japanese": "そのような熱意と明確な目標があれば、必ず成功します。あなたを信じています、ミア！",
        "korean": "그런 열정과 명확한 목표가 있으면 반드시 성공할 거예요. 미아, 응원해요!",
        "hindi": "इस उत्साह और स्पष्ट लक्ष्यों के साथ तुम निश्चित रूप से सफल होगी। मुझे तुम पर विश्वास है, मिया!",
        "vietnamese": "Với sự nhiệt tình và mục tiêu rõ ràng đó, bạn chắc chắn sẽ thành công. Tôi tin vào bạn, Mia!",
        "arabic": "مع هذا الحماس والأهداف الواضحة ستنجحين بالتأكيد. أنا أؤمن بك يا ميا!",
    },
    {
        "line_number": 30,
        "speaker_name": "Mia",
        "lithuanian": "Ačiū, Aleksai! Tavo palaikymas daug reiškia man. Pranešiu tau, kaip seksis po pirmosios savaitės!",
        "latvian": "Paldies, Alekss! Tavs atbalsts man daudz nozīmē. Es pastāstīšu tev, kā veicās pēc pirmās nedēļas!",
        "estonian": "Aitäh, Alex! Sinu toetus tähendab mulle palju. Annan sulle teada, kuidas läks pärast esimest nädalat!",
        "english": "Thank you, Alex! Your support means a lot to me. I will let you know how it goes after the first week!",
        "german": "Danke, Alex! Deine Unterstützung bedeutet mir viel. Ich werde dir nach der ersten Woche Bescheid geben!",
        "french": "Merci, Alex! Ton soutien compte beaucoup pour moi. Je te dirai comment ça s'est passé après la première semaine!",
        "spanish": "¡Gracias, Alex! Tu apoyo significa mucho para mí. ¡Te diré cómo va después de la primera semana!",
        "italian": "Grazie, Alex! Il tuo supporto significa molto per me. Ti farò sapere come va dopo la prima settimana!",
        "portuguese": "Obrigada, Alex! O teu apoio significa muito para mim. Digo-te como correu depois da primeira semana!",
        "dutch": "Bedankt, Alex! Jouw steun betekent veel voor mij. Ik zal je laten weten hoe het gaat na de eerste week!",
        "polish": "Dziękuję, Alex! Twoje wsparcie wiele dla mnie znaczy. Dam ci znać, jak poszło po pierwszym tygodniu!",
        "ukrainian": "Дякую, Алексе! Твоя підтримка для мене багато значить. Я повідомлю тебе, як пройде після першого тижня!",
        "russian": "Спасибо, Алекс! Твоя поддержка много значит для меня. Сообщу тебе, как всё прошло после первой недели!",
        "swedish": "Tack, Alex! Ditt stöd betyder mycket för mig. Jag berättar hur det gick efter första veckan!",
        "norwegian": "Takk, Alex! Din støtte betyr mye for meg. Jeg gir deg beskjed om hvordan det går etter den første uken!",
        "danish": "Tak, Alex! Din støtte betyder meget for mig. Jeg giver dig besked om, hvordan det går efter den første uge!",
        "finnish": "Kiitos, Alex! Tukesi merkitsee minulle paljon. Kerron sinulle miten meni ensimmäisen viikon jälkeen!",
        "greek": "Ευχαριστώ, Άλεξ! Η υποστήριξή σου σημαίνει πολλά για μένα. Θα σου πω πώς πήγε μετά την πρώτη εβδομάδα!",
        "brazilian_portuguese": "Obrigada, Alex! Seu apoio significa muito para mim. Vou te contar como foi depois da primeira semana!",
        "mandarin": "谢谢你，亚历克斯！你的支持对我意义重大。第一周后我会告诉你进展如何！",
        "japanese": "ありがとう、アレックス！あなたのサポートはとても嬉しいです。最初の1週間後にどうだったか教えます！",
        "korean": "고마워요, 알렉스! 당신의 응원이 큰 힘이 돼요. 첫 주가 지나면 어땠는지 알려드릴게요!",
        "hindi": "धन्यवाद, एलेक्स! तुम्हारा समर्थन मेरे लिए बहुत मायने रखता है। पहले हफ्ते के बाद मैं तुम्हें बताऊँगी कैसा रहा!",
        "vietnamese": "Cảm ơn bạn, Alex! Sự ủng hộ của bạn có ý nghĩa rất lớn với tôi. Tôi sẽ cho bạn biết kết quả sau tuần đầu tiên!",
        "arabic": "شكراً لك يا أليكس! دعمك يعني لي الكثير. سأخبرك كيف سارت الأمور بعد الأسبوع الأول!",
    },
]


def seed():
    with app.app_context():
        db.create_all()

        existing = Dialogue.query.filter_by(topic="Starting a New Job").first()
        if existing:
            print("B1 dialogue already exists — skipping.")
            return

        dialogue = Dialogue(
            topic="Starting a New Job",
            lang_level="B1",
            length=30
        )
        db.session.add(dialogue)
        db.session.flush()

        for line_data in lines_data:
            line = DialogueLine(
                dialogue_id=dialogue.id,
                **line_data
            )
            db.session.add(line)

        db.session.commit()
        print(f"Successfully seeded B1 dialogue ID {dialogue.id} with {len(lines_data)} lines in 25 languages.")


if __name__ == '__main__':
    seed()
